### ISSUE TITLE
Popups/Dialogs not working

### ISSUE THREAD

**Issue by snej0l** [platformio/platformio-atom-ide#100]
I use PlatformIO on my Mac and have the following problem: When open a dialog / window I can not choose anything there and not click on any button. This relates both to the window for the Serial Monitor and the Donate window. I can edit text in the background text editor but the dialog is always in the foreground.

**Comment by ivankravets** [comment]
1. What is the version of Atom?
2. Have you installed our IDE bundle with Atom or used http://atom.io?

**Comment by snej0l** [comment]
The current IDE bundle

**Comment by ivankravets** [comment]
Please try Atom from http://atom.io

**Comment by snej0l** [comment]
I found the problem. The theme in Atom was the problem. When I switched to the default theme everything works fine.

Thanks for helping

**Comment by ivankravets** [comment]
With which theme have you had a problem?

**Comment by snej0l** [comment]
https://atom.io/themes/native-ui

**Comment by ivankravets** [comment]
It looks that it can be fixed in `native-ui` theme. I've checked and it works fine.
