### ISSUE TITLE
OSError: [Errno 2] No such file or directory: /cygdrive

### ISSUE THREAD

**Issue by DeonMarais64** [platformio/platformio-atom-ide#1000]
I get "OSError: [Errno 2] No such file or directory:" installing from either "Atom" or "Visual Studio Code".

Installing from Atom :
OSError: [Errno 2] No such file or directory: '/cygdrive/c/Users/Deon-Marais/AppData/Local/atom/app-1.20.1/C:\\Users\\Deon-Marais\\.platformio\\penv'

Installing from Visual Studio Code
OSError: [Errno 2] No such file or directory: '/cygdrive/e/MSVSCode/C:\\Users\\Deon-Marais\\.platformio\\penv'

Any guidance or assistance would be appreciated.

**Comment by ivankravets** [comment]
Have you overridden `USER_HOME` directory in system environment?

**Comment by ivankravets** [comment]
Please reopen if you still need help
