### ISSUE TITLE
Feature request: Download SPIFFS image

### ISSUE THREAD

**Issue by viktak** [platformio/platformio-atom-ide#102]
I was wondering if it is at all possible to have a feature for downloading files from the ESP, similar to the Upload SPIFFS image, but the other way around. It's not a major problem not having this feature, but would make a great addition, IMHO.

Thanks for this great product!

**Comment by ivankravets** [comment]
Please move this issue to PlatformIO CLI repo https://github.com/platformio/platformio/issues

**Comment by viktak** [comment]
Done, and thanks!
#630
