### ISSUE TITLE
Feature request: Automatic save of (all) changed files when pressing the compile/upload button/Ctrl+Alt+U

### ISSUE THREAD

**Issue by viktak** [platformio/platformio-atom-ide#103]
I miss this feature a lot because I am used to working with Visual Studio. It drives me crazy that when I want to upload a new version of my code I have to press Ctrl+S, then Ctrl+Alt+U. Is there a way to eliminate the need for Ctrl+S? If not for everyone, at least at a setting level, where one could enable/disable it to suit his/her preferences.

**Comment by ivankravets** [comment]
Please read http://docs.platformio.org/en/latest/ide/atom.html#automatically-save-on-build

**Comment by viktak** [comment]
Oops, my mistake, I didn't see that.
