### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by thelastgamer** [platformio/platformio-atom-ide#1045]
Usage: platformio init [OPTIONS]

Error: Invalid value for "--project-dir" / "-d": Directory "C:\Users\OneDrive\??????\Digial Necleo project\Lab2" does not exist.

**Comment by ivankravets** [comment]
What is your user name?

**Comment by ivankravets** [comment]
Should be fixed in the latest PIO IDE 2.4.0-rc.4
