### ISSUE TITLE
C/C++ project index rebuild failed with MAC

### ISSUE THREAD

**Issue by ejngnng** [platformio/platformio-atom-ide#1052]
/Users/ninja/.platformio/penv/bin/python2.7: can't open file '/Users/ninja/.platformio/packages/_tmp_installing-xYTfdr-package/script/scons': [Errno 2] No such file or directory
========================= [ERROR] Took 101.39 seconds =========================

**Comment by ivankravets** [comment]
Please remove `/Users/ninja/.platformio/packages/tool-scons` adn start build again.
