### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by mukeshroy13** [platformio/platformio-atom-ide#1057]
Please manually remove file `C:\Users\mukesh\.platformio\packages\toolchain-xtensa\bin\libiconv-2.dll`

Error: Could not install 'toolchain-xtensa' with version requirements '~1.40802.0' for your system 'windows_x86'.
If you use Antivirus, it can block PlatformIO Package Manager. Try to disable it for a while.

**Comment by ivankravets** [comment]
Please manually remove folder `C:\Users\mukesh\.platformio\packages` and start build again
