### ISSUE TITLE
Error: Could not install 'toolchain-gccarmnoneeabi' with version requirements '>=1.60301.0' for your system 'windows_x86'

### ISSUE THREAD

**Issue by GerryGit** [platformio/platformio-atom-ide#1060]
Error: Could not install 'toolchain-gccarmnoneeabi' with version requirements '>=1.60301.0' for your system 'windows_x86'.
If you use Antivirus, it can block PlatformIO Package Manager. Try to disable it for a while.
Initiating a new project for ST Nucleo f401 board.
Antivirus is disabled. FW is disabled. Win7 64 Pro.
Problem seems to be specific to PlatformIO as I have gccarm running on my machine for other frameworks. Is it possible to specify the path to gccarm in PlatformIO?

**Comment by ivankravets** [comment]
Please provide an output from system Terminal `cmd`
```
echo %PATH%
echo %PYTHONPATH%
python --version
pip --version
pip list
```

**Comment by ivankravets** [comment]
Please reopen if you still need help
