### ISSUE TITLE
Update 1.2.0. problem

### ISSUE THREAD

**Issue by mf1040** [platformio/platformio-atom-ide#109]
Does anyone have a solution for this problem??

![error](https://cloud.githubusercontent.com/assets/13602342/14918979/d800dab2-0e26-11e6-944a-501aadcb4cfd.jpg)

**Comment by orgkhnargh** [comment]
1.2.1 should fix this.

**Comment by ivankravets** [comment]
Please update to PlatformIO IDE 1.2.1

**Comment by mf1040** [comment]
Thanks, now works again.
