### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by Kibabalu** [platformio/platformio-atom-ide#1096]
Traceback (most recent call last):
File "/Users/frankkirschbaum/.platformio/packages/tool-scons/script/scons", line 190, in <module>
import SCons.Script
ImportError: No module named SCons.Script
========================== [ERROR] Took 0.43 seconds ==========================
Environment ATmega1284P_aTeVal    	[ERROR]
========================== [ERROR] Took 0.43 seconds ==========================

**Comment by ivankravets** [comment]
Please remove `/Users/frankkirschbaum/.platformio/packages/tool-scons` folder and start build again
