### ISSUE TITLE
Windows problem?

### ISSUE THREAD

**Issue by IoTAdri** [platformio/platformio-atom-ide#11]
THNX for the great work involved in making this package!!

As you can see in this picture something is wrong with the path in Windows (U use "\\\" instead of "\") which generates an error when Building, Uploading and Compiling.
(it works just fine by hand from the commandline)

![error1](https://cloud.githubusercontent.com/assets/16754039/12535492/6d9bdbdc-c285-11e5-8a15-3c9952538d1b.jpg)

![error2](https://cloud.githubusercontent.com/assets/16754039/12535501/cb537226-c285-11e5-8600-a8a757ffd9f3.jpg)

What to do?

**Comment by ivankravets** [comment]
Temporary solution: rename your `*.ino` to `*.cpp` and place `#include <Arduino.h>` at top of this file.

**Comment by ivankravets** [comment]
Please upgrade PlatformIO IDE to 0.1.1
