### ISSUE TITLE
UnicodeDecodeError: Non-ASCII characters found in build environment

### ISSUE THREAD

**Issue by DaftpunkK** [platformio/platformio-atom-ide#1111]
C:\Users\user\.platformio\packages\tool-scons\script\..\engine\SCons\Environment.py:1303: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
val = [x for x in val if x not in dk]

UnicodeDecodeError: Non-ASCII characters found in build environment
See explanation in FAQ > Troubleshooting > Building
http://docs.platformio.org/page/faq.html

 [ERROR] Took 2.54 seconds

**Comment by ivankravets** [comment]
Please reopen if you still need help
