### ISSUE TITLE
Unable to start the PlatformIO IDE // Problem with Python and Locale 

### ISSUE THREAD

**Issue by MichMich** [platformio/platformio-atom-ide#112]
Hi guys,

I'm trying to het PlatformIO running on my MacBook (El Capitan). Unfortunately, I get an error when starting:
![screen shot 2016-05-10 at 11 51 49](https://cloud.githubusercontent.com/assets/210954/15142532/c5b93e9e-16a5-11e6-86e1-5fee4acbbba8.png)

I've tried reinstalling setuptools and platformio, but unfortunately with no luck.

**Comment by ivankravets** [comment]
Please try `rm -rf ~/.atom` and restart. Did it help you?

**Comment by MichMich** [comment]
Already tried that. Same problem. :(

**Comment by ivankravets** [comment]
Very strange problem. Something is wrong with setuptools.

1. Open system OS Terminal (non IDE Terminal) and run `sudo pip install -U setuptools`
2. `rm -rf ~/.atom`
3. Restart

**Comment by MichMich** [comment]
```
$ sudo pip install -U setuptools
Requirement already up-to-date: setuptools in /usr/local/lib/python2.7/site-packages

$ rm -rf ~/.atom
```
Still same problem.

Also interesting:
```
$ platformio
-bash: platformio: command not found

$ echo $PATH
/Users/Michael/.composer/vendor/bin:/usr/local/share/npm/lib/node_modules/grunt-cli/bin:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
```

**Comment by ivankravets** [comment]
Could you provide TeamViewer session for debug? Mail me@ikravets.com. Thanks.

**Comment by MichMich** [comment]
TeamViewer credentials in your mail.

**Comment by svogl** [comment]
I had the same problem on my Capitan with german OS settings; this command line worked for me:

`LC_ALL=C /Applications/Atom.app/Contents/MacOS/Atom`

**Comment by ivankravets** [comment]
Try to this line to your Shell profiles (`~/.bash_profile` or `~/.zshrc`):
```
export LC_ALL=en_US.UTF-8
```

**Comment by MichMich** [comment]
I agree that this solves the issue, but should't PlatformIO include a check for this?

**Comment by ivankravets** [comment]
> but should't PlatformIO include a check for this?

Of course, it should check. That is why this issue marked as `bug`.

**Comment by ivankravets** [comment]
@MichMich Could you try one idea?

1. Close Atom
2. Please disable `export LC_ALL=en_US.UTF-8` in `~/.bash_profile`
3. Open Atom. Now, it should raise an error.


------
Next:
1. Close Atom
2. Please edit this file [~/.atom/packages/platformio-ide/origin/lib/main.js](https://github.com/platformio/platformio-atom-ide/blob/develop/lib/main.js#L55)
3. Place this line `process.env.LC_ALL = 'en_US.UTF-8';` below `process.env.PATH = process.env.Path;`
4. Start Atom

====

Does it help?

**Comment by MichMich** [comment]
The file `~/.atom/packages/platformio-ide/origin/lib/main.js ` does not exist. (There isn't an `origin` folder.)
I tried that change in `~/.atom/packages/platformio-ide/lib/main.js ` and that indeed solved the issue.

**Comment by ivankravets** [comment]
> does not exist. (There isn't an origin folder.)

Sorry, it was my mistake.

> I tried that change in ~/.atom/packages/platformio-ide/lib/main.js and that indeed solved the issue.

Do you mean, that `process.env.LC_ALL = 'en_US.UTF-8';` helped you?

**Comment by ivankravets** [comment]
Could you try to restart Mac? It seems that OS caches system environment variables.

**Comment by MichMich** [comment]
> Do you mean, that process.env.LC_ALL = 'en_US.UTF-8'; helped you?

Yes, this is correct.

**Comment by ivankravets** [comment]
@svogl Could you try to replace this file `~/.atom/packages/platformio-ide/lib/main.js` with https://github.com/platformio/platformio-atom-ide/blob/develop/lib/main.js ?

**Comment by svogl** [comment]
@ivankravets Work for me as well - I copied the modified platformio-ide package into a clean .atom subdirectory and the base installation has completed successfully.

**Comment by ivankravets** [comment]
@svogl Thanks a lot for the report! I'll release new IDE version as soon as possible.
