### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by HAJMOUSA** [platformio/platformio-atom-ide#1120]
Error: [11/05/17 08:11:38] Processing featheresp32 (platform: espressif32; board: featheresp32; framework: Arduino)

Verbose mode can be enabled via `-v, --verbose` option
Error: This board doesn't support Arduino framework!
 [ERROR] Took 0.77 seconds

**Comment by ivankravets** [comment]
Please change Arduino to lowercase
