### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by anthonyjclarke** [platformio/platformio-atom-ide#1125]
PIP: Error: spawn /Volumes/Macintosh HD 2/Users/.platformio/penv/bin/pip ENOENT

I did a full uninstall of Atom as well and tried again.  Still same issue.

Any tips?

Using MAC OSX 10.13.1

**Comment by ivankravets** [comment]
http://docs.platformio.org/en/latest/faq.html#multiple-pio-cores-in-a-system

**Comment by ivankravets** [comment]
Please remove /Volumes/Macintosh HD 2/Users/.platformio/penv and restart IDE
