### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by ssaguiar** [platformio/platformio-atom-ide#1129]
Error: Could not install 'toolchain-xtensa32' with version requirements '~1.50200.0' for your system 'windows_x86'.
If you use Antivirus, it can block PlatformIO Package Manager. Try to disable it for a while.

**Comment by ivankravets** [comment]
If you use Antivirus, it can block PlatformIO Package Manager. Try to disable it for a while.
