### ISSUE TITLE
"Seems like PlatformIO IDE is already being installed in another window." on startup

### ISSUE THREAD

**Issue by hexaguin** [platformio/platformio-atom-ide#113]
Every time I start Atom, I get this message. Everything seems to work fine, but the message is getting annoying. What is causing it?

**Comment by ivankravets** [comment]
What is your OS?

**Comment by hexaguin** [comment]
Windows. I actually managed to fix the issue by deleting install.lock in the PlatformIO package directory and letting the installation finish again. Everything seems to work perfectly now.

**Comment by ivankravets** [comment]
We will try automatically to delete expired `install.lock`. Thanks.

**Comment by sansil** [comment]
Hi, I have the same issue, but i'm using OS X 10.10.3
I can't find install.lock where is located ?.  Thanks in advance

**Comment by ivankravets** [comment]
@sansil it is located in `~/.atom/packages/platformio-ide/install.lock`

**Comment by sansil** [comment]
thanks! it works :D

**Comment by ivankravets** [comment]
Thanks for the report. We will fix this issue in the next release.

**Comment by geekerator** [comment]
I also get this message, but in another way. I:
  Started atom (with Platformio previously installed) and did an update to the latest core
  Platformio Core flashing download icon never stopped (after about 2 hrs) - and reappears on any restart
  No work can be done while Installing is going on, so I
  Quit and restarted while randomly clicking on atom's menu items, then
  This message comes up. I don't seem to have an install.lock file anywhere
My specs are: openSuSE 42.3 and kernel 4.4.79-19. Any suggestions would be greatly appreciated...

**Comment by ivankravets** [comment]
Could you remove `~/.platformio/penv` folder and restart Atom?
