### ISSUE TITLE
Project Wizard - no defualt location hangs

### ISSUE THREAD

**Issue by Thijxx** [platformio/platformio-atom-ide#1135]
For a new project I need to go to PlatformIO Home, then to New Project, then select the settings but then when I disable the "Use default location" option the interface hangs..

Home 0.3.2·
Core 3.5.0b3
Atom 1.21.2-1

I looked around to change the default project location but I cannot find where I can change this.

![screenshot from 2017-11-09 22-05-09](https://user-images.githubusercontent.com/3355823/32629621-20527c0e-c59a-11e7-89d9-a7dfece214d6.png)

**Comment by ivankravets** [comment]
Should be fixed in the latest release. Does it work now?

**Comment by Thijxx** [comment]
Fixed, it now opens a non-re-sizable way too small window with an 'alternative' folder structure. This will be a new ticket.
