### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by joaoTrevizoli** [platformio/platformio-atom-ide#1138]
Error: [Sat Nov 11 16:24:35 2017] Processing nodemcuv2_dev (build_flags: -Wl,-Tesp8266.flash.4m.ld, '-DLABMET_SSID="secret"', '-DWIFI_PASSWORD="secret"', '-DDB_ID="test_user_2"', '-DTOPIC="/labmet_data_dev/"', '-DSTATION_UPDATE_INTERVAL=60000L', '-DREADING_RATE=4000L', '-DMESSAGE_FLASHING=1', '-DPROD=0'; lib_deps: 19, 64, 83, 576, 663, 748, 930, 1655; platform: espressif8266; upload_speed: 115200; board: nodemcuv2; framework: arduino; monitor_baud: 115200)
--------------------------------------------------------------------------------
Exception: [Errno 13] Permission denied: '/Users/joaotrevizoliesteves/projects/labmet-weatherstation/.pioenvs/do-not-modify-files-here.url':
File "/Users/joaotrevizoliesteves/.platformio/penv/lib/python2.7/site-packages/platformio/builder/main.py", line 93:
PROJECTPIOENVS_DIR=util.get_projectpioenvs_dir(),
File "/Users/joaotrevizoliesteves/.platformio/penv/lib/python2.7/site-packages/platformio/util.py", line 323:
raise Exception(e)
========================== [ERROR] Took 0.46 seconds ==========================

================================== [SUMMARY] ==================================
Environment nodemcuv2_dev 	[ERROR]
Environment nodemcuv2_prod	[SKIP]
========================== [ERROR] Took 0.46 seconds ==========================

**Comment by ivankravets** [comment]
Please remove `/Users/joaotrevizoliesteves/projects/labmet-weatherstation/.pioenvs` and build again
