### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by moth4017** [platformio/platformio-atom-ide#1142]
Message below keeps poping up every 2 seconds and will keep poping up in a list that get ever longer , can not use the software while this is happening , can not work out how yo stop ther error messages popping up.

Error: VCS: `git` client is not installed in your system

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/1102#issuecomment-341896048
