### ISSUE TITLE
How to upgrade from 8 Bit  Arduino to 32 Re-Arm with Ramps ----- Work in progress 

### ISSUE THREAD

**Issue by moth4017** [platformio/platformio-atom-ide#1143]
# **Work in progress** , 
Migrate from 8 Bit Arduino Mega to 32 bit Re-Arm

My aim is to do a step by step upgrade from a Mega + Ramps, to a Re-Arm + Ramps.

I have a Core x-y printer , with a filament runout sensor, Heated bed via 500W silicon heater & thermister , e3D hotend with thermocouple,

purchase a re-arm board
data sheet and info here
http://panucattdevices.freshdesk.com/support/solutions/folders/1000226299

Download Marlin V2.X from here http://marlinfw.org/meta/download/

Display connection details for the Rep Rap Full Graphic smart Display, http://panucattdevices.freshdesk.com/support/solutions/articles/1000243195-lcd-display-installation

Power connections

Pre checks before applying power

using  Atom to upload Marlin V2.x

Settings to update in configaration.h

pre testing . x y & z distance calibration, PID hot end and heated bed, Extruder Calibration etc

First text Print

Appendix A
Ethernet Module , Connecting to you LAN you will need to purchase the "Panucatt LAN Adaptor"
this module connects to the LAN/GPIO on the RE-Arm. https://s3.amazonaws.com/cdn.freshdesk.com/data/helpdesk/attachments/production/1048535821/original/-Gi4CxInd9zZmsEH0IS2rmRP4pySNdegUQ.JPG?1483391977
Setting IP address ...

## install Atom 
Install Atom software 
[https://atom.io/](url)

you may also get asked to install a program called "Clang" 

## Install  PlatformIO 
based on Bob-the-Kuhn setup
Installing PlatformIO is tedious but not hard.

 In Atom go to the FILE -> SETTINGS -> Install and search for PlatformIO.. 
You'll want to install platformio-ide, build-platformio and platformio-ide-terminal. platformio-ide takes a while to install and many (4?) restarts of Atom. Wouldn't hurt to do a couple extra restarts of Atom after it stops requesting restarts.

Once the PlatformIO home/welcome page is displayed
Click on the +New Project button.

Click -- choose a board -- and scroll down to the Platform NXPLPC area and click on NXP mbed LPC1768.
 
"Open Project"
Select Other under Chose the directory and then enter the directory ABOVE Marlin.

Click the Process button. Hopefully no errors will pop up.
In the extreme lower left corner of the Atom window there should be something with PIO Build in it. Click on that.
In the window that pops up enter Re-ARM in the search window.
Click on PIO Build (Re-ARM). That'll open up a window where it will show the compiler output.
If you have some compiler errors the window will stay open. Make your corrections and then, to re-run the compiler, click the lightning bolt button on the upper right of the window.
Once it says SUCCESS the executable will be the file firmware.bin in the directory .pioenvs\Re-ARM. Copy that to an SD card and insert in into the SD card reader on the motherboard. After cycling power (reset won't do it) the new code will be loaded and run.

## If you get issues try this below for a re-install
from Roxy-3D
When PlatformIO blows up and quits working... It leaves directories laying around that screw up any future installation. This is horribly crude and brute force. But if you fire up a command line (from within Windows) and do

cd \users\YOUR-USERNAME
dir *atom/s
remove any directory with atom files. some of the directories will be of the form .atom
dir platformio/s
remove any directory with PlatformIO files some of the directoriws will be of the form .platformio
restart the installation by first installing Atom

## If you get this error
![error](https://user-images.githubusercontent.com/22909429/32705483-da0219c0-c879-11e7-9620-05c438be4c6e.png)

it can be fixed by installing this [https://git-scm.com/download/win](url)

**Comment by ivankravets** [comment]
Thanks a lot for a great tutorial! Please move it to http://community.platformio.org/
