### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by brandrik** [platformio/platformio-atom-ide#1155]
Conda Virtualenv: 
CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://repo.continuum.io/pkgs/main/osx-64/repodata.json.bz2>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
ConnectionError(MaxRetryError("HTTPSConnectionPool(host='repo.continuum.io', port=443): Max retries exceeded with url: /pkgs/main/osx-64/repodata.json.bz2 (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x10aa60cf8>: Failed to establish a new connection: [Errno 61] Connection refused',))",),)

**Comment by ivankravets** [comment]
Something is wrong with @conda. Please try again
