### ISSUE TITLE
Adding multiple .c and .h files to esp32 project

### ISSUE THREAD

**Issue by mohamed-elsabagh** [platformio/platformio-atom-ide#1156]
I am new to platformio and I am trying to port my esp32 esp-idf project to platform io.
in my old project I had folder called components and it has different components and drivers e.g.
|--components
|  |--bluetooth
|  |  |--bluetooth.c
|  |  |--include
|  |     |- bluetooth.h
|--src
   |- main.c

once I call ```#include"bluetooth.h"``` from my main.c it knows where to search for, how can I do the same using platformio, I tried everything with no luck

**Comment by ivankravets** [comment]
http://docs.platformio.org/en/latest/projectconf/section_env_build.html#build-flags
