### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by vedatAltun** [platformio/platformio-atom-ide#1157]
Error: [11/20/17 13:00:56] Processing genericSTM32F103C8 (platform: ststm32; board: genericSTM32F103C8; framework: arduino)

Verbose mode can be enabled via `-v, --verbose` option
Collected 32 compatible libraries
Looking for dependencies...
Error: Could not find `Adafruit GFX Library` dependency for `Adafruit SSD1306` library
 [ERROR] Took 1.05 seconds

**Comment by ivankravets** [comment]
Please re-install Adafruit SSD1306 library via PIO Home > Libaries > Installed
