### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by andyeggs** [platformio/platformio-atom-ide#1167]
Error: Can not remove temporary directory `/Users/andymacbookpro/Desktop/Arduino/.pioenvs`. Please remove `.pioenvs` directory from the project manually to avoid build issues
[Wed Nov 22 13:41:02 2017] Processing due (platform: atmelsam; board: due; framework: arduino)
--------------------------------------------------------------------------------
Exception: [Errno 13] Permission denied: '/Users/andymacbookpro/Desktop/Arduino/.pioenvs/do-not-modify-files-here.url':
File "/Users/andymacbookpro/.platformio/penv/lib/python2.7/site-packages/platformio/builder/main.py", line 93:
PROJECTPIOENVS_DIR=util.get_projectpioenvs_dir(),
File "/Users/andymacbookpro/.platformio/penv/lib/python2.7/site-packages/platformio/util.py", line 323:
raise Exception(e)
========================== [ERROR] Took 0.38 seconds ==========================

**Comment by ivankravets** [comment]
Please remove `/Users/andymacbookpro/Desktop/Arduino/.pioenvs` and start build again
