### ISSUE TITLE
Can't create folder when intialising new project

### ISSUE THREAD

**Issue by cjastone** [platformio/platformio-atom-ide#1169]
Around a month or more ago, the file browser changed entirely, and creating a new / importing an existing project options moved from the PlatformIO menu and onto the home screen.

This new file browser is clean, but has moved away from the common Windows controls, are unfamiliar and difficult to navigate (for example, I have no one-click access to my Dropbox folder now) and most strangely, has no option to create a new folder when I'm creating a new project.

I have to ensure I have a suitable folder created prior to opening the dialog and browsing to the folder.  If I create this folder (from Windows Explorer) after having browsed to the parent directory, refreshing fails to show this folder.

In all, it's a very clunky process to ensure a per-project folder structure when it was a seamless process earlier.

I'm not sure if I'm missing something and I would welcome being corrected!

**Comment by ivankravets** [comment]
We will implement it soon. 

https://github.com/platformio/platformio-core/issues/1034
