### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by srg74** [platformio/platformio-atom-ide#1173]
Error: Can not remove temporary directory `/Users/SK/Documents/Arduino/esp8266-weather-station-master/.pioenvs`. Please remove `.pioenvs` directory from the project manually to avoid build issues
[Thu Nov 23 13:30:04 2017] Processing nodemcuv2 (framework: arduino; lib_deps: JsonStreamingParser; board_f_cpu: 160000000L; platform: espressif8266; upload_speed: 921600; board: nodemcuv2)
--------------------------------------------------------------------------------
Exception: [Errno 13] Permission denied: '/Users/SK/Documents/Arduino/esp8266-weather-station-master/.pioenvs/do-not-modify-files-here.url':
File "/Users/SK/.platformio/penv/lib/python2.7/site-packages/platformio/builder/main.py", line 93:
PROJECTPIOENVS_DIR=util.get_projectpioenvs_dir(),
File "/Users/SK/.platformio/penv/lib/python2.7/site-packages/platformio/util.py", line 323:
raise Exception(e)
========================== [ERROR] Took 0.30 seconds ==========================

**Comment by ivankravets** [comment]
Please remove this folder `/Users/SK/Documents/Arduino/esp8266-weather-station-master/.pioenvs` manually and start build again
