### ISSUE TITLE
PIO Home keeps loading

### ISSUE THREAD

**Issue by RaghuShankar22** [platformio/platformio-atom-ide#1174]
Installed platrofrmio package through Atom but it never launches but keeps loading.

![image](https://user-images.githubusercontent.com/33949482/33197564-446df50a-d10c-11e7-98de-6ff0264a8a77.png)

**Comment by ivankravets** [comment]
Do you have old Python is a system?

Please provide an output from system Terminal `cmd`
```
echo %PATH%
echo %PYTHONPATH%
python --version
pip --version
pip list
```

Also, take a look at https://community.platformio.org/t/platform-io-home-doesnt-work-in-atom-importerror-cannot-import-name-dependencywarning/2899/7?u=ivankravets

**Comment by ivankravets** [comment]
Please reopen if you still need help
