### ISSUE TITLE
InstallationManager Atom

### ISSUE THREAD

**Issue by McAlb** [platformio/platformio-atom-ide#1177]
Got this error message in Atom:

> Error: Failed to download file https://pypi.python.org/packages/source/v/virtualenv/virtualenv-14.0.6.tar.gz: Error: EACCES: permission denied, open '/Users/Alb/.platformio/.cache/virtualenv.tar.gz'
>     at _callee$ (/Users/Alb/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/lib/index.js:2522:19)
>     at tryCatch (/Users/Alb/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/lib/index.js:780:40)
>     at Generator.invoke [as _invoke] (/Users/Alb/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/lib/index.js:1014:22)
>     at Generator.prototype.(anonymous function) [as throw] (/Users/Alb/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/lib/index.js:832:21)
>     at step (/Users/Alb/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/lib/index.js:2631:191)
>     at /Users/Alb/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/lib/index.js:2631:402

**Comment by ivankravets** [comment]
Please remove this folder `/Users/Alb/.platformio` adn restart IDE
