### ISSUE TITLE
Cannot delete files

### ISSUE THREAD

**Issue by timoldenb** [platformio/platformio-atom-ide#1181]
Editor Version: Atom.io 1.22.1 x64
Package Version: platformio-ide 2.0.0-rc4
Operating System: Windows 10 PRO 
Other running software: Antivirus: Avira
(All other: default settings/installation, no fancy stuff)

Expected behaviour:
- I can delete every unnecessary file in folder structure of a project

Observed behaviour:
- After deleting file while Editor/Package is running, some files are magically restored
- Without running Editor/Package, file can be deleted, but will be restored after start of Editor/Package

Steps to reproduce:
- Create arduino project (megaatmega2560)
- Delete lib\readme.txt in treeview
- File disappears for a second or two
- Delete lib\readme.txt with SHIFT-DELETE in Explorer
- File disappears for a second or two ONLY if atom/platformio-ide is running

Same applies to file project-root\\.travis.yml

**Comment by ivankravets** [comment]
Depends on https://github.com/platformio/platformio-core/issues/446

User should be able to configure project settings (CI, etc.)
