### ISSUE TITLE
Won't work: "C/C++ project index rebuild failed"

### ISSUE THREAD

**Issue by binderth** [platformio/platformio-atom-ide#1189]
I tried different Things explained in some issues here, including:
* deleting the `penv` Directory
* deactivating AntiVirus
* deleting the `.platformio`directory and installing again

in the end:
* deinstalling Atom
* deleting `%HOMEDIR%/.atom`
* deleting `%HOMEDIR%/.platformio`
* reinstalling Atom
* reinstalling platformio package

still the same issue. plattformioIO Core keeps update *everytime* i restart Atom. If I ignore it, the error keeps popping up. How and what can I provide for more information?

**Comment by binderth** [comment]
After changing from Atom to VSCode, the same reinstalling/restarting procedure is present:
![image](https://user-images.githubusercontent.com/9037329/33229967-1a2030f0-d1da-11e7-8016-990bd54ea2b0.png)
You can Keep klicking "Reload now", it will reload, then tell you, PlattformIO Core will be installed and then you can Klick "Reload now", and so on and so forth....

**Comment by ivankravets** [comment]
Please upgrade to 0.8.0. Should be fixed.
