### ISSUE TITLE
Platform IO Installation Stops responding - Windows 7

### ISSUE THREAD

**Issue by siddharth119** [platformio/platformio-atom-ide#119]
When I try to install the PlatformIO IDE, everything works fine until Atom is installed. After this point, I get a dialog box saying "PlatformIO has stopped responding". I have Python 2.7.11 and the paths have been configured properly. Any clues as to how I can remedy this? 
![platformiodebug1](https://cloud.githubusercontent.com/assets/8594190/15625781/b5cb0b2c-24d1-11e6-8171-a73ba7abe714.JPG)

I have tried the installation with both Atom 1.7.0 and Atom 1.6.2. My machine runs Windows 7 64-bit

**Comment by ivankravets** [comment]
Just click on "Keep waiting"...

**Comment by ivankravets** [comment]
Please reopen if you still need any help
