### ISSUE TITLE
Error: spawn EACCES

### ISSUE THREAD

**Issue by gerisse** [platformio/platformio-atom-ide#1193]
when Platformio Core is installing , this message appears : "Error: spawn EACCES"

**Comment by ivankravets** [comment]
What is your OS?

http://docs.platformio.org/en/latest/faq.html#platformio-is-not-recognized-as-an-internal-or-external-command

**Comment by gerisse** [comment]
archlinux everywhere

**Comment by gerisse** [comment]
but it seems fixed : (i did anything !) : the message disappeared
