### ISSUE TITLE
How to set speed of Serial Monitor to 74880 baud?

### ISSUE THREAD

**Issue by krzychb** [platformio/platformio-atom-ide#120]
ESP8266 of ```platform = espressif ``` boots at 74880 baud providing debug messages on UART like:

```
ets Jan  8 2013,rst cause:2, boot mode:(3,7)

load 0x4010f000, len 1264, room 16 
tail 0
chksum 0x0f
csum 0x0f
~ld
```

Reasons to be able to see such messages is discussed [here](http://www.esp8266.com/viewtopic.php?f=33&t=2308).

I was trying to set up speed of 74880 baud in Serial Monitor of PlatformIO IDE but do not see such possibility and have to use external serial terminal. 

![new picture](https://cloud.githubusercontent.com/assets/12953787/15804989/bbc7a0e4-2b1b-11e6-971d-0a21293f9264.png)

Do I miss an option to somehow enter a custom speed in Serial Monitor or it is not supported?

**Comment by orgkhnargh** [comment]
As a workaround you can put the line `<option value="74880">74880</option>` somewhere between lines 11 and 28 of the file `C:\Users\%USERNAME%\.atom\packages\platformio-ide\lib\serial-monitor\template.html`.

**Comment by krzychb** [comment]
@orgkhnargh,

Thanks a lot for quick help with this issue!
Now I see why Atom is advertised as "A hackable text editor" :+1:

![new picture](https://cloud.githubusercontent.com/assets/12953787/15806555/cc1cdbd8-2b45-11e6-9fb2-01b9f0a13956.png)
