### ISSUE TITLE
C/C++ project index rebuild failed: Error: spawn platformio ENOENT

### ISSUE THREAD

**Issue by eventus17** [platformio/platformio-atom-ide#1202]
Nazwa 'platformio' nie jest rozpoznawana jako polecenie wewn�trzne lub zewn�trzne,
program wykonywalny lub plik wsadowy.
Error: spawn platformio ENOENT

**Comment by ivankravets** [comment]
What is your OS?

**Comment by ivankravets** [comment]
duplicate of https://github.com/platformio/platformio-atom-ide/issues/1203
