### ISSUE TITLE
Virtualenv Create: Error: spawn

### ISSUE THREAD

**Issue by Schnullerbua** [platformio/platformio-atom-ide#1207]
Virtualenv Create: Error: spawn C:\Users\dr_wa\.platformio\penv\Scripts\python.exe ENOENT

**Comment by ivankravets** [comment]
Please provide an output from system Terminal `cmd`
```
echo %PATH%
echo %PYTHONPATH%
python --version
pip --version
pip list
```

**Comment by ivankravets** [comment]
Please reopen if you still need help
