### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by sexyhexy** [platformio/platformio-atom-ide#1215]
Error: Could not install 'toolchain-xtensa32' with version requirements '~2.50200.0' for your system 'windows_x86'.
If you use Antivirus, it can block PlatformIO Package Manager. Try to disable it for a while.

**Comment by ivankravets** [comment]
Please provide an output from system Terminal `cmd`
```
echo %PATH%
echo %PYTHONPATH%
python --version
pip --version
pip list
```

**Comment by ivankravets** [comment]
Please reopen if you still need help

**Comment by cyberman54** [comment]
I run into exactly the same problem on a windows10 machine. Disabled antivirus.

Python 2.7.14
Pip 9.0.1

**Comment by ivankravets** [comment]
Have you tried these solutions? http://docs.platformio.org/en/latest/faq.html#error-5-access-is-denied

**Comment by Flos** [comment]
Same issue for me. It works if I install it manually, all other solutions failed for me.
Python 2.7.12
pip 9.0.1

after running "platformio update" it reliably breaks again

**Comment by ivankravets** [comment]
@Flos Also Windows? Do you use Antivirus?
