### ISSUE TITLE
pio

### ISSUE THREAD

**Issue by majsi** [platformio/platformio-atom-ide#122]
platformio : The term 'platformio' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct
and try again.
At line:1 char:1
+ platformio update
+ ~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (platformio:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by ivankravets** [comment]
Where do you see that output?

**Comment by majsi** [comment]
I fix it with add to nevironments path
C:\Users\user\.atom\packages\platformio-ide\penv\Scripts

**Comment by ivankravets** [comment]
Hm... IDE should append this to `PATH` automatically. Thanks for the answer.
