### ISSUE TITLE
Show free memory on controller after build

### ISSUE THREAD

**Issue by VanKurt** [platformio/platformio-atom-ide#1220]
After the project has been built it would be great if the amount of free memory on the device would be shown. I.E. the Arduino IDE shows the memory usage in percent, which is really nice and helpful.

Could this feature be added to PlatformIO as well?

**Comment by ivankravets** [comment]
Implemented in the latest PIO Core. Please upgrade.

**Comment by VanKurt** [comment]
Well done, works like a charm.
Thank you so much :+1:
