### ISSUE TITLE
ImportError: No module named Action

### ISSUE THREAD

**Issue by betschart** [platformio/platformio-atom-ide#1224]
Error: [12/03/17 02:06:08] Processing uno (platform: atmelavr; board: uno; framework: arduino)

SCons import failed. Unable to find engine files in:
C:\Users\pb\.platformio\packages\_tmp_installing-7u8uih-package\script\..\engine
C:\Users\pb\.platformio\packages\_tmp_installing-7u8uih-package\script\scons-local-2.5.1
C:\Users\pb\.platformio\packages\_tmp_installing-7u8uih-package\script\scons-local
c:\users\pb\.platformio\penv\scons-2.5.1
c:\users\pb\.platformio\penv\Lib\site-packages\scons-2.5.1
c:\users\pb\.platformio\penv\scons
c:\users\pb\.platformio\penv\Lib\site-packages\scons
Traceback (most recent call last):
File "C:\Users\pb\.platformio\packages\_tmp_installing-7u8uih-package\script\scons", line 190, in <module>
import SCons.Script
File "C:\Users\pb\.platformio\packages\_tmp_installing-7u8uih-package\script\..\engine\SCons\Script\__init__.py", line 75, in <module>
import SCons.Action
ImportError: No module named Action
 [ERROR] Took 2.21 seconds

**Comment by ivankravets** [comment]
Please provide an output from system Terminal `cmd`
```
echo %PATH%
echo %PYTHONPATH%
python --version
pip --version
pip list
```

**Comment by ivankravets** [comment]
Please reopen if you still need help
