### ISSUE TITLE
UnicodeDecodeError: Non-ASCII characters found in build environment

### ISSUE THREAD

**Issue by angelmicelti** [platformio/platformio-atom-ide#1225]
UnicodeDecodeError: Non-ASCII characters found in build environment
See explanation in FAQ > Troubleshooting > Building
http://docs.platformio.org/page/faq.html

 [ERROR] Took 33.62 seconds

**Comment by ivankravets** [comment]
What is your OS? Locale? Do you use the latest version of IDE and PIO Core?

**Comment by ivankravets** [comment]
Please reopen if you still need help
