### ISSUE TITLE
ImportError: No module named SCons.Script

### ISSUE THREAD

**Issue by Cinezaster** [platformio/platformio-atom-ide#1229]
Error: [Mon Dec  4 17:42:30 2017] Processing nodemcuv2 (platform: espressif8266; board: nodemcuv2; framework: arduino)
--------------------------------------------------------------------------------
PlatformManager: Installing espressif8266
Downloading...
Unpacking...
espressif8266 @ 1.4.0 has been successfully installed!
The platform 'espressif8266' has been successfully installed!
The rest of packages will be installed automatically depending on your build environment.
PackageManager: Installing toolchain-xtensa @ ~1.40802.0
Downloading...
Unpacking...
PackageManager: Installing tool-esptool @ ~1.409.0
Downloading...
Unpacking...
PackageManager: Installing framework-arduinoespressif8266 @ ~1.20300.1
Downloading...
Unpacking...
CorePackageManager: Installing tool-scons @ ~3.20501.2
Downloading...
Unpacking...
tool-scons @ 3.20501.2 has been successfully installed!
Traceback (most recent call last):
File "/Users/cinezaster/.platformio/packages/tool-scons/script/scons", line 190, in <module>
import SCons.Script
ImportError: No module named SCons.Script
SCons import failed. Unable to find engine files in:
/Users/cinezaster/.platformio/packages/tool-scons/script/../engine
/Users/cinezaster/.platformio/packages/tool-scons/script/scons-local-2.5.1
/Users/cinezaster/.platformio/packages/tool-scons/script/scons-local
/Users/cinezaster/.platformio/penv/lib/scons-2.5.1
/Users/cinezaster/.platformio/penv/lib/python2.7/site-packages/scons-2.5.1
/Users/cinezaster/.platformio/penv/lib/scons-2.5.1
/Users/cinezaster/.platformio/penv/lib/scons
/Users/cinezaster/.platformio/penv/lib/python2.7/site-packages/scons
/Users/cinezaster/.platformio/penv/lib/scons
========================== [ERROR] Took 36.46 seconds ==========================

**Comment by ivankravets** [comment]
1. Please run in PIO IDE Terminal `pio update`
2. Please remove `/Users/cinezaster/.platformio/packages/tool-scons` and start build again. Does it work now?

**Comment by ivankravets** [comment]
Please reopen if you still need help
