### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by WalterPrech** [platformio/platformio-atom-ide#1237]
Error: [Tue Dec  5 14:30:51 2017] Processing teensy31 (platform: teensy; board: teensy31; framework: arduino)
--------------------------------------------------------------------------------
Verbose mode can be enabled via `-v, --verbose` option
Converting ix_com.ino
Collected 100 compatible libraries
Looking for dependencies...
Error: Could not find `Adafruit-MAX31855` dependency for `CmdMessenger` library
========================== [ERROR] Took 0.82 seconds ==========================

**Comment by ivankravets** [comment]
Resolved in https://github.com/thijse/Arduino-CmdMessenger/pull/33
