### ISSUE TITLE
[Linux Fedora] Can't see any terminal prompt

### ISSUE THREAD

**Issue by thunderbirdtr** [platformio/platformio-atom-ide#124]
# Solution

See https://github.com/platformio/platformio-atom-ide/issues/124#issuecomment-225902576
-----

I have Fedora OS and made clean install system and atom. Then I install python tools via pip and install clang and everything else has installed. But when I click "terminal" I can't see anything on prompt It's just empty no "bash","zsh","sh" nothing is working at all. and here is screenshot;

![spectacle ti6100](https://cloud.githubusercontent.com/assets/1688848/16021098/8cdca654-31b9-11e6-9ee7-ae3a007373ed.png)

Prompt just sit there but I can't type 

Thank you.

**Comment by ivankravets** [comment]
1. Install `gcc` compiler and `npm`
2. Go to `~/.atom/packages/platformio-ide-terminal/node_modules/pty.js` and run `npm install`

**Comment by thunderbirdtr** [comment]
I already have "gcc and "npm" and I ran it and still didn't have terminal.

**Comment by ivankravets** [comment]
Could you provide an output of `npm install` in `node_modules/pty.js`?

**Comment by thunderbirdtr** [comment]
`
> pty.js@0.3.0 install /home/thunderbirdtr/.atom/packages/platformio-ide-terminal/node_modules/pty.js
> node scripts/install.js

make: Entering directory '/home/thunderbirdtr/.atom/packages/platformio-ide-terminal/node_modules/pty.js/build'
  CXX(target) Release/obj.target/pty/src/unix/pty.o
  SOLINK_MODULE(target) Release/obj.target/pty.node
  COPY Release/pty.node
make: Leaving directory '/home/thunderbirdtr/.atom/packages/platformio-ide-terminal/node_modules/pty.js/build'


> pty.js@0.3.0 postinstall /home/thunderbirdtr/.atom/packages/platformio-ide-terminal/node_modules/pty.js
> node scripts/post-install.js

`

**Comment by ivankravets** [comment]
Ok, let's try other hook

1. Change version of `nan` in `pty.js/package.json` from `2.0.5` to `2.3.5`
2. Remove `/pty.js/build` folder
3. Run again `npm install`
4. Restart Atom

**Comment by thunderbirdtr** [comment]
did it and no terminal

**Comment by thunderbirdtr** [comment]
Hello I fixed the problem myself and here is how I done ;

I installed atom-editor from repository which is installing seperating node packages so It's just atom binary and node packages coming from somewhere else. I checked my node and my atom so looks like I have tons of error with deps/unmed/ etc. So I delete atom from my system and install fresh one from "website" just rpm and done I also installed source-way "node"/"npm" and working better now. I have no-deps or unmed issue which is fix my problem. I just made simple test(with serial) and result is ; 

![spectacle j28718](https://cloud.githubusercontent.com/assets/1688848/16037034/5195a21c-3227-11e6-8c99-ff9024a54363.png)

Sorry for trouble
Thank you for help 
(We can close this issue)

**Comment by thunderbirdtr** [comment]
Oh btw before forget "Please add libncurses deps for upload" because It's needed for avr upload

**Comment by ivankravets** [comment]
Do you mean that now you use an Atom package from the system repository?

**Comment by thunderbirdtr** [comment]
Nope I'm using one from website(download and install standalone RPM) >> https://atom.io/download/rpm
I delete repository one from my system.

**Comment by ivankravets** [comment]
1. Install the Atom using 
2. Install `platformio-ide` package from Atom Package Registry

Is it enough? Need to write some comment as final solution and place link on the top of the original comment. I hope that this info will be useful for other users.

Thanks.

**Comment by thunderbirdtr** [comment]
Yes

I install atom from website and install package, install pip packages, install libncurses.so.5(depend on distro package name could be different so I type lib name) and done (Distro : fedora 24)

Thank you

**Comment by ivankravets** [comment]
> install pip packages

Why do you need them? PlatformIO IDE has built-in PlatformIO CLI.

**Comment by thunderbirdtr** [comment]
Ah yeah I notice that later yes. sorry

**Comment by ivankravets** [comment]
Thanks. I've just updated your https://github.com/platformio/platformio-atom-ide/issues/124#issue-160031050
