### ISSUE TITLE
Show build errors (F4) not working

### ISSUE THREAD

**Issue by M0ebiu5** [platformio/platformio-atom-ide#1247]
I've just installed platformio-atom-ide and tried to build espeasy.

Now it shows build errors, but i can only manually scroll through the build log - the shortcuts to show the build errors (F4, ctrl-alt-g) do not work.

Also linter shows some weird error in this line:
`Plugin_022_writeRegister(PCA9685_MODE2, (byte)0x10);`
Error shown is:
`Error	GCC	expected ')' before numeric constant	152:49`

I've tried it in Windows and Linux.
Atom version 1.22.1
PlatformIO 3.5.0rc5

**Comment by ivankravets** [comment]
We have just released a new version [2.7.0](https://github.com/platformio/platformio-atom-ide/releases/tag/v2.7.0), please upgrade.

**Please note that we HIGHLY recommend moving to [PlatformIO IDE for VSCode](https://platformio.org/platformio-ide) which resolves tons of issues and brings a lot of new features.**
