### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by jbmelectric** [platformio/platformio-atom-ide#1249]
Error: [12/09/17 15:36:32] Processing esp12e (platform: espressif8266; lib_deps: Homie; board: esp12e; framework: arduino)

Verbose mode can be enabled via `-v, --verbose` option
Collected 34 compatible libraries
Looking for dependencies...
Error: Could not find `AsyncMqttClient` dependency for `Homie` library
 [ERROR] Took 3.39 seconds

**Comment by ivankravets** [comment]
Please remove global libraries and use 
```
[env:myboard]
platform = espressif8266
board = ...
framework = arduino
lib_deps =
  ArduinoJson@<5.11.0
  Homie
```
