### ISSUE TITLE
Error: You need to specify board ID

### ISSUE THREAD

**Issue by Chistabo** [platformio/platformio-atom-ide#1252]
Error: You need to specify board ID using `-b` or `--board` option. Supported boards list is available via `platformio boards` command

I really do not know which board should I choose, could not find much info about 'platformio boards' with Google, seems this is CPU?

**Comment by ivankravets** [comment]
Please share your `platformio.ini` here.

**Comment by ivankravets** [comment]
Please reopen if you still need help
