### ISSUE TITLE
Error: Please install Git client

### ISSUE THREAD

**Issue by johoberm** [platformio/platformio-atom-ide#1258]
Error: Please install Git client from https://git-scm.com/downloads

Git is installed via initial Setup (Windows Atom)

**Comment by ivankravets** [comment]
Do you see it in PIO IDE Terminal?

```
git --version
```

**Comment by cosmocracy** [comment]
I get this error, too, after fresh Atom/PlatformIO install on Windows 10.

`git --version` output:
```
git version 2.15.1.windows.2
```

**Comment by cosmocracy** [comment]
Screenshot, below, shows error during build (in terminal window) as well as popup error boxes from IDE:

![image](https://user-images.githubusercontent.com/10222432/34323172-7c3bdd34-e80a-11e7-9fcc-6cd0f49a1043.png)

**Comment by cosmocracy** [comment]
(And I restarted Atom after Git install (including multiple reinstall attempts))

**Comment by ivankravets** [comment]
Please check that `git` is in your system PATH. Maybe, OS reboot will help.
