### ISSUE TITLE
Error: Could not install package

### ISSUE THREAD

**Issue by thiaguim18** [platformio/platformio-atom-ide#1262]
Error: Could not install 'framework-arduinoavr' with version requirements '~1.10620.0' for your system 'windows_amd64'.
If you use Antivirus, it can block PlatformIO Package Manager. Try to disable it for a while.

**Comment by ivankravets** [comment]
Please provide an output from system Terminal `cmd`
```
echo %PATH%
echo %PYTHONPATH%
python --version
pip --version
pip list
```

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/1171
