### ISSUE TITLE
Error: Could not load broken JSON

### ISSUE THREAD

**Issue by CaptainRon47** [platformio/platformio-atom-ide#1265]
Error: Could not load broken JSON: C:\Users\Ron\GitHub\kbox-firmware-rz\.piolibdeps\_tmp_installing-lb5xs_-package\library.json

**Comment by CaptainRon47** [comment]
performin a PI build this error showed up in PlatformIO home page?

**Comment by ivankravets** [comment]
Please provide an output from system Terminal `cmd`
```
echo %PATH%
echo %PYTHONPATH%
python --version
pip --version
pip list
```

**Comment by CaptainRon47** [comment]
Ivan,

Below (also attached) is the output you requested. 

 

I have a question about the request to try the staging version.

Could you try staging version? http://docs.platformio.org/en/latest/platforms/espressif8266.html#using-arduino-framework-with-staging-version

 

The ‘esp’ environment of the KBox project program BUILDS without errors, it is the UPLOAD to the Teensy where I get the error.   The instructions you sited only compare the BUILD of the project under the two IDE’s (PlatformIO and Arduino), do you want me to try the UPLOAD in both as well?

 

I did modify the platformio.ini file for the [env:esp] section of the project as below (also attached) and that BUILT successfully, but it did so under the original platform statement (teensy) as well.

 

Thanks,

Ron

 

…

[env:esp]

src_filter = +<common/*>,+<esp/*>

# TODO: enable -Werror once platformio published v2.4 of esp8266/Arduino (pr #3271)

build_flags = -Wall -Isrc/common -Isrc/esp -DHAVE_STRLCPY -DHAVE_STRLCAT

platform = https://github.com/platformio/platform-espressif8266.git#feature/stage

framework = arduino

board = esp_wroom_02

extra_scripts = tools/platformio_cfg_esp.py

lib_ldf_mode = deep

lib_ignore = NMEA2000-Teensy, FlexCAN_Library, Time

lib_deps =

  ${common.lib_deps_common}

  Adafruit NeoPixel

  elapsedMillis

  https://github.com/me-no-dev/ESPAsyncTCP#a57560d

  https://github.com/me-no-dev/ESPAsyncWebServer#63b5303

…

 

 

Please provide an output from system Terminal cmd

echo %PATH%

echo %PYTHONPATH%

python --version

pip --version

pip list

 

C:\Users\Ron>echo %PATH%

C:\Python27\;C:\Python27\Scripts;C:\Program Files\Java\jdk1.8.0_65\bin;C:\Progra

m Files\Common Files\Microsoft Shared\Windows Live;C:\Program Files (x86)\Common

Files\Microsoft Shared\Windows Live;C:\Windows\system32;C:\Windows;C:\Windows\S

ystem32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\

Windows Live\Shared;C:\Program Files (x86)\Common Files\Roxio Shared\DLLShared\;

C:\Program Files (x86)\Common Files\Roxio Shared\OEM\DLLShared\;C:\Program Files

(x86)\Common Files\Roxio Shared\OEM\DLLShared\;C:\Program Files (x86)\Common Fi

les\Roxio Shared\OEM\12.0\DLLShared\;C:\Program Files (x86)\Roxio\OEM\AudioCore\

;C:\Program Files (x86)\QuickTime\QTSystem\;C:\Users\Ron\.gradle\wrapper\dists\g

radle-2.3-bin\7a1ngj6cc7aafikc3uq95v6rn0\gradle-2.3\bin;C:\Users\Ron\.m2\reposit

ory;C:\Program Files (x86)\Java\Jre1.8.0_73;C:\users\Ron\apache-maven-3.3.9\bin;

C:\Program Files\nodejs\;C:\Program Files\LLVM\bin;C:\Program Files\Git\cmd;C:\P

rogram Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\Ron\AppData\R

oaming\npm:C:\cygwin64\bin;C:\Users\Ron\AppData\Local\atom\bin

 

 

C:\Users\Ron>ECHO %PYTHONPATH%

%PYTHONPATH%

 

C:\Users\Ron>python --version

Python 2.7.13

 

C:\Users\Ron>pip --version

pip 9.0.1 from c:\python27\lib\site-packages (python 2.7)

 

C:\Users\Ron>pip list

DEPRECATION: The default format will switch to columns in the future. You can us

e --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.con

f under the [list] section) to disable this warning.

arrow (0.12.0)

backports.functools-lru-cache (1.2.1)

bottle (0.12.13)

certifi (2017.11.5)

chardet (3.0.4)

click (5.1)

colorama (0.3.9)

idna (2.6)

lockfile (0.12.2)

pip (9.0.1)

platformio (3.4.1)

pyserial (3.4)

python-dateutil (2.6.1)

requests (2.18.4)

semantic-version (2.6.0)

setuptools (36.4.0)

six (1.11.0)

urllib3 (1.22)

 

C:\Users\Ron>

**Comment by CaptainRon47** [comment]
Ivan,
Sorry I answered both of your emails here, I should have realized they were for different issues.
Ron

**Comment by ivankravets** [comment]
I don't understand your problem. Please provide a simple project to reproduce this issue.

**Comment by ivankravets** [comment]
Please post 1 report to https://community.platformio.org
