### ISSUE TITLE
WindowsError: [Error 183] Cannot create a file when that file already exist

### ISSUE THREAD

**Issue by thetonto** [platformio/platformio-atom-ide#1271]
Cloning into 'C:\Users\the_d\Documents\PlatformIO\Projects\171216-211454-nodemcuv2\.piolibdeps\_tmp_installing-5wnwtw-package'...
Note: checking out '76e00a046255ae4ac9f61f36af90d8c5fc9828c9'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

Error: Traceback (most recent call last):
  File "c:\users\the_d\.platformio\penv\lib\site-packages\platformio\__main__.py", line 120, in main
    cli(None, None, None)
  File "c:\users\the_d\.platformio\penv\lib\site-packages\click\core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\the_d\.platformio\penv\lib\site-packages\click\core.py", line 680, in main
    rv = self.invoke(ctx)
  File "c:\users\the_d\.platformio\penv\lib\site-packages\click\core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\the_d\.platformio\penv\lib\site-packages\click\core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\the_d\.platformio\penv\lib\site-packages\click\core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "c:\users\the_d\.platformio\penv\lib\site-packages\click\decorators.py", line 16, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "c:\users\the_d\.platformio\penv\lib\site-packages\platformio\commands\init.py", line 102, in cli
    pg = ProjectGenerator(project_dir, ide, env_name)
  File "c:\users\the_d\.platformio\penv\lib\site-packages\platformio\ide\projectgenerator.py", line 38, in __init__
    self._gather_tplvars()
  File "c:\users\the_d\.platformio\penv\lib\site-packages\platformio\ide\projectgenerator.py", line 155, in _gather_tplvars
    self._tplvars.update(self.get_project_build_data())
  File "c:\users\the_d\.platformio\penv\lib\site-packages\platformio\util.py", line 134, in __call__
    value = self.func(*args)
  File "c:\users\the_d\.platformio\penv\lib\site-packages\platformio\ide\projectgenerator.py", line 79, in get_project_build_data
    raise result.exception
WindowsError: [Error 183] Cannot create a file when that file already exists

============================================================

An unexpected error occurred. Further steps:

* Verify that you have the latest version of PlatformIO using
  `pip install -U platformio` command

* Try to find answer in FAQ Troubleshooting section
  http://docs.platformio.org/page/faq.html

* Report this problem to the developers
  https://github.com/platformio/platformio-core/issues

============================================================

**Comment by ivankravets** [comment]
Could you share your `platformio.ini`?

**Comment by thetonto** [comment]
Morning.  
Ini file as requested:

[env:nodemcuv2]
platform = https://github.com/platformio/platform-espressif8266.git#feature/stage
board = nodemcuv2
framework = arduino

lib_deps = https://github.com/marvinroger/homie-esp8266.git#v2.0.0-beta.2

**Comment by ivankravets** [comment]
Could you reproduce this issue again?

**Comment by thetonto** [comment]
Tried, but I get inconsistent results from each build.  Latest is this.  I have unintalled ATOM removed all the directorys and re-installed.  Still errors.  Switched back to using Arduino as that is very solid, thou would like to understand why this does not work. 

Following this guide:
http://marvinroger.github.io/homie-esp8266/docs/2.0.0-beta.2/quickstart/getting-started/

Compiling .pioenvs\nodemcuv2\lib\ESPAsyncTCP_ID305\ESPAsyncTCP.o
Compiling .pioenvs\nodemcuv2\lib\ESPAsyncTCP_ID305\ESPAsyncTCPbuffer.o
Archiving .pioenvs\nodemcuv2\libFrameworkArduino.a
.piolibdeps\ESPAsyncTCP_ID305\src\ESPAsyncTCP.cpp: In constructor 'AsyncClient::AsyncClient(tcp_pcb*)':
.piolibdeps\ESPAsyncTCP_ID305\src\ESPAsyncTCP.cpp:77:28: error: invalid conversion from 'int8_t (*)(void*, tcp_pcb*, pbuf*, int8_t) {aka signed char (*)(void*, 

tcp_pcb*, pbuf*, signed char)}' to 'tcp_recv_fn {aka long int (*)(void*, tcp_pcb*, pbuf*, long int)}' [-fpermissive]
tcp_recv(_pcb, &_s_recv);
^


Severity | Provider | Description | Line
-- | -- | -- | --



Severity | Provider | Description | Line
-- | -- | -- | --



Severity | Provider | Description | Line
-- | -- | -- | --

**Comment by thetonto** [comment]
Switch to another Git Lib and this message appears.  (seen this alot of times)
; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; http://docs.platformio.org/page/projectconf.html
 
[env:nodemcuv2]
platform = https://github.com/platformio/platform-espressif8266.git#feature/stage
board = nodemcuv2
framework = arduino
 
lib_deps = https://github.com/marvinroger/homie-esp8266.git#v2.0.0-beta.1
 

32.2 s
platformio run --target upload
If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:
 
  git checkout -b <new-branch-name>
 
Checking out files: 100% (111/111), done.
Error: Traceback (most recent call last):

  File "c:\users\the_d\.platformio\penv\lib\site-packages\platformio\__main__.py", line 120, in main
    cli(None, None, None)
  File "c:\users\the_d\.platformio\penv\lib\site-packages\click\core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\the_d\.platformio\penv\lib\site-packages\click\core.py", line 680, in main
    rv = self.invoke(ctx)
  File "c:\users\the_d\.platformio\penv\lib\site-packages\click\core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
Linter
Severity 	Provider 	Description	Line

**Comment by ivankravets** [comment]
```ini
[env:nodemcuv2]
platform = https://github.com/platformio/platform-espressif8266.git#feature/stage
board = nodemcuv2
framework = arduino

lib_deps = 
  ArduinoJson@<5.11.0
  https://github.com/marvinroger/homie-esp8266.git#v2.0.0-beta.2
```

**Comment by thetonto** [comment]
Error is now

[env:nodemcuv2]
platform = https://github.com/platformio/platform-espressif8266.git#feature/stage
board = nodemcuv2
framework = arduino
 
lib_deps =
  ArduinoJson@<5.11.0
  https://github.com/marvinroger/homie-esp8266.git#v2.0.0-beta.2
 

187.0 s
platformio run
Compiling .pioenvs\nodemcuv2\lib\ESPAsyncTCP_ID305\AsyncPrinter.o
Compiling .pioenvs\nodemcuv2\lib\ESPAsyncTCP_ID305\ESPAsyncTCP.o
Compiling .pioenvs\nodemcuv2\lib\ESPAsyncTCP_ID305\ESPAsyncTCPbuffer.o
Archiving .pioenvs\nodemcuv2\libFrameworkArduino.a
Compiling .pioenvs\nodemcuv2\lib\ESPAsyncTCP_ID305\SyncClient.o
.piolibdeps\ESPAsyncTCP_ID305\src\ESPAsyncTCP.cpp: In constructor 'AsyncClient::AsyncClient(tcp_pcb*)':
.piolibdeps\ESPAsyncTCP_ID305\src\ESPAsyncTCP.cpp:77:28: error: invalid conversion from 'int8_t (*)(void*, tcp_pcb*, pbuf*, int8_t) {aka signed char (*)(void*, 

tcp_pcb*, pbuf*, signed char)}' to 'tcp_recv_fn {aka long int (*)(void*, tcp_pcb*, pbuf*, long int)}' [-fpermissive]
tcp_recv(_pcb, &_s_recv);
^
In file included from .piolibdeps\ESPAsyncTCP_ID305\src\ESPAsyncTCP.cpp:27:0:
Linter
Severity 	Provider 	Description	Line 

Note: this is all compiling fine over on Arduino

**Comment by ivankravets** [comment]
Sorry, I corrected config above. Please use the latest HOMIE version.

**Comment by thetonto** [comment]
And back to this error.    Not sure what is going on here.  All this compiles great on ArdunProject
171216-211454-nodemcuv2
lib
src
.gitignore
.travis.yml
platformio.ini
Test Homie
lib
src
.gitignore
.travis.yml
platformio.ini
platformio.ini — 171216-211454-nodemcuv2
PlatformIO Home
platformio.ini — Test Homie
1

; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; http://docs.platformio.org/page/projectconf.html
 
[env:nodemcuv2]
platform = https://github.com/platformio/platform-espressif8266.git#feature/stage
board = nodemcuv2
framework = arduino
 
lib_deps =
  ArduinoJson@<5.11.0
  https://github.com/marvinroger/homie-esp8266.git
 

48.3 s
platformio run
  `pip install -U platformio` command
 
* Try to find answer in FAQ Troubleshooting section
  http://docs.platformio.org/page/faq.html
 
* Report this problem to the developers
  https://github.com/platformio/platformio-core/issues

 
============================================================
 
 
Linter
Severity 	Provider 	Description	Line 
PIO Buildplatformio.ini00018:51
MixedUTF-8INI0 files
C/C++ project index rebuild failed
Cloning into 'C:\Users\the_d\Documents\PlatformIO\Projects\Test Homie\.piolibdeps\_tmp_installing-ydhm4a-package'...
Checking out files:  26% (32/119)   
Checking out files:  27% (33/119)   
Checking out files:  28% (34/119)   
Checking out files:  29% (35/119)   
Checking out files:  30% (36/119)   
Checking out files:  31% (37/119)   
Checking out files:  32% (39/119)   
Checking out files:  33% (40/119)   
Checking out files:  34% (41/119)   
Checking out files:  35% (42/119)   
Checking out files:  36% (43/119)   
Checking out files:  37% (45/119)   
Checking out files:  38% (46/119)   
Checking out files:  39% (47/119)   
Checking out files:  40% (48/119)   
Checking out files:  41% (49/119)   
Checking out files:  42% (50/119)   
Checking out files:  43% (52/119)   
Checking out files:  44% (53/119)   
Checking out files:  45% (54/119)   
Checking out files:  46% (55/119)   
Checking out files:  47% (56/119)   
Checking out files:  48% (58/119)   
Checking out files:  49% (59/119)   
Checking out files:  50% (60/119)   
Checking out files:  51% (61/119)   
Checking out files:  52% (62/119)   
Checking out files:  53% (64/119)   
Checking out files:  54% (65/119)   
Checking out files:  55% (66/119)   
Checking out files:  56% (67/119)   
Checking out files:  57% (68/119)   
Checking out files:  58% (70/119)   
Checking out files:  59% (71/119)   
Checking out files:  60% (72/119)   
Checking out files:  61% (73/119)   
Checking out files:  62% (74/119)   
Checking out files:  63% (75/119)   
Checking out files:  64% (77/119)   
Checking out files:  65% (78/119)   
Checking out files:  66% (79/119)   
Checking out files:  67% (80/119)   
Checking out files:  68% (81/119)   
Checking out files:  69% (83/119)   
Checking out files:  70% (84/119)   
Checking out files:  71% (85/119)   
Checking out files:  72% (86/119)   
Checking out files:  73% (87/119)   
Checking out files:  74% (89/119)   
Checking out files:  75% (90/119)   
Checking out files:  76% (91/119)   
Checking out files:  77% (92/119)   
Checking out files:  78% (93/119)   
Checking out files:  78% (94/119)   
Checking out files:  79% (95/119)   
Checking out files:  80% (96/119)   
Checking out files:  81% (97/119)   
Checking out files:  82% (98/119)   
Checking out files:  83% (99/119)   
Checking out files:  84% (100/119)   
Checking out files:  85% (102/119)   
Checking out files:  86% (103/119)   
Checking out files:  87% (104/119)   
Checking out files:  88% (105/119)   
Checking out files:  89% (106/119)   
Checking out files:  90% (108/119)   
Checking out files:  91% (109/119)   
Checking out files:  92% (110/119)   
Checking out files:  93% (111/119)   
Checking out files:  94% (112/119)   
Checking out files:  95% (114/119)   
Checking out files:  96% (115/119)   
Checking out files:  97% (116/119)   
Checking out files:  98% (117/119)   
Checking out files:  99% (118/119)   
Checking out files: 100% (119/119)   
Checking out files: 100% (119/119), done.
Error: Traceback (most recent call last):
  File "c:\users\the_d\.platformio\penv\lib\site-packages\platformio\__main__.py", line 120, in main
    cli(None, None, None)
  File "c:\users\the_d\.platformio\penv\lib\site-packages\click\core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\the_d\.platformio\penv\lib\site-packages\click\core.py", line 680, in main
    rv = self.invoke(ctx)
  File "c:\users\the_d\.platformio\penv\lib\site-packages\click\core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\the_d\.platformio\penv\lib\site-packages\click\core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\the_d\.platformio\penv\lib\site-packages\click\core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "c:\users\the_d\.platformio\penv\lib\site-packages\click\decorators.py", line 16, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "c:\users\the_d\.platformio\penv\lib\site-packages\platformio\commands\init.py", line 102, in cli
    pg = ProjectGenerator(project_dir, ide, env_name)
  File "c:\users\the_d\.platformio\penv\lib\site-packages\platformio\ide\projectgenerator.py", line 38, in __init__
    self._gather_tplvars()
  File "c:\users\the_d\.platformio\penv\lib\site-packages\platformio\ide\projectgenerator.py", line 155, in _gather_tplvars
    self._tplvars.update(self.get_project_build_data())
  File "c:\users\the_d\.platformio\penv\lib\site-packages\platformio\util.py", line 134, in __call__
    value = self.func(*args)
  File "c:\users\the_d\.platformio\penv\lib\site-packages\platformio\ide\projectgenerator.py", line 79, in get_project_build_data
    raise result.exception
WindowsError: [Error 2] The system cannot find the file specified

============================================================

An unexpected error occurred. Further steps:

* Verify that you have the latest version of PlatformIO using
  `pip install -U platformio` command

* Try to find answer in FAQ Troubleshooting section
  http://docs.platformio.org/page/faq.html

* Report this problem to the developers
  https://github.com/platformio/platformio-core/issues

============================================================

**Comment by ivankravets** [comment]
Please open PIO IDE Terminal and type `pio run`. Do you see any errors?

**Comment by thetonto** [comment]
Same errors as before

**Comment by thetonto** [comment]
.piolibdeps\ESPAsyncTCP_ID305\src\ESPAsyncTCP.cpp: In constructor 'AsyncClient::AsyncClient(tcp_pcb*)':
.piolibdeps\ESPAsyncTCP_ID305\src\ESPAsyncTCP.cpp:77:28: error: invalid conversion from 'int8_t (*)(void*, tcp_pcb*, pbuf*, int8_t) {aka signed char (*)(void*,
 tcp_pcb*, pbuf*, signed char)}' to 'tcp_recv_fn {aka long int (*)(void*, tcp_pcb*, pbuf*, long int)}' [-fpermissive]
tcp_recv(_pcb, &_s_recv);

**Comment by ivankravets** [comment]
Ok, it seems that issue relates to a specific library. Please explain in details here http://community.platformio.org/
