### ISSUE TITLE
Project won't compile, it requires an internet connection.

### ISSUE THREAD

**Issue by aguaviva** [platformio/platformio-atom-ide#1273]
> [12/16/17 14:06:17] Processing nodemcu (monitor_baud: 115200; platform: espressif8266; lib_deps: ESPAsyncTCP, ESP Async WebServer, ESPAsyncWiFiManager; board: nodemcu; fram
> ework: arduino)
>  
> Error: You are not connected to the Internet

**Comment by ivankravets** [comment]
You need internet first time to install all dependencies. The second build should work without Internet.

**Comment by aguaviva** [comment]
Thanks! I'd be great if the error message could mention your explanation.

**Comment by ivankravets** [comment]
Thanks, explained in https://github.com/platformio/platformio-core/commit/efceb5db72917b861b9a6d7dc03adb9f11be68db !

**Comment by aguaviva** [comment]
That was quick! :) Thanks for this great tool :D
