### ISSUE TITLE
after auto update to 2.0.0-rc.4 PlatformIO is no longer working  

### ISSUE THREAD

**Issue by wurmtal868** [platformio/platformio-atom-ide#1288]
I see issues https://github.com/platformio/platformio-atom-ide/issues/1287 and https://github.com/platformio/platformio-atom-ide/issues/1286 
Closing the pop ups result in a useless Atom

**Comment by ivankravets** [comment]
Try to restart IDE. Should work now.

**Comment by wurmtal868** [comment]
It's working thanks,
What was wrong?

**Comment by ivankravets** [comment]
Typo in https://github.com/platformio/platformio-core/commit/1171cb204c8c5ef3eb379f94e66754eda43c310f

Thanks a lot for the report!

**Comment by wurmtal868** [comment]
I see, 
Thanks for quick response!
