### ISSUE TITLE
Uncaught Error: Could not start PIO Home server: 

### ISSUE THREAD

**Issue by chamithchathuka** [platformio/platformio-atom-ide#1289]
PlatformIO Atom - MacOS - High Sierra error

<img width="1029" alt="screen shot 2017-12-19 at 9 10 03 pm" src="https://user-images.githubusercontent.com/17052727/34164976-05b3a18a-e501-11e7-91d1-0df757964876.png">

Could not open the IDE, deleted the package, removed all contents and reinstalled the atom.

**Comment by ivankravets** [comment]
Please open PIO IDE Terminal and type `pio upgrade --dev`. Should work now.

**Comment by chamithchathuka** [comment]
@ivankravets  Thanks it worked after the command and restarted! thanks
