### ISSUE TITLE
fatal: I don't handle protocol ' https'

### ISSUE THREAD

**Issue by tomathivanan** [platformio/platformio-atom-ide#1293]
Cloning into 'C:\Users\xx\.platformio\platforms\_tmp_installing-28jzsf-package'...
fatal: I don't handle protocol ' https'
Error: VCS: Could not process command ['git', 'clone', '--recursive', '--depth', '1', '--branch', 'feature/stage', ' https://github.com/platformio/platform-espressif8266.git', 'C:\\Users\\xx\\.platformio\\platforms\\_tmp_installing-28jzsf-package']

**Comment by ivankravets** [comment]
Could you share your `platformio.ini`?

**Comment by ivankravets** [comment]
Please reopen if you still need help
