### ISSUE TITLE
PIP: Unable to create process

### ISSUE THREAD

**Issue by TheComputerM** [platformio/platformio-atom-ide#1299]
PIP: Unable to create process using 'C:\Users\Lenovo Yoga\.platformio\penv\python.exe "C:\Users\Lenovo Yoga\.platformio\penv\Scripts\pip-script.py" install -U https://github.com/platformio/platformio/archive/develop.zip'

**Comment by ivankravets** [comment]
Do you have some software on a system which could block PlatformIO? Antivirus or etc? Could you block it for a while?

**Comment by ivankravets** [comment]
Please reopen if you still need help
