### ISSUE TITLE
Arduino IDE works while compiling, but platformio fails.

### ISSUE THREAD

**Issue by Gtrxs** [platformio/platformio-atom-ide#1303]
Example code: 

void setup() {

}

void loop()
{

long duration, inches, cm;

inches = microsecondsToInches(duration);
cm = microsecondsToCentimeters(duration);

delay(100);
}

long microsecondsToInches(long microseconds)
{

return microseconds / 74 / 2;
}

long microsecondsToCentimeters(long microseconds)
{

return microseconds / 29 / 2;
}

Works in the arduino IDE, while in the platformio ide in atom returns:

src/main.cpp: In function 'void loop()':
src/main.cpp:40:39: error: 'microsecondsToInches' was not declared in this scope
inches = microsecondsToInches(duration);
^
src/main.cpp:41:40: error: 'microsecondsToCentimeters' was not declared in this scope
cm = microsecondsToCentimeters(duration);
^
*** [.pioenvs/uno/src/main.o] Error 1

**Comment by ivankravets** [comment]
See http://docs.platformio.org/en/latest/faq.html#convert-arduino-file-to-c-manually

or change extension to INO
