### ISSUE TITLE
.gitignore Overwritten on Rebuild Project Index

### ISSUE THREAD

**Issue by plasticrake** [platformio/platformio-atom-ide#133]
My **.gitignore** file is overwritten each time I save changes to my platformio.ini file or **Rebuild C/C++ Project Index** is run.

**Comment by ivankravets** [comment]
This issue is related to PlatformIO CLI. Please move it to https://github.com/platformio/platformio/issues

P.S: Sorry that we forward you again. I'll fix it when you move the issue.

**Comment by ivankravets** [comment]
Fixed in https://github.com/platformio/platformio/commit/5cd3f9d84dfed77fc0f67baacee138dbd7507102
