### ISSUE TITLE
Problem occured while upgrading PlatformIO IDE

### ISSUE THREAD

**Issue by jphilip09** [platformio/platformio-atom-ide#1334]
Error: /snap/atom/109/usr/share/atom/resources/app/apm/bin/apm: line 63: 17782 Segmentation fault      (core dumped) "$binDir/$nodeBin" "$cliPath" "$@"

    at /home/pjoseph/.atom/packages/platformio-ide/lib/installer/ide.js:59:9
    at Generator.throw (<anonymous>)
    at step (/home/pjoseph/.atom/packages/platformio-ide/lib/installer/ide.js:176:2)

**Comment by ivankravets** [comment]
Please navigate to Atom > Settings > Updates and update packages manually
