### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by yaccard** [platformio/platformio-atom-ide#1343]
Usage: platformio-script.py init 

           [OPTIONS]

Error: Invalid value for "--ide": invalid choice: atom. (choose from clion, codeblocks, eclipse, emacs, netbeans, qtcreator, sublimetext, vim, visualstudio, vscode)

**Comment by ivankravets** [comment]
1. http://docs.platformio.org/en/latest/faq.html#multiple-pio-cores-in-a-system
2. Try to remove `%HOME_DIR%/.platformio/penv` folder and restart IDE.
