### ISSUE TITLE
Platformio doesn't generate EEPROM HEX

### ISSUE THREAD

**Issue by Trel725** [platformio/platformio-atom-ide#135]
If using placing constants into EEPROM memory, it is necessary to generate appropriate HEX file to program EEPROM. Platformio doesn't do that.

From Atmel reference:
> If we specify the EEPROM segment, we can generate a .hex file that can be used to program the EEPROM:
$ avr-objcopy -j .eeprom --change-section-lma .eeprom=0 -O ihex demo.elf demo_eeprom.hex

**Comment by ivankravets** [comment]
Please move this issue to PlatformIO CLI repository https://github.com/platformio/platformio/issues

**Comment by ivankravets** [comment]
You need to call `pio run -t uploadeep` from the PlatformIO IDE Terminal.

Does it work for you?

**Comment by Trel725** [comment]
Yes it does. I am sorry, but it is not obvious from CLI help.

**Comment by KenwoodFox** [comment]
Is there a way to generate the eep file without uploading it as well?

**Comment by zharovdv** [comment]
> Is there a way to generate the eep file without uploading it as well?

My way is:

eeprom.py
```
from os.path import join

Import("env")

env.Depends(join("$BUILD_DIR", "${PROGNAME}.hex"), join("$BUILD_DIR", "${PROGNAME}.eep"))
```

platformio.ini

`extra_scripts = eeprom.py`
