### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by alifeinbinary** [platformio/platformio-atom-ide#1350]
PIP: Error: spawn /Volumes/Macintosh HD/strangeways/.platformio/penv/bin/pip ENOENT

I just reinstalled MacOS High Sierra and haven't installed python3 or pip yet. Will do right now and update if error disappears.

**Comment by ivankravets** [comment]
Just remove `/Volumes/Macintosh HD/strangeways/.platformio/penv` folder and restart IDE
