### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by Overfinch** [platformio/platformio-atom-ide#1351]
Error: [01/07/18 01:29:25] Processing uno (platform: atmelavr; board: uno; framework: arduino)

SCons import failed. Unable to find engine files in:
C:\Users\bundi\.platformio\packages\_tmp_installing-e_vyoe-package\script\..\engine
C:\Users\bundi\.platformio\packages\_tmp_installing-e_vyoe-package\script\scons-local-2.5.1
C:\Users\bundi\.platformio\packages\_tmp_installing-e_vyoe-package\script\scons-local
c:\users\bundi\.platformio\penv\scons-2.5.1
c:\users\bundi\.platformio\penv\Lib\site-packages\scons-2.5.1
c:\users\bundi\.platformio\penv\scons
c:\users\bundi\.platformio\penv\Lib\site-packages\scons
Traceback (most recent call last):
File "C:\Users\bundi\.platformio\packages\_tmp_installing-e_vyoe-package\script\scons", line 190, in <module>
import SCons.Script
File "C:\Users\bundi\.platformio\packages\_tmp_installing-e_vyoe-package\script\..\engine\SCons\Script\__init__.py", line 75, in <module>
import SCons.Action
ImportError: No module named Action
 [ERROR] Took 0.33 seconds

**Comment by ivankravets** [comment]
Fixed in https://github.com/platformio/platformio-core/commit/ae38d17b7f422c5be24b74f14d3c0fcf92f689e3

Please open PIO IDE Terminal and type `pio upgrade --dev` and restart IDE.
