### ISSUE TITLE
platfromio home page can't load

### ISSUE THREAD

**Issue by talkingbeast** [platformio/platformio-atom-ide#1353]
hi,everyone.
 i have met this problem seveal times.
 the problem is when i click the platformio home button,the platformio home page don't show.
![screenshot from 2018-01-06 23-08-40](https://user-images.githubusercontent.com/17403867/34646454-af181614-f336-11e7-9bfa-b80f3cfe5b62.png)

  i search for the solution,delete the /home/talkingbeast/.platformio folder works and restart atom works.
![screenshot from 2018-01-06 23-11-18](https://user-images.githubusercontent.com/17403867/34646464-f3d0bf0e-f336-11e7-8551-2ed69135b05c.png)

but the problem is very  annoying and this experience is sucks.BTW,this solution is temperary,the same problem will happed after several days.
can someone give me some advice to solve the problem.

**Comment by ivankravets** [comment]
What is your OS/distro?

Please provide an output from a system Terminal
```
echo $PATH
echo $PYTHONPATH
python --version
pip --version
pip list
```

**Comment by talkingbeast** [comment]
this is the output of my system terminal:

``

**Comment by ivankravets** [comment]
Next time when you will have a problem with PIO Home, please open PIO IDE Terminal and type `pio home`. You will some errors. Please share them here. Thanks!

**Comment by talkingbeast** [comment]
sure thing.thank you. @ivankravets
