### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by hjindr** [platformio/platformio-atom-ide#1359]
Hello, anybody knows to help?

Error: [01/09/18 10:33:26] Processing esp12e (platform: espressif8266; board: esp12e; framework: arduino)

Verbose mode can be enabled via `-v, --verbose` option
Collected 32 compatible libraries
Scanning dependencies...
Library Dependency Graph ( http://bit.ly/configure-pio-ldf )
|-- <ESP8266WiFi> v1.0
|-- <uMQTTBroker> v1.0.0

*** Multiple ways to build the same target were specified for: C:\Users\Jindra01\Documents\PlatformIO\Projects\180109-084117-esp12e\.pioenvs\esp12e\libb4f\uMQTTBroker_ID1972\MQTT.o  (from ['C:\\Users\\Jindra01\\.platformio\\lib\\uMQTTBroker_ID1972\\src\\MQTT.cpp'] and from ['C:\\Users\\Jindra01\\.platformio\\lib\\uMQTTBroker_ID1972\\src\\MQTT.c'])
File "C:\Users\Jindra01\.platformio\penv\lib\site-packages\platformio\builder\tools\platformio.py", line 273, in BuildLibrary
 [ERROR] Took 2.34 seconds

**Comment by ivankravets** [comment]
Please file an issue here https://github.com/martin-ger/uMQTTBroker/issues and ask a developer to resolve `MQTT.cpp` and `MQTT.c`. PIO builds file to NAME.o and 2 files with the same name are conflicting.
