### ISSUE TITLE
Still crashes under windows 7 when loading home screen

### ISSUE THREAD

**Issue by wsnell** [platformio/platformio-atom-ide#1361]
Still crashes under windows 7 when loading home screen.  Even after I dir the pio update action requested in other bug report.

Uncaught Error: Could not start PIO Home server: Traceback (most recent call last): File "main.py", line 13, in init main File "C:\Users\wsnell.platformio\penv\lib\site-packages\platformio\app.py", line 24, in import requests File "C:\Users\wsnell.platformio\penv\lib\site-packages\requests__init.py", line 43, in import urllib3 File "C:\Users\wsnell.platformio\penv\lib\site-packages\urllib3\init__.py", line 8, in from .connectionpool import ( File "C:\Users\wsnell.platformio\penv\lib\site-packages\urllib3\connectionpool.py", line 7, in from socket import error as SocketError, timeout as SocketTimeout File "C:\Users\wsnell.platformio\penv\lib\socket.py", line 47, in import _socket ImportError: DLL load failed: The specified procedure could not be found.
C:\Users\wsnell\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\lib\index.js:1571
Show Stack Trace

![image](https://user-images.githubusercontent.com/33472290/34752698-bfc4a9da-f568-11e7-9709-6a64c222ec34.png)

The error was thrown from the platformio-ide package. This issue has already been reported.

**Comment by ivankravets** [comment]
Have you tried this solution? https://github.com/platformio/platformio-atom-ide/issues/1223#issuecomment-352085982

**Comment by ivankravets** [comment]
Please reopen if you still need help
