### ISSUE TITLE
ImportError: No module named zlib

### ISSUE THREAD

**Issue by thiminhnhut** [platformio/platformio-atom-ide#1375]
Virtualenv Create: Traceback (most recent call last):
  File "/home/minhnhut/.platformio/.cache/tmp-49564hIMjN7dw5uk/virtualenv-14.0.6/virtualenv.py", line 22, in <module>
    import zlib
ImportError: No module named zlib

**Comment by ivankravets** [comment]
Please provide an output from a system Terminal
```
echo $PATH
echo $PYTHONPATH
python --version
pip --version
pip list
```

**Comment by ivankravets** [comment]
Please reopen if you still need help
