### ISSUE TITLE
'platformio' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by captainwasabi** [platformio/platformio-atom-ide#138]
Updated platformio

Click on build from the toolbar.

'platformio' is not recognized as an internal or external command,
operable program or batch file.

However, all the commands work fine in the shell.

Windows 10

**Comment by ivankravets** [comment]
Do you use the latest 1.3.1 version of IDE?

It should be fixed here https://github.com/platformio/platformio-atom-ide/issues/134

**Comment by captainwasabi** [comment]
yes, just upgraded this morning.  There were some issues and I had to uninstall and reinstall.

**Comment by ivankravets** [comment]
>  There were some issues 

We know about these issues and they are fixed in this 1.3.1. You will not see these errors for the next update

----

Did it work before with 1.3.0?

**Comment by captainwasabi** [comment]
also now getting this trying to open a serial monitor:

io -f -c atom serialports monitor --port COM7
could not open port u'COM7': could not open port u'COM7': WindowsError(5, 'Access is denied.')

**Comment by captainwasabi** [comment]
Ivan, I am on 1.3.1, that is what I installed.  Not sure what version I was on before.  I just installed it last week, so probably 1.3.0, and it did work.

**Comment by ivankravets** [comment]
Could you provide me [TeamViewer](https://www.teamviewer.com) session for debug?

**Comment by captainwasabi** [comment]
check your personal email

--

**Comment by captainwasabi** [comment]
solved. Atom wasn't upgrading to latest.  I'll leave this open for your notes.

**Comment by ivankravets** [comment]
Thanks, we are working on the new installers for PlatformIO IDE with the latest Atom 1.8.0
