### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by saouinet** [platformio/platformio-atom-ide#1381]
Conda Virtualenv: 
CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://repo.continuum.io/pkgs/pro/win-64/repodata.json.bz2>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
ProxyError(MaxRetryError("HTTPSConnectionPool(host='repo.continuum.io', port=443): Max retries exceeded with url: /pkgs/pro/win-64/repodata.json.bz2 (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 407 Proxy Authentication Required',)))",),)

I ran on a work machine with not opened network access. Could it be possible to set the proxy in the Atom ide?
Best regards

**Comment by ivankravets** [comment]
similar to this https://wiki.archlinux.org/index.php/proxy_settings
