### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by ellingsson** [platformio/platformio-atom-ide#1390]
Error: [Sun Jan 14 22:15:03 2018] Processing esp32dev (platform: espressif32; board: esp32dev; framework: arduino)
--------------------------------------------------------------------------------
Verbose mode can be enabled via `-v, --verbose` option
Collected 25 compatible libraries
Scanning dependencies...
Error: Could not find `ESPAsyncWebServer` dependency for `Basecamp` library
========================== [ERROR] Took 0.86 seconds ==========================

**Comment by ellingsson** [comment]
Thanks for a great IDE. It seems that the dependency states "ESPAsyncWebServer" while the package name is "ESP Async Webserver". Is this the case?

**Comment by ivankravets** [comment]
Fixed in https://github.com/merlinschumacher/Basecamp/pull/13

Please wait when PR will be merged and PIO update this library.
