### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by westward** [platformio/platformio-atom-ide#1393]
Error: Could not install 'framework-arduinoespressif8266' with version requirements '~1.20400.0' for your system 'windows_amd64'.
More details: http://bit.ly/faq-package-manager

**Comment by ivankravets** [comment]
Have you read this http://bit.ly/faq-package-manager ?

Did you try all solutions?

**Comment by ivankravets** [comment]
Please reopen if you still need help

**Comment by westward** [comment]
Ivan,
The IDE offered me a dialog with a button like Submit report and I confirmed it. No more and no less.

**Comment by ivankravets** [comment]
Does it work now?

**Comment by westward** [comment]
Probably yes.
The trouble happens on a PlatformIO Home page. The IDE displayed a red bullet notification about two available Platforms updates: AtmelAVR and Espressif 8266. On a update of second one the error happens. When IDE was restarted, the update notification and error disappears. Don't know has it auto fixed or just hidden. As I may see, now IDE works.
