### ISSUE TITLE
PlatformIO Home: "Show at startup" checkbox not working

### ISSUE THREAD

**Issue by wurmtal868** [platformio/platformio-atom-ide#1395]
### Configuration

**Operating system**: Windows 7

**PlatformIO Version** (`platformio --version`): Home 0.6.1·Core 3.5.1a6

### Description of problem
"Show at startup" has no effect. PlatformIO Home will be shown no matter if the box is checked or not

#### Steps to Reproduce

1. Uncheck "Show at startup" on Home tab
2. Close the HOME tab
3. Restart Atom.IO 

### Actual Results

Atom.IO will open PlatformIO Home tab in foreground

### Expected Results

Atom.IO should restore the last state of tabs without the PlatformIO Home tab

**Comment by ivankravets** [comment]
Did you overwrite HOME environment variable?

**Comment by wurmtal868** [comment]
I have a HOME variable defined in Win 7 and PlatformIO is using this folder. I have not defined any HOME in PlatformIO-IDE

**Comment by ivankravets** [comment]
It seems that JS does not handle it in the same way as Python does. Please add extra http://docs.platformio.org/en/latest/envvars.html#envvar-PLATFORMIO_HOME_DIR environment variable.

**Comment by wurmtal868** [comment]
The extra HOME variable did the trick. 
This is nothing I would do intuitive.

**Comment by ivankravets** [comment]
Ok, let's debug it together. 

https://github.com/atom/fs-plus/blob/master/src/fs-plus.coffee#L20

Please provide an output of

```
echo %HOME%
echo %USERPROFILE%
```

**Comment by wurmtal868** [comment]
Here is the output:

C:\Users\wurmtal>echo %HOME%
c:\home

C:\Users\wurmtal>echo %USERPROFILE%
C:\Users\wurmtal

**Comment by ivankravets** [comment]
Good, I made PR https://github.com/atom/fs-plus/pull/44

If they don't merge it, I'll implement own `getHomeDirectory` for Node.JS.

**Comment by ivankravets** [comment]
Should work in the latest release

**Comment by wurmtal868** [comment]
I removed the environment variable.
It's working fine.
Thanks!
