### ISSUE TITLE
Missing build

### ISSUE THREAD

**Issue by amittel** [platformio/platformio-atom-ide#14]
Hi!
Just installed the package via Atom.
But https://atom.io/packages/build was missing.
Installed it by hand, restarted Atom and now build works.

**Comment by ivankravets** [comment]
Which is your OS?

**Comment by amittel** [comment]
Ah, sorry. My bad.
* Win7 pro SP1
* Atom 1.4.0
* PlatformIO IDE 0.1.0 | CLI 2.8.0.dev2

**Comment by ivankravets** [comment]
Hm. Could you try installation from the scratch?

Go to "settings" and remove all packages. Then install them. Thanks.

**Comment by ivankravets** [comment]
Do you have problems with the latest PlatformIO IDE?

**Comment by amittel** [comment]
Since I installed the build package by hand, I had no problems in the first place. After the update everything is still working fine.
I think it was only a problem on my system.

**Comment by ivankravets** [comment]
Thanks! What is your impression from the PlatformIO IDE beta? 

P.S: Don't forget to give us a start :star: https://github.com/platformio/platformio-atom-ide/stargazers

**Comment by amittel** [comment]
Looking good!
Already had the inoffical predecessor installed.

**Comment by ivankravets** [comment]
> Already had the inoffical predecessor installed.

Which type?

**Comment by amittel** [comment]
This one: https://atom.io/packages/platomformio
