### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by supereng** [platformio/platformio-atom-ide#1408]
Usage: platformio init [OPTIONS]

Error: Invalid value for "--project-dir" / "-d": Directory "/home/hb/Dropbox/Electronix/Arduino/Projects/PID-Temp-Control/WaterBath_LCD_23_3_2017" is not writable.
UBUNTU OS

**Comment by ivankravets** [comment]
Please fix permissions for /home/hb/Dropbox/Electronix/Arduino/Projects/PID-Temp-Control/WaterBath_LCD_23_3_2017
