### ISSUE TITLE
Don't stop serial monitor during upload if upload uses OTA

### ISSUE THREAD

**Issue by andig** [platformio/platformio-atom-ide#141]
That would allow monitoring debug output during the OTA upload process, e.g. for the espressif platform.
##

**Comment by ashthespy** [comment]
Would this be a difficult thing to integrate? It would be extremely handy!

**Comment by ivankravets** [comment]
1. Install the latest PIO IDE 2.0
2. Menu: PlatformIO > Settings > PIO IDE
3. Uncheck "Automatically close Serial port"
