### ISSUE TITLE
Error: Could not find ualloc dependency for mbed-drivers library

### ISSUE THREAD

**Issue by baldwin1974** [platformio/platformio-atom-ide#1417]
Error: [Sun Jan 21 09:48:47 2018] Processing disco_f469ni (platform: ststm32; board: disco_f469ni; framework: mbed)
--------------------------------------------------------------------------------
Verbose mode can be enabled via `-v, --verbose` option
Collected 16 compatible libraries
Scanning dependencies...
Error: Could not find `ualloc` dependency for `mbed-drivers` library
========================== [ERROR] Took 3.79 seconds ==========================

NOTES: (1) can't view PIO Core Call error log (no scrolling possible)
(2) this occurs on initiating a new project

**Comment by ivankravets** [comment]
Have you resolved this issue?

**Comment by baldwin1974** [comment]
I could not get platformio to recognize the library, so I took a break.  I think, however, it must be user error, as I am pretty new at this.  I will close the issue.

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/1356
