### ISSUE TITLE
Error: VCS: Could not process command

### ISSUE THREAD

**Issue by fork04** [platformio/platformio-atom-ide#1418]
Cloning into 'C:\Users\fork\espurna\code\.piolibdeps\_tmp_installing-kdpgfg-package'...
error: unable to stat just-written file espressif32_library.json: No such file or directory
error: unable to stat just-written file espressif8266_library.json: No such file or directory
fatal: Could not reset index file to revision '313f337'.
Error: VCS: Could not process command ['git', 'reset', '--hard', '313f337']

**Comment by ivankravets** [comment]
Have you resolved this issue?

**Comment by fork04** [comment]
Yes, it was a git for windows problem
