### ISSUE TITLE
Causes Atom to crash on Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by AnthonyJAttard** [platformio/platformio-atom-ide#142]
OptiPlex-GX620
Intel® 945G
Program froze on launch and I had to remove the package from the files on disk before atom would run.

**Comment by pgebhard** [comment]
This doesn't really provide much detail. Were you able to reproduce the issue? If so, who about with a clean install of Atom and trying to install Platformio again?

**Comment by AnthonyJAttard** [comment]
The problem is just on this linux PC. The issue is repeatable even after a clean install. Atom works fine without PlatformIO.

**Comment by ivankravets** [comment]
PlatformIO IDE 1.3.5 has been released today. Did you try it?

**Comment by ivankravets** [comment]
Does clean version of http://atom.io work for you? If yes, please reopen this issue.

**Comment by AnthonyJAttard** [comment]
Problem solved after the new update was installed. Thank you for your help and keep up the good work!
