### ISSUE TITLE
Virtualenv Create: dyld: Library not loaded

### ISSUE THREAD

**Issue by andrewhf01** [platformio/platformio-atom-ide#1426]
Virtualenv Create: dyld: Library not loaded: @rpath/Python
  Referenced from: /Users/andrewfindlow/.platformio/penv/bin/python2.7
  Reason: image not found

**Comment by ivankravets** [comment]
Please provide an output from a system Terminal
```
echo $PATH
echo $PYTHONPATH
python --version
pip --version
pip list
```

**Comment by ivankravets** [comment]
Please reopen if you still need help
