### ISSUE TITLE
FYI, Upgrading from 1.3.2 to 1.3.5 issue

### ISSUE THREAD

**Issue by captainwasabi** [platformio/platformio-atom-ide#143]
Had to uninstall 1.3.2, uninstall Atom, reinstall Atom, install 1.3.5.  Upgrading by itself didn't work. Uninstalling 1.3.2. didn't work without the complete uninstall.  Thankfully it remembers all the other plugins and settings.

**Comment by ivankravets** [comment]
Please upgrade to 1.3.6 Does it work now?

**Comment by captainwasabi** [comment]
Worked perfect!  

Thanks,

**Comment by ivankravets** [comment]
Do you use Windows 8/10?

**Comment by captainwasabi** [comment]
Win 10

**Comment by ivankravets** [comment]
https://twitter.com/platformio_org/status/757555655981015041
