### ISSUE TITLE
platformio esp8266wifi / dir issue

### ISSUE THREAD

**Issue by oly99** [platformio/platformio-atom-ide#1434]
i am having issues with platformio esp8266wifi / lib dir issue  , when i try to compile my sketch it comes up with an error file and dir not found. the files are there but its not picking up the path with #include  <esp8266wifi.h>   it does if i put the whole path in ""  but then this just throws up the same error with a different .h file   how can i set the root directory to it picks up the path is there a addon for atom / platformio that will solve this possibly . i did think it was an issue with     esp8266wifi.h   but inow think is simply a path issue .

**Comment by ivankravets** [comment]
Please file an issue here https://github.com/platformio/platform-espressif8266/issues and provide a test project to reproduce this issue.
