### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by albukrek** [platformio/platformio-atom-ide#1460]
Error: [Wed Jan 31 08:04:51 2018] Processing sonoff (build_flags: -Wl,-Tesp8266.flash.1m0.ld -DMQTT_MAX_PACKET_SIZE=512; lib_deps: PubSubClient, NeoPixelBus, IRremoteESP8266, ArduinoJSON; platform: espressif8266; board: esp01_1m; framework: arduino; monitor_baud: 115200; board_flash_mode: dout)
--------------------------------------------------------------------------------
CorePackageManager: Installing tool-scons @ ~2.20501.3
Downloading...
Unpacking...
tool-scons @ 2.20501.3 has been successfully installed!
/Users/a2d/.platformio/penv/bin/python: can't open file '/Users/a2d/.platformio/packages/tool-scons@2.20501.3/script/scons': [Errno 2] No such file or directory
========================== [ERROR] Took 5.36 seconds ==========================

================================== [SUMMARY] ==================================
Environment sonoff        	[ERROR]
Environment sonoff-NL     	[SKIP]
Environment sonoff-minimal	[SKIP]
Environment sonoff-ds18x20	[SKIP]
========================== [ERROR] Took 5.36 seconds ==========================

**Comment by ivankravets** [comment]
Please remove `/Users/a2d/.platformio/packages/tool-scons` and start build again.
