### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by p3c0** [platformio/platformio-atom-ide#1486]
Cloning into '.../arduino/.piolibdeps/_tmp_installing-uosgz4-package'...
remote: Not Found
fatal: repository 'https://github.com/RobTillaart/Arduino/tree/master/libraries/Statistic/' not found
Error: VCS: Could not process command ['git', 'clone', '--recursive', '--depth', '1', 'https://github.com/RobTillaart/Arduino/tree/master/libraries/Statistic', '.../arduino/.piolibdeps/_tmp_installing-uosgz4-package']

**Comment by ivankravets** [comment]
Please use valid VCS repository or copy that library manually to `project/lib` folder
