### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by gerritjflesicher** [platformio/platformio-atom-ide#1490]
Error: [02/05/18 18:48:20] Processing teensy31 (platform: teensy; board: teensy31; framework: arduino)

Verbose mode can be enabled via `-v, --verbose` option
System: MK20DX256 72MHz RAM/64K Flash/256K
Library Dependency Finder -> http://bit.ly/configure-pio-ldf
Modes: Finder/chain Compatibility/light
Collected 94 compatible libraries
Scanning dependencies...
Dependency Graph
|-- <src>

*** Multiple ways to build the same target were specified for: C:\Users\gerri\Documents\PlatformIO\Projects\180205-184149-teensy31\.pioenvs\teensy31\lib6e8\src\ChRt.o  (from ['C:\\Users\\gerri\\Documents\\PlatformIO\\Projects\\180205-184149-teensy31\\lib\\src\\ChRt.c'] and from ['C:\\Users\\gerri\\Documents\\PlatformIO\\Projects\\180205-184149-teensy31\\lib\\src\\ChRt.cpp'])
File "C:\Users\gerri\.platformio\penv\lib\site-packages\platformio\builder\tools\platformio.py", line 275, in BuildLibrary
 [ERROR] Took 1.60 seconds

**Comment by ivankravets** [comment]
Please avoid files with the same name for C and CPP
