### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by MacPit69** [platformio/platformio-atom-ide#1494]
Error: [Wed Feb  7 08:03:27 2018] Processing d1_mini_pro (platform: espressif8266; board: d1_mini_pro; framework: arduino; lib_extra_dirs: ~/Documents/Arduino/libraries)
--------------------------------------------------------------------------------
Verbose mode can be enabled via `-v, --verbose` option
System: ESP8266 80MHz RAM/80K Flash/16M
Converting ESP_Client.ino
Library Dependency Finder -> http://bit.ly/configure-pio-ldf
Modes: Finder/chain Compatibility/light
Collected 39 compatible libraries
Scanning dependencies...
Error: Could not find `OneWire` dependency for `DallasTemperature` library
========================== [ERROR] Took 0.64 seconds ==========================

**Comment by ivankravets** [comment]
Should work now
