### ISSUE TITLE
Library manager CLI breaks Serial Monitor (on Windows)

### ISSUE THREAD

**Issue by SvenDowideit** [platformio/platformio-atom-ide#150]
If I have the Serial Monitor open, and open the library manager, the Serial monitor window is closed/hidden.

when I'm done with the library, I close it, and then need to <Alt>-<Shift>-M again, and that results in

```
Windows PowerShell
Copyright (C) 2016 Microsoft Corporation. All rights reserved.

Cannot load PSReadline module.  Console is running without PSReadline.
PS C:\Users\sven\Documents\platformIO\blink> pio -f -c atom serialports monitor --port COM5 --baud 115200
could not open port u'COM5': could not open port u'COM5': WindowsError(5, 'Access is denied.')
PS C:\Users\sven\Documents\platformIO\blink>
```

I presume that the original Serial monitor windows wasn't actually closed fully.

as a workaround, I can pull out the USB and put it back in again - and most of the time, it works again.

**Comment by ivankravets** [comment]
It seems that port is already used by Serial Monitor in others tabs. Please close all Terminal Tabs.
