### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by ChristofDidier** [platformio/platformio-atom-ide#1510]
Error: [Sun Feb 11 22:32:56 2018] Processing lptm4c1230c3pm (platform: titiva; board: lptm4c1230c3pm; framework: libOpenCM3)
--------------------------------------------------------------------------------
Verbose mode can be enabled via `-v, --verbose` option
PLATFORM: TI TIVA > TI LaunchPad (Tiva C) w/ tm4c123 (80MHz)
SYSTEM: LPTM4C1230C3PM 80MHz RAM/32KB Flash/256KB
default
onboard
DEBUG: CURRENT/ti-icdi ON-BORD/ti-icdi
Error: This board doesn't support libOpenCM3 framework!
========================== [ERROR] Took 0.25 seconds ==========================

**Comment by ivankravets** [comment]
Please file a feature request here https://github.com/platformio/platform-titiva/issues
