### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by ed1385** [platformio/platformio-atom-ide#1515]
Error: [Tue Feb 13 16:01:08 2018] Processing due (platform: atmelsam; board: due; framework: arduino)
--------------------------------------------------------------------------------
Verbose mode can be enabled via `-v, --verbose` option
PLATFORM: Atmel SAM > Arduino Due (Programming Port)
SYSTEM: AT91SAM3X8E 84MHz 32KB (512KB Flash)
DEBUG: CURRENT(blackmagic) EXTERNAL(blackmagic, jlink)
Converting ed_nrf24_ROBOT_RULL_tx.ino
Library Dependency Finder -> http://bit.ly/configure-pio-ldf
LDF MODES: FINDER(chain) COMPATIBILITY(light)
Collected 15 compatible libraries
Scanning dependencies...
Error: Could not find `RF24` dependency for `RF24Network` library
========================== [ERROR] Took 4.94 seconds ==========================

================================== [SUMMARY] ==================================
Environment due           	[ERROR]
Environment megaatmega2560	[SKIP]
========================== [ERROR] Took 4.94 seconds ==========================

**Comment by ivankravets** [comment]
Fixed in https://github.com/nRF24/RF24Network/pull/122
