### ISSUE TITLE
Project fails to open after rename

### ISSUE THREAD

**Issue by korish** [platformio/platformio-atom-ide#1518]
Steps to reproduce:

1) Import any Arduino project
2) Close Visual Studio Code
3) Rename folder with project
4) Open Visual Studio Code and try to open renamed project

Expected result: Project is opened successfully

Actual Result: Platformio tab is closed and it even disappears from the panel. User needs to disable/enable platformio to work again

Maybe I'm wrong is there is another way to rename the project?

**Comment by ivankravets** [comment]
Atom or VSCode? Please upgrade to the latest version.
