### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by shekspir55** [platformio/platformio-atom-ide#1522]
Error: [Thu Feb 15 22:22:48 2018] Processing nanoatmega328 (platform: atmelavr; board: nanoatmega328; framework: arduino)
--------------------------------------------------------------------------------
Verbose mode can be enabled via `-v, --verbose` option
PLATFORM: Atmel AVR > Arduino Nano ATmega328
SYSTEM: ATMEGA328P 16MHz 2KB RAM (30KB Flash)
Library Dependency Finder -> http://bit.ly/configure-pio-ldf
LDF MODES: FINDER(chain) COMPATIBILITY(light)
Collected 30 compatible libraries
Scanning dependencies...
Dependency Graph
|-- <Keyboard> v1.0.1
|-- <UsbKeyboard>

*** Multiple ways to build the same target were specified for: /home/rouben/Documents/PlatformIO/Projects/180215-212520-nanoatmega328/.pioenvs/nanoatmega328/lib16a/UsbKeyboard/utility/usbdrvasm.o  (from ['/home/rouben/Documents/PlatformIO/Projects/180215-212520-nanoatmega328/lib/UsbKeyboard/utility/usbdrvasm.S'] and from ['/home/rouben/Documents/PlatformIO/Projects/180215-212520-nanoatmega328/lib/UsbKeyboard/utility/usbdrvasm.asm'])
File "/home/rouben/.platformio/penv/local/lib/python2.7/site-packages/platformio/builder/tools/platformio.py", line 275, in BuildLibrary
========================== [ERROR] Took 0.39 seconds ==========================

**Comment by ivankravets** [comment]
* usbdrvasm.asm
* usbdrvasm.S

/lib/UsbKeyboard/

Please remove `* usbdrvasm.asm`
