### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by Aa26300** [platformio/platformio-atom-ide#1527]
Cloning into 'D:\Dev\espurna-master\espurna-master\code\.piolibdeps\_tmp_installing-naqykz-package'...
error: unable to stat just-written file espressif32_library.json: No such file or directory
error: unable to stat just-written file espressif8266_library.json: No such file or directory
fatal: Could not reset index file to revision '313f337'.
Error: VCS: Could not process command ['git', 'reset', '--hard', '313f337']

**Comment by ivankravets** [comment]
Please upgrade Git Client
