### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by krzychoooo** [platformio/platformio-atom-ide#1534]
Error: [02/21/18 00:42:26] Processing nucleo_l031k6 (platform: ststm32; board: nucleo_l031k6; framework: arduino)

PackageManager: Installing framework-arduinoststm32 @ ~2.0.0
Downloading...
Unpacking...
Verbose mode can be enabled via `-v, --verbose` option
PLATFORM: ST STM32 > ST Nucleo L031K6
SYSTEM: STM32L031K6T6 32MHz 8KB RAM (32KB Flash)
DEBUG: CURRENT(stlink-v2-1) ON-BOARD(stlink-v2-1) EXTERNAL(blackmagic)
Error: This board doesn't support arduino framework!
 [ERROR] Took 25.96 seconds

**Comment by ivankravets** [comment]
Error: This board doesn't support arduino framework!
