### ISSUE TITLE
Problem occured while upgrading PlatformIO IDE

### ISSUE THREAD

**Issue by jacken** [platformio/platformio-atom-ide#1535]
Error: Request for package information failed: connect EHOSTDOWN 23.23.138.216:443 - Local (0.0.0.0:0)

    at /Users/jacken/.atom/packages/platformio-ide/lib/installer/ide.js:59:9
    at Generator.throw (<anonymous>)
    at step (/Users/jacken/.atom/packages/platformio-ide/lib/installer/ide.js:176:2)

**Comment by ivankravets** [comment]
Please manually upgrade `platformio-ide` to the latest release
