### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by krzychoooo** [platformio/platformio-atom-ide#1538]
Error: [02/21/18 15:30:47] Processing genericSTM32F103VE (platform: ststm32; board: genericSTM32F103VE; framework: arduino)

Verbose mode can be enabled via `-v, --verbose` option
Error: Unknown board ID 'genericSTM32F103VE'
 [ERROR] Took 1.41 seconds

**Comment by ivankravets** [comment]
PIO Home > Platforms > Updates
