### ISSUE TITLE
Add command for Upload using Programmer

### ISSUE THREAD

**Issue by thomasguenzel** [platformio/platformio-atom-ide#154]
I couldn't find a keyboard shortcut for Upload using Programmer and it seems like there is no command for it. It would be great if this command could be added. Unfortunately I don't have any experience in writing atom packages.

Having a command like `platformio-ide:target:upload` (maybe even mapped to cmd/ctrl-shift-alt-u) would be awesome!
##

**Comment by ivankravets** [comment]
Please re-test with PIO IDE 2.0
