### ISSUE TITLE
'function' in namespace 'std' does not name a type

### ISSUE THREAD

**Issue by MidoAssran** [platformio/platformio-atom-ide#157]
I have this line of code:
`std::function<String(String)> _callback; 
`So everything compiles fine because in the .gcc-flags.json file in platformIO "-std=c++11" is included, but the linter still shows the warning:
`'function' in namespace 'std' does not name a type`

**Comment by ivankravets** [comment]
Atom linter uses gcc/g++ options basing on the file type. The g++ options will be used for `.hpp, *.cpp`.

**Comment by MidoAssran** [comment]
Oh ok thanks. It was actually a header file '.h', but, changing the atom description of the file to c++ instead of c solved the issue.
