### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by johnacs** [platformio/platformio-atom-ide#1585]
Conda Virtualenv: ERROR conda.core.link:_execute_actions(337): An error occurred while installing package 'defaults::openssl-1.0.2n-hdbc3d79_0'.
OSError(2, 'No such file or directory')
Attempting to roll back.

OSError(2, 'No such file or directory')

**Comment by ivankravets** [comment]
Please upgrade conda, remove `~/.platformio/penv` folder and restart IDE.
