### ISSUE TITLE
gcc linter can't find rtos.h error, but can build/upload sucess

### ISSUE THREAD

**Issue by mintisan** [platformio/platformio-atom-ide#161]
I think it's not a functional bug, but may it's better to fix it.

Or maybe it's just not a bug. The description is below:

![image](https://cloud.githubusercontent.com/assets/9136049/18231522/075d387e-72ee-11e6-8996-a100c085075d.png)

ps: 
0. I resetart my Atom, but the result is the same.
1. it's not same with [issue-24](https://github.com/platformio/platformio-atom-ide/issues/24)
2. u can tell me what information else u need to know, I will offer it.

version:
- macOS: 10.11.6
- Atom: 1.10.0
- PlatformIO IDE:1.4.0
- PlatformIO CLI:2.11.2
- Other
```
[env:nucleo_f401re]
platform = ststm32
framework = mbed
board = nucleo_f401re
```

**Comment by ivankravets** [comment]
Please switch to development version with PlatformIO 3.0 (is going to be released next week). See http://docs.platformio.org/en/stable/installation.html#development-version

Then, Menu > Rebuild C/C++ Index.

Do you still have this issue?

**Comment by mintisan** [comment]
@ivankravets Wow, so quickly.

The network in China is not so fast to use PlatformIO. Especially initialize a new platform(It cost me an hour to initialize my first mbed example). So I will tell u the result as soon as I `Reinstalling Initiated` completely.

**Comment by ivankravets** [comment]
Thanks, keep me in touch. It's important for us because we are going to release PlatformIO 3.0. Need to be sure that you don't have this issue.

**Comment by mintisan** [comment]
@ivankravets After `Reinstalling Initiated` completely. 
I restart Atom. The linter is just gone.

<img width="1278" alt="2016-09-04 22 47 43" src="https://cloud.githubusercontent.com/assets/9136049/18231664/021cccae-72f2-11e6-926a-2424bb476585.png">


But When I `Menu > Rebuild C/C++ Index`, the Atom seems dead,,,

**Comment by mintisan** [comment]
So I can only terminate it through `Force Quit`.

**Comment by ivankravets** [comment]
PlatformIO IDE/Atom is wrapper around PlatformIO CLI. Looks that PlatformIO CLI upgrades from 2.0 to 3.0.

Yep, you can kill atom. Open it. Open PlatformIO IDE Terminal. Type something like `pio platform list`. What do you see?

**Comment by mintisan** [comment]
![image](https://cloud.githubusercontent.com/assets/9136049/18231723/fae749e0-72f2-11e6-877f-b3e8f8802c26.png)

![image](https://cloud.githubusercontent.com/assets/9136049/18231728/1027a7e6-72f3-11e6-8341-e0fc7243c49a.png)

**Comment by mintisan** [comment]
I didn't install `nxplpc` manually ever...

**Comment by ivankravets** [comment]
Does it work now?

**Comment by mintisan** [comment]
It work well. The Rebuild is also OK.

The Atom is not dead, it gives a successful result for a while,,,,  ^_^!

Waiting for PlatformIO 3.0😄 

<img width="1022" alt="2016-09-04 23 03 55" src="https://cloud.githubusercontent.com/assets/9136049/18231760/e04352f4-72f3-11e6-9507-6348e826bfae.png">

**Comment by ivankravets** [comment]
PlatformIO 3.0 is totally rewritten PlatformIO. We will receive a lot of new features and improvements. Please follow us on Twitter https://twitter.com/PlatformIO_Org to be notified about announcements.
