### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by anklimov** [platformio/platformio-atom-ide#1611]
Cloning into '/Users/andrey/Documents/Arduino/lighthub/.piolibdeps/_tmp_installing-PfjcAy-package'...
fatal: I don't handle protocol ' https'
Error: VCS: Could not process command ['git', 'clone', '--recursive', '--depth', '1', '--branch', 'feature/stage', ' https://github.com/platformio/platform-espressif8266.git', '/Users/andrey/Documents/Arduino/lighthub/.piolibdeps/_tmp_installing-PfjcAy-package']

**Comment by ivankravets** [comment]
Please upgrade Git client
