### ISSUE TITLE
Problem occured while upgrading PlatformIO IDE

### ISSUE THREAD

**Issue by Gladiatorevincente** [platformio/platformio-atom-ide#1615]
Error: Couldn't clone https://github.com/platformio/platformio-atom-ide.git or git+ssh://git@github.com/platformio/platformio-atom-ide.git

    at /Users/massimodilullo/.atom/packages/platformio-ide/lib/installer/ide.js:59:9
    at Generator.throw (<anonymous>)
    at step (/Users/massimodilullo/.atom/packages/platformio-ide/lib/installer/ide.js:176:2)

**Comment by ivankravets** [comment]
Please manually upgrade `platformio-ide` to the latest release
