### ISSUE TITLE
Problem occured while upgrading PlatformIO IDE

### ISSUE THREAD

**Issue by khoffy** [platformio/platformio-atom-ide#1624]
Error: EACCES: permission denied, unlink '/home/khoffy/.atom/packages/platformio-ide/.editorconfig'

    at /home/khoffy/.atom/packages/platformio-ide/lib/installer/ide.js:59:9
    at Generator.throw (<anonymous>)
    at step (/home/khoffy/.atom/packages/platformio-ide/lib/installer/ide.js:176:2)

**Comment by ivankravets** [comment]
Please check permissions.
