### ISSUE TITLE
Python Processes Still Running After Upload

### ISSUE THREAD

**Issue by neilmendoza** [platformio/platformio-atom-ide#1632]
I originally posted this bug in the ESP 32 section...

https://github.com/platformio/platform-espressif32/issues/37

I've been seeing this bug with multiple different microcontrollers since then. Every so often there seem to be multiple orphaned Python processes running, each of which wants to chew up 100% CPU. Think it might be when an upload is unsuccessful but haven't had time to test.

**Comment by ivankravets** [comment]
Please move to https://community.platformio.org/
