### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by kirkesolator** [platformio/platformio-atom-ide#1643]
PIP: Command "/Users/StensolaTor/.platformio/penv/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/2_/232brtcj3gq_hbhn1575s_440000gn/T/pip-build-UsXPxn/bottle/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/2_/232brtcj3gq_hbhn1575s_440000gn/T/pip-pNDwnP-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/2_/232brtcj3gq_hbhn1575s_440000gn/T/pip-build-UsXPxn/bottle/

**Comment by ivankravets** [comment]
Please remove `/Users/StensolaTor/.platformio/penv` folder and restart IDE.
