### ISSUE TITLE
avrdude not working anymore in 1.5.0

### ISSUE THREAD

**Issue by KarateBrot** [platformio/platformio-atom-ide#165]
[09/09/16 18:39:15] Processing uno (platform: atmelavr, board: uno, framework: arduino)
 
Verbose mode can be enabled via `-v, --verbose` option
Collected 34 compatible libraries
Looking for dependencies...
Library Dependency Graph
|-- <TimerOne>

|-- <Adafruit INA219> v1.0.0
|   |-- <Wire> v1.0
|-- <Wire> v1.0
|-- <ClickEncoder>
|-- <Adafruit MCP4725> v1.0.2
|   |-- <Wire> v1.0
|-- <Adafruit SSD1306> v1.1.0
|   |-- <Adafruit GFX Library> v1.1.5
|   |-- <SPI> v1.0
|   |-- <Wire> v1.0
|-- <Adafruit GFX Library> v1.1.5
Looking for upload port...
Auto-detected: COM14
Uploading .pioenvs\uno\firmware.hex
avrdude: can't open config file "C:\Users\Jan": No such file or directory
avrdude: error reading system wide configuration file "C:\Users\Jan"
*** [upload] Error 1
 [ERROR] Took 1.07 seconds

- - - - -

I already tried to uninstall and reinstall everything but it seems like avrdude can't handle my file path with spaces in it anymore.

**Comment by ivankravets** [comment]
Please move to appropriate repository (PlatformIO CLI) https://github.com/platformio/platformio/issues
