### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by Oleg371** [platformio/platformio-atom-ide#1658]
PIP: "C:\Users\Oleg\.platformio\penv\Scripts\pip" �� ���� ����७��� ��� ���譥�
��������, �ᯮ��塞�� �ணࠬ��� ��� ������ 䠩���.
Error: spawn C:\Users\Oleg\.platformio\penv\Scripts\pip ENOENT

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/1243
