### ISSUE TITLE
Internal error indexedDB.open

### ISSUE THREAD

**Issue by nooitaf** [platformio/platformio-atom-ide#166]
![screenshot from 2016-09-13 19-12-27](https://cloud.githubusercontent.com/assets/1898194/18483927/95a2f4ee-79e6-11e6-9e05-63557f307607.png)

I get these errors and screen at every atom startup (even though i unchecked "show on startup") and everytime it tries to update something (every 30m or so) i get those errors again. For the rest it works fine and i'm very happy.

**Comment by ivankravets** [comment]
Please open a developer console (click "View -> Developer -> Toggle Developer Tools") paste the string `indexedDB.deleteDatabase('platformio-ide')` and restart the editor.

**Comment by nooitaf** [comment]
I assume you mean paste it in the console, did that (twice), didn't fix it. 
Tried to update to 1.5.0, also didn't work.

![screenshot from 2016-09-13 19-28-37](https://cloud.githubusercontent.com/assets/1898194/18484366/61a0afd6-79e8-11e6-8ade-fd441e572efa.png)

**Comment by ivankravets** [comment]
What is your OS?

**Comment by nooitaf** [comment]
Linux Mint Sarah 18 
4.4.0-28-generic #47-Ubuntu x86_64 x86_64 x86_64 GNU/Linux

**Comment by ivankravets** [comment]
Could you try to remove DB again https://github.com/platformio/platformio-atom-ide/issues/166#issuecomment-246757091 and then `rm -rf ~/.atom`. Restart IDE.

Very strange error.

**Comment by nooitaf** [comment]
Well .. `rm -rf ~/.atom` deleted all my settings and packages, so i tried again. Same thing..
It's Atom version `1.8.0` btw

![screenshot from 2016-09-13 19-41-09](https://cloud.githubusercontent.com/assets/1898194/18484807/42a01bd8-79ea-11e6-96db-1d2c9eecb327.png)

![screenshot from 2016-09-13 19-41-28](https://cloud.githubusercontent.com/assets/1898194/18484809/469d0b10-79ea-11e6-9813-5c1ff6635ca8.png)

So i tried reinstalling atom..
`sudo apt-get remove atom`
downloaded & installed `atom.deb` `v1.10.2`
installed `platformio-ide` package

![screenshot from 2016-09-13 19-54-26](https://cloud.githubusercontent.com/assets/1898194/18485234/5650d7f6-79ec-11e6-8002-1680f6292532.png)

![screenshot from 2016-09-13 19-55-19](https://cloud.githubusercontent.com/assets/1898194/18485236/5a869c8e-79ec-11e6-8141-ba0e5b054efc.png)

**Comment by ivankravets** [comment]
Where is Atom application folder in your OS? See hint for macOS https://github.com/atom/atom/issues/11254#issuecomment-200355845

**Comment by orgkhnargh** [comment]
Neither reinstalling atom nor removing the `~/.atom` directory would not clear the indexeddb files, because they are stored under the `~/.config/Atom/IndexedDB/` directory. @nooitaf, you'll want to remove this one to make the error disappear (make a backup first just in case).

Do you have enough space on the hard drive? Someone [here](https://bugs.chromium.org/p/chromium/issues/detail?id=279106) said: 

> when I try to add more data than the available space, I get no error, success is received instead, disk gets full, and I don't get any error on page refresh, even though db is loaded again at page loading. Only when Chrome is closed and reopened and try to open the db, I get the above error.

**Comment by nooitaf** [comment]
@orgkhnargh That was it! Awesome \o/

I started Atom as root sometime back. So i had to re-own some of the index files...

`sudo chown -R username:username ~/.config/Atom` 

...fixed it. But this error didn't show before so i didn't notice it and thought it was related :O 

Thanks guys!
