### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by ozanoner** [platformio/platformio-atom-ide#1664]
Error: [03/21/18 14:23:26] Processing esp32doit-devkit-v1 (platform: espressif32; board: esp32doit-devkit-v1; framework: arduino)

SCons import failed. Unable to find engine files in:
C:\SPB_Data\.platformio\packages\tool-scons\script\..\engine
C:\SPB_Data\.platformio\packages\tool-scons\script\scons-local-2.5.1
C:\SPB_Data\.platformio\packages\tool-scons\script\scons-local
c:\spb_data\.platformio\penv\scons-2.5.1
c:\spb_data\.platformio\penv\Lib\site-packages\scons-2.5.1
c:\spb_data\.platformio\penv\scons
c:\spb_data\.platformio\penv\Lib\site-packages\scons
Traceback (most recent call last):
File "C:\SPB_Data\.platformio\packages\tool-scons\script\scons", line 190, in <module>
import SCons.Script
File "C:\SPB_Data\.platformio\packages\tool-scons\script\..\engine\SCons\__init__.py", line 43, in <module>
import SCons.compat
ImportError: No module named compat
 [ERROR] Took 2.32 seconds

**Comment by ivankravets** [comment]
Please remove `C:\SPB_Data.platformio\packages\tool-scons` folder and start build again.
