### ISSUE TITLE
Built-in serial terminal does not close serial connection properly 

### ISSUE THREAD

**Issue by wurmtal868** [platformio/platformio-atom-ide#1665]
PlatformIO-IDE Version:
Home 0.8.1·Core 3.5.3a3

OS:
Windows7 / 10

I'm programming an 32U4 based MCU (e.g Arduino  Leonardo) using the Arduino framework.
I want to send debug information only when a serial connection is detected.
Once serial terminal has been started the 32U4 will be sending debug information but won't stop when the terminal is closed.

How to reproduce:
Flash the serial_test.ino into a 32U4 based MCU
[serial_test.zip](https://github.com/platformio/platformio-atom-ide/files/1833166/serial_test.zip)

Expected behavior:
Every time the serial terminal within PlatformIO-IDE connects to the MCU it should be printing numbers counting up starting from 0

Current behavior:
Only the first connection after a (USB)-Reset the terminal will start counting from 0. The TX-LED (if available) is flashing constantly even when the terminal is closed, showing that MCU recognize the serial connection as always available after the first connection. 
Only a (USB)-Reset can stop the MCU from sending data.

To exclude a windows driver problem I attached serial_test.py that will open a serial connection, read 6 lines and close the connection. This script will always print the numbers 0-5 as expected.
It cannot fix the state after the built-in terminal has connected to the MCU

**Comment by ivankravets** [comment]
Please move to https://community.platformio.org/
