### ISSUE TITLE
InstallationManager unified issue

### ISSUE THREAD

**Issue by sdaitzman** [platformio/platformio-atom-ide#1675]
#1674 #1667 #1666 #1659 #1658 #1655 #1654 #1652 #1651 #1649 #1647 #1644 #1643 #1642 #1640 #1637 #1635 #1634 #1631 #1629 #1628 #1627 #1626 #1622 #1617

And also many more errors. I don't know about you all, but I was able to fix the issue. I modified the platformio binary at `/usr/local/bin/platformio` and the pio binary at `/usr/local/bin/pio
` to change the shebang (first line) to `#!/usr/bin/env python2.7` in both files which allowed those files to be executed. Its original contents referenced a Python installation that does not exist.

I also renamed the directory `~/.platformio` to `~/.platformio.bak`. I'm not sure which fixed the issue.

**Comment by ivankravets** [comment]
Please remove global PIO Cores => http://docs.platformio.org/en/latest/faq.html#multiple-pio-cores-in-a-system

Restart IDE.
