### ISSUE TITLE
Feature request: Collapse

### ISSUE THREAD

**Issue by viktak** [platformio/platformio-atom-ide#168]
Hi,

I extensively use the collapse function of the editor. When opening a source file, however, the editor expands all collapsed functions/blocks. Is there a way for the editor to remember what was collapsed the last time? Or failing that, could it open any file with all functions collapsed? Or provide a shortcut/button to do the same?

Every time I open a file I spend about a minute collapsing all functions that are of no interest to me at the time...

Thanks

viktak

**Comment by ivankravets** [comment]
PlatformIO IDE is based on http://atom.io text editor. Please post your issue here https://github.com/atom
