### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by joaquinmarcelolopez** [platformio/platformio-atom-ide#1680]
Error: [Sat Mar 24 20:09:16 2018] Processing frdm_k64f (platform: freescalekinetis; board: frdm_k64f; framework: mbed)
--------------------------------------------------------------------------------
Verbose mode can be enabled via `-v, --verbose` option
PLATFORM: Freescale Kinetis > Freescale Kinetis FRDM-K64F
SYSTEM: MK64FN1M0VLL12 120MHz 256KB RAM (1MB Flash)
DEBUG: CURRENT(cmsis-dap) ON-BOARD(cmsis-dap) EXTERNAL(jlink)
Library Dependency Finder -> http://bit.ly/configure-pio-ldf
LDF MODES: FINDER(chain) COMPATIBILITY(light)
Collected 18 compatible libraries
Scanning dependencies...
Error: Could not find `ualloc` dependency for `mbed-drivers` library
========================== [ERROR] Took 0.82 seconds ==========================

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/1356
