### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by ferazambuja** [platformio/platformio-atom-ide#1694]
Error: [Thu Mar 29 01:18:49 2018] Processing m5stack-core-esp32 (framework: arduino; platform: espressif; board: m5stack-core-esp32)
--------------------------------------------------------------------------------
Detected non-PlatformIO `lib_install` option in `[env:m5stack-core-esp32]` section
Warning! Platform `espressif` is deprecated and will be removed in the next release! Please use `espressif8266` instead.
Verbose mode can be enabled via `-v, --verbose` option
Error: Unknown board ID 'm5stack-core-esp32'
========================== [ERROR] Took 0.74 seconds ==========================

**Comment by ivankravets** [comment]
platform: espressif -> espressif32
