### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by aupilot** [platformio/platformio-atom-ide#1695]
Cloning into '/Users/kir/Documents/Programming/ESP/ESP8266-HomeKit/.piolibdeps/_tmp_installing-q_3zc6-package'...
fatal: unable to access 'https://github.com/"lib/wolfcrypt"/': The requested URL returned error: 400
Error: VCS: Could not process command ['git', 'clone', '--recursive', '--depth', '1', 'https://github.com/"lib/wolfcrypt"', '/Users/kir/Documents/Programming/ESP/ESP8266-HomeKit/.piolibdeps/_tmp_installing-q_3zc6-package']

**Comment by ivankravets** [comment]
Please upgrade Git client
