### ISSUE TITLE
Virtualenv Create: Traceback (most recent call last):   File "C:\Users\YUsuf\.platformio\.cache\tmp-5944AqSd7gTvagX1\virtualenv-14.0.6\virtualenv.py", line 2304, in <module>     main()   File "C:\Users\YUsuf\.platformio\.cache\tmp-5944AqSd7gTvagX1\virtualenv-14.0.6\virtualenv.py", line 705, in main     symlink=options.symlink)   File "C:\Users\YUsuf\.platformio\.cache\tmp-5944AqSd7gTvagX1\virtualenv-14.0.6\virtualenv.py", line 924, in create_environment     download=download,   File "C:\Users\YUsuf\.platformio\.cache\tmp-5944AqSd7gTvagX1\virtualenv-14.0.6\virtualenv.py", line 877, in install_wheel     call_subprocess(cmd, show_stdout=False, extra_env=env)   File "C:\Users\YUsuf\.platformio\.cache\tmp-5944AqSd7gTvagX1\virtualenv-14.0.6\virtualenv.py", line 783, in call_subprocess     % (cmd_desc, proc.returncode)) OSError: Command C:\Users\YUsuf\.plat...v\Scripts\python.exe -c "import sys, pip; sys...d\"] + sys.argv[1:]))" setuptools pip wheel failed with error code 2

### ISSUE THREAD

**Issue by usuf1** [platformio/platformio-atom-ide#1706]
Virtualenv Create: Traceback (most recent call last):
  File "C:\Users\YUsuf\.platformio\.cache\tmp-5944AqSd7gTvagX1\virtualenv-14.0.6\virtualenv.py", line 2304, in <module>
    main()
  File "C:\Users\YUsuf\.platformio\.cache\tmp-5944AqSd7gTvagX1\virtualenv-14.0.6\virtualenv.py", line 705, in main
    symlink=options.symlink)
  File "C:\Users\YUsuf\.platformio\.cache\tmp-5944AqSd7gTvagX1\virtualenv-14.0.6\virtualenv.py", line 924, in create_environment
    download=download,
  File "C:\Users\YUsuf\.platformio\.cache\tmp-5944AqSd7gTvagX1\virtualenv-14.0.6\virtualenv.py", line 877, in install_wheel
    call_subprocess(cmd, show_stdout=False, extra_env=env)
  File "C:\Users\YUsuf\.platformio\.cache\tmp-5944AqSd7gTvagX1\virtualenv-14.0.6\virtualenv.py", line 783, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command C:\Users\YUsuf\.plat...v\Scripts\python.exe -c "import sys, pip; sys...d\"] + sys.argv[1:]))" setuptools pip wheel failed with error code 2

**Comment by wormscoffer** [comment]
Whatever your issue is, I have the same as I get exactly the same error message.

Did  you find any resolution?

**Comment by usuf1** [comment]
Yes I got some of the solution to the problem

**Comment by wormscoffer** [comment]
Excellent - would you mind sharing as I have two machines and both do the same?

**Comment by ivankravets** [comment]
Please upgrade to `platformio-ide` 2.1.5, should be fixed. 
Please reopen if you still need help.
