### ISSUE TITLE
installation issue 

### ISSUE THREAD

**Issue by tilakjain** [platformio/platformio-atom-ide#1708]
I am trying to install platformIO on my mac and am receiving an "Installation manager error PIP:". Atom seems to have installed ok and I have python 2.7 and pip installed, so not sure what the problem is.

**Comment by WeeJeWel** [comment]
+1

**Comment by zen** [comment]
+1. Tried many methods and nothing worked. 
I reinstalled Atom and PIO because I was getting errors on project rebuild

**Comment by ivankravets** [comment]
Should be fixed in the latest release. Please update `platformio-ide` package via `Settings > Updates`.
