### ISSUE TITLE
Unable to retreive PlatformIO Core

### ISSUE THREAD

**Issue by clachance** [platformio/platformio-atom-ide#1711]
Hi, 

I juste made a fresh install of Atom on windows 10 and i tried to install PlatformIO-IDE, but im stucked in an infinit installing PlatformIO/ restarting Atom loop.  The thing is that when i start Atom, it still trying to retrieve the PlatformIO Core, after seconds, it says "PlatfromIO IDE has been successfully installed!" and tell me to restart atom to apply change.  If i press restart, Atom is restarting and the PlatformIO still try to install and retrieve the PlatformIO Core.

I dont have any error messages, so im completely blind on what is going on.  Anybody can help me on this one?

Christian.

**Comment by ivankravets** [comment]
Should be fixed in the latest release. Please => Settings > Updates.

**Comment by clachance** [comment]
Thanks for the fix!

**Comment by ivankravets** [comment]
Does it work now?
