### ISSUE TITLE
Error in the bash script " .platformio/packages/tool-stm32duino/stm32flash/serial_upload  "

### ISSUE THREAD

**Issue by renejeanmercier** [platformio/platformio-atom-ide#1719]
The "/dev/" parameter in the serial_upload file used to upload via the /dev/ttyUSBx port to a USB to serial converter device (module) causes Platformio to repeat /dev/ and to report the two following error messages :
1) Cannot handle device /dev//dev/ttyUSBx (x being a number (0,1 ...)
2) Failed to open port /dev//dev/ttyUSBx (x being a number (0, 1, ...)

So please REMOVE /dev/ in the following script :

#!/bin/bash
$(dirname $0)/stm32flash/stm32flash -g 0x8000000 -b 115200 -w "$4" /dev/"$1" 

Application : Platformio on Atom.
Operating system used : Debian 9.4 x64bits.

Regards,

R.J.M.

**Comment by ivankravets** [comment]
https://community.platformio.org/
