### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by rhodopsik** [platformio/platformio-atom-ide#1725]
PIP:   Could not find a version that satisfies the requirement bottle<0.13 (from platformio==3.5.3a8) (from versions: )
No matching distribution found for bottle<0.13 (from platformio==3.5.3a8)

What can I do? Any suggestion?
Thanks!

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/1592
