### ISSUE TITLE
Error installing IDE when python is installed in custom path

### ISSUE THREAD

**Issue by skuhtic** [platformio/platformio-atom-ide#174]
Installation is unable to find python when it is install in folder like c:\python\python27. There is path in PATH variable and python is working from command line. Installation is suggesting checking the PATH variable, installing python or aborting installation of Platform IDE. 

I installed python in default folder and it worked. It should work with other paths used or there should be option for manual locating the installation python path.

It is easy to fix situation, but i guess it's easy to fix to work as suggested (using PATH variable). 
##

**Comment by ivankravets** [comment]
If you have it in a PATH - it should work! See source code [here](https://github.com/platformio/platformio-atom-ide/blob/develop/lib/utils.js#L39).

As you can see, we check all possible locations. Could you try to specify both settings: `Path` in system section and `PATH` in user's section. I'm not Windows user but I saw these options when edit system environment variables.

**Comment by skuhtic** [comment]
I did try all combinations with user and system PATH variables. with and without trailing backslashes and renamed python folder to 'c:\python' but it does not work. When renamed to 'c:\python27' works even if variable are still set to 'c:\python' (and then command line does not work). Hope that helps.

**Comment by ivankravets** [comment]
Please open PlatformIO IDE Terminal and run 
```
echo %PATH%
echo %Path%
```

What do you see?

**Comment by skuhtic** [comment]
Same variables with python the first one.

**Comment by ivankravets** [comment]
Thanks, I'll take a look on it later.

**Comment by skuhtic** [comment]
C:\>echo %Path%
C:\Python\;C:\Python\Scripts;C:\ProgramData...
I got it working and it's easy to fix... I don't know how often python is installed in custom path so it's maybe minor issue. Thnx for all the effort...

**Comment by skuhtic** [comment]
I didn't test in IDE terminal but in cmd and now I have different result. Sorry, my mistake. So to not mislead you, this is the output:

Windows PowerShell
Copyright (C) 2016 Microsoft Corporation. All rights reserved.

PS C:\Users\xxx> cd /
PS C:\> echo %PATH%
%PATH%
PS C:\> echo %Path%
%Path%
PS C:\>

PS Keyboard is english and not the one I'm using in windows...

**Comment by ivankravets** [comment]
Ask google how to print current env var using PowerShell

**Comment by skuhtic** [comment]
Allredy did ;)

PS C:\> echo $env:PATH
C:\Users\Sinisha\.atom\packages\platformio-ide\penv\Scripts;C:\Python27\;C:\Python27\Scripts;C:\ProgramData

Link on the issue:
http://stackoverflow.com/questions/714877/setting-windows-powershell-path-variable

**Comment by ivankravets** [comment]
Do you see here `C:\Python\;C:\Python\Scripts`? I don't.

**Comment by ivankravets** [comment]
Atom doesn't see your custom environment PATHs. Looks like you set them incorrect.

**Comment by skuhtic** [comment]
There is: C:\Python27\;C:\Python27\Scripts i changed it to original...
After changing back to 'c:\python':

PS C:\> echo $env:Path
C:\Users\Sinisha\.atom\packages\platformio-ide\penv\Scripts;**C:\Python\;C:\Python\Scripts**;C:\ProgramData

**Comment by ivankravets** [comment]
Cool, I've jsut changed this issue to "bug". I'll fix it later.

**Comment by kvij** [comment]
I have been trying to set it up for a few hours now. I did have a pip problem because strawberry perl also has a pip command in PATH. When I use cmd or PS or even Komodo IDE and type "python" I have python 2.7.11 running (chocolatey install) so PATH is setup correctly. I also need python 3 so I am not going to uninstall that.

**Comment by ashthespy** [comment]
I seem to have a peculiar issue: 
OS: Win 8.1
I have `pyhton 2.7.12` installed via `miniconda` and is registered and available at the cmd prompt and PS. 
however, Atom and platformIO don't seem to be able to find python. 
Any ideas? Works fine if I install Python for Windows directly, but I would like to avoid two installs of Python on my system.

**Comment by ivankravets** [comment]
Could you try new PlatformIO IDE 2.0 Installer?

Menu: PlatformIO > Home > Try PlatformIO IDE 2.0 Preview.

Thanks!

**Comment by ivankravets** [comment]
@ashthespy please try to remove `penv` folder and restart Atom. It should handle a built-in conda installation automatically
