### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by gerhardvz** [platformio/platformio-atom-ide#1741]
PIP: sh: module: line 1: syntax error: unexpected end of file
sh: error importing function definition for `module'
sh: scl: line 1: syntax error: unexpected end of file
sh: error importing function definition for `scl'
Could not import setuptools which is required to install from a source distribution.
sh: module: line 1: syntax error: unexpected end of file
sh: error importing function definition for `module'
sh: scl: line 1: syntax error: unexpected end of file
sh: error importing function definition for `scl'

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/1729
