### ISSUE TITLE
Problems with upload to wemos d1 mini

### ISSUE THREAD

**Issue by Phili86** [platformio/platformio-atom-ide#1742]
Hey there, i have some Problems with upload Firmware. try another USP Port, another Cable another PC another Software another Firmware another wemos shild. everytime Error -1

`> Executing task: C:\Users\Ruth\.platformio\penv\Scripts\platformio.exe run --target upload <

[04/10/18 14:37:24] Processing nodemcuv2 (framework: arduino; platform: espressif8266; board: nodemcuv2)---------------------------------------------------------------------------------------
Verbose mode can be enabled via `-v, --verbose` option
PLATFORM: Espressif 8266 > NodeMCU 1.0 (ESP-12E Module)
SYSTEM: ESP8266 160MHz 80KB RAM (4MB Flash)
Library Dependency Finder -> http://bit.ly/configure-pio-ldf
LDF MODES: FINDER(chain) COMPATIBILITY(light)
Collected 42 compatible libraries
Scanning dependencies...
Dependency Graph
|-- <SPI> v1.0
|-- <ESP8266HTTPClient> v1.1
|   |-- <ESP8266WiFi> v1.0
|-- <PubSubClient> v2.6
|-- <Adafruit NeoMatrix> v1.1.2
|   |-- <Adafruit GFX Library> v1.2.3
|   |   |-- <SPI> v1.0
|   |-- <Adafruit NeoPixel> v1.1.6
|-- <Adafruit NeoPixel> v1.1.6
|-- <Adafruit GFX Library> v1.2.3
|   |-- <SPI> v1.0
|   |-- <SPI> v1.0
|-- <Adafruit Unified Sensor> v1.0.2
|-- <WifiManager> v0.12
|   |-- <ESP8266WiFi> v1.0
|   |-- <DNSServer> v1.1.0
|   |   |-- <ESP8266WiFi> v1.0
|   |-- <ESP8266WebServer> v1.0
|   |   |-- <ESP8266WiFi> v1.0
|-- <thinger.io> v2.9.1
|   |-- <DNSServer> v1.1.0
|   |   |-- <ESP8266WiFi> v1.0
|   |-- <WifiManager> v0.12
|   |   |-- <ESP8266WiFi> v1.0
|   |   |-- <DNSServer> v1.1.0
|   |   |   |-- <ESP8266WiFi> v1.0
|   |   |-- <ESP8266WebServer> v1.0
|   |   |   |-- <ESP8266WiFi> v1.0
|   |-- <ESP8266WebServer> v1.0
|   |   |-- <ESP8266WiFi> v1.0
|   |-- <ESP8266WiFi> v1.0
|-- <JsonStreamingParser> v1.0.5
|-- <DHT sensor library> v1.3.0
|   |-- <Adafruit Unified Sensor> v1.0.2
|-- <ArduinoJson> v5.13.1
|-- <Blynk> v0.5.2
|   |-- <ESP8266WiFi> v1.0
|   |-- <Time> v1.5
|-- <ESPAsyncTCP> v1.1.3
|   |-- <ESP8266WiFi> v1.0
|-- <FauxmoESP> v2.4.2
|   |-- <ESP8266WiFi> v1.0
|   |-- <ESPAsyncTCP> v1.1.3
|   |   |-- <ESP8266WiFi> v1.0
|-- <Time> v1.5
||-- <Awtrix>
|   |-- <Adafruit NeoPixel> v1.1.6
|   |-- <Adafruit GFX Library> v1.2.3
|   |   |-- <SPI> v1.0
|   |-- <ArduinoJson> v5.13.1
|   |-- <ArduinoOTA> v1.0
|   |   |-- <ESP8266WiFi> v1.0
|   |   |-- <ESP8266mDNS>
|   |   |   |-- <ESP8266WiFi> v1.0
|   |-- <PubSubClient> v2.6
|   |-- <ESP8266mDNS>
|   |   |-- <ESP8266WiFi> v1.0
|   |-- <ESP8266httpUpdate> v1.1
|   |   |-- <ESP8266HTTPClient> v1.1
|   |   |   |-- <ESP8266WiFi> v1.0
|   |   |-- <ESP8266WiFi> v1.0
|   |-- <Time> v1.5
|   |-- <ESP8266HTTPUpdateServer> v1.0
|   |   |-- <ESP8266WebServer> v1.0
|   |   |   |-- <ESP8266WiFi> v1.0
|   |   |-- <ESP8266WiFi> v1.0
|   |-- <Adafruit NeoMatrix> v1.1.2
|   |   |-- <Adafruit GFX Library> v1.2.3
|   |   |   |-- <SPI> v1.0
|   |   |-- <Adafruit NeoPixel> v1.1.6
|   |-- <FauxmoESP> v2.4.2
|   |   |-- <ESP8266WiFi> v1.0
|   |   |-- <ESPAsyncTCP> v1.1.3
|   |   |   |-- <ESP8266WiFi> v1.0
|   |-- <ESP8266WiFi> v1.0
|   |-- <ESP8266HTTPClient> v1.1
|   |   |-- <ESP8266WiFi> v1.0
|   |-- <ESP8266WebServer> v1.0
|   |   |-- <ESP8266WiFi> v1.0
|   |-- <WifiManager> v0.12
|   |   |-- <ESP8266WiFi> v1.0
|   |   |-- <DNSServer> v1.1.0
|   |   |   |-- <ESP8266WiFi> v1.0
|   |   |-- <ESP8266WebServer> v1.0
|   |   |   |-- <ESP8266WiFi> v1.0
|   |-- <Blynk> v0.5.2
|   |   |-- <ESP8266WiFi> v1.0
|   |   |-- <Time> v1.5
|-- <Applications>
|   |-- <Awtrix>
|   |   |-- <Adafruit NeoPixel> v1.1.6
|   |   |-- <Adafruit GFX Library> v1.2.3
|   |   |   |-- <SPI> v1.0
|   |   |-- <ArduinoJson> v5.13.1
|   |   |-- <ArduinoOTA> v1.0
|   |   |   |-- <ESP8266WiFi> v1.0
|   |   |   |-- <ESP8266mDNS>
|   |   |   |   |-- <ESP8266WiFi> v1.0
|   |   |-- <PubSubClient> v2.6
|   |   |-- <ESP8266mDNS>
|   |   |   |-- <ESP8266WiFi> v1.0
|   |   |-- <ESP8266httpUpdate> v1.1
|   |   |   |-- <ESP8266HTTPClient> v1.1
|   |   |   |   |-- <ESP8266WiFi> v1.0
|   |   |   |-- <ESP8266WiFi> v1.0
|   |   |-- <Time> v1.5
|   |   |-- <ESP8266HTTPUpdateServer> v1.0
|   |   |   |-- <ESP8266WebServer> v1.0
|   |   |   |   |-- <ESP8266WiFi> v1.0
|   |   |   |-- <ESP8266WiFi> v1.0
|   |   |-- <Adafruit NeoMatrix> v1.1.2
|   |   |   |-- <Adafruit GFX Library> v1.2.3
|   |   |   |   |-- <SPI> v1.0
|   |   |   |-- <Adafruit NeoPixel> v1.1.6
|   |   |-- <FauxmoESP> v2.4.2
|   |   |   |-- <ESP8266WiFi> v1.0
|   |   |   |-- <ESPAsyncTCP> v1.1.3
|   |   |   |   |-- <ESP8266WiFi> v1.0
|   |   |-- <ESP8266WiFi> v1.0
|   |   |-- <ESP8266HTTPClient> v1.1
|   |   |   |-- <ESP8266WiFi> v1.0
|   |   |-- <ESP8266WebServer> v1.0
|   |   |   |-- <ESP8266WiFi> v1.0
|   |   |-- <WifiManager> v0.12
|   |   |   |-- <ESP8266WiFi> v1.0
|   |   |   |-- <DNSServer> v1.1.0
|   |   |   |   |-- <ESP8266WiFi> v1.0
|   |   |   |-- <ESP8266WebServer> v1.0
|   |   |   |   |-- <ESP8266WiFi> v1.0
|   |   |-- <Blynk> v0.5.2
|   |   |   |-- <ESP8266WiFi> v1.0
|   |   |   |-- <Time> v1.5
|   |-- <Time> v1.5
|   |-- <EEPROM> v1.0
|   |-- <DHT sensor library> v1.3.0
|   |   |-- <Adafruit Unified Sensor> v1.0.2
|   |-- <ArduinoJson> v5.13.1
|   |-- <ESP8266HTTPClient> v1.1
|   |   |-- <ESP8266WiFi> v1.0
|   |-- <ESP8266WiFi> v1.0
Linking .pioenvs\nodemcuv2\firmware.elf
Checking program size
text       data     bss     dec     hex filename
500382    16516   32232  549130   8610a .pioenvs\nodemcuv2\firmware.elf
Building .pioenvs\nodemcuv2\firmware.bin
Configuring upload protocol...
Looking for upload port...
Auto-detected: COM10
Uploading .pioenvs\nodemcuv2\firmware.bin
error: Failed to open COM10
error: espcomm_open failed
error: espcomm_upload_mem failed
*** [upload] Error -1
=============================================================================================== [ERROR] Took 6.99 seconds ===============================================================================================
Der Terminalprozess wurde mit folgendem Exitcode beendet: 1

Das Terminal wird von Aufgaben wiederverwendet, drücken Sie zum Schließen eine beliebige Taste.`

anyone ideas?`
thanks Philipp

**Comment by ivankravets** [comment]
https://community.platformio.org/
