### ISSUE TITLE
Better toolbar options?

### ISSUE THREAD

**Issue by JamesCoyle** [platformio/platformio-atom-ide#175]
It would be great if PlatformIO would create its own toolbar rather than adding icons to the current one. I've already got a full toolbar so now I have to scroll meaning icons are never where expected. I'd much prefer PlatformIO to have its own toolbar that can be toggled. If not the option to disable just the PlatformIO icons would be good. 

https://github.com/suda/tool-bar/issues/174
##

**Comment by orgkhnargh** [comment]
You'll be able to toggle a certain package's toolbar buttons once suda/tool-bar#163 is merged.
