### ISSUE TITLE
HELP - PIO project folder structure support

### ISSUE THREAD

**Issue by zafrirron** [platformio/platformio-atom-ide#1759]
I'm trying to create the following project structure (running on windows, PIO Atom IDE, esp8266 style board.

|-code
| ----|-Config
|---------|-all-core-related-config-headers
|---------|-Header files include also other header files
|---------|-From Sensors/Devices/Services folders...
|----|-Data - static data files
|----|-Sensors
|--------|-SensorA
|------------|-SensorA.h
|------------|-SensorA.cpp
|--------|-SensorB
|----|-Devices
|--------|-DeviceA
|------------|-DeviceA.h 
|------------|-DeviceA.cpp
|--------|-DeviceB
|----|-Services
|--------|-ServiceA 
|------------|-SeriveA.h
|------------|-ServiceA.cpp
|--------|-ServiceB 
|----|-Html
|----|-Lib
|--------|-all-helper-utils-headers & cpp
|----|-Plugins
|--------|-Plugin1
|------------|-Plugin1.h
|------------|-Plugin1.cpp
|--------|-Plugin2
|-main.cpp
|-other-core-code.cpp
|-doc

After reading all library (and LDF) definitions/options, I could not find a way to configure PIO to handle this project type. 
Before giving up, can anyone help?

**Comment by ivankravets** [comment]
http://community.platformio.org/
