### ISSUE TITLE
Autosave in Editor

### ISSUE THREAD

**Issue by gberl001** [platformio/platformio-atom-ide#177]
Can you add a feature to automatically save? 

I am used to using JetBrains' products and they have a feature I like in which saving is always automatic all the time.

**Comment by ivankravets** [comment]
PlatformIO IDE is based on Github Atom text editor and you can use hudreds their plugins/packages. See https://atom.io/packages/autosave

Also, all list https://atom.io/packages

**Comment by gberl001** [comment]
Thanks for the quick response, I'll check out this package.

**Comment by ivankravets** [comment]
Just click on "Settings" (:gear:) icon, go to packages and search for "autosave". Click on settings and enable it.
