### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by botmakerpl** [platformio/platformio-atom-ide#1770]
Cloning into 'C:\Users\ProgWeb\.platformio\platforms\_tmp_installing-maipei-package'...
Error: Could not install 'toolchain-xtensa32' with version requirements '~2.50200.0' for your system 'windows_x86'.

Please try this solution -> http://bit.ly/faq-package-manager

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/1171
