### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by MariusLaurinaitis** [platformio/platformio-atom-ide#1774]
Cloning into '/Users/laurinaitis/Downloads/espurna-1.12.5/code/.piolibdeps/_tmp_installing-8uOK5y-package'...
warning: Could not find remote branch 1.1.0 to clone.
fatal: Remote branch 1.1.0 not found in upstream origin
Error: VCS: Could not process command ['git', 'clone', '--recursive', '--depth', '1', '--branch', '1.1.0', 'https://bitbucket.org/xoseperez/hlw8012.git', '/Users/laurinaitis/Downloads/espurna-1.12.5/code/.piolibdeps/_tmp_installing-8uOK5y-package']

**Comment by ivankravets** [comment]
Where did you find that link? Author moved repo to https://github.com/xoseperez/hlw8012
