### ISSUE TITLE
Unable to execute: platformio

### ISSUE THREAD

**Issue by maru-sama** [platformio/platformio-atom-ide#180]
Hello, 

After updating atom to the latest version (1.12.3) on macosx I suddenly have the issue that Building, Cleaning or Uploading fails with "Unable to execute: platformio"
Make sure cmd'platformio'.......
Looking at the path which is being searched shows, that the path to the built-in platformIO is missing. If I then go to the platform-ide settings and toggle "Use builtin PlatformIO" (uncheck and check it again) everything works. It looks like that for some reason this is not setup correctly during startup.

**Comment by ivankravets** [comment]
I can't reproduce this issue. Could you try to uninstall `platformio-ide` package from the Atom and install again? Please go to :gear: Settings > Packages

**Comment by maru-sama** [comment]
No, re-installing does not fix the issue. I removed both ide and the terminal and reinstalled. But I still get the same error message.

**Comment by ivankravets** [comment]
Is this option enabled " "Use builtin PlatformIO" (uncheck and check it again) "?

**Comment by maru-sama** [comment]
Yes this is enabled, when I uncheck and check it again it works for this sessions. When I close atom and reopen it, this checkbox is STILL checked but I get the error. Doing an uncheck-check makes it work again.

**Comment by maru-sama** [comment]
In the error message Binaries are found in these folders: ......
does not include the pioenvs directory.
For me it looks like this is not set correctly during startup but works later on when you toggle the checkbox.

**Comment by maru-sama** [comment]
Ok, I tried to debug this.
maintenance.js correctly sets process.env.PATH and prepends the correct folder a debug output clearly shows this. BUT later on the build package errors out with above mentioned error and in its output process.env.PATH does NOT contain the folder.

**Comment by maru-sama** [comment]
Ok I found the issue. Atom changed the way it starts up on the mac ( https://github.com/atom/atom/pull/13200). Adding "activationHooks": ["core:loaded-shell-environment"] to package.json as mentioned in the ticket fixes the issue for me.

**Comment by ivankravets** [comment]
Thanks, added it to manifest.

**Comment by bobyk** [comment]
https://docs.platformio.org/en/latest/core/installation.html#method-2
