### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by ffnull** [platformio/platformio-atom-ide#1805]
Error: 
[04/30/18 00:31:33] Processing STM32F4 (platform: ststm32; board: disco_f407vg; framework: arduino)

Verbose mode can be enabled via `-v, --verbose` option
PLATFORM: ST STM32 > ST STM32F4DISCOVERY
SYSTEM: STM32F407VGT6 168MHz 128KB RAM (1MB Flash)
DEBUG: CURRENT(stlink) ON-BOARD(stlink) EXTERNAL(blackmagic, jlink)
Converting Marlin.ino
Error: This board doesn't support arduino framework!
 [ERROR] Took 1.51 seconds 

 [SUMMARY] 
Environment megaatmega2560          	[SKIP]
Environment megaatmega1280          	[SKIP]
Environment DUE                     	[SKIP]
Environment DUE_USB                 	[SKIP]
Environment DUE_debug               	[SKIP]
Environment LPC1768                 	[SKIP]
Environment LPC1768_debug_and_upload	[SKIP]
Environment melzi                   	[SKIP]
Environment melzi_optiboot          	[SKIP]
Environment rambo                   	[SKIP]
Environment sanguino_atmega644p     	[SKIP]
Environment sanguino_atmega1284p    	[SKIP]
Environment STM32F1                 	[SKIP]
Environment STM32F4                 	[ERROR]
Environment teensy20                	[SKIP]
Environment teensy35                	[SKIP]
Environment malyanm200              	[SKIP]
 [ERROR] Took 1.51 seconds

**Comment by ivankravets** [comment]
This board doesn't support arduino framework yet
