### ISSUE TITLE
function as parameter -> "was not declared in this scope"

### ISSUE THREAD

**Issue by stozk** [platformio/platformio-atom-ide#181]
Hi all,

I have a problem with an Arduino Sketch for a NodeMCU (esp8266) board.

It compiles on the Arduino IDE and everything works fine, but when I try to build it in platform.io,
I get this error:

....: error: 'callback' was not declared in this scope

void setup() {
  client.set_callback(callback);
}

void callback(const MQTT::Publish& pub) {
...
}

Any idea what might be causing this?
If I change the callback function params, it seems to accept the declaration but then  an error is thrown regarding wrong function params.

BR
Daniel

**Comment by ivankravets** [comment]
Please move this issue to https://github.com/platformio/platform-espressif8266/issues
