### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by salikhov829** [platformio/platformio-atom-ide#1810]
Cloning into 'C:\espurna-dev\code\.piolibdeps\_tmp_installing-bhgzib-package'...
fatal: unable to access 'https://bitbucket.org/xoseperez/debounceevent.git/': OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to bitbucket.org:443 
Error: VCS: Could not process command ['git', 'clone', '--recursive', '--depth', '1', '--branch', '2.0.1', 'https://bitbucket.org/xoseperez/debounceevent.git', 'C:\\espurna-dev\\code\\.piolibdeps\\_tmp_installing-bhgzib-package']

**Comment by salikhov829** [comment]
hi,i trying to use am  platformio from windows, it doesnt work, what can i do to resolve it?)? thanks

**Comment by ivankravets** [comment]
Please upgrade Git client
