### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by lepczynski** [platformio/platformio-atom-ide#1811]
I was trying to add a library
#include <avr/power.h>
And I think the slash "/" might have broken things ?

Cloning into '/Platformio/DoLPoC-0.1/DoLPoC 0.1/.piolibdeps/_tmp_installing-njGSy6-package'...
fatal: could not read Username for 'https://github.com': No such device or address
Error: VCS: Could not process command ['git', 'clone', '--recursive', '--depth', '1', 'https://github.com/avr/power', '/Platformio/DoLPoC-0.1/DoLPoC 0.1/.piolibdeps/_tmp_installing-njGSy6-package']

**Comment by ivankravets** [comment]
Please upgrade Git client

**Comment by lepczynski** [comment]
`git is already the newest version (1:2.7.4-0ubuntu1.4).`
: )

**Comment by ivankravets** [comment]
https://github.com/avr/power
