### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by SylviaYou** [platformio/platformio-atom-ide#1813]
Conda Virtualenv: CondaOSError: OS error: failed to link (src='/Users/yousoyoung/anaconda/pkgs/readline-6.2-2/include/readline/chardefs.h', dst='/Users/yousoyoung/.platformio/penv/include/readline/chardefs.h', type=1, error=FileNotFoundError(2, 'No such file or directory'))

**Comment by ivankravets** [comment]
Something is wrong with `conda` installation. Please upgrade conda, remove `/Users/yousoyoung/.platformio/penv` and restart IDE
