### ISSUE TITLE
Hardware debugging with simulavr and avr-gdb on eclipse

### ISSUE THREAD

**Issue by UntilSunrise** [platformio/platformio-atom-ide#182]
Is there a way to use the avr-gcc build attribute -g with platformio? At least with -g in my env build_flags doesnt work.

I followed this guide: http://www.ikravets.com/computer-life/programming/2014/06/20/building-and-debugging-atmel-avr-arduino-based-project-using-eclipse-ideplatformio as far as I can with eclipse-cdt neon but avr-gdb throws this errors:

No source file named /home/"username"/workspace-ccpp/"project-dir"/src/main.c.

With loading the platformio builded firmware.elf i cannot follow the code lines which the pc is pointing at, eclipse says "No source available for "main() at 0x27e" "

If I build manually via avr-gcc and -g parameter and use this generated firmware.elf i have no issues at all.

Simulated mcu: ATmega328p
OS: Arch linux
uname -a: Linux *** 4.8.8-2-ARCH #1 SMP PREEMPT Thu Nov 17 14:51:03 CET 2016 x86_64 GNU/Linux

**Comment by ivankravets** [comment]
Please move issue to https://github.com/platformio/platform-atmelavr
