### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by jeylites** [platformio/platformio-atom-ide#1827]
Error: Please manually remove file `/Users/Ran/Documents/PLATFORM IO /Sonoff-Tasmota5.13.1a/.pioenvs`
Can not remove temporary directory `/Users/Ran/Documents/PLATFORM IO /Sonoff-Tasmota5.13.1a/.pioenvs`. Please remove it manually to avoid build issues

[Thu May 10 01:05:08 2018] Processing sonoff-knx (platform: espressif8266; board: esp01_1m; framework: arduino)
--------------------------------------------------------------------------------
Exception: [Errno 13] Permission denied: '/Users/Ran/Documents/PLATFORM IO /Sonoff-Tasmota5.13.1a/.pioenvs/do-not-modify-files-here.url':
File "/Users/Ran/.platformio/penv/lib/python2.7/site-packages/platformio/builder/main.py", line 98:
PROJECTBUILD_DIR=util.get_projectbuild_dir(),
File "/Users/Ran/.platformio/penv/lib/python2.7/site-packages/platformio/util.py", line 313:
raise Exception(e)
========================== [ERROR] Took 1.72 seconds ==========================

================================== [SUMMARY] ==================================
Environment sonoff           	[SKIP]
Environment sonoff-minimal   	[SKIP]
Environment sonoff-classic   	[SKIP]
Environment sonoff-knx       	[ERROR]
Environment sonoff-allsensors	[SKIP]
Environment sonoff-BG        	[SKIP]
Environment sonoff-CN        	[SKIP]
Environment sonoff-CZ        	[SKIP]
Environment sonoff-DE        	[SKIP]
Environment sonoff-ES        	[SKIP]
Environment sonoff-FR        	[SKIP]
Environment sonoff-GR        	[SKIP]
Environment sonoff-HU        	[SKIP]
Environment sonoff-IT        	[SKIP]
Environment sonoff-NL        	[SKIP]
Environment sonoff-PL        	[SKIP]
Environment sonoff-PT        	[SKIP]
Environment sonoff-RU        	[SKIP]
Environment sonoff-TW        	[SKIP]
========================== [ERROR] Took 1.73 seconds ==========================

**Comment by ivankravets** [comment]
Please manually remove file /Users/Ran/Documents/PLATFORM IO /Sonoff-Tasmota5.13.1a/.pioenvs
