### ISSUE TITLE
Problem has been occured while installing PlatformIO IDE.

### ISSUE THREAD

**Issue by sileshibayu** [platformio/platformio-atom-ide#1838]
Error: Uninstalling platformio-ide ✗
Failed to delete platformio-ide: Does not exist

    at /home/sileshi/.atom/packages/platformio-ide/lib/installer/ide.js:66:84
    at Generator.throw (<anonymous>)
    at step (/home/sileshi/.atom/packages/platformio-ide/lib/installer/ide.js:89:273)

**Comment by ivankravets** [comment]
Please uninstall `platformio-ide` package and install it again
