### ISSUE TITLE
ArduinoJson does not install

### ISSUE THREAD

**Issue by rudynz** [platformio/platformio-atom-ide#184]
Hello

when I try to "ArduinoJson" I get the following error.

rudy@imacoffice23 ~/D/P/s/e/code> platformio lib install "ArduinoJson"
Library Storage: /home/rudy/Documents/Projekte/sonoff/espurna/code/.piolibdeps
Looking for ArduinoJson library in registry
Found: http://platformio.org/lib/show/64/ArduinoJson
LibraryManager: Installing id=64
Error: Got an unrecognized status code '404' when downloaded http://dl.platformio.org/libraries/archives/0/5570.tar.gz
rudy@imacoffice23 ~/D/P/s/e/code>  

thank you for your help
Rudy

**Comment by ivankravets** [comment]
Please run `pio update` and try again.

**Comment by ivankravets** [comment]
Opss, sorry, really a bug.
