### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by apballard** [platformio/platformio-atom-ide#1840]
Error: 
[Mon May 14 17:21:34 2018] Processing LPC1768 (platform: nxplpc; board: lpc1768)
--------------------------------------------------------------------------------
Warning! Library `{'requirements': None, 'name': 'CMSIS-LPC1768'}` has not been found in PlatformIO Registry.
You can ignore this message, if `{'requirements': None, 'name': 'CMSIS-LPC1768'}` is a built-in library (included in framework, SDK). E.g., SPI, Wire, etc.
Verbose mode can be enabled via `-v, --verbose` option
PLATFORM: NXP LPC > NXP mbed LPC1768
SYSTEM: LPC1768 100MHz 64KB RAM (512KB Flash)
DEBUG: CURRENT(cmsis-dap) ON-BOARD(cmsis-dap)
Library Dependency Finder -> http://bit.ly/configure-pio-ldf
LDF MODES: FINDER(off) COMPATIBILITY(light)
Collected 3 compatible libraries
Scanning dependencies...
Dependency Graph
|-- <CMSIS-LPC1768> v0.0.0
|-- <U8glib-HAL> v0.4
|-- <TMC2130Stepper> v2.3.0
OSError: [Errno 13] Permission denied: '/Volumes/Data/':
File "/Users/Ballard/.platformio/penv/lib/python2.7/site-packages/platformio/builder/main.py", line 171:
env.SConscript(item, exports="env")
File "/Users/Ballard/.platformio/packages/tool-scons/script/../engine/SCons/Script/SConscript.py", line 541:
return _SConscript(self.fs, *files, **subst_kw)
File "/Users/Ballard/.platformio/packages/tool-scons/script/../engine/SCons/Script/SConscript.py", line 250:
exec _file_ in call_stack[-1].globals
File "/Users/Ballard/Documents/GitHub/BigBoxMarlin/Marlin/src/HAL/HAL_LPC1768/upload_extra_script.py", line 121:
filenames = os.listdir('/Volumes/' + drive + '/')
========================== [ERROR] Took 3.46 seconds ==========================

================================== [SUMMARY] ==================================
Environment megaatmega2560          	[SKIP]
Environment megaatmega1280          	[SKIP]
Environment DUE                     	[SKIP]
Environment DUE_USB                 	[SKIP]
Environment DUE_debug               	[SKIP]
Environment LPC1768                 	[ERROR]
Environment LPC1768_debug_and_upload	[SKIP]
Environment melzi                   	[SKIP]
Environment melzi_optiboot          	[SKIP]
Environment rambo                   	[SKIP]
Environment sanguino_atmega644p     	[SKIP]
Environment sanguino_atmega1284p    	[SKIP]
Environment STM32F1                 	[SKIP]
Environment STM32F4                 	[SKIP]
Environment teensy20                	[SKIP]
Environment teensy35                	[SKIP]
Environment malyanm200              	[SKIP]
========================== [ERROR] Took 3.46 seconds ==========================

**Comment by ivankravets** [comment]
Please check permissions
