### ISSUE TITLE
InstallationManager error,why it so sucks.

### ISSUE THREAD

**Issue by talkingbeast** [platformio/platformio-atom-ide#1844]
Conda Virtualenv: 

CondaHTTPError: HTTP None None for url <None>
Elapsed: None

An HTTP error occurred when trying to retrieve this URL.
ProxyError(MaxRetryError("HTTPSConnectionPool(host='repo.continuum.io', port=443): Max retries exceeded with url: /pkgs/free/win-64/repodata.json.bz2 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0000000004E75CC0>: Failed to establish a new connection: [WinError 10061] ����Ŀ�����������ܾ����޷����ӡ�',)))",),)

**Comment by ivankravets** [comment]
Fixed.
