### ISSUE TITLE
ERROR: LSOpenURLsWithRole() with error-10810

### ISSUE THREAD

**Issue by malikshubham827** [platformio/platformio-atom-ide#185]
Whenever I try to open a file using 
`atom filename.extension` 
like  `atom index.html` , I get the following error:
`LSOpenURLsWithRole() failed for the application /Applications/Atom.app with error -10810.
`

I even tried using 
`open -a Atom index.html` 
the little atom icon just appears but then suddenly vanishes but the file isn't opened and neither I get any error.
I am using OSX EI Capitan.
Also there are two packages installed platforio-ide@1.7.1 and platformio-ide-terminal@2.2.2, are both necessary?

**Comment by ivankravets** [comment]
Please move this issue to https://github.com/atom/atom/issues
