### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by dmnbi4** [platformio/platformio-atom-ide#1857]
Cloning into '/Users/dmnbi4/distr/ESP_firmware/espurna-1.12.6/code/.piolibdeps/_tmp_installing-ktlo7D-package'...
warning: Could not find remote branch 1.1.8 to clone.
fatal: Remote branch 1.1.8 not found in upstream origin
Error: VCS: Could not process command ['git', 'clone', '--recursive', '--depth', '1', '--branch', '1.1.8', 'https://bitbucket.org/xoseperez/justwifi.git', '/Users/dmnbi4/distr/ESP_firmware/espurna-1.12.6/code/.piolibdeps/_tmp_installing-ktlo7D-package']

**Comment by ivankravets** [comment]
Fixed in dev branch https://github.com/xoseperez/espurna/tree/dev/code
