### ISSUE TITLE
Atom Material Breaks Serial Monitor Prompt

### ISSUE THREAD

**Issue by sdaitzman** [platformio/platformio-atom-ide#186]
![screen shot 2016-12-06 at 2 27 43 pm](https://cloud.githubusercontent.com/assets/1499476/20940356/75f4c75a-bbc0-11e6-86f2-8feb76faaa9a.png)

It looks like the dropdowns are being displayed with a huge height and the dialog does not allow scrolling.

Raised issue about to be posted at https://github.com/atom-material/atom-material-ui

- Atom v1.12.6
- MacOS 10.12.1
- Platformio-IDE v1.7.1
- Platformio-IDE-Terminal v2.2.2
- UI theme is atom-material-ui v1.3.8
- Syntax theme is One Dark v1.5.0

**Comment by ivankravets** [comment]
I like those new buttons 😊

**Comment by ivankravets** [comment]
Fixed in the latest PIO IDE 2.0 Beta 3

**Comment by ivankravets** [comment]
Should be fixed
