### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by cent0** [platformio/platformio-atom-ide#1868]
Cloning into 'C:\Python27\1.12.6 espurna\code\.piolibdeps\_tmp_installing-q5_jzj-package'...
warning: Could not find remote branch 1.1.8 to clone.
fatal: Remote branch 1.1.8 not found in upstream origin
Error: VCS: Could not process command ['git', 'clone', '--recursive', '--depth', '1', '--branch', '1.1.8', 'https://bitbucket.org/xoseperez/justwifi.git', 'C:\\Python27\\1.12.6 espurna\\code\\.piolibdeps\\_tmp_installing-q5_jzj-package']

this error have solution ?
best regards

**Comment by ivankravets** [comment]
Fixed in dev branch https://github.com/xoseperez/espurna/tree/dev/code
