### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by danybugg** [platformio/platformio-atom-ide#1869]
Hi,

I ise to build the core with old version.
I update library, I have now thi problem.
What is the good Board ID.
Thanks for your help.

Error: [05/26/18 21:55:24] Processing sonoff (platform: espressif8266; board: esp01_1m; framework: arduino)

Warning! `monitor_baud` option is deprecated and will be removed in the next release! Please use `monitor_speed` instead.
Warning! `board_flash_mode` option is deprecated and will be removed in the next release! Please use `board_build.flash_mode` instead.
Verbose mode can be enabled via `-v, --verbose` option
Error: Unknown board ID 'esp01_1m'
 [ERROR] Took 1.32 seconds 

 [SUMMARY] 
Environment sonoff        	[ERROR]
Environment sonoff-NL     	[SKIP]
Environment sonoff-minimal	[SKIP]
Environment sonoff-ds18x20	[SKIP]
 [ERROR] Took 1.32 seconds

**Comment by ivankravets** [comment]
`pio update`
