### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by joaojunior7cc** [platformio/platformio-atom-ide#1872]
PIP: Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/home/joaojr/.platformio/penv/lib/python2.7/site-packages/platformio-3.5.3a1-py2.7.egg-info/installed-files.txt'
Consider using the `--user` option or check the permissions.

**Comment by ivankravets** [comment]
Should be fixed in the latest release. Please upgrade. Also, try to remove `/home/joaojr/.platformio/penv` folder.
