### ISSUE TITLE
ImportError: No module named zlib

### ISSUE THREAD

**Issue by ackerschott** [platformio/platformio-atom-ide#1875]
Virtualenv Create: Traceback (most recent call last):
  File "/home/uwe/.platformio/.cache/tmp-27294o6hipFLE29ms/virtualenv-15.2.0/virtualenv.py", line 22, in <module>
    import zlib
ImportError: No module named zlib

**Comment by ivankravets** [comment]
Please provide an output from system Terminal `cmd`
```
echo %PATH%
echo %PYTHONPATH%
python --version
pip --version
pip list
```

**Comment by ivankravets** [comment]
Should be fixed in the latest release. Please update `platformio-ide` package via `Settings > Updates`.
