### ISSUE TITLE
How to disable PlatformIO in Atom?

### ISSUE THREAD

**Issue by urbanmichal** [platformio/platformio-atom-ide#188]
How to disable PlatformIO in Atom?

**Comment by ivankravets** [comment]
Settings ⚙️ > Packages > PlatformIO IDE > Disable

**Comment by tomkcook** [comment]
I have to say, it does feel a lot like a PlatformIO takes over your Atom installation.  I use Atom for a lot of things - PlatformIO is one of them, but it's an occasional one.  Now, when I'm hacking on ESP32 things on a weekend, it's great.  But during the week when I'm hacking other stuff that requires me to pop up Atom to edit some python every hour or so, it feels like way too often that PlatformIO gets in the way.  Disabling the "Show PlatformIO Home on startup", "Automatically Update PlatformIO IDE" and "Check PIO Account authentication status on IDE startup" settings does get rid of most of it, but these feel kind of like they either should be defaults or it should be possible to disable the automatic display of features from those features (ie the login form should have a 'Don't show me this again' checkbox).

**Comment by ivankravets** [comment]
https://github.com/platformio/platformio-atom-ide/blob/develop/lib/config.js#L105

**Comment by tenten8401** [comment]
I personally think there should be a hotkey or menu option to quickly disable/enable PlatformIO in the atom installation, or even just to hide the toolbar & whatnot immediately.

**Comment by miroslavpetrov** [comment]
@tomkcook I feel the same way. I use Atom for many other things than Platformio and the left-side toolbar is quite irritating...So is there a solution to enable/disable platformio with shortcut or key combination?

**Comment by cquiroz** [comment]
I agree, I use PlatformIO maybe 10% of my time but I need to see it always. A shortcut would be great

**Comment by ivankravets** [comment]
Please sorry for the issue. We highly recommend using [PlatformIO IDE for VSCode](https://marketplace.visualstudio.com/items?itemName=platformio.platformio-ide). It has muuuuch better integration with PlatformIO and resolves this issue.
