### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by MikeOne86** [platformio/platformio-atom-ide#1881]
Cloning into 'C:\Users\Loyd\Documents\espurna-master\code\.piolibdeps\_tmp_installing-rqglfy-package'...
warning: Could not find remote branch 1.1.8 to clone.
fatal: Remote branch 1.1.8 not found in upstream origin
Error: VCS: Could not process command ['git', 'clone', '--recursive', '--depth', '1', '--branch', '1.1.8', 'https://bitbucket.org/xoseperez/justwifi.git', 'C:\\Users\\Loyd\\Documents\\espurna-master\\code\\.piolibdeps\\_tmp_installing-rqglfy-package']

**Comment by ivankravets** [comment]
Fixed in dev branch https://github.com/xoseperez/espurna/tree/dev/code
