### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by AlbertoLopSie** [platformio/platformio-atom-ide#1882]
Error: Please manually remove file `/Users/Alberto/Devel/Sonoff-Tasmota-5.14.0/.pioenvs`
Can not remove temporary directory `/Users/Alberto/Devel/Sonoff-Tasmota-5.14.0/.pioenvs`. Please remove it manually to avoid build issues
[Fri Jun  1 18:47:38 2018] Processing sonoff (platform: espressif8266@1.5.0; board: esp01_1m; framework: arduino)
--------------------------------------------------------------------------------
Warning! `monitor_baud` option is deprecated and will be removed in the next release! Please use `monitor_speed` instead.
Warning! `board_flash_mode` option is deprecated and will be removed in the next release! Please use `board_build.flash_mode` instead.
Exception: [Errno 13] Permission denied: '/Users/Alberto/Devel/Sonoff-Tasmota-5.14.0/.pioenvs/do-not-modify-files-here.url':
File "/Users/Alberto/.platformio/penv/lib/python2.7/site-packages/platformio/builder/main.py", line 100:
PROJECTBUILD_DIR=util.get_projectbuild_dir(),
File "/Users/Alberto/.platformio/penv/lib/python2.7/site-packages/platformio/util.py", line 314:
raise Exception(e)
========================== [ERROR] Took 0.60 seconds ==========================

================================== [SUMMARY] ==================================
Environment sonoff           	[ERROR]
Environment sonoff-minimal   	[SKIP]
Environment sonoff-classic   	[SKIP]
Environment sonoff-knx       	[SKIP]
Environment sonoff-allsensors	[SKIP]
Environment sonoff-BG        	[SKIP]
Environment sonoff-BR        	[SKIP]
Environment sonoff-CN        	[SKIP]
Environment sonoff-CZ        	[SKIP]
Environment sonoff-DE        	[SKIP]
Environment sonoff-ES        	[SKIP]
Environment sonoff-FR        	[SKIP]
Environment sonoff-GR        	[SKIP]
Environment sonoff-HU        	[SKIP]
Environment sonoff-IT        	[SKIP]
Environment sonoff-NL        	[SKIP]
Environment sonoff-PL        	[SKIP]
Environment sonoff-PT        	[SKIP]
Environment sonoff-RU        	[SKIP]
Environment sonoff-TW        	[SKIP]
========================== [ERROR] Took 0.60 seconds ==========================

**Comment by ivankravets** [comment]
Please manually remove file /Users/Alberto/Devel/Sonoff-Tasmota-5.14.0/.pioenvs
