### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by galg71** [platformio/platformio-atom-ide#1899]
Cloning into 'C:\Users\GalG\Documents\Arduino\espurna-master-1.12.6\code\.piolibdeps\_tmp_installing-pm3hia-package'...
Note: checking out 'cc3baec18f87779cb60bbc221ae8da5a0c89b94f'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

Cloning into 'C:\Users\GalG\Documents\Arduino\espurna-master-1.12.6\code\.piolibdeps\_tmp_installing-gtv1dl-package'...
Note: checking out '4d57a2b37afeaf2fee1fa75bbcab260404e8f3c7'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

Submodule 'lib/googletest' (https://github.com/google/googletest.git) registered for path 'lib/googletest'
Cloning into 'C:/Users/GalG/Documents/Arduino/espurna-master-1.12.6/code/.piolibdeps/_tmp_installing-gtv1dl-package/lib/googletest'...
Cloning into 'C:\Users\GalG\Documents\Arduino\espurna-master-1.12.6\code\.piolibdeps\_tmp_installing-ioh6qx-package'...
warning: Could not find remote branch 1.1.8 to clone.
fatal: Remote branch 1.1.8 not found in upstream origin
Error: VCS: Could not process command ['git', 'clone', '--recursive', '--depth', '1', '--branch', '1.1.8', 'https://bitbucket.org/xoseperez/justwifi.git', 'C:\\Users\\GalG\\Documents\\Arduino\\espurna-master-1.12.6\\code\\.piolibdeps\\_tmp_installing-ioh6qx-package']

**Comment by ivankravets** [comment]
Fixed in dev branch https://github.com/xoseperez/espurna/tree/dev/code
