### ISSUE TITLE
Autocompletion does not work

### ISSUE THREAD

**Issue by sdouze** [platformio/platformio-atom-ide#1916]
I installed today PlatformIO and I cannot get autocopletion for arduino to work.Any idea to solve this?
I have clang installed.
I am using atom.

**Comment by ivankravets** [comment]
It does not work for INO files. http://docs.platformio.org/en/latest/ide/atom.html#intelligent-code-completion

Also, try PIO IDE for VSCode.

**Comment by sdouze** [comment]
Hello,
I am using .cpp files not ino.
To use VSCode it's not a solution to the problem ,cause I don't like VSCode.

**Comment by ivankravets** [comment]
What is your OS?

**Comment by sdouze** [comment]
Windows 10

**Comment by sdouze** [comment]
Windows 10

**Comment by PNixx** [comment]
On Mac Os not working autocompletion.

**Comment by ivankravets** [comment]
Please switch to PlatformIO IDE for VSCode => https://platformio.org/install/ide?install=vscode

**Comment by PNixx** [comment]
I like Atom, not VSCode

**Comment by ivankravets** [comment]
See http://docs.platformio.org/en/latest/ide/atom.html#intelligent-code-completion

Atom has limited support for C/C++ programming and is not recommended.
