### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by kongon** [platformio/platformio-atom-ide#1917]
Error: Processing pico32 (platform: espressif32; board: pico32; framework: espidf)

Verbose mode can be enabled via `-v, --verbose` option
PLATFORM: Espressif 32 > ESP32 Pico Kit
SYSTEM: ESP32 240MHz 288KB RAM (1.25MB Flash)
Library Dependency Finder -> http://bit.ly/configure-pio-ldf
LDF MODES: FINDER(chain) COMPATIBILITY(soft)
Collected 0 compatible libraries
Scanning dependencies...
No dependencies

*** Multiple ways to build the same target were specified for: C:\Users\kongon\Documents\PlatformIO\Projects\bluevend\.pioenvs\pico32\src\main.o  (from ['C:\\Users\\kongon\\Documents\\PlatformIO\\Projects\\bluevend\\src\\main.c'] and from ['C:\\Users\\kongon\\Documents\\PlatformIO\\Projects\\bluevend\\src\\main.cpp'])
File "C:\Users\kongon\.platformio\penv\lib\site-packages\platformio\builder\tools\platformio.py", line 307, in BuildSources
 [ERROR] Took 7.08 seconds 

 [SUMMARY] 
Environment pico32  	[ERROR]
Environment esp32dev	[SKIP]
 [ERROR] Took 7.08 seconds

**Comment by ivankravets** [comment]
Please keep different names for `main.c` and `main.cpp`
