### ISSUE TITLE
PlatformIO Core keeps installing after every restart

### ISSUE THREAD

**Issue by hdavidka** [platformio/platformio-atom-ide#1925]
I've started Atom today, and this happened...

**Comment by ivankravets** [comment]
What is your OS?

**Comment by KlausBer** [comment]
Just for information i have the same problem. Try on different machines, my mac works but not on windows 10 and 8.1
It restarts and try instaææing the core again

**Comment by ivankravets** [comment]
Please provide a log from `Menu > View > Developer > Toggle Developer Tools > Console`

**Comment by ivankravets** [comment]
Sorry, that was a bug on our side. Please upgrade to v2.1.6

**Comment by Nos-De** [comment]
even today its still the same issue on my windows
