### ISSUE TITLE
No module named pip

### ISSUE THREAD

**Issue by Pandora-jshimpf** [platformio/platformio-atom-ide#1928]
# Description of problem
Leave a comment...

BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
- https://github.com/platformio/platformio-atom-ide/issues

# Configuration
Atom: 1.26.1
PIO IDE: v2.1.6
System: Darwin, 17.6.0, x64

# Exception
```
PIP: /Users/jim/.platformio/penv/bin/python: No module named pip

```

**Comment by ivankravets** [comment]
Please provide an output from a system Terminal
```
echo $PATH
echo $PYTHONPATH
python --version
pip --version
pip list
/Users/jim/.platformio/penv/bin/pip --version
```

**Comment by ivankravets** [comment]
Should be fixed in the latest release. Please update `platformio-ide` package via `Settings > Updates`.
