### ISSUE TITLE
(node:9746) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.

### ISSUE THREAD

**Issue by Adam-Morris** [platformio/platformio-atom-ide#193]
I get this error when trying to install the platformio-ide package for Atom. 

"(node:9746) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead."

**Comment by ivankravets** [comment]
Could you provide full exception output?

**Comment by ivankravets** [comment]
Please reopen if you still have this issue
