### ISSUE TITLE
Allow python executable to be installed at arbitrary location

### ISSUE THREAD

**Issue by cinderblock** [platformio/platformio-atom-ide#1932]
Currently the Atom PIO plugin seems to require `python` to be available on the path. The UI suggests this is not required but I haven't gotten that to work. This causes problems for me as I use Python 3's `python` from the path for other purposes. IMHO, binaries in the path are for humans, not scripts.

When `python` executable isn't found on the path, a dialog box is launched prompting me to select a folder that contains `python\python.exe`. This seems to be what I want, but it doesn't work for me for a couple reasons (that maybe could be changed on my end but I feel they should be fixed here).

1. Why is it looking for a folder that has a folder called `python` with a binary `python.exe` inside that? Why can't I just specify the folder that has `python.exe` inside it? Or better yet, just let me directly select the executable. Is there some reason this is not possible?
2. I tried renaming `C:\Python27` to `C:\python` and could not get the IDE to find my executable by selecting the `C:\` folder or the folder that has `python.exe` inside of it. I did not try putting the `python` folder at a deeper level.

I'm on Windows of course but I believe this is an issue for all OSes.

**Comment by ivankravets** [comment]
Please upgrade to v2.1.7 via Atom > Settings > Updates. Should be fixed.

Please remove `HOME_DIR/.platform/penv` folder and restart IDE.
