### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by mcsSolutions** [platformio/platformio-atom-ide#1936]
# Description of problem
Occurred after platformio pushed an update.  Incompatible Atom files found as noted by bug icon in lower right.  Rebuilt.  Serial Monitor opened, but no serial data was showing as it did before pushed update.  Closed Atom.  Opened again and the last project did not appear as normally happened before.  Opened the project folder and this message appeared.

BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
- https://github.com/platformio/platformio-atom-ide/issues

# Configuration
Atom: 1.28.0
PIO IDE: v2.1.6
System: Windows_NT, 6.1.7601, x64

# Exception
```
'platformio' is not recognized as an internal or external command,
operable program or batch file.
Error: spawn platformio ENOENT
```

**Comment by ivankravets** [comment]
Please upgrade to v2.1.7 via Atom > Settings > Updates. Should be fixed.
