### ISSUE TITLE
Start PIO Home Server

### ISSUE THREAD

**Issue by TheStonePlayer** [platformio/platformio-atom-ide#1939]
# Description of problem
Beside this, there was another problem .(ID: #1360 )

# Configuration
Atom: 1.28.0
PIO IDE: v2.1.6
System: Windows_NT, 10.0.15063, x64

# Exception
```
Could not start PIO Home server: Error: timeout
```

**Comment by ivankravets** [comment]
Please upgrade to v2.1.7 via Atom > Settings > Updates. Should be fixed.
