### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by lutz1502** [platformio/platformio-atom-ide#1941]
# Description of problem
Leave a comment...

BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
- https://github.com/platformio/platformio-atom-ide/issues

# Configuration
Atom: 1.28.0
PIO IDE: v2.1.6
System: Windows_NT, 6.1.7601, x64

# Exception
```
'platformio' n�o � reconhecido como um comando interno
ou externo, um programa oper�vel ou um arquivo em lotes.
Error: spawn platformio ENOENT
```

**Comment by ivankravets** [comment]
Please provide an output from system Terminal `cmd`
```
echo %PATH%
echo %PYTHONPATH%
python --version
pip --version
pip list
```

**Comment by ivankravets** [comment]
Please upgrade to v2.1.7 via Atom > Settings > Updates. Should be fixed.
