### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by igitapino** [platformio/platformio-atom-ide#1944]
# Description of problem
Leave a comment...

BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
- https://github.com/platformio/platformio-atom-ide/issues

# Configuration
Atom: 1.27.2
PIO IDE: v2.1.6
System: Windows_NT, 10.0.16299, x64

# Exception
```
Error: Processing nodemcuv2 (platform: espressif8266; board: nodemcuv2h; framework: arduino)

Verbose mode can be enabled via `-v, --verbose` option
Error: Unknown board ID 'nodemcuv2h'
 [ERROR] Took 20.92 seconds 


```

**Comment by ivankravets** [comment]
nodemcuv2h -> nodemcuv2
