### ISSUE TITLE
PlatformIO IDE insists I want minimap

### ISSUE THREAD

**Issue by micr0me** [platformio/platformio-atom-ide#195]
Minimap is a package I find little use for (and find rather annoying). I've tried disabling minimap under Settings->Packages -- that doesn't work. I've tried uninstalling the package. However, every time I start atom PlatformIO installs it again.

Can someone please point me to a way of disabling this? I apologize if it's obvious.

**Comment by ivankravets** [comment]
This is a bug, thank you! 

Temporary solution is to manually remove/comment this line

* https://github.com/platformio/platformio-atom-ide/blob/develop/lib/config.js#L103

This file is located in `~/.atom/packages/platformio-ide/lib/config.js`.

**Comment by micr0me** [comment]
That works great. Thank you!

**Comment by ivankravets** [comment]
Fixed in a new PlatformIO IDE 2.0 installer

**Comment by surdu** [comment]
This is still an issue in v2.0.0-beta.6

**Comment by ivankravets** [comment]
Just disable Minimap package

**Comment by surdu** [comment]
Isn't desireable to have an option to disable minimap requirement ?

I could try implementing it ...
