### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by jorgeassuncao** [platformio/platformio-atom-ide#1952]
# Description of problem
Leave a comment...

BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
- https://github.com/platformio/platformio-atom-ide/issues

# Configuration
Atom: 1.28.0
PIO IDE: v2.1.7
System: Windows_NT, 10.0.17134, x64

# Exception
```
Error: spawn platformio ENOENT
```

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/1243
