### ISSUE TITLE
PlatformIO: Terminal service is not registered

### ISSUE THREAD

**Issue by cristianszwarc** [platformio/platformio-atom-ide#196]
Hi, put myself in this position and not able to find info on any current similar issue.

- Fresh Lubuntu 16.04 installation
- Installed Atom 1.12.7 and a bunch of packages that "should" not conflict with platformio (webdev)
- Selected to install `platformio-atom-ide` from the packages search, this also installed `platformio-ide-terminal` as expected
- added my user to dialup, installed clang and 99-platformio-udev.rules

I'm able to compile and flash a nodemcu esp8266 but I can not open the Terminal nor the Serial Monitor (can select the port but then when tries to show the terminal fails)

**getting:**

```
PlatformIO: Terminal service is not registered.
Make sure that "platformio-ide-terminal" package is installed.
```

uninstalled `platformio-ide-terminal` and installed it again, but same deal

any suggestions?

(thanks for this amazing piece of work, love it)

**Comment by ivankravets** [comment]
1. Install `gcc`
2. Goto to Package Manager in Atom and uninstall `platformio-ide-terminal`
3. Install `platformio-ide-terminal` again.
4. Restart Atom

**Comment by cristianszwarc** [comment]
hi, thanks for your answer, sorry for the delay on answering, regarding gcc it is already installed, uninstalled and installed it again that day and again Today, same deal :(
```
sudo apt-get install gcc
Reading package lists... Done
Building dependency tree       
Reading state information... Done
gcc is already the newest version (4:5.3.1-1ubuntu1).
gcc set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

**Comment by marble** [comment]
I can confirm the problem for Ubuntu 14.04 LTS, Atom 1.13.1, PlatformIO 1.7.1, platform-ide-terminal 2.2.2. GCC is installed, reinstalled platform-ide-terminal + restart, problem remains.

**Comment by marble** [comment]
Same or similar to https://github.com/platformio/platformio-atom-ide-terminal/issues/117

**Comment by cristianszwarc** [comment]
@marble yes! that's it

same "1 bug icon" on the bottom right. thanks!

**Comment by amayii0** [comment]
Had exact same issue after multiple upgraded packages/stuff, rebuilding didn't helped.
Uninstall + Install of Terminal package fixed it.
