### ISSUE TITLE
platformio-ide breaks pyls (python language server)

### ISSUE THREAD

**Issue by HetorusNL** [platformio/platformio-atom-ide#1960]
before installing platformio-ide and when disabling the platformio-ide package, the python language server (pyls) was working correctly.
after installing platformio-ide, Atom complains about:
Unable to start the Python language server.
Make sure to install pyls 0.19 or newer by running:
python -m pip install 'python-language-server[all]'

Python: 2.7 (running in virtual-env)
OS: Kali Linux (based on Debian Stretch)
Atom: 1.27.2 (started from console in python virtual-env)

![screenshot from 2018-06-28 16-08-39](https://user-images.githubusercontent.com/17402329/42039676-3f3021bc-7aee-11e8-9eb3-483172524ae7.png)
![screenshot from 2018-06-28 16-10-30](https://user-images.githubusercontent.com/17402329/42039677-3f71f358-7aee-11e8-82e7-916f0cf47c83.png)

**Comment by martenjacobs** [comment]
I have the same issue under macOS 10.14 (18A391)

**Comment by ivankravets** [comment]
We have just released a new version [2.7.0](https://github.com/platformio/platformio-atom-ide/releases/tag/v2.7.0), please upgrade.

**Please note that we HIGHLY recommend moving to [PlatformIO IDE for VSCode](https://platformio.org/platformio-ide) which resolves tons of issues and brings a lot of new features.**
