### ISSUE TITLE
Start PIO Home Server

### ISSUE THREAD

**Issue by UweSeifert** [platformio/platformio-atom-ide#1969]
# Description of problem
Leave a comment...

BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
- https://github.com/platformio/platformio-atom-ide/issues

# Configuration
Atom: 1.28.0
PIO IDE: v2.1.7
System: Darwin, 17.6.0, x64

# Exception
```
Traceback (most recent call last):
  File "main.py", line 17, in init main
  File "cmd_home.py", line 39, in init cmd_home
TypeError: __init__() got an unexpected keyword argument 'expire'

```

After update PIO

**Comment by ivankravets** [comment]
Please open PIO IDE Terminal and type
```
pio upgrade --dev
pio update
```

Restart IDE. Everything should work now.
