### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'startswith'

### ISSUE THREAD

**Issue by stelgenhof** [platformio/platformio-atom-ide#1983]
In Atom when updating PlatformIO, I got the following error message:

```
Virtualenv Create: Traceback (most recent call last):
  File "/home/sacha/.platformio/.cache/tmp-3382AeqmhbB1WsBX/virtualenv-14.0.6/virtualenv.py", line 2304, in <module>
    main()
  File "/home/sacha/.platformio/.cache/tmp-3382AeqmhbB1WsBX/virtualenv-14.0.6/virtualenv.py", line 705, in main
    symlink=options.symlink)
  File "/home/sacha/.platformio/.cache/tmp-3382AeqmhbB1WsBX/virtualenv-14.0.6/virtualenv.py", line 904, in create_environment
    site_packages=site_packages, clear=clear, symlink=symlink))
  File "/home/sacha/.platformio/penv/lib/python2.7/posixpath.py", line 360, in abspath
    if not isabs(path):
  File "/home/sacha/.platformio/penv/lib/python2.7/posixpath.py", line 54, in isabs
    return s.startswith('/')
AttributeError: 'NoneType' object has no attribute 'startswith'
```

I'm running Arch Linux  4.17.3-1-ARCH

**Comment by ivankravets** [comment]
Could you try to remove `/home/sacha/.platformio/penv` folder and restart? Does it work now?

**Comment by stelgenhof** [comment]
I have removed `/home/sacha/.platformio/penv` and can see other updates are being installed successfully. However when Atom tries to update/upgrade PlatformIO I now get the following message:

> Install Virtualenv globally: /usr/bin/python2.7: No module named pip

**Comment by stelgenhof** [comment]
Sure!
```
$PATH: /usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
$PYTHONPATH: <blank>
python --version: Python 3.6.6
pip --version: pip 10.0.1 from /usr/lib/python3.6/site-packages/pip (python 3.6)
pip list:Package           Version         
----------------- ----------------
altgraph          0.15            
appdirs           1.4.3           
astroid           1.6.1           
autopep8          1.3.1           
btrfsutil         1.0.0           
CacheControl      0.12.5          
chardet           3.0.4           
colorama          0.3.9           
distlib           0.2.7           
distro            1.3.0           
ecdsa             0.13            
enum-compat       0.0.2           
esptool           2.0             
future            0.16.0          
html5lib          1.0.1           
idna              2.7             
isort             4.3.4           
lazy-object-proxy 1.3.1           
lensfun           0.3.2           
lockfile          0.12.2          
louis             3.6.0           
macholib          1.9             
mccabe            0.6.1           
msgpack           0.5.6           
netifaces         0.10.6          
packaging         17.1            
pbr               3.1.1           
pefile            2017.11.5       
pip               10.0.1          
progress          1.4             
psutil            5.4.6           
pyaes             1.6.0           
pycodestyle       2.3.1           
Pygments          2.2.0           
pygobject         3.28.3          
PyInstaller       3.3.1           
pylint            1.8.2           
pyparsing         2.2.0           
PyQt5-sip         4.19.12         
pyqtdeploy        2.1             
pyserial          3.3             
pytoml            0.1.16          
pyxdg             0.26            
Reflector         2018.3.3.22.1.34
requests          2.19.1          
retrying          1.3.3           
setuptools        39.2.0          
six               1.11.0          
sortedcontainers  1.5.9           
stevedore         1.28.0          
urllib3           1.23            
virtualenv        15.1.0          
virtualenv-clone  0.2.6           
virtualenvwrapper 4.8.2           
webencodings      0.5.1           
wrapt             1.10.11         
zeroconf          0.19.1 
```

**Comment by ivankravets** [comment]
Do you have python2.7 in a system?

**Comment by stelgenhof** [comment]
Yes, python 2.7 is also installed on my system however the binary is located here:` /usr/bin/python2`

**Comment by stelgenhof** [comment]
I've removed the entire ~/.platformio folder and started Atom again. Now the upgrade finished successfully. However after restarting Atom, I get the following message:

`Error: Could not create PIO Core Virtual Environment. Please create it manually -> http://bit.ly/pio-core-virtualenv at t. (/home/sacha/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/lib/index.js:1:29674) at P (/home/sacha/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/lib/index.js:1:16056) at Generator._invoke (/home/sacha/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/lib/index.js:1:15844) at Generator.e.(anonymous function) [as throw] (/home/sacha/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/lib/index.js:1:16235) at n (/home/sacha/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/lib/index.js:1:22314) at /home/sacha/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/lib/index.js:1:22433 at...`

**Comment by ivankravets** [comment]
Could you provide TeamViewer session where I can try investigate this issue? You can send details to me@ikravets.com

**Comment by stelgenhof** [comment]
Sure! I'm not familiar with TeamViewer so you may need to help me get through it :)

**Comment by stelgenhof** [comment]
@ivankravets Thank you for the time checking my environment. As it turns out my Python2 installation was broken. I have performed a reinstall of Python2 and managed to upgrade PlatformIO successfully. 

Thanks again for your support!

**Comment by ivankravets** [comment]
Happy coding with PlatformIO! ;)
