### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by Phlatline03** [platformio/platformio-atom-ide#1989]
# Description of problem
Leave a comment...

BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
- https://github.com/platformio/platformio-atom-ide/issues

# Configuration
Atom: 1.28.1
PIO IDE: v2.1.7
System: Windows_NT, 10.0.17134, x64

# Exception
```
Error: [API] Invalid response: <html>

<head>

<meta http-equiv="Refresh" content="1; URL=https://avertizare.starnet.md?uid=25C07F5C-708B-4AFC-A16B-3E34E0A06C8E&vc=3ZIYHBl">

<meta http-equiv="pragma" content="no-cache">

</head>

<body>

Please wait while you are redirected ...

</body>

</html>



```

**Comment by ivankravets** [comment]
Do you use proxy? Please check your Internet connection
