### ISSUE TITLE
Object.extname is deprecated.

### ISSUE THREAD

**Issue by blakehurlburt** [platformio/platformio-atom-ide#199]
Argument to `path.extname` must be a string
```
Object.extname (/usr/share/atom/resources/app.asar/src/electron-shims.js:20:10)
<unknown> ($HOME/.atom/packages/platformio-ide/lib/main.js:274:39)
Workspace.observeTextEditors (/usr/share/atom/resources/app.asar/src/workspace.js:329:9)
Object.setupCommands ($HOME/.atom/packages/platformio-ide/lib/main.js:272:43)
<unknown> ($HOME/.atom/packages/platformio-ide/lib/main.js:89:20)
```

**Comment by ivankravets** [comment]
What is a version of PIO IDE? How to reproduce this issue?

**Comment by ivankravets** [comment]
@sobodash what is your PIO IDE version?

**Comment by ivankravets** [comment]
This is a stupid warning. Please ignore it. Do you see it after Atom restart?

**Comment by sobodash** [comment]
I see it every time I open Atom in the lower right corner. I am on IDE 1.7.1 and Core 3.2.1

**Comment by lukehoggett** [comment]
I get this warning after upgrading to Atom 1.13.0 in the deprecations screen

**Comment by chedongzhe** [comment]
Argument to path.extname must be a string
Report Issue
Object.extname - C:\Users\CheDongZhe\AppData\Local\atom\app-1.13.0\resources\app.asar\src\electron-shims.js:20:10
<unknown> - C:\Users\CheDongZhe\.atom\packages\platformio-ide\lib\main.js:274:39
Workspace.observeTextEditors - C:\Users\CheDongZhe\AppData\Local\atom\app-1.13.0\resources\app.asar\src\workspace.js:329:9
Object.setupCommands - C:\Users\CheDongZhe\.atom\packages\platformio-ide\lib\main.js:272:43
<unknown> - C:\Users\CheDongZhe\.atom\packages\platformio-ide\lib\main.js:89:20

**Comment by shanevanj** [comment]
Guys - the error is still there - can it be patched out?

**Comment by ivankravets** [comment]
@shanevanj soon! :) Stay tuned with us on https://twitter.com/PlatformIO_Org
