### ISSUE TITLE
Start PIO Home Server

### ISSUE THREAD

**Issue by fraeggle** [platformio/platformio-atom-ide#1990]
# Description of problem
Leave a comment...

BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
- https://github.com/platformio/platformio-atom-ide/issues

# Configuration
Atom: 1.28.1
PIO IDE: v2.1.7
System: Windows_NT, 10.0.17134, x64

# Exception
```
Der Befehl "platformio" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
Error: spawn platformio ENOENT
```

**Comment by fraeggle** [comment]
I allways receive this error. If i open the Folder in a new Window, everything is okay

**Comment by ivankravets** [comment]
Please open PIO IDE Terminal and type
```
pio upgrade --dev
pio update
```

Restart IDE. Everything should work now.
