### ISSUE TITLE
dependency linker can't deal with multiple folder layers.

### ISSUE THREAD

**Issue by DasVoelkel** [platformio/platformio-atom-ide#1991]
https://community.platformio.org/t/esp88266-i-think-your-linker-is-wrongly-configured-or-broken/4529

Pretty easy to reproduce, and i am confused by this since the readme file in the lib folder has such a case...

**Comment by ivankravets** [comment]
https://community.platformio.org/t/esp88266-i-think-your-linker-is-wrongly-configured-or-broken/4529/14?u=ivankravets
