### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by ethan92429** [platformio/platformio-atom-ide#1992]
# Description of problem
Leave a comment...

BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
- https://github.com/platformio/platformio-atom-ide/issues

# Configuration
Atom: 1.28.1
PIO IDE: v2.1.7
System: Darwin, 17.5.0, x64

# Exception
```
Conda Virtualenv: ERROR conda.core.link:_execute(502): An error occurred while installing package 'conda-forge::ca-certificates-2018.4.16-0'.
AssertionError()
Attempting to roll back.


AssertionError()



```

**Comment by ivankravets** [comment]
Please upgrade/fix your Conda installation
