### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by studentstudio** [platformio/platformio-atom-ide#1993]
# Description of problem
Leave a comment...

BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
- https://github.com/platformio/platformio-atom-ide/issues

# Configuration
Atom: 1.28.1
PIO IDE: v2.1.7
System: Windows_NT, 6.1.7601, x64

# Exception
```
platformio nen� n�zvem vnit�n�ho ani vn�j�ho p��kazu,
spustiteln�ho programu nebo d�vkov�ho souboru.
Error: spawn platformio ENOENT
```

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/1243
