### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by PrakashManoharan** [platformio/platformio-atom-ide#2001]
# Description of problem
Leave a comment...

BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
- https://github.com/platformio/platformio-atom-ide/issues

# Configuration
Atom: 1.28.1
PIO IDE: v2.1.7
System: Windows_NT, 10.0.17134, x64

# Exception
```
Install Virtualenv globally: Error: spawn C:\Users\praka\.platformio\penv\Scripts\python.exe ENOENT
```

**Comment by Henkeh** [comment]
I have seen this error as well during my struggles to get PIO installed. Possible solution can be found in my post in:
https://github.com/platformio/platformio-atom-ide/issues/1950

**Comment by ivankravets** [comment]
Please try this solution http://docs.platformio.org/en/latest/installation.html#virtual-environment
