### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by rjpo** [platformio/platformio-atom-ide#2016]
# Description of problem
Leave a comment...

BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
- https://github.com/platformio/platformio-atom-ide/issues

# Configuration
Atom: 1.28.1
PIO IDE: v2.1.7
System: Windows_NT, 10.0.14393, x64

# Exception
```
Install Virtualenv globally: El sistema no puede encontrar la ruta especificada.
Error: spawn C:\Users\Ricardo\.platformio\penv\Scripts\python.exe ENOENT
```

**Comment by ivankravets** [comment]
Please try this solution http://docs.platformio.org/en/latest/installation.html#virtual-environment
