### ISSUE TITLE
Start PIO Home Server

### ISSUE THREAD

**Issue by nbJosh** [platformio/platformio-atom-ide#2021]
# Description of problem
Unable to get to the "Home" screen for platformIO in Atom,   so I can't start any new projects,  or convert any arduino projects

when attempting to update platformIO I get the following:
:> platformio upgrade
Error: Can not retrieve the latest PlatformIO version

BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
- https://github.com/platformio/platformio-atom-ide/issues

# Configuration
Atom: 1.28.1
PIO IDE: v2.1.7
System: Darwin, 17.7.0, x64

# Exception
```
Traceback (most recent call last):
  File "main.py", line 17, in init main
  File "cmd_home.py", line 39, in init cmd_home
TypeError: __init__() got an unexpected keyword argument 'expire'

```

**Comment by ivankravets** [comment]
Please remove multiple PIO Cores from a system http://docs.platformio.org/en/latest/faq.html#multiple-pio-cores-in-a-system
