### ISSUE TITLE
Installed / Built-in libraries not found

### ISSUE THREAD

**Issue by ambarusa** [platformio/platformio-atom-ide#2028]
After developing a software for a while, suddenly the compiler gives "fatal error: ... no such file or directory" errors on libraries. I wasn't modifying anything at all, he code was tested and it worked perfectly. Already tried cleaning the project, adding libraries with lib_deps, reinstalling libraries, nothing helped. I have the same issue with ESP8266WiFi and EEPROM built-in libraries.

**Comment by ivankravets** [comment]
Please post to https://community.platformio.org/
