### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by roboter** [platformio/platformio-atom-ide#2030]
# Description of problem
Leave a comment...

BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
- https://github.com/platformio/platformio-atom-ide/issues

# Configuration
Atom: 1.28.2
PIO IDE: v2.1.11
System: Windows_NT, 10.0.17692, x64

# Exception
```
'platformio' is not recognized as an internal or external command,
operable program or batch file.
Error: spawn platformio ENOENT
```

**Comment by ivankravets** [comment]
Fixed in the latest version of Atom and PlatformIO IDE package. Please update.
