### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by harrylisby** [platformio/platformio-atom-ide#2033]
# Description of problem
Leave a comment...

BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
- https://github.com/platformio/platformio-atom-ide/issues

# Configuration
Atom: 1.28.2
PIO IDE: v2.1.7
System: Linux, 4.15.0-29-generic, x64

# Exception
```
Install Virtualenv globally: Error: spawn /home/lisby/.platformio/penv/bin/python2.7 ENOENT
```

**Comment by ivankravets** [comment]
Please try to create PIO Core virtual environment manually http://docs.platformio.org/en/latest/installation.html#virtual-environment
