### ISSUE TITLE
Start PIO Home Server

### ISSUE THREAD

**Issue by seristee** [platformio/platformio-atom-ide#2035]
# Description of problem
Leave a comment...

BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
- https://github.com/platformio/platformio-atom-ide/issues

# Configuration
Atom: 1.28.2
PIO IDE: v2.1.11
System: Windows_NT, 10.0.17134, x64

# Exception
```
Could not start PIO Home server: Error: timeout
```

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-vscode-ide/issues/205
