### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by bobhinkle** [platformio/platformio-atom-ide#2036]
# Description of problem
Leave a comment...

BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
- https://github.com/platformio/platformio-atom-ide/issues

# Configuration
Atom: 1.28.1
PIO IDE: v2.1.7
System: Windows_NT, 6.1.7601, x64

# Exception
```
Error: spawn platformio ENOENT
```

**Comment by ivankravets** [comment]
Fixed in the latest version of Atom and PlatformIO IDE package. Please update.
