### ISSUE TITLE
Start PIO Home Server

### ISSUE THREAD

**Issue by thbui** [platformio/platformio-atom-ide#2050]
# Description of problem
This happens every time PlatformIO try to do an upgrade.

BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
- https://github.com/platformio/platformio-atom-ide/issues

# Configuration
Atom: 1.28.2
PIO IDE: v2.1.7
System: Windows_NT, 6.3.9600, ia32

# Exception
```
Please manually remove file `C:\Users\thbui\.platformio\packages\tool-pioplus\pioplus.exe`
Please manually remove file `C:\Users\thbui\.platformio\packages\tool-pioplus\pioplus.exe`
Error: Could not install 'tool-pioplus' with version requirements '^1.4.2' for your system 'windows_x86'.

Please try this solution -> http://bit.ly/faq-package-manager

```

**Comment by ivankravets** [comment]
Please update Atom + PlatformIO IDE package to the latest version. Everything should work well.
