### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by spaxxomatic** [platformio/platformio-atom-ide#2051]
# Description of problem
Leave a comment...

BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
- https://github.com/platformio/platformio-atom-ide/issues

# Configuration
Atom: 1.28.2
PIO IDE: v2.1.11
System: Windows_NT, 10.0.17134, ia32

# Exception
```
Der Befehl "platformio" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
Error: spawn platformio ENOENT
```

**Comment by ivankravets** [comment]
Fixed in the latest version of Atom and PlatformIO IDE package. Please update.
