### ISSUE TITLE
Start PIO Home Server

### ISSUE THREAD

**Issue by Phlatline03** [platformio/platformio-atom-ide#2053]
# Description of problem
Leave a comment...

BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
- https://github.com/platformio/platformio-atom-ide/issues

# Configuration
Atom: 1.29.0
PIO IDE: v2.1.7
System: Windows_NT, 10.0.17134, x64

# Exception
```
"platformio" �� ���� ����७��� ��� ���譥�
��������, �ᯮ��塞�� �ணࠬ��� ��� ������ 䠩���.
Error: spawn platformio ENOENT
```

**Comment by ivankravets** [comment]
Please update Atom + PlatformIO IDE package to the latest version. Everything should work well.
