### ISSUE TITLE
Problem occured while upgrading PlatformIO IDE

### ISSUE THREAD

**Issue by belalmc** [platformio/platformio-atom-ide#2054]
Error: Unable to download https://www.atom.io/api/packages/platformio-ide/versions/2.1.13/tarball: self signed certificate in certificate chain

    at file:///C:/Users/Omar/.atom/packages/platformio-ide/lib/installer/ide.js:59:9
    at Generator.throw (<anonymous>)
    at step (file:///C:/Users/Omar/.atom/packages/platformio-ide/lib/installer/ide.js:176:2)
    at <anonymous>

**Comment by ivankravets** [comment]
Fixed in the latest version 2.2.2. Please update via Atom > Settings > Updates
