### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by mamelmahdy** [platformio/platformio-atom-ide#2056]
# Description of problem
Leave a comment...

BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
- https://github.com/platformio/platformio-atom-ide/issues

# Configuration
Atom: 1.29.0
PIO IDE: v2.1.7
System: Windows_NT, 10.0.17134, x64

# Exception
```
Install Virtualenv globally:   File "C:\Python37-32\lib\site.py", line 177
    file=sys.stderr)
        ^
SyntaxError: invalid syntax

```

**Comment by ivankravets** [comment]
Depends on https://github.com/platformio/platformio-core/issues/895

Please use Python 2
