### ISSUE TITLE
Start PIO Home Server

### ISSUE THREAD

**Issue by larryyyyy** [platformio/platformio-atom-ide#2062]
# Description of problem
Leave a comment...

BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
- https://github.com/platformio/platformio-atom-ide/issues

# Configuration
Atom: 1.29.0
PIO IDE: v2.1.7
System: Darwin, 17.7.0, x64

# Exception
```
Error: spawn platformio ENOENT
```

**Comment by ivankravets** [comment]
Fixed in the latest version 2.2.2. Please update via Atom > Settings > Updates
