### ISSUE TITLE
Project indexer  creates VSCode config directory 

### ISSUE THREAD

**Issue by ashthespy** [platformio/platformio-atom-ide#2064]
The `platformio-node-helpers` [project indexer](https://github.com/platformio/platformio-node-helpers/blob/7fc85bf62044047e3a97813449eb6e5c03c3a9f6/src/project/indexer.js#L39) seems to create a `.vscode` directory for all my projects - even though I use Atom.

```
C:\Program Files\PlatformIO\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\lib\index.js:1

runCommand platformio (8) ["-f", "-c", "atom", "init", "--ide", "vscode", "--project-dir", "E:\Documents\PlatformIO\akdjf"] {}
```

**Comment by ivankravets** [comment]
Fixed in the latest version 2.2.2. Please update via Atom > Settings > Updates
