### ISSUE TITLE
The .gitignore file keeps being updated

### ISSUE THREAD

**Issue by sakishrist** [platformio/platformio-atom-ide#2066]
The issue that I have hit is that on an imported project, while I perform rebases (and all of the time I believe, not just during rebases), this file keeps being updated and interferes with any work being done. This repository that I have is one that has not been created in PlatformIO and, while having a .gitignore file, it does not have those two lines.

I many times have to jump around in branches, pull the latest changes from the remote, rebase and other such normal operations. The result is that even if I add these lines to the repository on my working branch, when I jump around the commits, I often see those lines appearing, and I have to revert the file to it's original state, since git will whine about loosing changes. This is a tracked file in my project (and is tracked in the majority of the projects I've known), that's why it creates these headaches. It is especially _confusing_ when I am in the middle of a rebase, as it confuses git and stops rebasing in the middle of nothing.

I have searched for an option to disable this feature, but have not managed to find one. Is this by design, or is it an issue with my setup?

I would be glad to provide more information or example scenario if needed

Thanks in advance!

**Comment by ivankravets** [comment]
Fixed in https://github.com/platformio/platformio-core/commit/22ceae014919a427b97a6a51d39c71b1f82f3b55

Please open PIO IDE Terminal and type `pio upgrade --dev`
