### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by BlackSMmb** [platformio/platformio-atom-ide#2069]
PIP: Error: spawn /Volumes/Macintosh HD/Users/silviodesiderio/.platformio/penv/bin/pip ENOENT

How can I solve it?

**Comment by ivankravets** [comment]
1. Please remove `/Volumes/Macintosh HD/Users/silviodesiderio/.platformio/penv`. 
2. Could you reproduce this issue with [PlatformIO IDE for VSCode](https://platformio.org/platformio-ide)

**Comment by BlackSMmb** [comment]
I solved the issue reinstalling thanks
