### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by ahatzikonstantinou** [platformio/platformio-atom-ide#2082]
# Description of problem
Leave a comment...

BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
- https://github.com/platformio/platformio-atom-ide/issues

# Configuration
Atom: 1.26.1
PIO IDE: v2.1.7
System: Linux, 4.15.0-34-generic, x64

# Exception
```
Install Virtualenv globally: Error: spawn /home/antonis/.platformio/penv/bin/python2.7 ENOENT
```

**Comment by ivankravets** [comment]
Please switch to PlatformIO IDE for VSCode => https://platformio.org/platformio-ide
