### ISSUE TITLE
Start PIO Home Server

### ISSUE THREAD

**Issue by YASH-GOYALL** [platformio/platformio-atom-ide#2083]
# Description of problem
Leave a comment...

BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
- https://github.com/platformio/platformio-atom-ide/issues

# Configuration
Atom: 1.31.1
PIO IDE: v2.2.2
System: Windows_NT, 10.0.17134, x64

# Exception
```
Could not start PIO Home server: Error: connect EADDRNOTAVAIL 127.0.0.1 - Local (0.0.0.0:52408)
```

**Comment by ivankravets** [comment]
Please switch to PlatformIO IDE for VSCode => https://platformio.org/platformio-ide
