### ISSUE TITLE
pioplus fails to run linux_armv7l

### ISSUE THREAD

**Issue by cdzieciol** [platformio/platformio-atom-ide#2084]
<h2>Installation</h2>

ubuntu@ubuntu:~pip install -U platformio
Collecting platformio
  Using cached https://files.pythonhosted.org/packages/b4/fe/6cf776ae6feb69c6afd3362700174e9e03a020113a3f0b1684deafefec95/platformio-3.6.0-py27-none-any.whl
Collecting colorama (from platformio)
  Using cached https://files.pythonhosted.org/packages/db/c8/7dcf9dbcb22429512708fe3a547f8b6101c0d02137acbd892505aee57adf/colorama-0.3.9-py2.py3-none-any.whl
Collecting bottle<0.13 (from platformio)
Collecting semantic-version<3,>=2.5.0 (from platformio)
Collecting requests<3,>=2.4.0 (from platformio)
  Using cached https://files.pythonhosted.org/packages/65/47/7e02164a2a3db50ed6d8a6ab1d6d60b69c4c3fdf57a284257925dfc12bda/requests-2.19.1-py2.py3-none-any.whl
Collecting pyserial!=3.3,<4,>=3 (from platformio)
  Using cached https://files.pythonhosted.org/packages/0d/e4/2a744dd9e3be04a0c0907414e2a01a7c88bb3915cbe3c8cc06e209f59c30/pyserial-3.4-py2.py3-none-any.whl
Collecting click<6,>=5 (from platformio)
  Using cached https://files.pythonhosted.org/packages/8f/98/14966b6d772fd5fba1eb3bb34a62a7f736d609572493397cdc5715c14514/click-5.1-py2.py3-none-any.whl
Collecting idna<2.8,>=2.5 (from requests<3,>=2.4.0->platformio)
  Using cached https://files.pythonhosted.org/packages/4b/2a/0276479a4b3caeb8a8c1af2f8e4355746a97fab05a372e4a2c6a6b876165/idna-2.7-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests<3,>=2.4.0->platformio)
  Using cached https://files.pythonhosted.org/packages/df/f7/04fee6ac349e915b82171f8e23cee63644d83663b34c539f7a09aed18f9e/certifi-2018.8.24-py2.py3-none-any.whl
Collecting urllib3<1.24,>=1.21.1 (from requests<3,>=2.4.0->platformio)
  Using cached https://files.pythonhosted.org/packages/bd/c9/6fdd990019071a4a32a5e7cb78a1d92c53851ef4f56f62a3486e6a7d8ffb/urllib3-1.23-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests<3,>=2.4.0->platformio)
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Installing collected packages: colorama, bottle, semantic-version, idna, certifi, urllib3, chardet, requests, pyserial, click, platformio
Successfully installed bottle-0.12.13 certifi-2018.8.24 chardet-3.0.4 click-5.1 colorama-0.3.9 idna-2.7 platformio-3.6.0 pyserial-3.4 requests-2.19.1 semantic-version-2.6.0 urllib3-1.23

<h2> Configuration </h2>
ubuntu@ubuntu:~$ uname -a
Linux ubuntu 4.15.0-1024-raspi2 #26-Ubuntu SMP PREEMPT Tue Sep 25 06:39:44 UTC 2018 armv7l armv7l armv7l GNU/Linux

ubuntu@ubuntu:~$ pio update
Updating tool-scons                      @ 2.20501.4      [Up-to-date]
Updating contrib-pysite                  @ 0.3.2          [Up-to-date]
Updating tool-pioplus                    @ 1.4.10         [Up-to-date]

Platform Manager
================
Platform Atmel AVR
--------
Updating atmelavr                        @ 1.10.1         [Up-to-date]
Updating toolchain-atmelavr              @ 1.40902.0      [Up-to-date]
Updating framework-arduinoavr            @ 1.10621.1      [Up-to-date]
Updating tool-avrdude                    @ 1.60300.2      [Up-to-date]

Library Manager
===============
Updating CONTROLLINO                     @ 3.0.2          [Up-to-date]

ubuntu@ubuntu:~$ pio upgrade
You're up-to-date!
PlatformIO 3.6.0 is currently the newest version available.

<h2>Exception</h2>

ubuntu@ubuntu:~$ pio home
Error: Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python2.7/site-packages/platformio/__main__.py", line 120, in main
    cli(None, None, None)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/click/core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/click/core.py", line 680, in main
    rv = self.invoke(ctx)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/click/core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ubuntu/.local/lib/python2.7/site-packages/click/core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/platformio/commands/home.py", line 32, in cli
    pioplus_call(sys.argv[1:])
  File "/home/ubuntu/.local/lib/python2.7/site-packages/platformio/managers/core.py", line 114, in pioplus_call
    code = subprocess.call([pioplus_path] + args, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 172, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

ubuntu@ubuntu:~/.platformio/packages/tool-pioplus$ ./pioplus
-bash: ./pioplus: No such file or directory

**Comment by cdzieciol** [comment]
ubuntu@ubuntu:~$ file ~/.platformio/packages/tool-pioplus/pioplus
/home/ubuntu/.platformio/packages/tool-pioplus/pioplus: ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux.so.3, for GNU/Linux 3.2.0, BuildID[sha1]=966936a0bb7822079126640c59553cb36fc23444, stripped

ubuntu@ubuntu:~$ ldd ~/.platformio/packages/tool-pioplus/pioplus
	not a dynamic executable

**Comment by ivankravets** [comment]
Fixed in the latest release. Please run in terminal `pio upgrade`.
