### ISSUE TITLE
Feature request: Support external terminals

### ISSUE THREAD

**Issue by momostein** [platformio/platformio-atom-ide#2122]
Since platformio-atom-ide-terminal is no longer being developed/maintained, I thought it could be great to support other terminals/external terminals. I think this could be a great feater because a lot of Windows users experience bugs and issues with the platformio-atom-ide-terminal package.

I found some packages that might support this (with a little bit of editing):
Powershell: https://atom.io/packages/atom-terminal-powershell
Other: https://github.com/karan/atom-terminal

As opening the serial monitor etc is as simple as opening the terminal and executing a command, maybe we should be able to implement this?

**Comment by ivankravets** [comment]
We have just released a new version [2.7.0](https://github.com/platformio/platformio-atom-ide/releases/tag/v2.7.0), please upgrade.

**Please note that we HIGHLY recommend moving to [PlatformIO IDE for VSCode](https://platformio.org/platformio-ide) which resolves tons of issues and brings a lot of new features.**
