### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by kikoloko** [platformio/platformio-atom-ide#2128]
# Description of problem
Leave a comment...

BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
- https://github.com/platformio/platformio-atom-ide/issues

# Configuration
Atom: 1.29.0-beta1
PIO IDE: v2.1.7
System: Linux, 4.15.0-39-generic, x64

# Exception
```
Install Virtualenv globally: Error: spawn /home/kiko/.platformio/penv/bin/python2.7 ENOENT
```

**Comment by ivankravets** [comment]
We have just released a new version [2.7.0](https://github.com/platformio/platformio-atom-ide/releases/tag/v2.7.0), please upgrade.

**Please note that we HIGHLY recommend moving to [PlatformIO IDE for VSCode](https://platformio.org/platformio-ide) which resolves tons of issues and brings a lot of new features.**
