### ISSUE TITLE
Start PIO Home Server

### ISSUE THREAD

**Issue by labamnus** [platformio/platformio-atom-ide#2129]
# Description of problem
Leave a comment...

BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
- https://github.com/platformio/platformio-atom-ide/issues

# Configuration
Atom: 1.33.1
PIO IDE: v2.3.1
System: Windows_NT, 6.1.7601, x64

# Exception
```
Error: Could not start PIO Home server: Error: connect ENOTCONN 127.0.0.1:8011
    at l.default.waitUntilUsed.then.e (C:\Users\Adnin\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\dist\index.js:1:15068)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by ivankravets** [comment]
We have just released a new version [2.7.0](https://github.com/platformio/platformio-atom-ide/releases/tag/v2.7.0), please upgrade.

**Please note that we HIGHLY recommend moving to [PlatformIO IDE for VSCode](https://platformio.org/platformio-ide) which resolves tons of issues and brings a lot of new features.**
