### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by Wernermack** [platformio/platformio-atom-ide#2130]
# Description of problem
Leave a comment...

BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
- https://github.com/platformio/platformio-atom-ide/issues

# Configuration
Atom: 1.28.1
PIO IDE: v2.1.7
System: Windows_NT, 6.1.7601, ia32

# Exception
```
Install Virtualenv globally: Das System kann den angegebenen Pfad nicht finden.
Error: spawn C:\Users\Werner Satrapa\.platformio\penv\Scripts\python.exe ENOENT
```

**Comment by ivankravets** [comment]
We have just released a new version [2.7.0](https://github.com/platformio/platformio-atom-ide/releases/tag/v2.7.0), please upgrade.

**Please note that we HIGHLY recommend moving to [PlatformIO IDE for VSCode](https://platformio.org/platformio-ide) which resolves tons of issues and brings a lot of new features.**
