### ISSUE TITLE
AVR Development without arduino

### ISSUE THREAD

**Issue by isarfaktor** [platformio/platformio-atom-ide#2134]
Hi all,
i set up the platformio.ini as follows:

`[env:atmega328pb]
platform = atmelavr
board = atmega328pb
upload_protocol = usbtiny
`
I want to develop on C/C++ level the ATMEGA328p directly via platformio.
I removed the arduino reference in the ini and rebuild the C/C++ project index in platformio, I uninstalled the atemavr driver initially and reinstalled via `pio platforms uninstall atmelavr` but I get the following error when building the empty project:

`Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/atmelavr/atmega328pb.html
PLATFORM: Atmel AVR > Atmel ATmega328PB
HARDWARE: ATMEGA328PB 16MHz 2KB RAM (31.50KB Flash)
Library Dependency Finder -> http://bit.ly/configure-pio-ldf
LDF MODES: FINDER(chain) COMPATIBILITY(soft)
Collected 0 compatible libraries
Scanning dependencies...
No dependencies
Compiling .pioenvs/atmega328pb/src/main.o
src/main.cpp:1:21: fatal error: Arduino.h: No such file or directory`

Can you help me with the problem here?

Thanks

**Comment by ivankravets** [comment]
We have just released a new version [2.7.0](https://github.com/platformio/platformio-atom-ide/releases/tag/v2.7.0), please upgrade.

**Please note that we HIGHLY recommend moving to [PlatformIO IDE for VSCode](https://platformio.org/platformio-ide) which resolves tons of issues and brings a lot of new features.**
