### ISSUE TITLE
Linux do not refresh usb port

### ISSUE THREAD

**Issue by e3bble** [platformio/platformio-atom-ide#2136]
after turning of ant turning on USB to TTL converter on linux mint, platformIO didint see it but in cli it see.
After reloading atom it works and find it.

**Comment by ivankravets** [comment]
We have just released a new version [2.7.0](https://github.com/platformio/platformio-atom-ide/releases/tag/v2.7.0), please upgrade.

**Please note that we HIGHLY recommend moving to [PlatformIO IDE for VSCode](https://platformio.org/platformio-ide) which resolves tons of issues and brings a lot of new features.**
