### ISSUE TITLE
Linter no longer working

### ISSUE THREAD

**Issue by cjastone** [platformio/platformio-atom-ide#2165]
Thanks for your tireless work on this project!

Just one small issue I'd like to report - on a new install of Atom and PlatformIO, linter no longer functional for gcc.

There appears to be potentially more than one issue at play here:

- Support has been dropped for linter v1 as at v2.3.0 (this is worked around by uninstalling linter and running `apm install linter@2.2.0` from the terminal).

- linter-gcc appears to be no longer in active development (though I'm not certain that this supports linter v2 either.)

I'm not sure if any of this is even able to be rectified at your end or if it's all third-party, but I thought I would bring this to your attention regardless as it's a very powerful feature.

**Comment by ivankravets** [comment]
We have just released a new version [2.7.0](https://github.com/platformio/platformio-atom-ide/releases/tag/v2.7.0), please upgrade.

**Please note that we HIGHLY recommend moving to [PlatformIO IDE for VSCode](https://platformio.org/platformio-ide) which resolves tons of issues and brings a lot of new features.**
