### ISSUE TITLE
typo in "PlaftormIO: Unable to get a list of serial ports"

### ISSUE THREAD

**Issue by trogper** [platformio/platformio-atom-ide#2168]
the "Unable to get a list of serial ports" message has a typo in it's tag, it is written as PlaFTormio
I'm not sure where it originates , whether in platformio-atom-ide or platformio-core

**Comment by ivankravets** [comment]
We have just released a new version [2.7.0](https://github.com/platformio/platformio-atom-ide/releases/tag/v2.7.0), please upgrade.

**Please note that we HIGHLY recommend moving to [PlatformIO IDE for VSCode](https://platformio.org/platformio-ide) which resolves tons of issues and brings a lot of new features.**
