### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by MontyFlange** [platformio/platformio-atom-ide#2189]
# Description of problem
Leave a comment...

BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
- https://github.com/platformio/platformio-atom-ide/issues

# Configuration
Atom: 1.36.1
PIO IDE: v2.3.1
System: Windows_NT, 10.0.17763, x64

# Exception
```
Error: Could not create PIO Core Virtual Environment. Please create it manually -> http://bit.ly/pio-core-virtualenv 
 Error: Virtualenv Create: Error: spawn EACCES

    at t.value (C:\Users\Montague\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\dist\index.js:1:25605)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by ivankravets** [comment]
Please switch to PlatformIO IDE for VSCode => https://platformio.org/platformio-ide

Does it work here?
