### ISSUE TITLE
IDE for OSX is damaged

### ISSUE THREAD

**Issue by mdanetzky** [platformio/platformio-atom-ide#220]
IDE downloaded from:
http://platformio.org/get-started/ide?dl=platformio-atom-mac.zip
opens with message:
“Atom.app” is damaged and can’t be opened. You should move it to the Trash.
Application downloaded from atom.io opens without any problems.

**Comment by mdanetzky** [comment]
Temporary solution is to reset the com.apple.quarantine flag.
xattr -d com.apple.quarantine Atom.app

**Comment by ivankravets** [comment]
Temporary solution is to use GitHub's official Atom and manually install `platformio-ide` packages. See
* http://docs.platformio.org/en/latest/ide/atom.html#ide-installation

**Comment by ivankravets** [comment]
We have updated all our pages and stopped publishing own Atom bundle.
We added instruction how to install official atom and our installer.

http://platformio.org/platformio-ide
