### ISSUE TITLE
Start PIO Home Server: get_project_test_dir

### ISSUE THREAD

**Issue by irbigturtle** [platformio/platformio-atom-ide#2201]
# Description of problem
Trying to start the pio home server - fails after a few seconds. 

BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
- https://github.com/platformio/platformio-atom-ide/issues

# Configuration
Atom: 1.37.0
PIO IDE: v2.3.1
System: Windows_NT, 10.0.17763, x64

# Exception
```
Error: Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<string>", line 38, in <module>
  File "<string>", line 39, in <module>
  File "<string>", line 18, in load_module
  File "<string>", line 23, in <module>
ImportError: cannot import name get_project_test_dir

    at C:\Users\Christian\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\dist\index.js:1:14992
    at ChildProcess.h (C:\Users\Christian\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\dist\index.js:1:5916)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at ChildProcess.cp.emit (C:\Users\Christian\.atom\packages\platformio-ide\node_modules\cross-spawn\lib\enoent.js:34:29)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
```

**Comment by LemarinelNet** [comment]
Same for me, old installation, was working a few days ago !

**Comment by drzacek** [comment]
Same

**Comment by ivankravets** [comment]
What is your PlatformIO Core version? 
Please open PIO IDE Terminal and type: 
`pio —version`

**Comment by LemarinelNet** [comment]
PlatformIO, version 4.0.0a14

**Comment by ivankravets** [comment]
Please open PlatformIO IDE Terminal and type
```
pio upgrade --dev
```

Restart Atom.

**Comment by drzacek** [comment]
Would be great if I could open the terminal, but I can't. Seems to not work too. Don't know how to get any verbose output on that though.

**Comment by ivankravets** [comment]
Atom > Menu > PlatformIO > Upgrade PlatformIO Core
![58536635-ffa37480-81a5-11e9-9718-0b6662ff337c](https://user-images.githubusercontent.com/1760209/58545666-652a4c00-820c-11e9-8060-62df217a500d.png)

**Comment by drzacek** [comment]
![image](https://user-images.githubusercontent.com/19291550/58545784-4922ac80-8204-11e9-8d5e-0dbb30f3e82b.png)

Yes, platformio-ide-terminal is installed. Tried installing, deinstalling, restarting. (Edit->Prefferences->Install)

**Comment by LemarinelNet** [comment]
> Please open PlatformIO IDE Terminal and type
> 
> ```
> pio upgrade --dev
> ```
> 
> Restart IDE.

Worked for me. Thanks

**Comment by drzacek** [comment]
Don't ask me what I did, I reinstalled many many times and it kicked in. 
Did pio upgrade --dev though and it seem to work now.
