### ISSUE TITLE
Add Close Button to PopUp

### ISSUE THREAD

**Issue by denzelwamburu** [platformio/platformio-atom-ide#221]
Each time the ide start seems to have a **Keep PlatformIO alive and Independent!**
![screenshot from 2017-02-17 08-29-30](https://cloud.githubusercontent.com/assets/6532631/23053571/910e1960-f4eb-11e6-8f4f-af8b34a3d3a9.png)

Or how do i get rid of it?

**Comment by ivankravets** [comment]
Could you try to switch to Atom Dark theme, then "Menu: PlatformIO > Help > Donate".

**Comment by denzelwamburu** [comment]
I can now be able to see the footer options now.

Seems to be an issue with Atom Material.

**Comment by denzelwamburu** [comment]
:+1:

**Comment by ivankravets** [comment]
Add `overflow-y: auto` for all spaghetti popups (temporary code from PlatformIO IDE 1.0 ):

* Donate Popup
* Serial Monitor Popup (when user clicks on "Advance")
