### ISSUE TITLE
Start PIO Home Server

### ISSUE THREAD

**Issue by petrusmuc** [platformio/platformio-atom-ide#2217]
# Description of problem
Leave a comment...

BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
- https://github.com/platformio/platformio-atom-ide/issues

# Configuration
Atom: 1.38.2
PIO IDE: v2.3.1
System: Windows_NT, 6.1.7601, x64

# Exception
```
Error: Error: You are not connected to the Internet.
If you build a project first time, we need Internet connection to install all dependencies and toolchains.

    at C:\Users\Administrator\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\dist\index.js:1:15270
    at ChildProcess.h (C:\Users\Administrator\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\dist\index.js:1:5904)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at ChildProcess.cp.emit (C:\Users\Administrator\.atom\packages\platformio-ide\node_modules\cross-spawn\lib\enoent.js:34:29)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
```
Whatever I do and wherever I install Atom + platformio (Win 7 x64, Win7 x86, 3 different machines) I get this error message. I'm really out of my wits what I still could do, more so as all my other applications have a nice and undisturbed internet connection.
Searching the net didn't bring any results for me (either too far off the problem or too cryptic) :-)
Any help is very much appreciated !

Thanks and best regards

Peter

**Comment by ivankravets** [comment]
We have just released a new version [2.7.0](https://github.com/platformio/platformio-atom-ide/releases/tag/v2.7.0), please upgrade.

**Please note that we HIGHLY recommend moving to [PlatformIO IDE for VSCode](https://platformio.org/platformio-ide) which resolves tons of issues and brings a lot of new features.**
