### ISSUE TITLE
Error building example  with atom > 1.13.1 on OS X

### ISSUE THREAD

**Issue by rwalli** [platformio/platformio-atom-ide#222]
On Atom version 1.14 and later: load Project Example and hit the "PlatformIO: Build" button:
Error message: "No configuration to build this project exists."

This error occurs on latest stable and alpha version on OS X 10.11 and 10.12.
Linux version works.

**Comment by ivankravets** [comment]
I've just made a PR for "build" packages. Need to wait when it will be merged and released.
See https://github.com/noseglid/atom-build/pull/501
