### ISSUE TITLE
npm ERR! Unexpected end of JSON input while parsing near '...encies":{"form-data":'

### ISSUE THREAD

**Issue by carl1961** [platformio/platformio-atom-ide#2224]
windows 7 64bit
Atom 1.38.2
Installing “platformio-ide@2.3.1” failed.

npm ERR! Unexpected end of JSON input while parsing near '...encies":{"form-data":'

**Comment by ivankravets** [comment]
We have just released a new version [2.7.0](https://github.com/platformio/platformio-atom-ide/releases/tag/v2.7.0), please upgrade.

**Please note that we HIGHLY recommend moving to [PlatformIO IDE for VSCode](https://platformio.org/platformio-ide) which resolves tons of issues and brings a lot of new features.**
