### ISSUE TITLE
Different actions for upload between button and keybinding

### ISSUE THREAD

**Issue by LukasAV** [platformio/platformio-atom-ide#2234]
Issue described already in the [PlatformIO community](https://community.platformio.org/t/different-actions-for-upload-between-button-and-keybinding/8905)

System information:

Linux Mint 18.1 Cinnamon 64-bit
Kernel 4.4.0-157-generic
Atom 1.38.2
PlatformIO 4.0.0

**Comment by ivankravets** [comment]
We have just released a new version [2.7.0](https://github.com/platformio/platformio-atom-ide/releases/tag/v2.7.0), please upgrade.

**Please note that we HIGHLY recommend moving to [PlatformIO IDE for VSCode](https://platformio.org/platformio-ide) which resolves tons of issues and brings a lot of new features.**
