### ISSUE TITLE
InstallationManager - Could not create PIO Core Virtual Environment

### ISSUE THREAD

**Issue by icancwhatusay** [platformio/platformio-atom-ide#2241]
Error: Could not create PIO Core Virtual Environment. Please create it manually -> http://bit.ly/pio-core-virtualenv Error: Virtualenv Create: Traceback (most recent call last): File 

I have no idea how to fix this. I've followed all the instructions on the page and it gave me zero improvements.

**Comment by ivankravets** [comment]
We have just released a new version [2.7.0](https://github.com/platformio/platformio-atom-ide/releases/tag/v2.7.0), please upgrade.

**Please note that we HIGHLY recommend moving to [PlatformIO IDE for VSCode](https://platformio.org/platformio-ide) which resolves tons of issues and brings a lot of new features.**
