### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by LDC12** [platformio/platformio-atom-ide#2246]
Error: Could not create PIO Core Virtual Environment. Please create it manually -> http://bit.ly/pio-core-virtualenv Error: Virtualenv Create: Traceback (most recent call last): File "C:\Users\hands.platformio.cache\tmp-1141264NU3Q9Bx5yI\virtualenv-16.1.0\src\virtualenv.py", line 2462, in main() File "C:\Users\hands.platformio.cache\tmp-1141264NU3Q9Bx5yI\virtualenv-16.1.0\src\virtualenv.py", line 762, in main symlink=options.symlink, File "C:\Users\hands.platformio.cache\tmp-1141264NU3Q9Bx5yI\virtualenv-16.1.0\src\virtualenv.py", line 998, in create_environment install_python(home_dir, lib_dir, inc_dir, bin_dir, site_packages=site_packages, clear=clear, symlink=symlink) File "C:\Users\hands.platformio.cache\tmp-1141264NU3Q9Bx5yI\virtualenv-16.1.0\src\virtualenv.py", line 1317, in install_python shutil.copyfile(executable, py_executable) File "C:\Users\hands.platformio\python27\lib\shutil.py", line 83, in copyfile with open(dst, 'wb') as fdst: IOError: [Errno 13] Permission denied: 'C:\Users\hands\.platformio\penv\Scripts\python.exe'

New python executable in C:\Users\hands.platformio\penv\Scripts\python.exe

at t.value (C:\Users\hands\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\dist\index.js:1:31159)
at <anonymous>
at process._tickCallback (internal/process/next_tick.js:188:7)
Report a problem

**Comment by ivankravets** [comment]
We have just released a new version [2.7.0](https://github.com/platformio/platformio-atom-ide/releases/tag/v2.7.0), please upgrade.

**Please note that we HIGHLY recommend moving to [PlatformIO IDE for VSCode](https://platformio.org/platformio-ide) which resolves tons of issues and brings a lot of new features.**
