### ISSUE TITLE
Can't install packages

### ISSUE THREAD

**Issue by jjabal** [platformio/platformio-atom-ide#2250]
Since atom updated to 1.4 i cant install packages, im super new to programming so maybe im doing something wrong, i used platformio-ide and platformio-ide-terminal and now i cant install either of those.

This is the error that i get

error>

node-pty-prebuilt-multiarch@0.9.0-beta21.legacy install C:\Users\Juan\AppData\Local\Temp\apm-install-dir-119715-7656-1o7qseo.qmxp\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch prebuild-install || node scripts/install.js

C:\Users\Juan\AppData\Local\Temp\apm-install-dir-119715-7656-1o7qseo.qmxp\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch>if not defined npm_config_node_gyp (node "C:\Users\Juan\AppData\Local\atom\app-1.40.0\resources\app\apm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\....\node_modules\node-gyp\bin\node-gyp.js" rebuild ) else (node "C:\Users\Juan\AppData\Local\atom\app-1.40.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )

Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch. MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe". To fix this, 1) install the .NET Framework 2.0 SDK, 2) install Microsoft Visual Studio 2005 or 3) add the location of the component to the system path if it is installed elsewhere. [C:\Users\Juan\AppData\Local\Temp\apm-install-dir-119715-7656-1o7qseo.qmxp\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch\build\binding.sln]

MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe". To fix this, 1) install the .NET Framework 2.0 SDK, 2) install Microsoft Visual Studio 2005 or 3) add the location of the component to the system path if it is installed elsewhere. [C:\Users\Juan\AppData\Local\Temp\apm-install-dir-119715-7656-1o7qseo.qmxp\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch\build\binding.sln]

MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe". To fix this, 1) install the .NET Framework 2.0 SDK, 2) install Microsoft Visual Studio 2005 or 3) add the location of the component to the system path if it is installed elsewhere. [C:\Users\Juan\AppData\Local\Temp\apm-install-dir-119715-7656-1o7qseo.qmxp\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch\build\binding.sln]

MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe". To fix this, 1) install the .NET Framework 2.0 SDK, 2) install Microsoft Visual Studio 2005 or 3) add the location of the component to the system path if it is installed elsewhere. [C:\Users\Juan\AppData\Local\Temp\apm-install-dir-119715-7656-1o7qseo.qmxp\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch\build\binding.sln]

prebuild-install WARN install No prebuilt binaries found (target=3.1.10 runtime=node arch=x64 libc= platform=win32) gyp ERR! build error gyp ERR! stack Error: C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe failed with exit code: 1 gyp ERR! stack at ChildProcess.onExit (C:\Users\Juan\AppData\Local\atom\app-1.40.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23) gyp ERR! stack at ChildProcess.emit (events.js:182:13) gyp ERR! stack at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12) gyp ERR! System Windows_NT 10.0.17134 gyp ERR! command "C:\Users\Juan\AppData\Local\atom\app-1.40.0\resources\app\apm\bin\node.exe" "C:\Users\Juan\AppData\Local\atom\app-1.40.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" "rebuild" gyp ERR! cwd C:\Users\Juan\AppData\Local\Temp\apm-install-dir-119715-7656-1o7qseo.qmxp\node_modules\platformio-ide-terminal\node_modules\node-pty-prebuilt-multiarch gyp ERR! node -v v10.2.1 gyp ERR! node-gyp -v v3.7.0 gyp ERR! not ok npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\Juan\AppData\Local\Temp\apm-install-dir-119715-7656-1o7qseo.qmxp\package.json' npm WARN apm-install-dir-119715-7656-1o7qseo.qmxp No description npm WARN apm-install-dir-119715-7656-1o7qseo.qmxp No repository field. npm WARN apm-install-dir-119715-7656-1o7qseo.qmxp No README data npm WARN apm-install-dir-119715-7656-1o7qseo.qmxp No license field.

npm ERR! code ELIFECYCLE npm ERR! errno 1 npm ERR! node-pty-prebuilt-multiarch@0.9.0-beta21.legacy install: prebuild-install || node scripts/install.js npm ERR! Exit status 1 npm ERR! npm ERR! Failed at the node-pty-prebuilt-multiarch@0.9.0-beta21.legacy install script. npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in: npm ERR! C:\Users\Juan.atom.apm_logs\2019-08-15T13_56_51_302Z-debug.log

**Comment by ivankravets** [comment]
We have just released a new version [2.7.0](https://github.com/platformio/platformio-atom-ide/releases/tag/v2.7.0), please upgrade.

**Please note that we HIGHLY recommend moving to [PlatformIO IDE for VSCode](https://platformio.org/platformio-ide) which resolves tons of issues and brings a lot of new features.**
