### ISSUE TITLE
Mointor does not write anything

### ISSUE THREAD

**Issue by chopin2712** [platformio/platformio-atom-ide#2251]
I opened the Serial Monitor in 9600 bauds.
My Arduino code is the following one:
```
#include <Arduino.h>

void setup() {
  // put your setup code here, to run once:
  pinMode(13, OUTPUT);
  Serial.begin(9600);
}

void loop() {
  // put your main code here, to run repeatedly:
  digitalWrite(13, HIGH);
  Serial.println("Hello World");
  delay(1000);
}
```

But nothing displays into the Platformio's Monitor. 
But when I start the Arduino IDE's Monitor it works and write "Hello World" every seconds.

I already tried to change themes of Atom but it don't works.

**Comment by ivankravets** [comment]
We have just released a new version [2.7.0](https://github.com/platformio/platformio-atom-ide/releases/tag/v2.7.0), please upgrade.

**Please note that we HIGHLY recommend moving to [PlatformIO IDE for VSCode](https://platformio.org/platformio-ide) which resolves tons of issues and brings a lot of new features.**
