### ISSUE TITLE
Lots of functionalities don't works at all on Linux

### ISSUE THREAD

**Issue by chopin2712** [platformio/platformio-atom-ide#2252]
I actually have installed Platformio on Atom and I have big issues the following minute!

First, I was not able to upload to Arduino. I solved this issue after 10 minutes by installing udpn (Don't know) rules.

Second, I cannot access to Liner. When I got an error then save or compile Linter don't detect anything wrong so I needed to analyse the error code to find where I needed to place my ; at the end of the line. It was for this reason that I moved to Platformio.

Third, the serial monitor don't works too! When I relate it to the issue #2251
#2251 

And finally when I startup and create a new project the window is buggy and needs 10 seconds before displaying the project created. The is the least important issue of course...

Thanks in advance

**Comment by ivankravets** [comment]
We have just released a new version [2.7.0](https://github.com/platformio/platformio-atom-ide/releases/tag/v2.7.0), please upgrade.

**Please note that we HIGHLY recommend moving to [PlatformIO IDE for VSCode](https://platformio.org/platformio-ide) which resolves tons of issues and brings a lot of new features.**
