### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by sandeshth** [platformio/platformio-atom-ide#2254]
# Description of problem
Leave a comment...

BEFORE SUBMITTING, PLEASE SEARCH FOR DUPLICATES IN
- https://github.com/platformio/platformio-atom-ide/issues

# Configuration
Atom: 1.40.0
PIO IDE: v2.3.1
System: Linux, 5.2.8-200.fc30.x86_64, x64

# Exception
```
Error: Could not create PIO Core Virtual Environment. Please create it manually -> http://bit.ly/pio-core-virtualenv 
 Error: Virtualenv Create: Traceback (most recent call last):
  File "/home/sthapa/.platformio/.cache/tmp-5608ItKw2suRErO4/virtualenv-16.1.0/src/virtualenv.py", line 33, in <module>
    import zlib
ImportError: No module named zlib


    at t.value (/home/sthapa/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/dist/index.js:1:25605)
```

**Comment by ivankravets** [comment]
We have just released a new version [2.7.0](https://github.com/platformio/platformio-atom-ide/releases/tag/v2.7.0), please upgrade.

**Please note that we HIGHLY recommend moving to [PlatformIO IDE for VSCode](https://platformio.org/platformio-ide) which resolves tons of issues and brings a lot of new features.**
