### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by quarkpower** [platformio/platformio-atom-ide#2255]
After installing platformio I do allways get this error:

Error: Could not create PIO Core Virtual Environment. Please create it manually -> http://bit.ly/pio-core-virtualenv Error: Virtualenv Create: Traceback (most recent call last): File "C:\Users\kike.platformio.cache\tmp-11644V9baqUC3JQEk\virtualenv-16.1.0\src\virtualenv.py", line 2462, in main() File "C:\Users\kike.platformio.cache\tmp-11644V9baqUC3JQEk\virtualenv-16.1.0\src\virtualenv.py", line 762, in main symlink=options.symlink, File "C:\Users\kike.platformio.cache\tmp-11644V9baqUC3JQEk\virtualenv-16.1.0\src\virtualenv.py", line 1015, in create_environment install_wheel(to_install, py_executable, search_dirs, download=download) File "C:\Users\kike.platformio.cache\tmp-11644V9baqUC3JQEk\virtualenv-16.1.0\src\virtualenv.py", line 905, in install_wheel from urllib.parse import urljoin File "C:\Users\kike.platformio\python27\lib\urllib.py", line 26, in import socket File "C:\Users\kike.platformio\python27\lib\socket.py", line 47, in import _socket ImportError: No module named _socket

New python executable in C:\Users\kike.platformio\penv\Scripts\python.exe

at t.value (C:\Users\kike\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\dist\index.js:1:31185)
at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by ivankravets** [comment]
We have just released a new version [2.7.0](https://github.com/platformio/platformio-atom-ide/releases/tag/v2.7.0), please upgrade.

**Please note that we HIGHLY recommend moving to [PlatformIO IDE for VSCode](https://platformio.org/platformio-ide) which resolves tons of issues and brings a lot of new features.**
