### ISSUE TITLE
Start PIO Home Server

### ISSUE THREAD

**Issue by DAMOCLESXXI** [platformio/platformio-atom-ide#2260]
Error: Error: Could not find a version that satisfies the requirement '~2.38.190418' for your system 'windows_amd64'

at C:\Users\Usuario\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\dist\index.js:1:17225
at ChildProcess.h (C:\Users\Usuario\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\dist\index.js:1:6033)
at ChildProcess.emit (events.js:182:13)
at ChildProcess.cp.emit (C:\Users\Usuario\.atom\packages\platformio-ide\node_modules\cross-spawn\lib\enoent.js:34:29)
at maybeClose (internal/child_process.js:961:16)
at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)

**Comment by sphereinabox** [comment]
I hit the same issue with 64-bit vscode. Switching to 32-bit vscode fixed it for me.

**Comment by luc-debug** [comment]
I have the same problem.
Unfortunately your suggestion does not solve it for me.
Do you have any other suggestions?

**Comment by Cheeseborgers** [comment]
Same Issue here. was working fine yesterday.
Tried Python 3.6-3.8, both x86 and amd64 versions.

`CorePackageManager: Installing contrib-pysite @ ~2.38.190418
Error: Could not find a version that satisfies the requirement '~2.38.190418' for your system 'windows_amd64'`

And just "Loading..." with VS code.

**Comment by Cheeseborgers** [comment]
Switching to X86 VS code did not work for me though.

**Comment by swd120** [comment]
I'm also getting this error - both VS Code and Atom

**Comment by michelcve** [comment]
Same here

**Comment by pushkin42** [comment]
+1

**Comment by JasonFevang** [comment]
same

**Comment by yulong88888** [comment]
Guys, have your problems solved? I also encountered this problem. I have never encountered it before using PIO. Due to the reinstallation of the Windows system, I have problems. I think the reason is that contrib-pysite-windows_amd64-2.38.191019.tar cannot be downloaded.

**Comment by ivankravets** [comment]
We have just released a new version [2.7.0](https://github.com/platformio/platformio-atom-ide/releases/tag/v2.7.0), please upgrade.

**Please note that we HIGHLY recommend moving to [PlatformIO IDE for VSCode](https://platformio.org/platformio-ide) which resolves tons of issues and brings a lot of new features.**
