### ISSUE TITLE
Feature request "upload and monitor" command

### ISSUE THREAD

**Issue by SRGDamia1** [platformio/platformio-atom-ide#2266]
The serial monitor can be set to automatically close and re-open if it was open in advance of an upload, but it would be very nice to have the explicit "upload and monitor" command like the one in VSCode.

**Comment by ivankravets** [comment]
We have just released a new version [2.7.0](https://github.com/platformio/platformio-atom-ide/releases/tag/v2.7.0), please upgrade.

**Please note that we HIGHLY recommend moving to [PlatformIO IDE for VSCode](https://platformio.org/platformio-ide) which resolves tons of issues and brings a lot of new features.**
