### ISSUE TITLE
InstallationManager crashed in windows 10

### ISSUE THREAD

**Issue by tvixen** [platformio/platformio-atom-ide#2267]
Suddently Crash in windows 10 after using 100% cpu and starting 2118 threads up (see attached)
![image](https://user-images.githubusercontent.com/4704279/64730225-1b295580-d4df-11e9-9386-83c4a1f06cde.png)

InstallationManager

Error: Could not create PIO Core Virtual Environment. Please create it manually -> http://bit.ly/pio-core-virtualenv Error: Virtualenv Create: Traceback (most recent call last): File "C:\Users\Cool.platformio.cache\tmp-121404oqjSPlmKCLK\virtualenv-16.1.0\src\virtualenv.py", line 2462, in main() File "C:\Users\Cool.platformio.cache\tmp-121404oqjSPlmKCLK\virtualenv-16.1.0\src\virtualenv.py", line 762, in main symlink=options.symlink, File "C:\Users\Cool.platformio.cache\tmp-121404oqjSPlmKCLK\virtualenv-16.1.0\src\virtualenv.py", line 1015, in create_environment install_wheel(to_install, py_executable, search_dirs, download=download) File "C:\Users\Cool.platformio.cache\tmp-121404oqjSPlmKCLK\virtualenv-16.1.0\src\virtualenv.py", line 968, in install_wheel call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=SCRIPT) File "C:\Users\Cool.platformio.cache\tmp-121404oqjSPlmKCLK\virtualenv-16.1.0\src\virtualenv.py", line 854, in call_subprocess raise OSError("Command {} failed with error code {}".format(cmd_desc, proc.returncode)) OSError: Command C:\Users\Cool.platf...v\Scripts\python.exe - setuptools pip wheel failed with error code 1

New python executable in C:\Users\Cool.platformio\penv\Scripts\python.exe Installing setuptools, pip, wheel...

Complete output from command C:\Users\Cool.platf...v\Scripts\python.exe - setuptools pip wheel: Traceback (most recent call last): File "", line 11, in

ImportError: cannot import name main
...Installing setuptools, pip, wheel...done.

at t.value (C:\Users\Cool\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\dist\index.js:1:31159)
at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by ivankravets** [comment]
We have just released a new version [2.7.0](https://github.com/platformio/platformio-atom-ide/releases/tag/v2.7.0), please upgrade.

**Please note that we HIGHLY recommend moving to [PlatformIO IDE for VSCode](https://platformio.org/platformio-ide) which resolves tons of issues and brings a lot of new features.**
