### ISSUE TITLE
Help Me! Start PIO Home Server

### ISSUE THREAD

**Issue by FlavioTrelles** [platformio/platformio-atom-ide#2268]
Error: Error: Traceback (most recent call last): File "c:\users\flaviodaniel.platformio\penv\lib\site-packages\platformio__main__.py", line 90, in main cli(None, None, None) File "c:\users\flaviodaniel.platformio\penv\lib\site-packages\click\core.py", line 700, in call return self.main(args, kwargs) File "c:\users\flaviodaniel.platformio\penv\lib\site-packages\click\core.py", line 680, in main rv = self.invoke(ctx) File "c:\users\flaviodaniel.platformio\penv\lib\site-packages\platformio\commands__init__.py", line 37, in invoke return super(PlatformioCLI, self).invoke(ctx) File "c:\users\flaviodaniel.platformio\penv\lib\site-packages\click\core.py", line 1027, in invoke return _process_result(sub_ctx.command.invoke(sub_ctx)) File "c:\users\flaviodaniel.platformio\penv\lib\site-packages\click\core.py", line 873, in invoke return ctx.invoke(self.callback, ctx.params) File "c:\users\flaviodaniel.platformio\penv\lib\site-packages\click\core.py", line 508, in invoke return callback(args, **kwargs) File "c:\users\flaviodaniel.platformio\penv\lib\site-packages\platformio\commands\home\command.py", line 38, in cli from autobahn.twisted.resource import WebSocketResource File "C:\Users\FlavioDaniel.platformio\packages\contrib-pysite\autobahn\twisted__init__.py", line 44, in from autobahn.twisted.websocket import \ File "C:\Users\FlavioDaniel.platformio\packages\contrib-pysite\autobahn\twisted\websocket.py", line 41, in from autobahn.util import public File "C:\Users\FlavioDaniel.platformio\packages\contrib-pysite\autobahn\util.py", line 48, in from OpenSSL import SSL File "C:\Users\FlavioDaniel.platformio\packages\contrib-pysite\OpenSSL__init__.py", line 8, in from OpenSSL import crypto, SSL File "C:\Users\FlavioDaniel.platformio\packages\contrib-pysite\OpenSSL\crypto.py", line 12, in from cryptography import x509 File "C:\Users\FlavioDaniel.platformio\packages\contrib-pysite\cryptography\x509__init__.py", line 8, in from cryptography.x509.base import ( File "C:\Users\FlavioDaniel.platformio\packages\contrib-pysite\cryptography\x509\base.py", line 16, in from cryptography.x509.extensions import Extension, ExtensionType File "C:\Users\FlavioDaniel.platformio\packages\contrib-pysite\cryptography\x509\extensions.py", line 24, in from cryptography.x509.general_name import GeneralName, IPAddress, OtherName File "C:\Users\FlavioDaniel.platformio\packages\contrib-pysite\cryptography\x509\general_name.py", line 16, in from cryptography.x509.name import Name File "C:\Users\FlavioDaniel.platformio\packages\contrib-pysite\cryptography\x509\name.py", line 12, in from cryptography.x509.oid import NameOID, ObjectIdentifier File "C:\Users\FlavioDaniel.platformio\packages\contrib-pysite\cryptography\x509\oid.py", line 102, in SignatureAlgorithmOID.RSA_WITH_MD5: hashes.MD5(), AttributeError: 'module' object has no attribute 'MD5'

**Comment by ivankravets** [comment]
We have just released a new version [2.7.0](https://github.com/platformio/platformio-atom-ide/releases/tag/v2.7.0), please upgrade.

**Please note that we HIGHLY recommend moving to [PlatformIO IDE for VSCode](https://platformio.org/platformio-ide) which resolves tons of issues and brings a lot of new features.**
