### ISSUE TITLE
Start PIO Home Server

### ISSUE THREAD

**Issue by karim1221** [platformio/platformio-atom-ide#2269]
rror at /Users/karimherrera/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/dist/index.js:1:17372 at ChildProcess.h (/Users/karimherrera/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/dist/index.js:1:6150) at ChildProcess.emit (events.js:182:13) at maybeClose (internal/child_process.js:961:16) at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)

**Comment by ivankravets** [comment]
We have just released a new version [2.7.0](https://github.com/platformio/platformio-atom-ide/releases/tag/v2.7.0), please upgrade.

**Please note that we HIGHLY recommend moving to [PlatformIO IDE for VSCode](https://platformio.org/platformio-ide) which resolves tons of issues and brings a lot of new features.**
