### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by zfzhang123** [platformio/platformio-atom-ide#2271]
rror: Could not create PIO Core Virtual Environment. Please create it manually -> http://bit.ly/pio-core-virtualenv Error: Virtualenv Create: Traceback (most recent call last): File "C:\Users\Administrator.platformio.cache\tmp-13640hElpqnkIXAzs\virtualenv-16.1.0\src\virtualenv.py", line 2462, in main() File "C:\Users\Administrator.platformio.cache\tmp-13640hElpqnkIXAzs\virtualenv-16.1.0\src\virtualenv.py", line 762, in main symlink=options.symlink, File "C:\Users\Administrator.platformio.cache\tmp-13640hElpqnkIXAzs\virtualenv-16.1.0\src\virtualenv.py", line 1015, in create_environment install_wheel(to_install, py_executable, search_dirs, download=download) File "C:\Users\Administrator.platformio.cache\tmp-13640hElpqnkIXAzs\virtualenv-16.1.0\src\virtualenv.py", line 968, in install_wheel call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=SCRIPT) File "C:\Users\Administrator.platformio.cache\tmp-13640hElpqnkIXAzs\virtualenv-16.1.0\src\virtualenv.py", line 812, in call_subprocess env=env, File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\Lib\subprocess.py", line 756, in init restore_signals, start_new_session) File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\Lib\subprocess.py", line 1155, in _execute_child startupinfo) PermissionError: [WinError 5] �ܾ����ʡ�

Please use the system python to run this script Installing setuptools, pip, wheel...

Error [WinError 5] �ܾ����ʡ� while executing command C:\Users\Administrat...tformio\penv\Scripts - setuptools pip wheel ...Installing setuptools, pip, wheel...done.

at t.value (C:\Users\Administrator\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\dist\index.js:1:31332)
at <anonymous>
at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by ivankravets** [comment]
We have just released a new version [2.7.0](https://github.com/platformio/platformio-atom-ide/releases/tag/v2.7.0), please upgrade.

**Please note that we HIGHLY recommend moving to [PlatformIO IDE for VSCode](https://platformio.org/platformio-ide) which resolves tons of issues and brings a lot of new features.**
