### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by JayTee2312** [platformio/platformio-atom-ide#2273]
Error: PIP Core: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x106f840d0>: Failed to establish a new connection: [Errno 64] Host is down',)': /simple/platformio/ Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x106f84210>: Failed to establish a new connection: [Errno 64] Host is down',)': /simple/platformio/ Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x106f84350>: Failed to establish a new connection: [Errno 64] Host is down',)': /simple/platformio/ Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x106f84490>: Failed to establish a new connection: [Errno 64] Host is down',)': /simple/platformio/ Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x106f845d0>: Failed to establish a new connection: [Errno 64] Host is down',)': /simple/platformio/ Could not find a version that satisfies the requirement platformio (from versions: ) No matching distribution found for platformio

**Comment by ivankravets** [comment]
We have just released a new version [2.7.0](https://github.com/platformio/platformio-atom-ide/releases/tag/v2.7.0), please upgrade.

**Please note that we HIGHLY recommend moving to [PlatformIO IDE for VSCode](https://platformio.org/platformio-ide) which resolves tons of issues and brings a lot of new features.**
