### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by ilangol** [platformio/platformio-atom-ide#2281]
endless loop encounter while installing atom and platform ide

**Comment by leseaw** [comment]
same here :(

**Comment by Xsev1** [comment]
same here, i have phyton 2.7 installed but he dont accept it...
The help opens 3.7 but installer says 3.x is not supported... very funny...

**Comment by ivankravets** [comment]
We have just released a new version [2.7.0](https://github.com/platformio/platformio-atom-ide/releases/tag/v2.7.0), please upgrade.

**Please note that we HIGHLY recommend moving to [PlatformIO IDE for VSCode](https://platformio.org/platformio-ide) which resolves tons of issues and brings a lot of new features.**
