### ISSUE TITLE
Start PIO Home Server

### ISSUE THREAD

**Issue by catmaster444** [platformio/platformio-atom-ide#2282]
hi Guys
I am completely new to this staff
I have ATOM on macOS Catalina

My problem is that I can not open platformIO home
<img width="468" alt="Bildschirmfoto 2019-10-10 um 13 31 48" src="https://user-images.githubusercontent.com/43067088/66565445-cb33c200-eb62-11e9-9277-9248b98e7ece.png">

and two errors are displayed

thanks in advance for help

**Comment by ivankravets** [comment]
We have just released a new version [2.7.0](https://github.com/platformio/platformio-atom-ide/releases/tag/v2.7.0), please upgrade.

**Please note that we HIGHLY recommend moving to [PlatformIO IDE for VSCode](https://platformio.org/platformio-ide) which resolves tons of issues and brings a lot of new features.**
