### ISSUE TITLE
Start PIO Home Server

### ISSUE THREAD

**Issue by Mythkd** [platformio/platformio-atom-ide#2283]
Error at /Users/yuriyvoloshin/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/dist/index.js:1:17383 at ChildProcess.h (/Users/yuriyvoloshin/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/dist/index.js:1:6150) at ChildProcess.emit (events.js:182:13) at maybeClose (internal/child_process.js:961:16) at Socket.stream.socket.on (internal/child_process.js:380:11) at Socket.emit (events.js:182:13) at Pipe._handle.close [as _onclose] (net.js:596:12)

**Comment by ivankravets** [comment]
We have just released a new version [2.7.0](https://github.com/platformio/platformio-atom-ide/releases/tag/v2.7.0), please upgrade.

**Please note that we HIGHLY recommend moving to [PlatformIO IDE for VSCode](https://platformio.org/platformio-ide) which resolves tons of issues and brings a lot of new features.**
