### ISSUE TITLE
Start PIO Home Server

### ISSUE THREAD

**Issue by Pepyno001** [platformio/platformio-atom-ide#2284]
Please help. :(
![Screen Shot 2019-10-13 at 05 20 39](https://user-images.githubusercontent.com/54188759/66727611-45e92f80-ee38-11e9-93ad-49c8640ded00.png)

**Comment by ivankravets** [comment]
We have just released a new version [2.7.0](https://github.com/platformio/platformio-atom-ide/releases/tag/v2.7.0), please upgrade.

**Please note that we HIGHLY recommend moving to [PlatformIO IDE for VSCode](https://platformio.org/platformio-ide) which resolves tons of issues and brings a lot of new features.**
