### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by cbodington** [platformio/platformio-atom-ide#2289]
Uncaught TypeError: i.default.isFileSync is not a function

C:\Users\bodingcx.US\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\dist\index.js:1
Show Stack Trace
The error was thrown from the platformio-ide package. You can help by creating an issue. Please explain what actions triggered this error.

**Comment by ivankravets** [comment]
We have just released a new version [2.7.0](https://github.com/platformio/platformio-atom-ide/releases/tag/v2.7.0), please upgrade.

**Please note that we HIGHLY recommend moving to [PlatformIO IDE for VSCode](https://platformio.org/platformio-ide) which resolves tons of issues and brings a lot of new features.**
