### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by mdanetzky** [platformio/platformio-atom-ide#229]
Error: Error: ENOTEMPTY: directory not empty, rmdir '/Users/matthias/.atom/packages/platformio-ide/project-examples'

Error was thrown during update from IDE 2.0.0-alpha.5 to IDE 2.0.0-alpha.6

System is OSX Sierra

ls -1 /Users/matthias/.atom/packages/platformio-ide/project-examples
LICENSE
atmelavr-and-arduino
atmelsam-and-arduino
desktop
espressif
ide
intel_arc32
lattice_ice40
library-manager
mbed
microchippic32
nordicnrf51
platformio-examples.png
pumbaa
raspberrypi
simba
stm32
teensy
timsp430
titiva
unit-testing
wiring-blink

**Comment by ivankravets** [comment]
Thanks! Try 
```
rm -rf /Users/matthias/.atom/packages/platformio-ide/project-examples
```
and restart Atom.

**Comment by mdanetzky** [comment]
Works
