### ISSUE TITLE
Can't Start PIO Home on macOS Catalina

### ISSUE THREAD

**Issue by miljume** [platformio/platformio-atom-ide#2296]
When installing Platformio IDE from VSCode I receive the following error
`Error: Could not install 'contrib-piohome' with version requirements '^2.3.2' for your system 'darwin_x86_64'.`

I have both python2.7 and python3.7 installed

**Comment by uvwxy** [comment]
I have the same problem.

Above the message it says:

```
Warning! Package Mirror: The 'sha1' sum '17c2a8e8c9c426660f85d5132ac31da752518f49' of downloaded file 'contrib-piohome-2.3.3.tar.gz' is not equal to remote '3cc39a68453fdb6420e1c07766250c8a0d92b3f6'
Looking for another mirror...
```

**Comment by miljume** [comment]
Suddenly my Platform started working, no clue why but now I don't get the error ...

**Comment by ivankravets** [comment]
Fixed. Please upgrade to 2.5.0
