### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by Kshitij993** [platformio/platformio-atom-ide#2297]
![Screenshot (4)](https://user-images.githubusercontent.com/31708480/67330927-b845c800-f53a-11e9-956e-ee36dd16cdac.png)

Having trouble installing Platformio 
tried to create the virtual environment manually but nothing happened
any help please.

**Comment by ivankravets** [comment]
We have just released a new version [2.7.0](https://github.com/platformio/platformio-atom-ide/releases/tag/v2.7.0), please upgrade.

**Please note that we HIGHLY recommend moving to [PlatformIO IDE for VSCode](https://platformio.org/platformio-ide) which resolves tons of issues and brings a lot of new features.**
