### ISSUE TITLE
build window autoclose, advice error

### ISSUE THREAD

**Issue by sstaub** [platformio/platformio-atom-ide#23]
When a build or upload is finished with **no** errors, the window is closing itself automatic.
It will be usefull to let the window stay open to see the build summaries, like memory consumption
of the board etc. I think we can close the window manual
Same problem when have errors on initialize or updating a project, when errors the red advice window closes automatic after a while, it is to fast to analyze the errors.

**Comment by ivankravets** [comment]
@noseglid does Atom Build has this functionality?

**Comment by sstaub** [comment]
The build window stays open when there are errors:
![update_error](https://cloud.githubusercontent.com/assets/6450325/12654651/527961c6-c5f5-11e5-96a3-a9151c3f4ba3.png)

There is also render issue when I fold up and down the window.

**Comment by ivankravets** [comment]
@sstaub thanks! Fixed in https://github.com/platformio/platformio/commit/3bc5cb0d273194cba091aa651fd9fc218ea7e4b3. Please again `Menu: PlatformIO > Upgrade PlatformIO`.

**Comment by sstaub** [comment]
The info for upgrading stay no open, great work. When you can do it also for the build window...

**Comment by ivankravets** [comment]
You can `Menu: PlatformIO > Toggle the build panel` and press `RUN/FIRE` button on the panel. In this case panel will not be close.

**Comment by noseglid** [comment]
There is a setting in the build package where visibility can be set to `Keep visible`.

`cmd-alt-v` will also toggle the window, regardless of visibility

**Comment by ivankravets** [comment]
@noseglid Thanks!!! Sorry, I missed it :(

P.S: Do you have any ideas as for https://github.com/noseglid/atom-build/issues/304#issuecomment-176294269 ?

**Comment by ivankravets** [comment]
@sstaub Please go to `Atom > Preferences > Packages > Build > Settings > Panel Visibility

![screen shot 2016-01-28 at 21 57 09](https://cloud.githubusercontent.com/assets/1760209/12657050/1a29ad3e-c60a-11e5-8efc-e4a16d6f3f63.png)
