### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by amihaita** [platformio/platformio-atom-ide#2305]
rror: Could not create PIO Core Virtual Environment. Please create it manually -> http://bit.ly/pio-core-virtualenv Error: Virtualenv Create: Traceback (most recent call last): File "C:\Users\user.platformio.cache\tmp-10196VyFGDPhDUKW2\virtualenv-16.7.5\virtualenv.py", line 2632, in main() File "C:\Users\user.platformio.cache\tmp-10196VyFGDPhDUKW2\virtualenv-16.7.5\virtualenv.py", line 860, in main create_environment( File "C:\Users\user.platformio.cache\tmp-10196VyFGDPhDUKW2\virtualenv-16.7.5\virtualenv.py", line 1156, in create_environment install_python(home_dir, lib_dir, inc_dir, bin_dir, site_packages=site_packages, clear=clear, symlink=symlink) File "C:\Users\user.platformio.cache\tmp-10196VyFGDPhDUKW2\virtualenv-16.7.5\virtualenv.py", line 1526, in install_python shutil.copyfile(executable, py_executable) File "C:\Program Files\Python38\lib\shutil.py", line 259, in copyfile with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst: PermissionError: [Errno 13] Permission denied: 'C:\Users\user\.platformio\penv\Scripts\python.exe'

Using base prefix 'C:\Program Files\Python38' New python executable in C:\Users\user.platformio\penv\Scripts\python.exe

at t.value (C:\Users\user\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\dist\index.js:1:31671)
at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by ivankravets** [comment]
We have just released a new version [2.7.0](https://github.com/platformio/platformio-atom-ide/releases/tag/v2.7.0), please upgrade.

**Please note that we HIGHLY recommend moving to [PlatformIO IDE for VSCode](https://platformio.org/platformio-ide) which resolves tons of issues and brings a lot of new features.**
