### ISSUE TITLE
Start PIO Home Server

### ISSUE THREAD

**Issue by aswitcom** [platformio/platformio-atom-ide#2315]
Error: Error: Traceback (most recent call last): File "c:\users\karl-heinz.platformio\penv\lib\site-packages\platformio__main__.py", line 90, in main cli(None, None, None) File "c:\users\karl-heinz.platformio\penv\lib\site-packages\click\core.py", line 700, in call return self.main(args, kwargs) File "c:\users\karl-heinz.platformio\penv\lib\site-packages\click\core.py", line 680, in main rv = self.invoke(ctx) File "c:\users\karl-heinz.platformio\penv\lib\site-packages\platformio\commands__init__.py", line 37, in invoke return super(PlatformioCLI, self).invoke(ctx) File "c:\users\karl-heinz.platformio\penv\lib\site-packages\click\core.py", line 1027, in invoke return _process_result(sub_ctx.command.invoke(sub_ctx)) File "c:\users\karl-heinz.platformio\penv\lib\site-packages\click\core.py", line 873, in invoke return ctx.invoke(self.callback, ctx.params) File "c:\users\karl-heinz.platformio\penv\lib\site-packages\click\core.py", line 508, in invoke return callback(args, **kwargs) File "c:\users\karl-heinz.platformio\penv\lib\site-packages\platformio\commands\home\command.py", line 108, in cli reactor.listenTCP(port, site, interface=host) File "C:\Users\Karl-Heinz.platformio\packages\contrib-pysite\twisted\internet\posixbase.py", line 495, in listenTCP p.startListening() File "C:\Users\Karl-Heinz.platformio\packages\contrib-pysite\twisted\internet\tcp.py", line 1363, in startListening raise CannotListenError(self.interface, self.port, le) CannotListenError: Couldn't listen on 127.0.0.1:8010: [Errno 10048] Normalerweise darf jede Socketadresse (Protokoll, Netzwerkadresse oder Anschluss) nur jeweils einmal verwendet werden.

============================================================

An unexpected error occurred. Further steps:

Verify that you have the latest version of PlatformIO using pip install -U platformio command

Try to find answer in FAQ Troubleshooting section https://docs.platformio.org/page/faq.html

Report this problem to the developers https://github.com/platformio/platformio-core/issues

============================================================

**Comment by ivankravets** [comment]
We have just released a new version [2.7.0](https://github.com/platformio/platformio-atom-ide/releases/tag/v2.7.0), please upgrade.

**Please note that we HIGHLY recommend moving to [PlatformIO IDE for VSCode](https://platformio.org/platformio-ide) which resolves tons of issues and brings a lot of new features.**
