### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by ghclifton** [platformio/platformio-atom-ide#2325]
installed Atom for use in installing firmware but received following error when installing platformio-ide..
![platfornio](https://user-images.githubusercontent.com/57623662/68584691-2512fa80-0435-11ea-8a95-87611ba69223.JPG)

any help appreciated.

thanks
Gary

**Comment by dant220** [comment]
Me too!

**Comment by dant220** [comment]
Try this:
sudo apt-get install python3-distutils
sudo apt-get install python3-venv

But I see you are using windows. In any case you need to install distutils and venv. For your version of python.

**Comment by ivankravets** [comment]
We have just released a new version [2.7.0](https://github.com/platformio/platformio-atom-ide/releases/tag/v2.7.0), please upgrade.

**Please note that we HIGHLY recommend moving to [PlatformIO IDE for VSCode](https://platformio.org/platformio-ide) which resolves tons of issues and brings a lot of new features.**
