### ISSUE TITLE
marlin 2.0 build error "can not remove....pioenvs"

### ISSUE THREAD

**Issue by JohannesF93** [platformio/platformio-atom-ide#2327]
Hello,
I still have the problem from one day to another, that I can not build anymore with sucess.
there is always this error:
Can not remove temporary directory  `c:\Users\sepp\Desktop\Marlin-bugfix-2.0.x\.pioenvs`. Please remove it manually to avoid build issues

I have done this serveral times but no change.... 
What can be the issue? could someone help me please?

Thank you guys!

Can not remove temporary directory `c:\Users\sepp\Desktop\Marlin-bugfix-2.0.x\.pioenvs`. Please remove it manually to avoid build issues
Processing LPC1768 (platform: https://github.com/p3p/pio-nxplpc-arduino-lpc176x/archive/master.zip; framework: arduino; board: nxp_lpc1768)
-------------------------------------------------------------------------------------------------------------------------------------------------------

Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/nxplpc-arduino-lpc176x/nxp_lpc1768.html
PLATFORM: NXP Arduino LPC176x 0.0.2 > NXP LPC1768
HARDWARE: LPC1768 100MHz, 31.80KB RAM, 464KB Flash
DEBUG: Current (cmsis-dap) On-board (cmsis-dap) External (blackmagic, jlink)
PACKAGES: toolchain-gccarmnoneeabi 1.80201.190214 (8.2.1), framework-arduino-lpc176x 0.1.3
Converting Marlin.ino
LDF: Library Dependency Finder -> http://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ off, Compatibility ~ strict
Found 4 compatible libraries
Scanning dependencies...
Dependency Graph
|-- <Servo> 1.0.0        
|-- <LiquidCrystal> 1.0.0
|-- <U8glib-HAL> 0.4     
|-- <TMCStepper> 0.5.2   
Building in release mode
  File "C:\Users\sepp\Desktop\Marlin-bugfix-2.0.x\Marlin\src\HAL\HAL_LPC1768\upload_extra_script.py", line 16

    print '\nUnable to find destination disk (' + e + ')\n' \

                                              ^

SyntaxError: invalid syntax

============================================================= [FAILED] Took 2.55 seconds =============================================================

Environment           Status    Duration
--------------------  --------  ------------
megaatmega2560        IGNORED
megaatmega1280        IGNORED
at90usb1286_cdc       IGNORED
at90usb1286_dfu       IGNORED
DUE                   IGNORED
DUE_USB               IGNORED
DUE_debug             IGNORED
LPC1768               FAILED    00:00:02.546
LPC1769               IGNORED
melzi                 IGNORED
melzi_optiboot        IGNORED
rambo                 IGNORED
sanguino_atmega644p   IGNORED
sanguino_atmega1284p  IGNORED
STM32F1               IGNORED
STM32F4               IGNORED
ARMED                 IGNORED
mks_robin             IGNORED
teensy35              IGNORED
malyanm200            IGNORED
esp32                 IGNORED
fysetc_f6_13          IGNORED
linux_native          IGNORED
======================================================== 1 failed, 0 succeeded in 00:00:02.546 ========================================================

**Comment by ivankravets** [comment]
We have just released a new version [2.7.0](https://github.com/platformio/platformio-atom-ide/releases/tag/v2.7.0), please upgrade.

**Please note that we HIGHLY recommend moving to [PlatformIO IDE for VSCode](https://platformio.org/platformio-ide) which resolves tons of issues and brings a lot of new features.**
