### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by Manliusque** [platformio/platformio-atom-ide#2332]
Error: Could not create PIO Core Virtual Environment. Please create it manually -> http://bit.ly/pio-core-virtualenv Error: Virtualenv Create: Traceback (most recent call last): File 

trying installing platformIO Core Package on Atom.

This appens after [#322](https://github.com/atom/apm/issues/322) Issue still not solved.

can anyone help me?

**Comment by ivankravets** [comment]
We have just released a new version [2.7.0](https://github.com/platformio/platformio-atom-ide/releases/tag/v2.7.0), please upgrade.

**Please note that we HIGHLY recommend moving to [PlatformIO IDE for VSCode](https://platformio.org/platformio-ide) which resolves tons of issues and brings a lot of new features.**
