### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by Jeronimo016** [platformio/platformio-atom-ide#2351]
**The error:**
Error: Could not create PIO Core Virtual Environment. Please create it manually -> http://bit.ly/pio-core-virtualenv Error: Virtualenv Create: Traceback (most recent call last): File "C:.platformio.cache\tmp-2684K1wXBrj55zSG\virtualenv-16.7.7\virtualenv.py", line 2628, in main() File "C:.platformio.cache\tmp-2684K1wXBrj55zSG\virtualenv-16.7.7\virtualenv.py", line 870, in main symlink=options.symlink, File "C:.platformio.cache\tmp-2684K1wXBrj55zSG\virtualenv-16.7.7\virtualenv.py", line 1173, in create_environment install_wheel(to_install, py_executable, search_dirs, download=download) File "C:.platformio.cache\tmp-2684K1wXBrj55zSG\virtualenv-16.7.7\virtualenv.py", line 1019, in install_wheel _install_wheel_with_search_dir(download, project_names, py_executable, search_dirs) File "C:.platformio.cache\tmp-2684K1wXBrj55zSG\virtualenv-16.7.7\virtualenv.py", line 1110, in _install_wheel_with_search_dir call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=script) File "C:.platformio.cache\tmp-2684K1wXBrj55zSG\virtualenv-16.7.7\virtualenv.py", line 963, in call_subprocess raise OSError("Command {} failed with error code {}".format(cmd_desc, proc.returncode)) OSError: Command C:.platformio\penv\Scripts\python.exe - setuptools pip wheel failed with error code 1

Using base prefix 'C:\Users\Jer�nimo Torres\AppData\Local\Programs\Python\Python37' New python executable in C:.platformio\penv\Scripts\python.exe Command C:.platformio\penv\Scripts\python.exe -m pip config list had error code 1 Installing setuptools, pip, wheel...

Complete output from command C:.platformio\penv\Scripts\python.exe - setuptools pip wheel: Traceback (most recent call last): File "", line 3, in

ModuleNotFoundError: No module named 'pkgutil'
...Installing setuptools, pip, wheel...done.

```
at t.value (C:\Users\Jerónimo Torres\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\dist\index.js:1:34170)
at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by ivankravets** [comment]
We have just released a new version [2.7.0](https://github.com/platformio/platformio-atom-ide/releases/tag/v2.7.0), please upgrade.

**Please note that we HIGHLY recommend moving to [PlatformIO IDE for VSCode](https://platformio.org/platformio-ide) which resolves tons of issues and brings a lot of new features.**
