### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by 3dle** [platformio/platformio-atom-ide#2352]
Error: PIP Core: If you have antivirus/firewall/defender software in a system, try to disable it for a while. ERROR: Could not install packages due to an EnvironmentError: Failed to parse:

**Comment by ivankravets** [comment]
We have just released a new version [2.7.0](https://github.com/platformio/platformio-atom-ide/releases/tag/v2.7.0), please upgrade.

**Please note that we HIGHLY recommend moving to [PlatformIO IDE for VSCode](https://platformio.org/platformio-ide) which resolves tons of issues and brings a lot of new features.**
