### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by mohitora** [platformio/platformio-atom-ide#2359]
InstallationManager

Error: Could not create PIO Core Virtual Environment. Please create it manually -> http://bit.ly/pio-core-virtualenv Error: Virtualenv Create: Traceback (most recent call last): File "/Users/mohit/.platformio/.cache/tmp-47717HdfBa1SitdC/virtualenv-16.7.7/virtualenv.py", line 2628, in main() File "/Users/mohit/.platformio/.cache/tmp-47717HdfBa1SitdC/virtualenv-16.7.7/virtualenv.py", line 870, in main symlink=options.symlink, File "/Users/mohit/.platformio/.cache/tmp-47717HdfBa1SitdC/virtualenv-16.7.7/virtualenv.py", line 1156, in create_environment install_python(home_dir, lib_dir, inc_dir, bin_dir, site_packages=site_packages, clear=clear, symlink=symlink) File "/Users/mohit/.platformio/penv/lib/python2.7/posixpath.py", line 367, in abspath if not isabs(path): File "/Users/mohit/.platformio/penv/lib/python2.7/posixpath.py", line 54, in isabs return s.startswith('/') AttributeError: 'NoneType' object has no attribute 'startswith'

Please use the system python to run this script

at t.value (/Users/mohit/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/dist/index.js:1:34170)
at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by ivankravets** [comment]
We have just released a new version [2.7.0](https://github.com/platformio/platformio-atom-ide/releases/tag/v2.7.0), please upgrade.

**Please note that we HIGHLY recommend moving to [PlatformIO IDE for VSCode](https://platformio.org/platformio-ide) which resolves tons of issues and brings a lot of new features.**
