### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by sebkunmv** [platformio/platformio-atom-ide#2371]
Can't get rid of the message, despite all my trials. 

Zlib is installed yet (not sure if it's the real problem). However, it might be a matter of conflict. Here is a notice from a reinstall of Zlib (brew reinstall zlib)

```
zlib is keg-only, which means it was not symlinked into /usr/local,
because macOS already provides this software and installing another version in
parallel can cause all kinds of trouble.

For compilers to find zlib you may need to set:
  export LDFLAGS="-L/usr/local/opt/zlib/lib"
  export CPPFLAGS="-I/usr/local/opt/zlib/include"

For pkg-config to find zlib you may need to set:
  export PKG_CONFIG_PATH="/usr/local/opt/zlib/lib/pkgconfig"

```

**Comment by ivankravets** [comment]
We have just released a new version [2.7.0](https://github.com/platformio/platformio-atom-ide/releases/tag/v2.7.0), please upgrade.

**Please note that we HIGHLY recommend moving to [PlatformIO IDE for VSCode](https://platformio.org/platformio-ide) which resolves tons of issues and brings a lot of new features.**
