### ISSUE TITLE
Install Platformio-atom-ide/ win7 /Python 2.7 not found solved

### ISSUE THREAD

**Issue by jefman** [platformio/platformio-atom-ide#2374]
Hi
I am new user, I finally installed plateform-ide. (Atom 1.45.0, Platform-ide 2.6.0, win7)
When adding the package, a message "python 2.7 not found" appears.

In fact , if you have a look in "ChangeLog" it says that this version uses Python 3.7.5. (Also in the console of debug)

- Install Python 3.7.5 (not in automatic and do not forget to add in PATH)
- In atom, click on disable/enable on the package, it will start again the installation
- specify the path to Python 3.7.5 (if the platform package was installed first)

suggestion : change the version of Python on the error window
All done

**Comment by ivankravets** [comment]
We have just released a new version [2.7.0](https://github.com/platformio/platformio-atom-ide/releases/tag/v2.7.0), please upgrade.

**Please note that we HIGHLY recommend moving to [PlatformIO IDE for VSCode](https://platformio.org/platformio-ide) which resolves tons of issues and brings a lot of new features.**
