### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by DAKSie** [platformio/platformio-atom-ide#2386]
Error: Could not create PIO Core Virtual Environment. Please create it manually -> http://bit.ly/pio-core-virtualenv Error: Virtualenv Create: Traceback (most recent call last): File "C:\Users\user.platformio.cache\tmp-3896XxeGBC6tcfw9\virtualenv-16.7.7\virtualenv.py", line 2628, in main() File "C:\Users\user.platformio.cache\tmp-3896XxeGBC6tcfw9\virtualenv-16.7.7\virtualenv.py", line 870, in main symlink=options.symlink, File "C:\Users\user.platformio.cache\tmp-3896XxeGBC6tcfw9\virtualenv-16.7.7\virtualenv.py", line 1156, in create_environment install_python(home_dir, lib_dir, inc_dir, bin_dir, site_packages=site_packages, clear=clear, symlink=symlink) File "C:\Users\user\AppData\Local\Programs\Python\Python37-32\Lib\ntpath.py", line 526, in abspath return normpath(_getfullpathname(path)) TypeError: _getfullpathname: path should be string, bytes or os.PathLike, not NoneType

Please use the system python to run this script

**Comment by ivankravets** [comment]
Please upgrade to v2.7.0 where the new installer is added https://github.com/platformio/platformio-atom-ide/releases/tag/v2.7.0
