### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by matt142** [platformio/platformio-atom-ide#2393]
listen, if you guys select a dependant such as a build of python like 2.7 and don't support the latest version of python. Then you must take control of the availability of that dependant. I am having a very hard time getting this to work cause the latest version of python is not supported, understandably. But the version you do support is not easily found. Why is it that this is not included in your download? Why do you not have this build stored permanently at a convenient place with link? Why can't a simple search for the correct build solve this problem? This is a huge failure on your part and not acceptable in this day and age. One download and it works. Or put the necessary downloads in a safe place and in a sequential order. Such as your website or a support site. Not hard, I do this all the time with my projects. Get to work your way behind the times. 

Exact issue, atom needs pythond build 2.7, link provided takes me to latest build, which is NOT supported. 

I search for the correct build on pythons site and find lots a 2.7.x builds, which is it? 

I select the latest 2.7.x build and download. The download succeeded but Atom will not recognize it.

WHAT...... THE......Fu**k! 

The solution to the problem is not clear at this time.

**Comment by ivankravets** [comment]
Please upgrade to v2.7.0 where the new installer is added https://github.com/platformio/platformio-atom-ide/releases/tag/v2.7.0
