### ISSUE TITLE
Start PIO Home Server

### ISSUE THREAD

**Issue by overgara2012** [platformio/platformio-atom-ide#2396]
Error: Error: Traceback (most recent call last): File "/home/omarv/.platformio/penv/local/lib/python2.7/site-packages/platformio/main.py", line 109, in main cli() # pylint: disable=no-value-for-parameter File "/home/omarv/.platformio/penv/local/lib/python2.7/site-packages/click/core.py", line 764, in call return self.main(args, kwargs) File "/home/omarv/.platformio/penv/local/lib/python2.7/site-packages/click/core.py", line 717, in main rv = self.invoke(ctx) File "/home/omarv/.platformio/penv/local/lib/python2.7/site-packages/platformio/commands/init.py", line 44, in invoke return super(PlatformioCLI, self).invoke(ctx) File "/home/omarv/.platformio/penv/local/lib/python2.7/site-packages/click/core.py", line 1134, in invoke Command.invoke(self, ctx) File "/home/omarv/.platformio/penv/local/lib/python2.7/site-packages/click/core.py", line 956, in invoke return ctx.invoke(self.callback, ctx.params) File "/home/omarv/.platformio/penv/local/lib/python2.7/site-packages/click/core.py", line 555, in invoke return callback(args, kwargs) File "/home/omarv/.platformio/penv/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func return f(get_current_context(), *args, kwargs) File "/home/omarv/.platformio/penv/local/lib/python2.7/site-packages/platformio/main.py", line 63, in cli maintenance.on_platformio_start(ctx, force, caller) File "/home/omarv/.platformio/penv/local/lib/python2.7/site-packages/platformio/maintenance.py", line 41, in on_platformio_start after_upgrade(ctx) File "/home/omarv/.platformio/penv/local/lib/python2.7/site-packages/platformio/maintenance.py", line 142, in after_upgrade app.clean_cache() File "/home/omarv/.platformio/penv/local/lib/python2.7/site-packages/platformio/app.py", line 308, in clean_cache with ContentCache() as cc: File "/home/omarv/.platformio/penv/local/lib/python2.7/site-packages/platformio/app.py", line 182, in enter self.delete() File "/home/omarv/.platformio/penv/local/lib/python2.7/site-packages/platformio/app.py", line 295, in delete with open(self._db_path, "w") as fp: IOError: [Errno 13] Permission denied: '/home/omarv/.platformio/.cache/db.data'

**Comment by ivankravets** [comment]
We have just released a new version [2.7.0](https://github.com/platformio/platformio-atom-ide/releases/tag/v2.7.0), please upgrade.

**Please note that we HIGHLY recommend moving to [PlatformIO IDE for VSCode](https://platformio.org/platformio-ide) which resolves tons of issues and brings a lot of new features.**
