### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by tojaish** [platformio/platformio-atom-ide#240]
Error: Error: ENOENT: no such file or directory, open '/Users/xxxxxxx/.atom/packages/platformio-ide/project-examples/atmelavr-and-arduino/arduino-external-libs/lib/OneWire/examples/DS18x20_Temperature/DS18x20_Temperature.pde'

**Comment by ivankravets** [comment]
Could you reproduce this issue after Atom restart?

**Comment by ivankravets** [comment]
Please upgrade to the latest version
