### ISSUE TITLE
Start PIO Home Server

### ISSUE THREAD

**Issue by abhijitpadhi** [platformio/platformio-atom-ide#2400]
E:\WindowsOS\Code\ArduinoWorkspace>pio home
CorePackageManager: Installing contrib-pysite @ ~2.27.0
Downloading...
Error: Please read http://bit.ly/package-manager-ioerror
Warning! Package Mirror: ("Connection broken: error(10054, 'An existing connection was forcibly closed by the remote host')", error(10054, 'An existing connection was forcibly closed by the remote host'))
Looking for another mirror...
Error: Could not install 'contrib-pysite' with version requirements '~2.27.0' for your system 'windows_amd64'.

Please try this solution -> http://bit.ly/faq-package-manager

**Comment by ivankravets** [comment]
We have just released a new version [2.7.0](https://github.com/platformio/platformio-atom-ide/releases/tag/v2.7.0), please upgrade.

**Please note that we HIGHLY recommend moving to [PlatformIO IDE for VSCode](https://platformio.org/platformio-ide) which resolves tons of issues and brings a lot of new features.**
