### ISSUE TITLE
Terminal service is not registered

### ISSUE THREAD

**Issue by juanitomaille** [platformio/platformio-atom-ide#2406]
Hi, after atom and platformio update I have this message on click on serial terminal menu.

```
Platformio: Terminal service is not registered
Make sure that "platformio-ide-terminal" package is installed and activated.
```

I tried to reinstall platformio-ide-terminal without success.

I'm on Ubuntu 20.04

extract of installed packages :

Built-in Atom Packages (93)
├── atom-dark-syntax@0.29.1
├── atom-dark-ui@0.53.3
├── atom-light-syntax@0.29.1
├── atom-light-ui@0.46.3
├── base16-tomorrow-dark-theme@1.6.0
├── base16-tomorrow-light-theme@1.6.0
├── one-dark-ui@1.12.5
├── one-light-ui@1.12.5
├── one-dark-syntax@1.8.4
├── one-light-syntax@1.8.4
├── solarized-dark-syntax@1.3.0
├── solarized-light-syntax@1.3.0
├── about@1.9.1
├── archive-view@0.65.2
├── autocomplete-atom-api@0.10.7
├── autocomplete-css@0.17.5
├── autocomplete-html@0.8.8
├── autocomplete-plus@2.42.3
├── autocomplete-snippets@1.12.1
├── autoflow@0.29.4
├── autosave@0.24.6
├── background-tips@0.28.0
├── bookmarks@0.46.0
├── bracket-matcher@0.91.2
├── command-palette@0.43.5
├── dalek@0.2.2
├── deprecation-cop@0.56.9
├── dev-live-reload@0.48.1
├── encoding-selector@0.23.9
├── exception-reporting@0.43.1
├── find-and-replace@0.219.3
├── fuzzy-finder@1.14.2
├── github@0.34.2
├── git-diff@1.3.9
├── go-to-line@0.33.0
├── grammar-selector@0.50.1
├── image-view@0.64.0
├── incompatible-packages@0.27.3
├── keybinding-resolver@0.39.0
├── line-ending-selector@0.7.7
├── link@0.31.6
├── markdown-preview@0.160.2
├── metrics@1.8.1
├── notifications@0.71.0
├── open-on-github@1.3.2
├── package-generator@1.3.0
├── settings-view@0.261.4
├── snippets@1.5.1
├── spell-check@0.76.1
├── status-bar@1.8.17
├── styleguide@0.49.12
├── symbols-view@0.118.4
├── tabs@0.110.0
├── timecop@0.36.2
├── tree-view@0.228.0
├── update-package-dependencies@0.13.1
├── welcome@0.36.9
├── whitespace@0.37.7
├── wrap-guide@0.41.0
├── language-c@0.60.19
├── language-clojure@0.22.8
├── language-coffee-script@0.50.0
├── language-csharp@1.1.0
├── language-css@0.44.4
├── language-gfm@0.90.7
├── language-git@0.19.1
├── language-go@0.47.2
├── language-html@0.53.1
├── language-hyperlink@0.17.1
├── language-java@0.31.5
├── language-javascript@0.134.1
├── language-json@1.0.5
├── language-less@0.34.3
├── language-make@0.23.0
├── language-mustache@0.14.5
├── language-objective-c@0.16.0
├── language-perl@0.38.1
├── language-php@0.44.4
├── language-property-list@0.9.1
├── language-python@0.53.4
├── language-ruby@0.72.23
├── language-ruby-on-rails@0.25.3
├── language-rust-bundled@0.1.0
├── language-sass@0.62.1
├── language-shellscript@0.28.2
├── language-source@0.9.0
├── language-sql@0.25.10
├── language-text@0.7.4
├── language-todo@0.29.4
├── language-toml@0.20.0
├── language-typescript@0.6.2
├── language-xml@0.35.3
└── language-yaml@0.32.0

Community Packages (18) /home/jean/.atom/packages
├── atom-beautify@0.33.4
├── atom-material-syntax@1.0.8
├── atom-material-ui@2.1.3
├── autocomplete-clang@0.13.1
├── build@0.70.0
├── busy-signal@2.0.1
├── file-icons@2.1.41
├── intentions@1.1.5
├── language-ini@1.23.0
├── linter@2.3.1
├── linter-gcc@0.9.0
├── linter-gcc2@0.8.8
├── linter-ui-default@1.8.1
├── platformio-ide@2.7.1
├── platformio-ide-debugger@1.2.6
├── platformio-ide-terminal@2.10.0
├── tool-bar@1.3.0
└── vue-template-beautify@0.1.2

**Comment by ivankravets** [comment]
Please update to 2.7.2. Sorry for the issue.
