### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by mewman1234** [platformio/platformio-atom-ide#2407]
Install Atom when open it showed error message as below, 

Error: TypeError: pioNodeHelpers.misc.runCommand is not a function at AtomDependenciesStage. (/Users/.../.atom/packages/platformio-ide/lib/installer/stages/atom-dependencies.js:194:13) at Generator.throw () at step (/Users/..../.atom/packages/platformio-ide/lib/installer/stages/atom-dependencies.js:15:273)

Unsure how to fix, thank you

**Comment by ivankravets** [comment]
Please update to 2.7.2. Sorry for the issue.
