### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by bleiente** [platformio/platformio-atom-ide#2420]
OS: MacOS 10.12.6
Python: 2.7.10
Atom: 1.48.0

Installed platformio as plugin a few month ago.
I started atom today again after a few days (maybe 2 weeks?) of not using and it automatically updated platformio. Unfortunately the update failed and it disabled platformio.

Error message:
Error: Error: Could not create PIO Core Virtual Environment. Please report to https://github.com/platformio/platformio-core-installer/issues -> Installer version: 0.3.2 Platform: Darwin-16.7.0 Python version: 2.7.10 (default, Feb 7 2017, 00:08:15) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)] Python path: /usr/bin/python Creating a virtual environment at /Users/myuser/.platformio/penv

at /Users/myuser/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/dist/index.js:1:4975
at ChildProcess.c (/Users/myuser/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/dist/index.js:1:4871)
at ChildProcess.emit (events.js:194:13)
at maybeClose (internal/child_process.js:998:16)
at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)

Any suggestions how to fix this?
Is there a possibility to install the previous version?

**Comment by ivankravets** [comment]
Please update to 2.7.2. Sorry for the issue.
