### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by drewskix86** [platformio/platformio-atom-ide#2421]
Error received during automatic update of PlatformIO on Atom 1.48.0 MacOS 10.15.5:

Error: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available. Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/platformio/ Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/platformio/ Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/platformio/ Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/platformio/ Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/platformio/ Could not find a version that satisfies the requirement platformio (from versions: ) No matching distribution found for platformio pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available. Error: Could not install PlatformIO Core: Command '['/Users/drew/.platformio/penv/bin/python', '-m', 'pip', 'install', '-U', 'platformio']' returned non-zero exit status 1. -> Installer version: 0.3.2 Platform: Darwin-19.5.0 Python version: 3.7.4 (default, Jul 9 2019, 18:13:23) [Clang 10.0.1 (clang-1001.0.46.4)] Python path: /usr/local/opt/python/bin/python3.7 Creating a virtual environment at /Users/drew/.platformio/penv Updating Python package manager (PIP) in a virtual environment Virtual environment has been successfully created! Installing PlatformIO Core Collecting platformio Could not fetch URL https://pypi.org/simple/platformio/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/platformio/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping

at /Users/drew/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/dist/index.js:1:4975
at ChildProcess.c (/Users/drew/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/dist/index.js:1:4871)
at ChildProcess.emit (events.js:194:13)
at maybeClose (internal/child_process.js:998:16)
at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)

**Comment by ivankravets** [comment]
Please update to 2.7.2. Sorry for the issue.
