### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by pmemeo** [platformio/platformio-atom-ide#2425]
Error: Could not find a version that satisfies the requirement platformio (from versions: ) No matching distribution found for platformio Error: Could not install PlatformIO Core: Command '['/Users/patric/.platformio/penv/bin/python', '-m', 'pip', 'install', '-U', 'platformio']' returned non-zero exit status 1 -> Installer version: 0.3.2 Platform: Darwin-19.5.0 Python version: 3.5.0 (v3.5.0:374f501f4567, Sep 12 2015, 11:00:19) [GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] Python path: /Library/Frameworks/Python.framework/Versions/3.5/bin/python3 Creating a virtual environment at /Users/patric/.platformio/penv Updating Python package manager (PIP) in a virtual environment Virtual environment has been successfully created! Installing PlatformIO Core Collecting platformio

at /Users/patric/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/dist/index.js:1:4975
at ChildProcess.c (/Users/patric/.atom/packages/platformio-ide/node_modules/platformio-node-helpers/dist/index.js:1:4871)
at ChildProcess.emit (events.js:194:13)
at maybeClose (internal/child_process.js:998:16)
at Socket.<anonymous> (internal/child_process.js:403:11)
at Socket.emit (events.js:194:13)
at Pipe.<anonymous> (net.js:593:12)

**Comment by ivankravets** [comment]
Please update to 2.7.2. Sorry for the issue.
