### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by Jeronimo016** [platformio/platformio-atom-ide#2428]
**InstallationManager**

`Error: Traceback (most recent call last): File "C:.platformio.cache\get-platformio-0.3.2.py", line 53, in main() File "C:.platformio.cache\get-platformio-0.3.2.py", line 46, in main bootstrap() File "C:.platformio.cache\get-platformio-0.3.2.py", line 32, in bootstrap pioinstaller.main.main() File "C:\Users\JERNIM~1\AppData\Local\Temp\tmpbyd4mase\pioinstaller.zip\pioinstaller__main__.py", line 122, in main File "C:\Users\JERNIM~1\AppData\Local\Temp\tmpbyd4mase\pioinstaller.zip\click\core.py", line 829, in call File "C:\Users\JERNIM~1\AppData\Local\Temp\tmpbyd4mase\pioinstaller.zip\click\core.py", line 782, in main File "C:\Users\JERNIM~1\AppData\Local\Temp\tmpbyd4mase\pioinstaller.zip\click\core.py", line 1236, in invoke File "C:\Users\JERNIM~1\AppData\Local\Temp\tmpbyd4mase\pioinstaller.zip\click\core.py", line 1066, in invoke File "C:\Users\JERNIM~1\AppData\Local\Temp\tmpbyd4mase\pioinstaller.zip\click\core.py", line 610, in invoke File "C:\Users\JERNIM~1\AppData\Local\Temp\tmpbyd4mase\pioinstaller.zip\click\decorators.py", line 21, in new_func File "C:\Users\JERNIM~1\AppData\Local\Temp\tmpbyd4mase\pioinstaller.zip\pioinstaller__main__.py", line 52, in cli File "C:\Users\JERNIM~1\AppData\Local\Temp\tmpbyd4mase\pioinstaller.zip\pioinstaller\core.py", line 72, in install_platformio_core File "C:\Users\JERNIM~1\AppData\Local\Temp\tmpbyd4mase\pioinstaller.zip\pioinstaller\penv.py", line 52, in create_core_penv File "C:\Users\JERNIM~1\AppData\Local\Temp\tmpbyd4mase\pioinstaller.zip\pioinstaller\python.py", line 170, in find_compatible_pythons UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf3 in position 30: invalid continuation byte -> Installer version: 0.3.2 Platform: Windows-10 Python version: 3.7.7 (tags/v3.7.7:d7c567b08f, Mar 10 2020, 10:41:24) [MSC v.1900 64 bit (AMD64)] Python path: C:.platformio\python37\python.exe Creating a virtual environment at C:.platformio\penv
`
```
at C:\Users\Jerónimo Torres\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\dist\index.js:1:4975
at ChildProcess.c (C:\Users\Jerónimo Torres\.atom\packages\platformio-ide\node_modules\platformio-node-helpers\dist\index.js:1:4871)
at ChildProcess.emit (events.js:194:13)
at ChildProcess.cp.emit (C:\Users\Jerónimo Torres\.atom\packages\platformio-ide\node_modules\cross-spawn\lib\enoent.js:34:29)
at maybeClose (internal/child_process.js:998:16)
at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
```

**Comment by ivankravets** [comment]
Please update to 2.7.2. Sorry for the issue.
