### ISSUE TITLE
Platform-ide not installing on Atom

### ISSUE THREAD

**Issue by maccacino** [platformio/platformio-atom-ide#2429]
Platform-ide package not installing on Atom 1.48 x64, Ubuntu 20.04.
Crashes atoms main window.

Only solution is to run atom in safe mode;
`>> atom -safe`

or remove the package from `~/.atom/packages/` by deleting the platform-ide folder.

**Comment by maccacino** [comment]
Seems to be a fix here #2412

**Comment by ivankravets** [comment]
Please update to 2.7.2. Sorry for the issue.
