### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by overgara2012** [platformio/platformio-atom-ide#2434]
Error: Error: Could not create PIO Core Virtual Environment. Please report to https://github.com/platformio/platformio-core-installer/issues -> Installer version: 0.3.2 Platform: Windows-10 Python version: 3.7.5 (tags/v3.7.5:5c02a39a0b, Oct 15 2019, 00:11:34) [MSC v.1916 64 bit (AMD64)] Python path: C:\Users\overg.platformio\python37\python.exe Creating a virtual environment at C:\Users\overg.platformio\penv

**Comment by ivankravets** [comment]
Please update to 2.7.2. Sorry for the issue.
