### ISSUE TITLE
Platformio-ide crashs the Editor

### ISSUE THREAD

**Issue by ITCrowdIOB** [platformio/platformio-atom-ide#2439]
Platformio-ide crashs the Editor. Deinstall Atom and install don't solve the problem.

On next Start Atom shows:
PlatformIO IDE installation has been suspended.

Seems like PlatformIO IDE Installer is already started in another window.

**Comment by ErrOzz** [comment]
Confirm. Win10x64. Atom1.50.0x64. Platformio-IDE2.7.1

**Comment by ITCrowdIOB** [comment]
Win10x64  pro  18363.1016

Atom 1.50.0 x64

Platformio-IDE2.7.1

 

 

 

Von: Егор <notifications@github.com> 
Gesendet: Mittwoch, 12. August 2020 22:40
An: platformio/platformio-atom-ide <platformio-atom-ide@noreply.github.com>
Cc: ITCrowdIOB <reg2@team-eul.de>; Author <author@noreply.github.com>
Betreff: Re: [platformio/platformio-atom-ide] Platformio-ide crashs the Editor (#2439)

 

Confirm. Win10x64. Atom1.50.0x64. Platformio-IDE2.7.1

**Comment by clemans** [comment]
Same. 
`~$: cat /etc/os-release | grep -i "PRETTY NAME"` Pop!_OS 20.04 LTS
`~$: atom --version` Atom    : 1.49.0 | Electron: 5.0.13 | Chrome  : 73.0.3683.121 | Node    : 12.0.0
Platformio-ide  : 2.7.1

**Comment by ErrOzz** [comment]
At the moment I have temporary fixed this by installing the previous platformio-ide version 2.6.0: apm install platformio-ide@2.6.0

**Comment by Kubis12** [comment]
Could you tell me please, how can I instal platformio-ide version 2.6.0?

**Comment by clemans** [comment]
> apm install platformio-ide@2.6.0

This worked for me as well. Thank you @ErrOzz . Looking forward for the @latest to getting fixed.

**Comment by ErrOzz** [comment]
> Could you tell me please, how can I instal platformio-ide version 2.6.0?
You need to uninstall platformio-ide 2.7.1. Just type in the command line:
apm uninstall platformio-ide@2.7.1
You can clarify the names of the installed packages with folowing command:
apm list
When the uninstall is complete, just install previous platformio package using the command:
apm install platformio-ide@2.6.0
Launch Atom for the platformio to finish installing the required components.

**Comment by ivankravets** [comment]
Please update to 2.7.2. Sorry for the issue.
