### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by lmsb** [platformio/platformio-atom-ide#2440]
I had installed Atom and Platformio IDE with no issue but now it's failing complaining about something Python related. Can you kindly help ?  
I have Atom 1.45 .0 x64
Platformio IDE: v2.7.1

Error: Error: Could not create PIO Core Virtual Environment. Please report to https://github.com/platformio/platformio-core-installer/issues profiling:/home/luis/Python-3.8.2/build/temp.linux-x86_64-3.8/home/luis/Python-3.8.2/Modules/_multiprocessing/semaphore.gcda:Cannot open profiling:/home/luis/Python-3.8.2/build/temp.linux-x86_64-3.8/home/luis/Python-3.8.2/Modules/_multiprocessing/multiprocessing.gcda:Cannot open profiling:/home/luis/Python-3.8.2/build/temp.linux-x86_64-3.8/home/luis/Python-3.8.2/Modules/unicodedata.gcda:Cannot open profiling:/home/luis/Python-3.8.2/build/temp.linux-x86_64-

**Comment by ivankravets** [comment]
Please update to 2.7.2. Sorry for the issue.
