### ISSUE TITLE
Platformio Crashes Atom

### ISSUE THREAD

**Issue by Lsn93** [platformio/platformio-atom-ide#2441]
I can't open Atom IDE... platformio just crashed it

**Comment by svdb99** [comment]
Same here. After a clean Atom install (any version, Win10), Platformio-atom-ide destabilizes Atom which can launch but ends up freezing.

**Comment by Unisolve** [comment]
Same here I'm afraid (in Windows 7)

**Comment by iamkendall** [comment]
Same it's my first time trying to use atom but I don't think that's the problem (Windows 10)

**Comment by ivankravets** [comment]
Please update to 2.7.2. Sorry for the issue.
