### ISSUE TITLE
Causing Atom to crash

### ISSUE THREAD

**Issue by TravellerNL** [platformio/platformio-atom-ide#2443]
**_(See workaround below)_**

After installing PlatformIO-IDE 2.7.1 from the package manager in Atom 1.50.0 x64, Atom crashes completely and pops up a critical warning: "Editor is not responding":

After removing PlatformIO from the folder: C:\Users\<USERNAME>\.atom\packages Atom works fine again, but without the PlatformIO-IDE.

![AtomPlatformioCrashAfterInstall](https://user-images.githubusercontent.com/28827822/91973195-1b3bea00-ed1c-11ea-9a65-6724b9b61755.JPG)

![AtomPlatformioCrash](https://user-images.githubusercontent.com/28827822/91972852-8e912c00-ed1b-11ea-9d6b-c8d4a829cc71.JPG)

**System used is:**
Windows 10 Pro, Version 1909, OS build 18363.1016, x64
Intel Core i&-3610QM @2.30GHz, 16GB, x64

**WORK AROUND**
**Deinstall V2.7.0 and install V2.6.0**

**How to:**
Close any instance of Atom.
Right-click The Windows Logo in the lower left corner of the screen and click on Run.
Uninstall version 2.7.1 by entering: `apm uninstall platformio-ide@2.7.1`
Install version 2.6.0 by entering: `apm install platformio-ide@2.6.0`

**Comment by ivankravets** [comment]
Please update to 2.7.2. Sorry for the issue.
