### ISSUE TITLE
Editor Window Has Become Unresponsive macos

### ISSUE THREAD

**Issue by utdrmac** [platformio/platformio-atom-ide#2444]
Just downloaded the latest Atom, and tried to install the latest platformIO. Atom keeps displaying the noted error.

```
$ atom --version
Atom    : 1.50.0
Electron: 5.0.13
Chrome  : 73.0.3683.121
Node    : 12.0.0
```

If I `apm remove platformio-ide`, then Atom works again. Others posted the solution to install a specific, previous version, of platformIO, 2.6.0

`apm install platformio-ide@2.6.0`

Atom works now without issue and I'm able to edit my projects with platformIO.

**Comment by ivankravets** [comment]
Please update to 2.7.2. Sorry for the issue.

**Comment by mf-1** [comment]
Issue is still happen....
![image](https://user-images.githubusercontent.com/1529283/93100164-29d5ba00-f6a9-11ea-8a62-fdd677002ecb.png)


https://github.com/platformio/platformio-atom-ide/issues/2445#issuecomment-692101902
