### ISSUE TITLE
Mac Install Error

### ISSUE THREAD

**Issue by laz666** [platformio/platformio-atom-ide#2454]
Install error on a Mac

> node-pty-prebuilt-multiarch@0.9.0-beta21.legacy install /private/var/folders/01/gck519w902x_8nc1wyrqymhm0000gn/T/apm-install-dir-2020104-7088-1tglkpf.5169/node_modules/platformio-ide-terminal/node_modules/node-pty-prebuilt-multiarch
> prebuild-install || node scripts/install.js

prebuild-install WARN install No prebuilt binaries found (target=6.1.12 runtime=electron arch=x64 libc= platform=darwin)
No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.

**Comment by ivankravets** [comment]
Fixed in https://github.com/platformio/platformio-atom-ide-terminal/releases/tag/v2.10.1

Please update `platformio-ide-terminal` to the latest version.
