### ISSUE TITLE
Platformio-ide

### ISSUE THREAD

**Issue by Blakinas** [platformio/platformio-atom-ide#2457]
instaliing whole week, when it will finish? Please help.
if i restart Atom, the same keeps tring after some time. but never finished.
![2](https://user-images.githubusercontent.com/37005046/98459599-0a3ca880-21a5-11eb-8403-b9311724b037.jpg)
![1](https://user-images.githubusercontent.com/37005046/98459601-0b6dd580-21a5-11eb-8861-b86778bdde96.jpg)

my email is tomas.sliauteris@gmail.com

**Comment by Winch-** [comment]
I have the same issue, install hangs with installing dependences platformio toolbar is there but does not work. also small flashing icon at bottom of screen, checking PIO core.
tried all sorts of suggestions from web but no good. *my coding skills are basic so some suggestions were beyond my skill set*. surely this is a flagship app and should work without bugs. I am following online coding examples where Atom is used and it seems like a great tool so why does it work for some and not others.

**Comment by n3o23** [comment]
Same issue here. Been stuck installing all day.
I heard if you install the older version it will work just fine.  I am researching and will provide an update once I get it fixed.

**Comment by B0bb3rl3** [comment]
I've the same problem. Tried a workaround. But it still hangs up... Hope there will be a solution for this problem soon.

**Comment by maxgerhardt** [comment]
@ivankravets can you have a look at this? Also just popped up in https://community.platformio.org/t/platformio-ide-install-failure-under-atom-editior-under-windows/17703

**Comment by ptmartellock** [comment]
LOL, the last one's reference only points to this thread... circular no answers.

**Comment by ivankravets** [comment]
Fixed in https://github.com/platformio/platformio-atom-ide-terminal/releases/tag/v2.10.1

Please update `platformio-ide-terminal` to the latest version.
