### ISSUE TITLE
Platform IO invokes multiple instances of Python

### ISSUE THREAD

**Issue by mrkaroshi** [platformio/platformio-atom-ide#246]
Since using Platform IO I've noticed it's invoking multiple instances of Python 2.7 on my Mac (OSX 10.11.6, IDE 2.0.0-alpha.7, Core 3.3.0a12), is this normal? Do you think this is an issue with the IDE or the core? It maxes out my CPU after a few hours use.
![cpu_usage_atom](https://cloud.githubusercontent.com/assets/6320261/23508127/831fdf40-ff50-11e6-91a4-56134706732f.jpg)

**Comment by ivankravets** [comment]
Thanks a lot for your report. That is not normal.

1. Please close Atom
2. Check that all `python2.7` process are halted
3. Start Atom and try to find a case where multiple `python` process are starting.

Thanks!

**Comment by ivankravets** [comment]
Also, `View > Developer > Toggle Developer Tools > Console` should help us.

**Comment by mrkaroshi** [comment]
Okay will do, will test over the next few hours.

**Comment by mrkaroshi** [comment]
Still trying to replicate the issue, it hasn't cropped up for some reason.

**Comment by ivankravets** [comment]
Please reopen this issue if you will have any problems again.

**Comment by mrkaroshi** [comment]
I think I've been able to replicate the issue, and I'm almost 100% certain the serial monitor is causing it. If I program my Teensy and let the serial monitor open I will view my data over the space of a few minutes, then close it using the shortcut 'Ctrl+C', and do this repeatedly throughout a working session. I think, for whatever reason, PlatformIO may be invoking the multiple instances to handle serial communication, then not clearing them when the communication is over. Can anyone replicate this?

**Comment by chris-gunawardena** [comment]
I get this every time I open the serial monitor.
I'm using the visual studio plugin.
![image](https://user-images.githubusercontent.com/5763108/27761306-c4ccce2c-5e59-11e7-956e-9434ebf26e5d.png)

**Comment by ivankravets** [comment]
http://docs.platformio.org/en/latest/faq.html#multiple-pio-cores-in-a-system

**Comment by chris-gunawardena** [comment]
Thanks @ivankravets when I uninstalled Atom the issue got fixed.
