### ISSUE TITLE
Failed to run BUILD command

### ISSUE THREAD

**Issue by chakrihacker** [platformio/platformio-atom-ide#248]
Platformio alpha version unable to trigger build from the icon when ide is restarted, however I can run build command from command pallette (ctrl+shift+p)
I get this message when I click build 
> PlatformIO: Failed to run a command: Build', "Please make sure that 'build package is installed and activated

Using Atom latest Stable and Ubuntu 16.04

**Comment by ivankravets** [comment]
Could you try the latest PIO IDE Alpha.13?

**Comment by chakrihacker** [comment]
sorry, I'm little busy with office work so closing this issue, will open if needed.
