### ISSUE TITLE
Serial Monitor modal popup extended options doesn't fit small screens

### ISSUE THREAD

**Issue by peekpt** [platformio/platformio-atom-ide#250]
Serial Monitor[icon] > Toggle advanced settings

The number of options is to big to fit my macbook air 11". Some options are small text, maybe put them side by side.

![captura de ecra 2017-03-04 as 18 01 43](https://cloud.githubusercontent.com/assets/222385/23581120/468b2816-0106-11e7-8c05-75c7f96c45f5.png)

**Comment by ivankravets** [comment]
@orgkhnargh `overflow-y: auto`
