### ISSUE TITLE
Platform command failed: platform install nordicnrf51@1.6.0

### ISSUE THREAD

**Issue by amin-git** [platformio/platformio-atom-ide#256]
Error: Error: Can not install 'tool-sreccat' with version requirements '~1.164.0' for your system 'windows_amd64'

**Comment by ivankravets** [comment]
Do you have antivirus in a system?

**Comment by amin-git** [comment]
yes,i disable it & installation work without problem!
tnx

**Comment by ivankravets** [comment]
I've just opened an issue. Will add detailed information later

* https://github.com/platformio/platformio-core/issues/916
