### ISSUE TITLE
Linter Repeatedly Reindexes

### ISSUE THREAD

**Issue by mrkaroshi** [platformio/platformio-atom-ide#260]
I've got an issue whereby the Linter 'reindexing' message is coming up over and over again, and now I'm getting 'no such file or directory' errors for frameworks I know are installed.

One clue might be that when I open the Developer Console I get this message:

> Failed to clear temp storage: It was determined that certain files are unsafe for access within a Web application, or that too many calls are being made on file resources. SecurityError

I believe the error coincides with when I created a new .cpp file in my library folder called 'draft.cpp' that I was just using to try out a redraft of my contributions. Any clues as to what this might be?

(OSX 10.11.6, IDE 1.7.3, Core 3.2.1, Atom 1.15.0)

**Comment by mrkaroshi** [comment]
It also seems to be tied into the Python issue...
![cpu_python](https://cloud.githubusercontent.com/assets/6320261/23904884/afd15302-08c9-11e7-8e2a-c1825424a545.jpg)

**Comment by mrkaroshi** [comment]
The issue may be to do with dependencies also, as Linter appears to be repeatedly indexing the same things. Removing 'lib/Adafruit_BNO055' from my platformio.ini stopped the repeated indexing but now Build appears to be building twice and trying to upload twice.
![build_issue](https://cloud.githubusercontent.com/assets/6320261/23906392/1ec8ec12-08ce-11e7-84be-5f17df44c1e0.gif)

**Comment by ivankravets** [comment]
1. OS
2. PIO IDE Version
3. PIO Core version
4. Atom version

**Comment by mrkaroshi** [comment]
Sorry, knew I'd forgotten something, put the info in the revised issue.

**Comment by ivankravets** [comment]
> IDE 1.7.3,

Please switch to PlatformIO IDE 2.0.
Menu: PlatformIO > Home > Switch to PIO IDE 2.0

**Comment by mrkaroshi** [comment]
Seems to be working well, I'll post at the end of the day - if nothing happens I think we can close. Thank you for your support!

**Comment by mrkaroshi** [comment]
Problem solved, think this can be closed, many thanks!
