### ISSUE TITLE
Restart infinite cycle in version 2.0.0 alpha 11

### ISSUE THREAD

**Issue by sabas1080** [platformio/platformio-atom-ide#262]
Hi

I have the next error restart infinite cycle in version 2.0.0 alpha 11

![captura de pantalla 2017-03-14 a la s 17 38 59](https://cloud.githubusercontent.com/assets/2874292/23927299/674d8082-08de-11e7-8322-681a56a5ff61.png)

OS: Mac Sierra
Atom: 1.12.3

I was working fine until the version 2.0.0 alpha 7

Thanks

**Comment by ivankravets** [comment]
Menu: View > Developers > Toggle Developers Tools> Console

Could you provide and output?

**Comment by ivankravets** [comment]
Please restart Atom and update to A12. PIO IDE 2.0 is switched to new PIO IDE Terminal v2.5.0

**Comment by sabas1080** [comment]
Update to A12 and work

Thanks
