### ISSUE TITLE
VSCode support

### ISSUE THREAD

**Issue by jeasonstudio** [platformio/platformio-atom-ide#265]
Hey there.
PlatformIO IDE is amazing for us hardware developers.
I'm Chinese and we use VSCode most time.
So I think it's better to support VSCode, thanks.

**Comment by formulahendry** [comment]
@jeasonstudio [PlatformIO for Visual Studio Code](https://marketplace.visualstudio.com/items?itemName=formulahendry.platformio) is just coming. 😃
