### ISSUE TITLE
in Windows. recurring IDE install everytime atom starts

### ISSUE THREAD

**Issue by syddo** [platformio/platformio-atom-ide#266]
I'm encountering a recurring install every time i start/open the atom editor. platformio-ide has already been installed successfully installed previously.

**Comment by ivankravets** [comment]
https://community.platformio.org/t/urgent-platformio-ide-2-0-preview-doesnt-receive-any-updates/1620/11

**Comment by hisoka0323** [comment]
I also encountered this problem, it's that a solution?
