### ISSUE TITLE
Stuck at "PlatformIO IDE: Installing ..." after install via apm & keeps opening new python processes

### ISSUE THREAD

**Issue by dmte** [platformio/platformio-atom-ide#267]
I'm using Windows 10 and after installing PlatformIO IDE via apm (I also tried installation from within Atom) the atom startup gets stuck at this loading screen:

![platformio-atominstall](https://cloud.githubusercontent.com/assets/26488228/24052902/62ae1946-0b37-11e7-8dba-5ecaea4f41ce.jpg)

When checking the taskmanager you can see hundereds of python processes:

![platformio-taskmanager](https://cloud.githubusercontent.com/assets/26488228/24052922/768b87f0-0b37-11e7-8eb6-0be651c25252.jpg)
![platformio-procexp](https://cloud.githubusercontent.com/assets/26488228/24052923/76a2adc2-0b37-11e7-9f9c-9f02f9f677d1.jpg)

**Comment by ivankravets** [comment]
Please try `apm install --production platformio/platformio-atom-ide`

**Comment by ivankravets** [comment]
Should be fixed in the latest PIO IDE 2.0 Beta 3
