### ISSUE TITLE
Find in project gives to many results

### ISSUE THREAD

**Issue by sstaub** [platformio/platformio-atom-ide#27]
The new Tool-Button "Find" (in project) gives to many results. Maybe it should changed that the
function looks only in the src folder and only cpp/c/h files, but it will better that find works only
for the current buffer. Sorry, my mistake.

**Comment by ivankravets** [comment]
How about Atom's comment in the 3-rd field?
![screen shot 2016-01-29 at 22 45 17](https://cloud.githubusercontent.com/assets/1760209/12687669/fdfd5928-c6d9-11e5-93aa-1f98eca0575c.png)

**Comment by sstaub** [comment]
OK, see it. But for a shortcut symbol button I think it is better to use the simple standard version.
But it is my personal opinion.

**Comment by ivankravets** [comment]
This universal Find panel which allow to search everywhere within project. Don't mean something private but I don't want to make "Word" from PlatformIO IDE. I hope that users will also use Atom menu hotkeys. The idea of this toolbar to give access to PlatformIO commands/function and some global.

What do you think?

**Comment by ivankravets** [comment]
Also, I implement `Menu: PlatformIO > Settings` where you can configure your request https://github.com/platformio/platformio-atom-ide/issues/23

**Comment by sstaub** [comment]
That's really great.

**Comment by ivankravets** [comment]
I propose to keep single universal search on the toolbar.
