### ISSUE TITLE
Restart prompt on every time IDE starts

### ISSUE THREAD

**Issue by mdogancay** [platformio/platformio-atom-ide#275]
Hi I got restart prompt on every time IDE starts, like:
![screenshot from 2017-03-20 20-06-56](https://cloud.githubusercontent.com/assets/3320364/24111876/8872c6f2-0da0-11e7-932a-f9329be69c7e.png)
Can anyone help?

**Comment by jburns20** [comment]
I had this and uninstalling/reinstalling the Platformio package worked for me.

**Comment by bmv437** [comment]
That also worked for me, but I had to make sure to completely close Atom after uninstalling the `platformio-ide` package, then open Atom and reinstall `platformio-ide`. Otherwise you end up with errors like #273.

**Comment by mdogancay** [comment]
It's works guys, remove platformio and reinstall after restart Atom; working perfectly.
Thanks.
