### ISSUE TITLE
Toolbar Position at start

### ISSUE THREAD

**Issue by sstaub** [platformio/platformio-atom-ide#28]
The Toolbar is always at the left side when starting atom, regardless of the main settings in the tool-bar package.

**Comment by ivankravets** [comment]
Which version of IDE do you use? https://github.com/platformio/platformio-atom-ide/blob/develop/HISTORY.md

**Comment by sstaub** [comment]
Platform IDE 0.3.1, Atom 1.4.1 on MacBook Pro Retina

**Comment by ivankravets** [comment]
Thanks!

**Comment by ivankravets** [comment]
Just curious: which is your favourite position?

**Comment by sstaub** [comment]
Meanwhile at top, because I use an addition package (tool-bar-atom). On the side view I
need to scroll to see all the symbols. But I think at start the left side is ok when you use only the
platformIDE toolbar.

stefan

**Comment by ivankravets** [comment]
Thanks for the reports.
