### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by greypanda** [platformio/platformio-atom-ide#283]
Error: Error: ENOENT: no such file or directory, open '/home/john/.atom/packages/platformio-ide/.cache/examples.tar.gz'

**Comment by ivankravets** [comment]
1. PIO IDE version
2. OS

Do you see this problem after restart?

**Comment by greypanda** [comment]
Linux Ubuntu 16.0.4.


I uninstalled atom and cleaned up all the dot files.

Reinstalled everything, now it's happy.

**Comment by ivankravets** [comment]
@orgkhnargh could we improve something here? If not, please close this issue.
