### ISSUE TITLE
telemetry crap kills CPU

### ISSUE THREAD

**Issue by Spongman** [platformio/platformio-atom-ide#290]
ugh. if you add a hosts entry pointing www.google-analytics.com to localhost, then platformio's telemetry loops, causing errors hundreds of times a second. it's sending telemetry on every exception, and if it fails to send telemetry, then it throws an exception.

**Comment by ivankravets** [comment]
Thanks a lot for the report!

Please re-test it:

1. Comment www.google-analytics.com in your host
2. Start PIO IDE
3. Navigate to Menu: PlatformIO > Settings > PIO IDE
4. Click on "Use development version of PIO IDE"
5. Return back your hosts.

Does it work now?
