### ISSUE TITLE
InstallationManager: Virtualenv => AttributeError: 'NoneType' object has no attribute 'startswith'

### ISSUE THREAD

**Issue by mainephd** [platformio/platformio-atom-ide#295]
Virtualenv Download: Traceback (most recent call last):
  File "/var/folders/yv/0z1k9z255nl2plpk4wb8g_sw0000gq/T/tmp-87003oEDrL3vEl6Ii/virtualenv-15.1.0/virtualenv.py", line 2328, in <module>

    main()
  File "/var/folders/yv/0z1k9z255nl2plpk4wb8g_sw0000gq/T/tmp-87003oEDrL3vEl6Ii/virtualenv-15.1.0/virtualenv.py", line 713, in main

    symlink=options.symlink)
  File "/var/folders/yv/0z1k9z255nl2plpk4wb8g_sw0000gq/T/tmp-87003oEDrL3vEl6Ii/virtualenv-15.1.0/virtualenv.py", line 925, in create_environment

    site_packages=site_packages, clear=clear, symlink=symlink))
  File "/Users/me/.platformio/penv/lib/python2.7/posixpath.py", line 360, in abspath

    if not isabs(path):
  File "/Users/me/.platformio/penv/lib/python2.7/posixpath.py", line 54, in isabs
    return s.startswith('/')
AttributeError: 'NoneType' object has no attribute 'startswith'

**Comment by ivankravets** [comment]
Do you see this error after Atom restart?

**Comment by mainephd** [comment]
The error goes away after the restart of atom @ivankravets

**Comment by M0derator** [comment]
Did anyone get this fixed? I am having the same error after Sophos AV decided to delete the requirements.txt file which I could not reinstall for some reason.

**Comment by ivankravets** [comment]
@M0derator try 
```
sudo pip install -U pip setuptools
rm -rf ~/.platformio/penv
```

Start Atom.

**Comment by M0derator** [comment]
The directory '/home/itwasluckvpn/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/itwasluckvpn/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.

This is the error I'm getting, I kind of know its related to Sophos AV to removing the file. I tried removing Sophos AV and giving it another go but using the commands you provide I'm getting this. Thanks for the quick reply BTW, much appreciated!
