### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by cghercoias** [platformio/platformio-atom-ide#299]
PIP: Error: spawn /Users/LocalUser/.platformio/penv/bin/pip ENOENT

I have installed Atom and from Preferences->Install->Platformio-IDE and at the end gave me this error.

**Comment by ivankravets** [comment]
Could you try restart Atom?

**Comment by ivankravets** [comment]
Please upgrade to the latest PIO IDE 2.0 Beta 3
