### ISSUE TITLE
telemetry is sent against user's wishes

### ISSUE THREAD

**Issue by Spongman** [platformio/platformio-atom-ide#304]
telemetry is sent even though atom's telemetry setting is set to "Do not send any telemetry data". 

please honor that setting.

**Comment by ivankravets** [comment]
Telemetry was removed in the latest commit. New version with PIO Home 2.0 coming soon

- https://github.com/platformio/platformio-atom-ide/commit/9ee495e0e10a817fe46a2b53dbb96f88d972e5c6
