### ISSUE TITLE
InstallationManager: Error: PIP

### ISSUE THREAD

**Issue by ryanbbernstein** [platformio/platformio-atom-ide#312]
PIP: 

That's all is says. Not able to use platformio at all.

**Comment by ivankravets** [comment]
What is your OS?

**Comment by ryanbbernstein** [comment]
Windows 10 64bit

None of the menu options seem to do anything. Doesn't give me any error. I have tried reinstalling through command line as well and it says failed.

**Comment by ivankravets** [comment]
1. Do you have Python installed in a system? If yes, which version?
2. Did you use PIO IDE before?

**Comment by ryanbbernstein** [comment]
Ya python 2.7
First time trying to use PIO

**Comment by ivankravets** [comment]
Could you make clean uninstallation and install the latest Atom + stable PIO IDE 2.0.0-beta.2? Thanks!

* http://docs.platformio.org/en/latest/ide/atom.html#uninstall-atom-with-platformio-ide

**Comment by ryanbbernstein** [comment]
Followed the instructions but still nothing.
Goes through installation with dependencies and core still flashing and then straight to this.
![pio](https://cloud.githubusercontent.com/assets/16244525/24582460/3bddc30c-16e5-11e7-9bb4-5dfd41bc89ce.PNG)

**Comment by ivankravets** [comment]
Please mail me@ikravets.com, I'll explain further steps

**Comment by ryanbbernstein** [comment]
Virtualenv=1.9.1

**Comment by mapsi-fixi** [comment]
Hello, i have same problem. Windows 7 64bit. Python 2.7

**Comment by ryanbbernstein** [comment]
Problem came from virtualenv being way out of date. Try updating to latest version and reinstalling PIO.

**Comment by ivankravets** [comment]
Try in system terminal
```
pip install -U pip setuptools virtualenv
```

Restart Atom
