### ISSUE TITLE
extra_script.py - Running a serial monitor after upload

### ISSUE THREAD

**Issue by MabezDev** [platformio/platformio-atom-ide#349]
Hey I am trying to get a serial monitor to open automatically. I have been using the script found on the website and it runs but I have no idea what target, source and env are. I have looked through the documentation and can't see anything on them except target?

Any hints on how to solve my problem? Sorry I if I am missing something really obvious!

**Comment by ivankravets** [comment]
Please move your question to http://community.platformio.org/
