### ISSUE TITLE
InstallationManager: Virtualenv Download: Error: connect ENOTCONN

### ISSUE THREAD

**Issue by sve95** [platformio/platformio-atom-ide#359]
Virtualenv Download: Error: connect ENOTCONN 151.101.36.223:443

**Comment by ivankravets** [comment]
Please open system terminal (`cmd`) and provide:
```
python --version
pip --version
virtualenv -- version
echo %PATH%
```

Thanks!

**Comment by ivankravets** [comment]
Please check your internet connection and upgrade to PIO IDE 2.0 Beta 3
