### ISSUE TITLE
InstallationManager pip not recognized as internal or external command

### ISSUE THREAD

**Issue by mgulsoy** [platformio/platformio-atom-ide#360]
When trying to install platformio-ide, on the last step named "platformio-core" I got the message (also translated) below and installation stops. I got this error both with x64 and x86 setups.

Here are my system specs:
- Win7 home ed. x64
- Has working installation of python 2.7 and pip.
- Windows ide is Turkish. Region is Turkey. 

PIP: 'C:\Users\mert\.platformio\penv\Scripts\pip' i� ya da d�� komut, �al��t�r�labilir
program ya da toplu i� dosyas� olarak tan�nm�yor.
 ------------------------Translation of the message: 
PIP: 'C:\Users\mert\.platformio\penv\Scripts\pip' not recognized as internal or external command or batch file.

**Comment by ivankravets** [comment]
Please open system terminal (`cmd`) and provide:
```
python --version
pip --version
virtualenv -- version
echo %PATH%
```

Thanks!

**Comment by ivankravets** [comment]
Also, please update to the latest PIO IDE 2.0 beta 3

**Comment by ivankravets** [comment]
Please reopen if you still need help
