### ISSUE TITLE
InstallationManager: Virtualenv Download

### ISSUE THREAD

**Issue by pelorr** [platformio/platformio-atom-ide#367]
Virtualenv Download:   File "C:\Program Files\Python\Lib\site.py", line 177
    file=sys.stderr)
        ^
SyntaxError: invalid syntax

**Comment by ivankravets** [comment]
Do you have `virtualenv` installed in a system?

```
python --version
virtualenv --version
```

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/337

Issue with Python 3
