### ISSUE TITLE
Elements on "Custom Library Storages" path not found by #include

### ISSUE THREAD

**Issue by dsjstc** [platformio/platformio-atom-ide#378]
IDE settings -> Advanced -> Custom Library Storages

From the description, this looks like a library path.  However, libraries on this path are not found by the compiler -- each project must *also* have the path included on a LIB_EXTRA_DIRS in that project's platformio.ini.  I suspect this path is only used by the GUI library manager.  Perhaps the description could be updated to save others my confusion.  Suggested text:

> List of additional paths where the library manager GUI (but no other tools) may find or manage libraries.  Paths are delimited by comma+space.

**Comment by ivankravets** [comment]
New PlatformIO Home 2.0 looks for extra storages in `platformio.ini` automatically. See https://github.com/platformio/platformio-atom-ide/commit/9ee495e0e10a817fe46a2b53dbb96f88d972e5c6

The next release is coming this week.
