### ISSUE TITLE
InstallationManager: PIP

### ISSUE THREAD

**Issue by obor00** [platformio/platformio-atom-ide#389]
PIP:
I get an error when installing platformio-ide on Atom windows 64, it always fail and I get an error window saying "report a problem". 
Platformio-ide version 2.0.0-beta2
Where to search to debug ?

**Comment by ivankravets** [comment]
* Do you have Python install in a system?
* Do you have `virtualenv` installed in a system?

**Comment by ivankravets** [comment]
Please open system terminal (`cmd`) and provide:
```
python --version
pip --version
virtualenv -- version
echo %PATH%
```

Thanks!

**Comment by ivankravets** [comment]
Please provide an output from system Terminal `cmd`
```
echo %PATH%
python --version
pip --version
pip list
```

Please reopen if you still need help
