### ISSUE TITLE
Modifying the MQTT_MAX_PACKET_SIZE value in PubSubClient.h (library 89) and saving it causes compile errors

### ISSUE THREAD

**Issue by tonykambo** [platformio/platformio-atom-ide#40]
@ivankravets 

1. Navigate to .pioenvs/nodemcu/PubSubClinet_ID89
2. Chang value of MQTT_MAX_PACKET_SIZE from 128 to 256
3. Save header file (Cmd-S on Mac)
4. A number of GCC warnings and errors appear

Building the project does not result in the change being processed in the build.
This change has worked in the past.

The following errors are presented when saving the header file:

![screen shot 2016-02-15 at 12 22 04 am](https://cloud.githubusercontent.com/assets/1737417/13033890/2e0db8d6-d37a-11e5-8fa1-2bd042726b34.png)

**Comment by ivankravets** [comment]
`.pioenvs` is temporary directory for PlatformIO. Please don't edit here source files.

**Comment by ivankravets** [comment]
Discussed it personally via Gitter PM.
