### ISSUE TITLE
Set the upload_port setting via an environment setting rather than platformio.ini

### ISSUE THREAD

**Issue by tonykambo** [platformio/platformio-atom-ide#41]
It would be appreciated if we could set the upload_port setting currently found in platformio.ini (in support of OTA firmware updates) to be set via environment variable rather than hard coding IP address in platform.ini. This will help with team development using repo and avoid having to manually change IP. 

Thanks.

**Comment by ivankravets** [comment]
Sorry, please move it to https://github.com/platformio/platformio/issues

This issue is related to PlatformIO Tool (CLI) not to IDE.

Thanks a lot!
