### ISSUE TITLE
InstallationManager: Virtualenv Download: Error: unable to verify the first certificate

### ISSUE THREAD

**Issue by az-z** [platformio/platformio-atom-ide#413]
Virtualenv Download: Error: unable to verify the first certificate

this installation is behind the corporate NTLM proxy.
the curl is working fine with if i explicitly specify the proxy type ( NTLM).

**Comment by ivankravets** [comment]
You need to set proxy settings for Atom and Python's PIP.

**Comment by ivankravets** [comment]
Please reopen if you still need help
