### ISSUE TITLE
Platform command failed: platform search --json-output

### ISSUE THREAD

**Issue by cmburg** [platformio/platformio-atom-ide#443]
This error occured when I clicked the 'platforms'-button on the left from the pio-home. Wasn't able to reproduce yet.
> Error: Traceback (most recent call last):
>   File "/home/claas/.platformio/penv/bin/platformio", line 11, in <module>
>     load_entry_point('platformio==3.4.0b1', 'console_scripts', 'platformio')()
>   File "/home/claas/.platformio/penv/local/lib/python2.7/site-packages/platformio/__main__.py", line 109, in main
> 
>     maintenance.on_platformio_exception(e)
>   File "/home/claas/.platformio/penv/local/lib/python2.7/site-packages/platformio/maintenance.py", line 85, in on_platformio_exception
>     telemetry.on_exception(e)
>   File "/home/claas/.platformio/penv/local/lib/python2.7/site-packages/platformio/telemetry.py", line 314, in on_exception
>     mp = MeasurementProtocol()
>   File "/home/claas/.platformio/penv/local/lib/python2.7/site-packages/platformio/telemetry.py", line 65, in __init__
>     self['cid'] = app.get_cid()
>   File "/home/claas/.platformio/penv/local/lib/python2.7/site-packages/platformio/app.py", line 322, in get_cid
>     cid = get_state_item("cid")
>   File "/home/claas/.platformio/penv/local/lib/python2.7/site-packages/platformio/app.py", line 271, in get_state_item
>     with State() as data:
>   File "/home/claas/.platformio/penv/local/lib/python2.7/site-packages/platformio/app.py", line 89, in __enter__
>     self._state = util.load_json(self.path)
>   File "/home/claas/.platformio/penv/local/lib/python2.7/site-packages/platformio/util.py", line 178, in load_json
>     file_path)
> platformio.exception.PlatformioException: Could not load broken JSON: /home/claas/.platformio/appstate.json
> 
> Error in atexit._run_exitfuncs:
> Traceback (most recent call last):
> 
>   File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
> 
>     func(*targs, **kargs)
>   File "/home/claas/.platformio/penv/local/lib/python2.7/site-packages/platformio/telemetry.py", line 331, in _finalize
> 
>     backup_reports(MPDataPusher().get_items())
>   File "/home/claas/.platformio/penv/local/lib/python2.7/site-packages/platformio/telemetry.py", line 341, in backup_reports
> 
>     tm = app.get_state_item("telemetry", {})
>   File "/home/claas/.platformio/penv/local/lib/python2.7/site-packages/platformio/app.py", line 271, in get_state_item
> 
>     with State() as data:
>   File "/home/claas/.platformio/penv/local/lib/python2.7/site-packages/platformio/app.py", line 89, in __enter__
> 
>     self._state = util.load_json(self.path)
>   File "/home/claas/.platformio/penv/local/lib/python2.7/site-packages/platformio/util.py", line 178, in load_json
> 
>     file_path)
> 
> PlatformioException: Could not load broken JSON: /home/claas/.platformio/appstate.json
> 
> Error in sys.exitfunc:
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
>     func(*targs, **kargs)
>   File "/home/claas/.platformio/penv/local/lib/python2.7/site-packages/platformio/telemetry.py", line 331, in _finalize
> 
>     backup_reports(MPDataPusher().get_items())
>   File "/home/claas/.platformio/penv/local/lib/python2.7/site-packages/platformio/telemetry.py", line 341, in backup_reports
> 
>     tm = app.get_state_item("telemetry", {})
>   File "/home/claas/.platformio/penv/local/lib/python2.7/site-packages/platformio/app.py", line 271, in get_state_item
> 
>     with State() as data:
>   File "/home/claas/.platformio/penv/local/lib/python2.7/site-packages/platformio/app.py", line 89, in __enter__
>     self._state = util.load_json(self.path)
> 
>   File "/home/claas/.platformio/penv/local/lib/python2.7/site-packages/platformio/util.py", line 178, in load_json
>     file_path)
> platformio.exception.PlatformioException: Could not load broken JSON: /home/claas/.platformio/appstate.json
> 
>     at /home/claas/.atom/packages/platformio-ide/lib/platform/helpers.js:61:25
>     at onExit (/home/claas/.atom/packages/platformio-ide/lib/utils.js:92:7)
>     at exit (/home/claas/.atom/packages/platformio-ide/lib/utils.js:102:21)
>     at triggerExitCallback (/opt/atom/resources/app.asar/src/buffered-process.js:322:11)
>     at ChildProcess.<anonymous> (/opt/atom/resources/app.asar/src/buffered-process.js:352:11)
>     at emitTwo (events.js:106:13)
>     at ChildProcess.emit (events.js:191:7)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)

**Comment by ivankravets** [comment]
Please remove this file /home/claas/.platformio/appstate.json and restart Atom
