### ISSUE TITLE
InstallationManager: PIP: Could not import setuptools which is required to install from a source distribution.

### ISSUE THREAD

**Issue by davestroud** [platformio/platformio-atom-ide#469]
PIP: Could not import setuptools which is required to install from a source distribution.
Traceback (most recent call last):
  File "/Users/davidstroud/.platformio/penv/lib/python2.7/site-packages/pip/req/req_install.py", line 387, in setup_py
    import setuptools  # noqa
  File "/Users/davidstroud/.local/lib/python2.7/site-packages/setuptools/__init__.py", line 10, in <module>
    from six.moves import filter, map
ImportError: No module named six.moves

**Comment by ivankravets** [comment]
What is your MacOS version?

**Comment by davestroud** [comment]
macOS Sierra
Version 10.12.6 Beta(16G8c)
Processor 2.2 GHz Intel Core i7

**Comment by ivankravets** [comment]
Have you resolved this issue?

**Comment by davestroud** [comment]
I have! Thank you!!

**Comment by ivankravets** [comment]
Could you explain how?

**Comment by ivankravets** [comment]
@davestroud Please give us a solution how did you resolve this issue. Thanks!
