### ISSUE TITLE
InstallationManager: ImportError: No module named functools

### ISSUE THREAD

**Issue by egn-dev** [platformio/platformio-atom-ide#488]
Trying to install one of the following versions:
- platformio-ide 2.0.0-beta.2
- platformio-ide 2.0.0-beta.3
- platformio-ide 2.0.0-beta.4
I get this error:

Virtualenv Download: Traceback (most recent call last):
  File "C:/Users/admin/.platformio/penv/lib/python2.7/site.py", line 703, in <module>
    main()
  File "C:/Users/admin/.platformio/penv/lib/python2.7/site.py", line 692, in main
    aliasmbcs()
  File "C:/Users/admin/.platformio/penv/lib/python2.7/site.py", line 515, in aliasmbcs
    import locale, codecs
  File "C:\Users\admin\.platformio\penv\lib\python2.7/locale.py", line 17, in <module>
    import functools
ImportError: No module named functools

Details about my system:
1) Windows 10 (1607) x64
2) Python 3.6.1 x64 (C:\Program Files\Python36) - No Python 2.x
3) Atom 1.16.0 x64
4) Environment variable "Path" (system/all users):
C:\Program Files\Python36\Scripts\;C:\Program Files\Python36\;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Git\cmd;%MSYS_PATH%\bin;%MINGW_PATH%\bin;C:\Program Files\CMake\bin;C:\Program Files\dotnet\;C:\Program Files\LLVM\bin
Note. "%MSYS_PATH%\bin" (== "C:\msys64\usr\bin") contains, among others, these binary: "python2.7.exe", "python2.exe"
5) Directory "C:\Users\admin\.platformio\penv\Lib\python2.7" contains only:
_abcoll.py
_abcoll.pyc
_weakrefset.py
_weakrefset.pyc
abc.py
abc.pyc
codecs.py
codecs.pyc
copy_reg.py
copy_reg.pyc
encodings
files_list.txt
fnmatch.py
genericpath.py
genericpath.pyc
lib-dynload
linecache.py
linecache.pyc
locale.py
locale.pyc
no-global-site-packages.txt
ntpath.py
ntpath.pyc
orig-prefix.txt
os.py
os.pyc
posixpath.py
re.py
re.pyc
site.py
site.pyc
sre.py
sre_compile.py
sre_compile.pyc
sre_constants.py
sre_constants.pyc
sre_parse.py
sre_parse.pyc
stat.py
stat.pyc
types.py
types.pyc
UserDict.py
UserDict.pyc
warnings.py
warnings.pyc

**Comment by egn-dev** [comment]
I managed to install platformio-ide only after manually installing Python 2.7.13 in its default directory "C:\Python27" (without adding it to "Path" environment path)

**Comment by ivankravets** [comment]
Could you run?
```
C:/msys64/usr/bin/python2.exe -c "import functools; import ConfigParser; import sys; print ".".join(str(v) for v in sys.version_info[:2])"
```

**Comment by ivankravets** [comment]
@stefan-schindler do you also have `C:/msys64/usr/bin/python2.exe`?

**Comment by stefan-schindler** [comment]
@ivankravets No, but here `C:/msys64/mingw32/bin/` (this is added to PATH when **msys** is instaled) I have theses files:
![image](https://cloud.githubusercontent.com/assets/26493472/26696835/5997e67e-4710-11e7-9168-a8d164627514.png)

**Comment by stefan-schindler** [comment]
And when I call the `command` you provided above, it runs ok (it outputs `2.7`). The `functools` module isn't missing from **msys** python interpereter, but from the Python which isn't successfully created using `virtualenv.py` (which is executed by **msys** python interpreter).

**Comment by raxetul** [comment]
Platformio-ide package under atom seems to want the python.exe under a python directory. Because of this it fails.
![pio-error](https://user-images.githubusercontent.com/1366577/27213588-8a16e44c-5270-11e7-83e1-baf315cbd411.png)
