### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by sjschaff** [platformio/platformio-atom-ide#510]
I moved some project library files from outside of atom (specifically moved lib/glm -> lib/glm/glm due to glm's internal header usages), and I immediately started getting this error from platformio.  Deleting .pioenvs fixed it, but presumably shouldn't have happened

Exception: [Errno 13] Permission denied: '/Users/<user>/Files/Projects/Totem/platformio/.pioenvs/do-not-modify-files-here.url':

File "/Users/<user>/.platformio/penv/lib/python2.7/site-packages/platformio/builder/main.py", line 86:
PROJECTPIOENVS_DIR=util.get_projectpioenvs_dir(),
File "/Users/<user>/.platformio/penv/lib/python2.7/site-packages/platformio/util.py", line 309:
raise Exception(e)

========================== [ERROR] Took 5.14 seconds ==========================

**Comment by ivankravets** [comment]
Just close Atom, remove `/Users//Files/Projects/Totem/platformio/.pioenvs` and start Atom

**Comment by sjschaff** [comment]
Yeah I got it fixed, thanks.  Still seems like a bug though.

**Comment by ivankravets** [comment]
Something has gone with permission :(
