### ISSUE TITLE
After install PlatformIO-IDE on Atom, Atom show restart Window Infinitly

### ISSUE THREAD

**Issue by wjm0621** [platformio/platformio-atom-ide#521]
![default](https://cloud.githubusercontent.com/assets/4524843/26520262/f374d74e-4309-11e7-85c2-7fd6b7764b1a.png)
![default](https://cloud.githubusercontent.com/assets/4524843/26520264/f7be74f4-4309-11e7-84a8-0c2b075fca1d.png)

after remove atom and platformio, LLVM, Python 2.7 I reinstalled Atom and platformIO-IDE.
but Atom just show Message "please restart Atom to apply the changes"
after restart, show again
after restart, show again....
....
infinitly

how can i solve this problem?

**Comment by ivankravets** [comment]
https://github.com/platformio/platformio-core/releases/tag/v3.3.1

Please restart Atom

**Comment by wjm0621** [comment]
Thank you ivankravets!! I solved this problem. Thank you a million!!!
