### ISSUE TITLE
Linter bug with user library

### ISSUE THREAD

**Issue by sstaub** [platformio/platformio-atom-ide#54]
I use in my program a user library, but I get stupid linter warning message:
![linter_error_1](https://cloud.githubusercontent.com/assets/6450325/13197855/36e6560a-d7fa-11e5-9270-df3e7b27bd3a.png)
When I comment the include Header file out (// #include "TextLCD.h") the warning goes away.
![linter_error_2](https://cloud.githubusercontent.com/assets/6450325/13197867/a0b9a0dc-d7fa-11e5-86f3-dd0a5033226b.png)

**Comment by ivankravets** [comment]
Please add `-Wno-comment` to `gccDefaultCFlags` and `gccDefaultCppFlags` fields after `-Wall` in `.gcc-flags.json` file.

Does it work?

**Comment by sstaub** [comment]
Yes, it works.
Thank you for that fast replay.

**Comment by ivankravets** [comment]
Should I include it by default for all projects?

**Comment by sstaub** [comment]
I think yes. But I didn't really understand why this warning comes up, and the col-number is not existing.

**Comment by sstaub** [comment]
Here is a copy from the code, which cause the following warning:
"gcc warning multi-line comment [-Wcomment] at line 54 col 34"
- The column doesn't exist. 
- The warning disappears when deleting #include "TextLCD.h"
- the code works, also the functionality of the user library
![warning](https://cloud.githubusercontent.com/assets/6450325/13201916/dc3e5892-d885-11e5-87b1-1edc83ec074a.png)
![files](https://cloud.githubusercontent.com/assets/6450325/13201918/df8382de-d885-11e5-9a16-26f4fd1099c4.png)
[mbedBase.zip](https://github.com/platformio/platformio-atom-ide/files/139535/mbedBase.zip)

**Comment by ivankravets** [comment]
I opened issue https://github.com/platformio/platformio/issues/528 where you will have ability to use `build_flags = -Wno-comment -Wl,-u,_printf_float,-u,_scanf_float` and PlatformIO IDE `Menu: Rebuild C/C++ Project Index`.

Please subscribe to https://github.com/platformio/platformio/issues/528 and test when it will be fixed.
