### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by silps** [platformio/platformio-atom-ide#542]
Error: Could not install 'framework-arduinoespressif32' with version requirements '~1.1.4' for your system 'darwin_x86_64'.
If you use Antivirus, it can block PlatformIO Package Manager. Try to disable it for a while.

**Comment by ivankravets** [comment]
Could you reproduce this issue after restart?

**Comment by silps** [comment]
Hey, thanks for the fast reply. Sorry didn't try that before reporting it, I first also didn't understand that reporting things creates a GitHub issue. After the reboot it looks working now 👍

**Comment by ivankravets** [comment]
Happy coding with PlatformIO!
