### ISSUE TITLE
allow to / remeber the  pre select the platforms you have 

### ISSUE THREAD

**Issue by dothebart** [platformio/platformio-atom-ide#56]
There is a cute `import from arduino ide` thingabob. 

It asks you to choose from the devices you've got and choose from several hundrets each time you import a project.

It should preselect or show the already choosen platforms to quickly buypass this step for subsequent import approaches.

Btw, great fun to see how fast a .js ide can be in comparison to the original arduino java ide. 
##

**Comment by ivankravets** [comment]
You can use quick filter in new PIO Home
