### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by DJManas** [platformio/platformio-atom-ide#561]
warning: Ignoring missing SConscript '/Users/djmanas/.platformio/penv/lib/python2.7/site-packages/platformio/builder/main.py'
File "/Users/djmanas/.platformio/packages/tool-scons/script/scons", line 199, in <module>

*** Do not know how to make File target `idedata' (/Users/djmanas/Dropbox/Projekty/Arduino/__Test Sketches__/APDS-9960/idedata).  Stop.

========================== [ERROR] Took 1.27 seconds ==========================

**Comment by ivankravets** [comment]
Try to remove `/Users/djmanas/.platformio/penv` and restart Atom.

**Comment by DJManas** [comment]
Restart helped. Sorry I had published it, just wanted to be useful. Thanks for the support.
