### ISSUE TITLE
Add to Menu: PlatformIO > Settings direct links to the settings of dependent packages

### ISSUE THREAD

**Issue by aperepel** [platformio/platformio-atom-ide#57]
Hi folks, great effort on the IDE, looking forward to what it evolves into. Would like to request an option to save automatically on build. Tried out the IDE on a project and realized how annoying the prompt is on each build. As a long-time professional IDE user I expect it to save when I invoke the build action.

I'd prefer it even to be the default, but you're free to add it as a setting to the PlatformIO IDE.

**Comment by orgkhnargh** [comment]
Go to "Settings > Packages > build" and check the "Automatically save on build" checkbox.

**Comment by aperepel** [comment]
Cool, any way you can control it from the IDE module? I guess it's a different `build` module you are reusing, but locating those switches is non-trivial. Maybe add a doc note if nothing else?

**Comment by ivankravets** [comment]
![screen shot 2016-03-07 at 00 33 30](https://cloud.githubusercontent.com/assets/1760209/13557587/3da73e74-e3fc-11e5-8b89-ae6031f14ec4.png)
