### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by tuhuynh** [platformio/platformio-atom-ide#572]
Error: Could not find a version that satisfies the requirement '~1.50200.0' for your system 'linux_i686'

**Comment by tuhuynh** [comment]
i use lubuntu 32 bit.
PackageManager: Installing toolchain-xtensa32 @ ~1.50200.0
Error: Could not find a version that satisfies the requirement '~1.50200.0' for your system 'linux_i686'

**Comment by ivankravets** [comment]
Please try again, we have just added a missed package for linux_i686
