### ISSUE TITLE
Once again, after upgrade to PlatformIO 2.0.0 beta6 the program keeps reinstalling PlatformIO Core ...

### ISSUE THREAD

**Issue by chessweb01** [platformio/platformio-atom-ide#580]
... and after it finishes, it requires a restart and the cycle repeats.

When the restart is refused, the IDE is not working properly. The icons are not responsive to clicks. One cannot open the PlatformIO -> Settings -> PlatformIO IDE dialog, building does not work, neither does uploading nor can one open a terminal.

In short, PlatformIO IDE is completely broken for me after upgrading to 2.0.0 beta6.

**Comment by ivankravets** [comment]
Could you reinstall PIO IDE?

* http://docs.platformio.org/en/latest/ide/atom.html#uninstall-atom-with-platformio-ide

Also, please remove PIO Core from `~/.platformio`
