### ISSUE TITLE
Can't disable "Use built-in platformio core"

### ISSUE THREAD

**Issue by DeltaCore** [platformio/platformio-atom-ide#587]
I have the problem that i can't disable the option "Use built-in platformio core" in the settings. When ever i disable it, atom want's to restart. I then went ahead and restarted atom. After that, platformio says that it finished installation and wants to restart. If I ignore that i can't compile or programm anything so i restarted. After that restart the option was checked again.

**Comment by ivankravets** [comment]
http://docs.platformio.org/en/latest/faq.html#multiple-pio-cores-in-a-system
