### ISSUE TITLE
Serial monitor keymap

### ISSUE THREAD

**Issue by Bladeslayer1000** [platformio/platformio-atom-ide#59]
Hello,

I cant find the assignment for a keymap value to open the Serial monitor. Is there a option to open it with a keymap?

Greetings,
Bladeslayer1000

**Comment by orgkhnargh** [comment]
Click "Edit > Open Your Keymap" ("Atom > Open Your Keymap" on Mac) and add the following to the file that opens:

```
'atom-workspace':
  'ctrl-shift-h': 'platformio-ide:maintenance.serial-monitor'
```

The `ctrl-shift-h` may be altered according to your needs. Put any (available) keystroke here. 

The `platformio-ide:maintenance.serial-monitor` is the name of the command that shows the Serial Monitor. You can find a list of available commands in here: https://github.com/platformio/platformio-atom-ide/blob/develop/menus/main.cson

This is also described in Atom docs: https://atom.io/docs/latest/using-atom-basic-customization#customizing-key-bindings

**Comment by ivankravets** [comment]
@orgkhnargh need to add default keymap to our IDE. Please check which keystroke is available.

**Comment by Bladeslayer1000** [comment]
Thank you for the good support! Keep going.

**Comment by ivankravets** [comment]
@Bladeslayer1000 don't forget to give us a star :star: https://github.com/platformio/platformio-atom-ide/stargazers

**Comment by Bladeslayer1000** [comment]
Is it possible, to add the baudrate, and port automatically? So you go directly to the Serial monitor?

**Comment by ivankravets** [comment]
Please rephrase your question.
