### ISSUE TITLE
C/C++ project index rebuild failed: Multiple ways to build the same target 

### ISSUE THREAD

**Issue by Aarleks** [platformio/platformio-atom-ide#605]
*** Multiple ways to build the same target were specified for: C:\Users\Aarle\OneDrive\Documents\Arduino\.pioenvs\uno\src\wiring_pulse.o  (from ['C:\\Users\\Aarle\\OneDrive\\Documents\\Arduino\\src\\wiring_pulse.S'] and from ['C:\\Users\\Aarle\\OneDrive\\Documents\\Arduino\\src\\wiring_pulse.c'])

File "C:\Users\Aarle\.platformio\penv\lib\site-packages\platformio\builder\tools\platformio.py", line 101, in BuildProgram

 [ERROR] Took 0.91 seconds

**Comment by ivankravets** [comment]
Could you provide `platformio.ini`?

**Comment by ivankravets** [comment]
Please reopen if you still need help
