### ISSUE TITLE
Suggested Enhancement to Platform.ini - for building arduino as component under espidf

### ISSUE THREAD

**Issue by anilanilb** [platformio/platformio-atom-ide#617]
Hi, Can the platformio team provide an enhancement to Platform.ini that can simplify building arduino as component under espidf. Probably by providing an option in the "framework" or any other suitable way.  
Example
[env:esp32dev]
framework = **espidfwitharduino**
board = esp32dev
platform = espressif32

**Comment by ivankravets** [comment]
https://github.com/platformio/platform-espressif32/issues/24
