### ISSUE TITLE
"Installation has failed" error on windows 10

### ISSUE THREAD

**Issue by PhilippeBonnaz** [platformio/platformio-atom-ide#64]
When trying to install platforio IDE with "platformio-atom-windows" installer I get the following error message: 
"Installation has failed
There was an error while installing the application. Check the setup log for more information and contact the author"

Here is the setup log file, the problem seems to be a too long path name, but I have no idea how to solve that issue

[PlatformioInstallErrorLog.txt](https://github.com/platformio/platformio-atom-ide/files/161610/PlatformioInstallErrorLog.txt)

**Comment by ivankravets** [comment]
Do you have Atom already installed?

**Comment by PhilippeBonnaz** [comment]
I get the exact same error message when trying to install Atom.

And I think the same Error log

[AtomInstallErrorLog.txt](https://github.com/platformio/platformio-atom-ide/files/161620/AtomInstallErrorLog.txt)

**Comment by ivankravets** [comment]
Try to remove this folder `C:\Users\consultant.DAV-IDF-CON-PBO\AppData\Local\atom`

**Comment by PhilippeBonnaz** [comment]
Still the same error

[AtomInstallErrorLog2.txt](https://github.com/platformio/platformio-atom-ide/files/161645/AtomInstallErrorLog2.txt)

**Comment by ivankravets** [comment]
Could you try this archive (not installer) https://github.com/atom/atom/releases/download/v1.5.4/atom-windows.zip

Does Atom start?

**Comment by cbentle** [comment]
I promise you that the issue is exactly the same issue I had. My solution was to remove the installer from the downloads folder, run it with administrator privileges even if you are already an administrator, you need to explicitly run its as administrator on Windows by right clicking. Once installed, platformio wouldn't spawn due to my Antivirus App firewall,  so I had to add python, atom, and all of the build tools to the white list. It is easiest to run the build command and then as each tool in the chain tries to run, allow it through your Antivirus pop up notification, I had to run build 8 times or so until it was all white listed.

**Comment by PhilippeBonnaz** [comment]
Hi,
Yes atom is starting with that archive !

**Comment by PhilippeBonnaz** [comment]
cbentle: I still get the exact same error message and error log, when trying to install atom or platforiom as administrator from outside the download folder ;)

**Comment by ivankravets** [comment]
> Yes atom is starting with that archive !

Now install our package manually. See http://docs.platformio.org/en/latest/ide/atom.html#manual-installation

Step 2

**Comment by PhilippeBonnaz** [comment]
Thank you !
Platformio installation worked

**Comment by ivankravets** [comment]
@PhilippeBonnaz can you confirm that successfully built some project?

**Comment by PhilippeBonnaz** [comment]
Yes Ivan, I'll let you know ;)

**Comment by PhilippeBonnaz** [comment]
I hame having difficulties building the project.
No problem setting up the project (FYI the board I'm using is ST NUCLEO-L152RE)
I create the main.cpp file in src directory, copy the example project.
And get an "arduino.h" no such file or directory when building

[ArduinoNoSuchFile.txt](https://github.com/platformio/platformio-atom-ide/files/165326/ArduinoNoSuchFile.txt)

**Comment by valeros** [comment]
Hi @PhilippeBonnaz please take a look at our [mbed Blink example](https://github.com/platformio/platformio/tree/develop/examples/mbed/mbed-blink)

**Comment by PhilippeBonnaz** [comment]
Thank you @ivankravets and @valeros now it is working
