### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by firesgc** [platformio/platformio-atom-ide#648]
Hi,

I have this problem if I try to install "tool-scons".

Exception AttributeError: "'FileDownloader' object has no attribute '_request'" in <bound method FileDownloader.__del__ of <platformio.downloader.FileDownloader object at 0x05A38F30>> ignored
Error: Could not install 'tool-scons' with version requirements '~3.20501.2' for your system 'windows_x86'.
If you use Antivirus, it can block PlatformIO Package Manager. Try to disable it for a while.

I am using Win10, I havnt installed any Antivirus and I have disabled the Windows Defender. I don't use a proxy. I have no clue what I could do to fix it :/

**Comment by ivankravets** [comment]
Please remove `{HOMEUSER}/.platformio` folder and start again
