### ISSUE TITLE
Autocomplete and GCC not updating when adding library

### ISSUE THREAD

**Issue by ajajack** [platformio/platformio-atom-ide#65]
I added a library to my project using the terminal in the IDE. I included the header file in my code (#include <U8glib.h>), and everything compiled just fine. However, the IDE was complaining about the include line, saying that the file or directory doesn't exist. Once I added the full path "/Users/andrew/123-init/.pioenvs/diecimilaatmega328/U8glib_ID7" to both the .clang_complete and the gcc-flags.json files, the GCC error went away and I was able to use the autocomplete function.

Why doesn't the IDE automatically search for these added libraries? Am I doing anything wrong?

**Comment by ivankravets** [comment]
http://docs.platformio.org/en/latest/ide/atom.html#intelligent-code-autocompletion

```
The libraries which are added/installed after initializing process will not be reflected in code linter. You need Menu: PlatformIO > Rebuild C/C++ Project Index (Autocomplete, Linter).
```
