### ISSUE TITLE
Always updating

### ISSUE THREAD

**Issue by Desertgeek** [platformio/platformio-atom-ide#652]
I recently reinstalled PlatformIO IDE so that I can use the terminal app in OSX to view my Arduino output. Now, every time I upload a program to the Arduino from my laptop, I get a "Please wait while updating PlatformIO..." message. It updates just fine but then when I issue the "pio device monitor..." in OSX terminal, it updates again, successfully and runs.
I have Auto update unchecked in PlatformIO settings and I'm looking for some other place that might be forcing the update but cannot find it.
Why is this happening?

**Comment by ivankravets** [comment]
See 

* http://docs.platformio.org/en/latest/faq.html#multiple-pio-cores-in-a-system
* http://docs.platformio.org/en/latest/faq.html#install-pio-core-shell-commands
