### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by Littrow** [platformio/platformio-atom-ide#663]
UnicodeDecodeError: Non-ASCII characters found in build environment
See explanation in FAQ > Troubleshooting > Building
http://docs.platformio.org/page/faq.html

 [ERROR] Took 0.75 seconds

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/658

**Comment by Littrow** [comment]
Thanks, everybody alright.
