### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by Zhurzhin** [platformio/platformio-atom-ide#666]
Error: Could not install 'tool-scons' with version requirements '~3.20501.2' for your system 'darwin_x86_64'.
If you use Antivirus, it can block PlatformIO Package Manager. Try to disable it for a while.

Traceback (most recent call last):
File "/Users/KOCMOHABT/.platformio/packages/tool-scons/script/scons", line 190, in <module>
import SCons.Script
ImportError: No module named SCons.Script

on my Comp i can`t find it this file

**Comment by ivankravets** [comment]
Please remove `/Users/KOCMOHABT/.platformio/packages/tool-scons/` folder and start again

**Comment by Zhurzhin** [comment]
Removing folder not solved this problem.
but i delete Atom + Platformio and full reinstall - solved.

**Comment by ivankravets** [comment]
Thank you for the report!
