### ISSUE TITLE
All settings lost after package update

### ISSUE THREAD

**Issue by ghs** [platformio/platformio-atom-ide#669]
Some weeks ago there was an issue about the "annoying" platformio startup window https://github.com/platformio/platformio-atom-ide/issues/453 and the possibility to add some option to disable it.

It works as a charm, but every time the package is updated, all settings are gone including the "annoying" "show ... on startup".

It is pretty annoying that have to configure everything again and try to remember what and where it was.

**Comment by ivankravets** [comment]
This issue is fixed and will be released soon.
