### ISSUE TITLE
Uncaught Error: spawn platformio ENOENT

### ISSUE THREAD

**Issue by kuro114** [platformio/platformio-atom-ide#68]
So this is a clean install and I have only Python 2.7 installed. The following error pops up on launch and I've poked around but to no avail. Any idea on how to make it go away? 

'platformio' could not be spawned. Is it installed and on your path? If so please open an issue on the package spawning the process.

Uncaught Error: spawn platformio ENOENT

**Comment by orgkhnargh** [comment]
Did the installation process go fine? Have you tried to reinstall the IDE?

**Comment by kuro114** [comment]
Yup restarted computer, uninstalled, reinstalled, and stuck. Not sure how to proceed.

**Comment by orgkhnargh** [comment]
Which OS is it on?

**Comment by kuro114** [comment]
WIndows 10

**Comment by ivankravets** [comment]
Try to open system Terminal (cmd?) and paste this `python --version`. What do you see?

**Comment by kuro114** [comment]
PS C:\Users\Spartan114> python --version
python : The term 'python' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the
name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ python --version
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (python:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by ivankravets** [comment]
You have received the answer for your question. Please perform step 2 http://docs.platformio.org/en/latest/ide/atom.html#installation

**Comment by ivankravets** [comment]
Please upgrade PlatformIO IDE to the latest 1.1.0 http://community.platformio.org/t/platformio-ide-1-1-0-and-platformio-cli-2-8-6/73/1
