### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by gcopeland** [platformio/platformio-atom-ide#683]
Error: This board doesn't support esp8266-rtos-sdk framework!

================================= [ERROR] Took 0.24 seconds =================================

Is esp8266-rtos-sdk framework not supported under platform.io? 

http://platformio.org/platforms/espressif8266
Under packages:
framework-esp8266-rtos-sdk	ESP8266 SDK based on FreeRTOS

framework-simba does install via framework = simba in platform.ini.

**Comment by ivankravets** [comment]
Please update Espressif 8266 development platform in PIO Home and start build again.
