### ISSUE TITLE
C/C++ project index rebuild failed: No platform named 'win32'

### ISSUE THREAD

**Issue by ShardanX** [platformio/platformio-atom-ide#686]
*** No platform named 'win32'

File "C:\users\root.antec-i7.000\.platformio\penv\lib\site-packages\platformio\builder\main.py", line 112, in <module>

 [ERROR] Took 104.57 seconds 

Environment normal_1024	[ERROR]

 [ERROR] Took 104.57 seconds

**Comment by ivankravets** [comment]
Could you provide `platformio.ini`?

**Comment by ivankravets** [comment]
Please reopen if you still need help
