### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by rafa400** [platformio/platformio-atom-ide#694]
Error: Unknown board ID 'esp32doit-devkit-v1'

========================== [ERROR] Took 0.38 seconds ==========================
First error said:
PlatformIO: Failed to initialize PlatformIO project!
Second error said:
C/C++ project index rebuild failed

Before this:
I upgraded Atom to the last version on the web and installed 
Then installed platformio-ide and did select a new project using  esp32doit-devkit-v1 board

**Comment by ivankravets** [comment]
Please navigate to PIO Home > Platforms > Updates and update all platforms. Start again.

**Comment by rafa400** [comment]
My system is Devian  jessie
I tried to use the menu option "PlatformIO" / "Update Platforms, Packages and Libraries" and it failed executing "platformio update" command with 
bash: platformio: command not found
(I had installed platformio-ide-terminal)
I searched the command into the install dir and fount (~/.platformio/penv/bin/platformio)
By executing this with the new path I found 
```
cd ~/.platformio
penv/bin/platformio update
```
the update was finally executed and now everything is working with 'esp32doit-devkit-v1'
Thank you

**Comment by ivankravets** [comment]
See http://docs.platformio.org/en/latest/faq.html#platformio-is-not-recognized-as-an-internal-or-external-command
