### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by totovr** [platformio/platformio-atom-ide#705]
Conda Virtualenv: 
CondaHTTPError: HTTP 401 UNAUTHORIZED for url <https://conda.anaconda.org/anaconda-fusion/osx-64/repodata.json>
Elapsed: 00:00.821070
CF-RAY: 37a836faf8ae206c-KIX

The remote server has indicated you are using invalid credentials for this channel.

If the remote site is anaconda.org or follows the Anaconda Server API, you
will need to
  (a) remove the invalid token from your system with `anaconda logout`, optionally
      followed by collecting a new token with `anaconda login`, or
  (b) provide conda with a valid token directly.

Further configuration help can be found at <https://conda.io/docs/config.html>.

**Comment by ivankravets** [comment]
Please upgrade conda, remove `~/.platformio/penv` folder and start again.
