### ISSUE TITLE
Could not find a version that satisfies the requirement

### ISSUE THREAD

**Issue by manuelbarraza** [platformio/platformio-atom-ide#710]
c:\users\electa04\.platformio\penv\lib\site-packages\platformio\managers\package.py:284: UnicodeWarning: Unicode unequal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  elif not pkg_id and manifest['name'] != name:
c:\users\electa04\.platformio\penv\lib\site-packages\platformio\commands\run.py:315: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  if any([l.get("name") == lib_name for l in storage['items']]):

Error: Could not find a version that satisfies the requirement '> = 3,24' for your system 'windows_amd64'

**Comment by ivankravets** [comment]
Could you provide more details?

**Comment by ivankravets** [comment]
Please reopen if you still need help

**Comment by GeorgeFlorian** [comment]
I have this problem as well. Is there any fix to this ?

**Comment by ivankravets** [comment]
@GeorgeFlorian which package do you install?
