### ISSUE TITLE
Can't open PlatformIO home

### ISSUE THREAD

**Issue by andagent** [platformio/platformio-atom-ide#712]
Hello, after the last update I can't open PlatformIO home. I tried in the top menu (in the dropdown menu) and on the left (PlatformIO toolbar). Can you help me, please?

**Comment by mattb5906** [comment]
I have this issue as well. Half of the PlatformIO buttons/menus don't function. No warnings or errors are displayed.
See https://drive.google.com/uc?id=0B6dFu9niJIpEQ2J6Qy04b1M4d0k

**Comment by andagent** [comment]
And this issue also in Windows (before I was testing in Linux Ubuntu). As I see sometimes it doesn't work, sometimes it does!

**Comment by ivankravets** [comment]
Have you resolved this issue?

**Comment by andagent** [comment]
Yes
