### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by vknector** [platformio/platformio-atom-ide#721]
D:\SPB_Data\.platformio\packages\tool-scons\script\..\engine\SCons\Environment.py:1303: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
val = [x for x in val if x not in dk]

C:\users\lubotec-dc\.platformio\penv\lib\site-packages\platformio\builder\tools\piolib.py:596: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
if path not in self.envorigin.get("CPPPATH", []):

UnicodeDecodeError: Non-ASCII characters found in build environment
See explanation in FAQ > Troubleshooting > Building

http://docs.platformio.org/page/faq.html

 [ERROR] Took 1.03 seconds

**Comment by ivankravets** [comment]
Have you resolved this issue?

**Comment by ivankravets** [comment]
Please reopen if you need a help
