### ISSUE TITLE
Stop displaying annoying welcome screen to log in

### ISSUE THREAD

**Issue by piotrbazan** [platformio/platformio-atom-ide#726]
Whenever atom starts platformio keeps showing screen to log in. Could you remember user option to opt out i.e. skip log in and don't show it in the future?

**Comment by ivankravets** [comment]
Settings?

**Comment by piotrbazan** [comment]
Which type of settings do you mean?
Unchecking 'Show PlatformIO on startup' does not help. The full popup dialog to log in appears. Clicking Skip button is not recorded and the same thing happens after atom restart.

You are basing your platform on open source software, be so kind as to respect users ability to opt-out from logging.

**Comment by ivankravets** [comment]
https://github.com/platformio/platformio-atom-ide/blob/develop/lib/config.js#L105

We will remove this option and other things soon. Stau tuned with us.
