### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by AlejandrLara12** [platformio/platformio-atom-ide#727]
Error: Failed to download file https://pypi.python.org/packages/source/v/virtualenv/virtualenv-14.0.6.tar.gz: 
    at /Users/ricardolara/.atom/packages/platformio-ide/lib/installer/helpers.js:49:9
    at next (<anonymous>)
    at step (/Users/ricardolara/.atom/packages/platformio-ide/lib/installer/helpers.js:156:2)

**Comment by ivankravets** [comment]
Please remove `/Users/ricardolara/.platformio/penv` folder and restart Atom. If it didn't help, please reopen an issue.
