### ISSUE TITLE
IDE showing GCC error for successfully included library header files

### ISSUE THREAD

**Issue by joelwetzel** [platformio/platformio-atom-ide#73]
- Using Atom IDE on Mac
- Initialize new project for Arduino Uno
- Open platformio.ini and add:
```
[platformio]
lib_dir = ~/Documents/Arduino/libraries
```
- Open Library Manager CLI
- Run "pio lib install 13" to add Adafruit-GFX to ~/Documents/Arduino/libraries
- Add a file src/main.cpp:
```
#include "Arduino.h"

#include <Adafruit_GFX.h>

void setup()
{
}

void loop()
{
}
```
- Compile successfully.
- See that in project_root/.pioenvs/uno, there is now an Adafruit_GFX_ID13 folder, and a compiled libAdafruit_GFX_ID13.a

However, even though it compiled successfully, I see a red dot in main.cpp indicating "GCC error,  Adafruit_GFX.h: No such file or directory at line 3 col 26"

This happens with any global library I try to include, not just Adafruit_GFX.

**Comment by ivankravets** [comment]
Will be fixed in https://github.com/platformio/platformio-atom-ide/issues/70

Temporary solution: `Menu: PlatformIO > Rebuild C/C++ Index`.
