### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by mcprakash** [platformio/platformio-atom-ide#736]
Exception: [Errno 13] Permission denied: '/home/chandra/Projects/OpenFlightSys/.pioenvs/do-not-modify-files-here.url':

File "/home/chandra/.platformio/penv/local/lib/python2.7/site-packages/platformio/builder/main.py", line 92:
PROJECTPIOENVS_DIR=util.get_projectpioenvs_dir(),
File "/home/chandra/.platformio/penv/local/lib/python2.7/site-packages/platformio/util.py", line 309:
raise Exception(e)

========================================================================================================== [ERROR] Took 0.79 seconds ==========================================================================================================

**Comment by ivankravets** [comment]
Please remove this /home/chandra/Projects/OpenFlightSys/.pioenvs
