### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by manderson** [platformio/platformio-atom-ide#743]
Error: You need to specify board ID using `-b` or `--board` option. Supported boards list is available via `platformio boards` command

Note: I have no idea what this is, Atom just reports it on launch. This not reported the first time it launched but started after installing the first update and requiring a restart. This is not the first time I've had Atom installed on this system, though I've never used it much in the past.

**Comment by ivankravets** [comment]
Should be fixed in PIO Core 3.4.1
