### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by karlaycosta** [platformio/platformio-atom-ide#753]
AttributeError: 'module' object has no attribute 'parse_conf_multi_values':
File "C:\Users\karlay.costa\.platformio\penv\lib\site-packages\platformio\builder\main.py", line 119:

env[k] = util.parse_conf_multi_values(env[k])

 [ERROR] Took 1.43 seconds 

Environment uno        	[ERROR]

 [ERROR] Took 1.43 seconds

**Comment by ivankravets** [comment]
Please remove `C:\Users\karlay.costa/.platformio` folder and restart Atom. If it didn't help, please reopen an issue.
