### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by wataruland** [platformio/platformio-atom-ide#759]
warning: Ignoring missing SConscript 'C:\Users\Wataru\.platformio\penv\lib\site-packages\platformio\builder\main.py'
File "C:\Users\Wataru\.platformio\packages\tool-scons\script\scons", line 199, in <module>

*** Do not know how to make File target `idedata' (C:\Users\Wataru\Documents\Arduino\PlatformIO\Weather\esp8266-weather-station-color\idedata).  Stop.

 [ERROR] Took 0.51 seconds

**Comment by ivankravets** [comment]
Please remove `C:\Users\Wataru/.platformio/penv` folder and restart Atom. If it didn't help, please reopen an issue.
