### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by LiaoLi327** [platformio/platformio-atom-ide#764]
C:\Users\13711\.platformio\packages\tool-scons\script\..\engine\SCons\Environment.py:1303: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal

val = [x for x in val if x not in dk]

C:\users\13711\.platformio\penv\lib\site-packages\platformio\builder\tools\piolib.py:596: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
if path not in self.envorigin.get("CPPPATH", []):

UnicodeDecodeError: Non-ASCII characters found in build environment
See explanation in FAQ > Troubleshooting > Building
http://docs.platformio.org/page/faq.html

 [ERROR] Took 507.04 seconds 

Environment d1-debug                	[ERROR]

 [ERROR] Took 507.05 seconds

**Comment by ivankravets** [comment]
Do you have non-ASCII chars in project path?

**Comment by ivankravets** [comment]
Please reopen if you still need help

**Comment by LiaoLi327** [comment]
sorry i just see. my project path have non-ASCII chars,It's C:\Lab_project\EspurnaTestMQTT
