### ISSUE TITLE
"Arduino.h: No such file or directory" error after upgrading to 1.1.0

### ISSUE THREAD

**Issue by mettinoktay** [platformio/platformio-atom-ide#77]
After updating to 1.1.0, PlatformIO has begun to throwing this error. What is the solution to this problem? I can upload project files if requested.
![adsiz](https://cloud.githubusercontent.com/assets/3055191/13984552/986450f8-f0ff-11e5-9897-b8b379263c69.png)

**Comment by ivankravets** [comment]
Please run in PlatformIO Terminal:
```
pio platforms list
```

And then delete all platforms
```
pio platforms uninstall platform1 paltformN
```

**Comment by mettinoktay** [comment]
I received `Error: Unknown platform 'platform1'`.

**Comment by ivankravets** [comment]
Of course you will receive it. It was an example. Please run `pio platforms list` and then delete all platforms listed in this command. For example (real), `pio platforms uninstall atmelavr`. Then try to build project.

**Comment by mettinoktay** [comment]
Hahaha sorry, my mistake :smile: I ran `pio platforms uninstall atmelavr`. After I hit compile, PlatformIO redownloaded atmelavr. Now it works properly. Thanks!

**Comment by ivankravets** [comment]
Happy Coding! :smile: 

Please give a star :star: for our repositories:
- https://github.com/platformio/platformio-atom-ide/stargazers
- https://github.com/platformio/platformio/stargazers

Thanks!
