### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by KISSMonX** [platformio/platformio-atom-ide#770]
Error: Failed to download file https://pypi.python.org/packages/source/v/virtualenv/virtualenv-14.0.6.tar.gz: Error: tunneling socket could not be established, cause=connect ETIMEDOUT 192.168.1.119:1080
    at /home/mingh/.atom/packages/platformio-ide/lib/installer/helpers.js:49:9
    at throw (<anonymous>)
    at step (/home/mingh/.atom/packages/platformio-ide/lib/installer/helpers.js:156:2)
    at process._tickCallback (internal/process/next_tick.js:103:7)

**Comment by ivankravets** [comment]
Please remove `/home/mingh/.platformio/penv` folder and restart Atom. If it didn't help, please reopen an issue.
