### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by Zwaubel** [platformio/platformio-atom-ide#776]
Error: VCS: `git` client is not installed in your system

Windows 10 x64, Git-2.13.3-64-bit installed and working.

I'm trying to build Marlin, branch 2.0.x (https://github.com/MarlinFirmware/Marlin/tree/2.0.x).
Just pulled the branch and opened the platformio project that is included in this branch.

I'd appreciate any help!

**Comment by ivankravets** [comment]
Please install https://git-scm.com/download/win
