### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by przywoj** [platformio/platformio-atom-ide#781]
Exception AttributeError: "'FileDownloader' object has no attribute '_request'" in <bound method FileDownloader.__del__ of <platformio.downloader.FileDownloader object at 0x021A03D0>> ignored
Exception AttributeError: "'FileDownloader' object has no attribute '_request'" in <bound method FileDownloader.__del__ of <platformio.downloader.FileDownloader object at 0x033C0370>> ignored
Error: Could not install 'toolchain-gccarmnoneeabi' with version requirements '>=1.60301.0' for your system 'windows_x86'.
If you use Antivirus, it can block PlatformIO Package Manager. Try to disable it for a while.

**Comment by ivankravets** [comment]
have you resolved this issue?

**Comment by ivankravets** [comment]
Please reopen if you still need help
