### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by jmaniish** [platformio/platformio-atom-ide#784]
Error: Failed to download file https://pypi.python.org/packages/source/v/virtualenv/virtualenv-14.0.6.tar.gz: 
    at /Users/manishjain/.atom/packages/platformio-ide/lib/installer/helpers.js:49:9
    at next (<anonymous>)
    at step (/Users/manishjain/.atom/packages/platformio-ide/lib/installer/helpers.js:156:2)

**Comment by ivankravets** [comment]
Please remove `/Users/manishjain/.platformio/penv` folder and restart Atom. If it didn't help, please reopen an issue.
