### ISSUE TITLE
Failed to run command: Build/Compile/Clean

### ISSUE THREAD

**Issue by brbrr** [platformio/platformio-atom-ide#79]
Unable to use side bar/menu item for build/compile/clean commands. I got `Failed to run command: Build`

running it from terminal like `pio run` works fine. 

Using latest dev package on Mac OS
```
$ platformio upgrade
You're up-to-date!
PlatformIO 2.8.6 is currently the newest version available.
```

**Comment by orgkhnargh** [comment]
Does it work when you use `PlatformIO > Run other target...`?

**Comment by brbrr** [comment]
`Run other target`/`Update targets`/`Toggle build panel` don't have any visual effect.
I was worked for me few weeks ago(with previous package version(s))

**Comment by orgkhnargh** [comment]
The config you've posted at #72 indicates that the `build` package is disabled. Please enable it back and try again.

**Comment by brbrr** [comment]
great! thanks. Should pio inform users about uninstalled/disabled requirements?

**Comment by orgkhnargh** [comment]
It does install and enable all requirements on start.

**Comment by brbrr** [comment]
looks like it's not. I've enable pio package, and `build` was disabled. Also I switch to dev build, and `build` still wasn't enabled. 

in general - it would be nice to see more explaining tooltip for failed build command

**Comment by orgkhnargh** [comment]
You're right. It does not activate dependencies, unless it also installed or upgraded anything. This is certainly a bug. Thanks for pointing this out.

> it would be nice to see more explaining tooltip for failed build command

Fair point. I will add more information to a tooltip.

**Comment by brbrr** [comment]
Thanks!

**Comment by orgkhnargh** [comment]
Should work fine now.
