### ISSUE TITLE
The 'platformio==3.4.1a6' distribution was not found

### ISSUE THREAD

**Issue by mikesowter** [platformio/platformio-atom-ide#796]
pio device list is broken: IDE 2.0.0 beta 7 core 3.5.0a1
traceback:
File "C:\Users\Mikes 6700K\.platformio\penv\Scripts\pio-script.py", line 6, in <module>
    from pkg_resources import load_entry_point
  File "c:\users\mikes6~1\platfo~1\penv\lib\site-packages\pkg_resources\__init__.py", line 3036, in <module>
    @_call_aside
  File "c:\users\mikes6~1\platfo~1\penv\lib\site-packages\pkg_resources\__init__.py", line 3020, in _call_aside

    f(*args, **kwargs)
  File "c:\users\mikes6~1\platfo~1\penv\lib\site-packages\pkg_resources\__init__.py", line 3049, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "c:\users\mikes6~1\platfo~1\penv\lib\site-packages\pkg_resources\__init__.py", line 656, in _build_master
    return cls._build_from_requirements(__requires__)
  File "c:\users\mikes6~1\platfo~1\penv\lib\site-packages\pkg_resources\__init__.py", line 669, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "c:\users\mikes6~1\platfo~1\penv\lib\site-packages\pkg_resources\__init__.py", line 854, in resolve
    raise DistributionNotFound(req, requirers)

pkg_resources.DistributionNotFound: The 'platformio==3.4.1a6' distribution was not found and is required by the application

tried updating and rebuilding, but it's stuck... assume update issue

**Comment by ivankravets** [comment]
Try to remove `c:\users\mikes61\.platformio\penv` folder and restart atom
