### ISSUE TITLE
InstallationManager: Virtualenv Create: ImportError: No module named site

### ISSUE THREAD

**Issue by ChrisKal** [platformio/platformio-atom-ide#799]
"Virtualenv Create: ImportError: No module named site"

Popped up after a fresh installation of atom when i tried to install platform.io

**Comment by ivankravets** [comment]
Please provide an output from system Terminal `cmd`
```
echo $PATH
echo $PYTHONPATH
python --version
pip --version
pip list
```

**Comment by ivankravets** [comment]
Please reopen if you still need help
