### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by sstaub** [platformio/platformio-atom-ide#800]
This comes up after updating the ide to v2b8, but all works fine

Exception: [Errno 13] Permission denied: '/Users/sstaub/Documents/Development/mbed/WIZnet/node2/.pioenvs/do-not-modify-files-here.url':
File "/Users/sstaub/.platformio/penv/lib/python2.7/site-packages/platformio/builder/main.py", line 93:

PROJECTPIOENVS_DIR=util.get_projectpioenvs_dir(),
File "/Users/sstaub/.platformio/penv/lib/python2.7/site-packages/platformio/util.py", line 309:
raise Exception(e)

========================== [ERROR] Took 0.50 seconds ==========================

**Comment by ivankravets** [comment]
Please remove this folder `/Users/sstaub/Documents/Development/mbed/WIZnet/node2/.pioenvs` ansd start build again.
