### ISSUE TITLE
UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode

### ISSUE THREAD

**Issue by Kami-Rotschild** [platformio/platformio-atom-ide#802]
C:\Users\Kami\.platformio\packages\tool-scons\script\..\engine\SCons\Environment.py:1303: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
val = [x for x in val if x not in dk]

UnicodeDecodeError: Non-ASCII characters found in build environment

See explanation in FAQ > Troubleshooting > Building
http://docs.platformio.org/page/faq.html

 [ERROR] Took 3.69 seconds 

Environment esp12e   	[ERROR]

 [ERROR] Took 3.69 seconds 

I used a project directory name including a unicode character (the german "ä"). Should be explained, especially in Europe ;)

**Comment by ivankravets** [comment]
Known issue, please use ASCII chars in folder name.
