### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by Fuellhase** [platformio/platformio-atom-ide#805]
Hello!
I get the following Error message when I try to install platformio-ide. Any Idea?

PIP: Error: spawn /Volumes/Macintosh HD/Users/Peter/.platformio/penv/bin/pip ENOENT

Greetings from Germany - Peter

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/698
