### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by bertbigb** [platformio/platformio-atom-ide#809]
/Users/bertbuiskool/.platformio/penv/bin/python: can't open file '/Users/bertbuiskool/.platformio/packages/_tmp_installing-UIWoVL-package/script/scons': [Errno 2] No such file or directory

========================== [ERROR] Took 21.98 seconds ==========================

Environment normal_1024	[ERROR]

========================== [ERROR] Took 21.98 seconds ==========================

Complete new with this don't know if I submit or not or if it is I did wrong

**Comment by ivankravets** [comment]
Please remove `/Users/bertbuiskool/.platformio` folder and restart IDE
