### ISSUE TITLE
Arduino library

### ISSUE THREAD

**Issue by blasterbug** [platformio/platformio-atom-ide#81]
Is there a way to automatically import libraries I use/develop with the Arduino IDE ?

**Comment by ivankravets** [comment]
Could you explain what do you mean? If you install libs using Arduino IDE and later switched project to its libs, you need perform `Menu: PlatformIO > Rebuild C/C++ Index`.

**Comment by blasterbug** [comment]
I mean, is there a way to use Arduino libraries, the ones I wrote just 
I used to do with the Arduino IDE ?

**Comment by ivankravets** [comment]
@blasterbug Sure, just place your library to the `lib` directory in the project

**Comment by blasterbug** [comment]
So I need to copy/paste the libs within the projects I need it... Not 
really efficient!

**Comment by ivankravets** [comment]
In this case you need to place library to global `LIB` dir. See http://docs.platformio.org/en/latest/projectconf.html#lib-dir

**Comment by ivankravets** [comment]
Resolved via `Menu: Import Arduino IDE Project...`
