### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by peeratpop** [platformio/platformio-atom-ide#810]
C:\Users\ASUS\.platformio\packages\tool-scons\script\..\engine\SCons\Environment.py:1303: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
val = [x for x in val if x not in dk]

C:\Users\ASUS\.platformio\penv\lib\site-packages\platformio\builder\tools\piolib.py:562: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
if path not in self.envorigin.get("CPPPATH", []):

UnicodeDecodeError: Non-ASCII characters found in build environment
See explanation in FAQ > Troubleshooting > Building
http://docs.platformio.org/page/faq.html

 [ERROR] Took 2.02 seconds

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/768
