### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by BBorowy** [platformio/platformio-atom-ide#811]
Exception: [Errno 13] Permission denied: '/Users/BogdanBorowy/Documents/MyProjects/TestESP12/.pioenvs/do-not-modify-files-here.url':
File "/Users/BogdanBorowy/.platformio/penv/lib/python2.7/site-packages/platformio/builder/main.py", line 93:

PROJECTPIOENVS_DIR=util.get_projectpioenvs_dir(),
File "/Users/BogdanBorowy/.platformio/penv/lib/python2.7/site-packages/platformio/util.py", line 309:
raise Exception(e)

========================== [ERROR] Took 2.27 seconds ==========================

**Comment by nk36** [comment]
Hi,

I'm having the same problem since 10 minutes and I don't know why..

Have you found a solution ??

Thanks

**Comment by nk36** [comment]
Ok, I found the solution by myself.. I just remove the .pioenvs in my project!

**Comment by ivankravets** [comment]
Please remove `/Users/BogdanBorowy/Documents/MyProjects/TestESP12/.pioenvs`

P.S: Fixed issue in the latest PIO Core
