### ISSUE TITLE
Editor and gcc/lint panel scrolling bug

### ISSUE THREAD

**Issue by Deekers** [platformio/platformio-atom-ide#82]
Attached are two screen shots: The first shows the gcc/lint bubble in the editor panel.

![image](https://cloud.githubusercontent.com/assets/6326148/14047170/55261c30-f263-11e5-849a-e701f33afcf7.png)

As the editor panel is scrolled the same bubble moves up and down with the scroll action and moves over top of the gcc/lint panel.

![image](https://cloud.githubusercontent.com/assets/6326148/14047198/a71070a4-f263-11e5-83ad-578284021d99.png)

The fact that the gcc/lint bubble is actually pointing to an incorrect line is a separate problem.

Atom 1.6.0
OSX 10.11.2

**Comment by orgkhnargh** [comment]
A bubble also covers a tab bar when you scroll down.

@Deekers Thank you for the report!

**Comment by ivankravets** [comment]
Please forward this issue to Atom Linter package https://github.com/steelbrain/linter/issues

Thanks!
