### ISSUE TITLE
C/C++ project index rebuild failed: Could not load broken JSON

### ISSUE THREAD

**Issue by Roxy-3D** [platformio/platformio-atom-ide#823]
Error: Could not load broken JSON: C:\Users\Roxy\.platformio\packages\_tmp_installing-4cyozz-package\package.json

I can't get this message to go away.   And as a result...  I can't build anything right now.
I think PlatformIO did an auto update.   And this problem started happening.

**Comment by ivankravets** [comment]
Have you resolved this issue?

**Comment by ivankravets** [comment]
Please reopen if you still need help
