### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by JSCSJSCS** [platformio/platformio-atom-ide#826]
Traceback (most recent call last):

File "C:\Users\JSCS\.platformio\packages\_tmp_installing-qunyr3-package\script\scons", line 190, in <module>
ImportError: No module named SCons.Script

 [ERROR] Took 268.96 seconds 
Environment sonoff        	[ERROR]
 [ERROR] Took 268.96 seconds 

New install of Atom, platformio, clang 3.91 windows 32 bit

**Comment by ivankravets** [comment]
Please remove `%HOME_DIR%/.platformio/packages/tool-scons` folder and start build again.
