### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by thingAS** [platformio/platformio-atom-ide#831]
warning: Ignoring missing SConscript 'C:\users\admin\.platformio\penv\lib\site-packages\platformio\builder\main.py'

File "C:\Users\admin\.platformio\packages\tool-scons\script\scons", line 199, in <module>

*** Do not know how to make File target `idedata' (I:\My Backup\Backup redundante do Toshiba\D\docs\DOCUMENTOS DIVERSOS\HI-TEC\Arduino\Projetos\Arrecada��o - Security Control\CV_SC_WiFi_Lib\idedata).  Stop.
 [ERROR] Took 1.27 seconds

**Comment by ivankravets** [comment]
Please remove `C:\Users\admin.platformio` and restart IDE
