### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by ming4883** [platformio/platformio-atom-ide#832]
c:\users\user\.platformio\penv\scripts\python.exe: can't open file 'C:\Users\User\.platformio\packages\_tmp_installing-jfd3ic-package\script\scons': [Errno 2] No such file or directory

 [ERROR] Took 101.35 seconds

**Comment by ivankravets** [comment]
Please remove `C:\Users\User.platformio` and restart IDE
