### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by ngentil** [platformio/platformio-atom-ide#838]
Traceback (most recent call last):
File "/home/nathan/.platformio/packages/tool-scons/script/scons", line 190, in <module>
import SCons.Script
ImportError: No module named SCons.Script

========================== [ERROR] Took 0.29 seconds ==========================

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-atom-ide/issues/826
