### ISSUE TITLE
Cannot open Serial Monitor after recent update - PlatformIO using Atom

### ISSUE THREAD

**Issue by frank3141** [platformio/platformio-atom-ide#847]
I can compile a program and the terminal shows up prperly.  If I execute adn need to use the serial monitor I get the following message instead
"PlatformIO: Terminal service is not registered.
Make sure that "platformio-ide-terminal" package is installed and activated."

Serial monitor worked quite well a week ago.  The terminal-ide package is installed, and deleted and reinstalled. Not sure what the 'activation' involves but shouldn't have been broken by an update.

**Comment by ivankravets** [comment]
https://github.com/platformio/platformio-atom-ide-terminal/issues/297
