### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by supermason** [platformio/platformio-atom-ide#864]
Exception AttributeError: "'FileDownloader' object has no attribute '_request'" in <bound method FileDownloader.__del__ of <platformio.downloader.FileDownloader object at 0x0000000006E438D0>> ignored
Exception AttributeError: "'FileDownloader' object has no attribute '_request'" in <bound method FileDownloader.__del__ of <platformio.downloader.FileDownloader object at 0x00000000070E5B70>> ignored

Error: Could not install 'toolchain-xtensa32' with version requirements '~1.50200.0' for your system 'windows_amd64'.
If you use Antivirus, it can block PlatformIO Package Manager. Try to disable it for a while.

**Comment by ivankravets** [comment]
Fixed in the latest PIO Core. Please upgrade to PIO IDE 2.0.0-rc.1
