### ISSUE TITLE
ESP8266 protected OTA

### ISSUE THREAD

**Issue by scropion86** [platformio/platformio-atom-ide#87]
i tries the BasicOTA.ino with Platformio IDE and it's working fine , but when i set the password to protect the OTA process after that it's not possible and i get Authentication failed error.

**Comment by valeros** [comment]
Hi @scropion86 !
Heve you tried `--auth=PASS` in `build_flags` [option](http://docs.platformio.org/en/latest/platforms/espressif.html?highlight=ota#authentication-and-upload-options)?

**Comment by scropion86** [comment]
thanks for the replay
NO i didn't , i will try it as and let you know.

**Comment by ivankravets** [comment]
Please reopen if you still need help.

**Comment by scropion86** [comment]
sorry for late replay , it's working with password now.
