### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by chappy1978** [platformio/platformio-atom-ide#875]
Error: PlatformIO temporary does not support cross-compilation for WiringPi framework. Please use PIO Core directly on Raspberry Pi

I tried to start a new project for the pi zero and got this error

**Comment by ivankravets** [comment]
You should initialize project on RPi side and build it there using PIO Core (CLI tool)

**Comment by yochem** [comment]
So it isn't possible to work on your desktop computer and build it to your RPi?

**Comment by ivankravets** [comment]
@yochem please take a look at http://docs.platformio.org/en/latest/plus/pio-remote.html
