### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by tenspot** [platformio/platformio-atom-ide#878]
Virtualenv Create:   File "C:\Users\mervyn\AppData\Local\Programs\Python\Python36-32\lib\site.py", line 177
    file=sys.stderr)
        ^
SyntaxError: invalid syntax

**Comment by tenspot** [comment]
This problem occurs when Atom starts and has the title: InstallationManager

**Comment by ivankravets** [comment]
Please upgrade to the latest 2.0.0-rc.1
