### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by nosratullah** [platformio/platformio-atom-ide#903]
Error: Error: ENOENT: no such file or directory, open '/Users/nosratullah/.atom/packages/platformio-ide/.cache/examples.tar.gz'

**Comment by ivankravets** [comment]
Please upgrade to the latest 2.0.0-rc.1

**Comment by honzakucera** [comment]
Same error, Atom 1.20.1, PIO 2.0.0-rc.2, Ubuntu 17.04
