### ISSUE TITLE
Huge cpu and ram usage of platformio atom IDE with Ubuntu 16.04 X64

### ISSUE THREAD

**Issue by Pilleo** [platformio/platformio-atom-ide#91]
Sometimes Atom can crash, sometimes it just shows that it was closed unexpectedly, but it still works, without such a huge cpu and ram load after that.

**Comment by ivankravets** [comment]
What is Atom version? Did you use our installer or native from atom.io?

**Comment by Pilleo** [comment]
Atom 1.6.0
It was your installer.

**Comment by ivankravets** [comment]
1. Try to uninstall Atom IDE
2. Delete ~/.atom
3. Install clean Atom IDE from http://atom.io

Do you still see high CPU usage?

**Comment by Pilleo** [comment]
Works perfect now. Thank you!
