### ISSUE TITLE
Menu "initialize new project" has disappeared

### ISSUE THREAD

**Issue by kalsan** [platformio/platformio-atom-ide#912]
After auto-installation of the latest update, PlatformIO IDE has no more button for initializing a new project. This applies both to the left hand panel as well as to the PlatformIO menu.

EDIT: Downgrading to 1.7.3 brings the buttons back, therefore this issue is specific to 2.0

**Comment by ivankravets** [comment]
That is OK, now PIO Home contains all these buttons. See

- http://docs.platformio.org/en/latest/ide/atom.html#setting-up-the-project

**Comment by kalsan** [comment]
Thanks for your fast reply. I'd recommend adding the word "initialize" somewhere in the doc you referenced, this would help existing users to find out what happened to "initialize".
