### ISSUE TITLE
InstallationManager

### ISSUE THREAD

**Issue by gerardoamc** [platformio/platformio-atom-ide#916]
Conda Virtualenv: ERROR conda.core.link:_execute_actions(335): An error occurred while installing package 'defaults::vs2008_runtime-9.00.30729.5054-0'.
CondaError: Cannot link a source that does not exist. C:\Anaconda3\pkgs\vs2008_runtime-9.00.30729.5054-0\Library\bin\msvcm90.dll

Attempting to roll back.

CondaError: Cannot link a source that does not exist. C:\Anaconda3\pkgs\vs2008_runtime-9.00.30729.5054-0\Library\bin\msvcm90.dll

**Comment by ivankravets** [comment]
Please upgrade Anaconda or unisntall it
