### ISSUE TITLE
PlaformIO Home does not show

### ISSUE THREAD

**Issue by eczajk1** [platformio/platformio-atom-ide#918]
I just did a fresh install of Atom and PlatformIO. The PlatformIO Home tab opens, but all I see is a spinning graphic:

![spinner](https://user-images.githubusercontent.com/2584923/30166425-571964ca-93b1-11e7-950b-45058b4f4371.gif)

I'm not an expert in debugging Atom, but I do see this message in the developer console:

```
internal/process/next_tick.js:103 Uncaught (in promise) Could not start PIO Home server: Error: timeout
```

I am on Windows 10:

```
atom --version

Atom    : 1.19.6
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0
```

**Comment by ivankravets** [comment]
Please open PlatformIO IDE Terminal and type
```
pio home
```

What do you see?

**Comment by eczajk1** [comment]
When I try to type in the terminal, I get this issue: https://github.com/platformio/platformio-atom-ide-terminal/issues/350

**Comment by mac-bleck** [comment]
I'm with the same problem, have you found the error?

**Comment by mac-bleck** [comment]
When I type pio home this appears:

PS C:\Users\Maurcio\.atom> pio home
CorePackageManager: Installing tool-pioplus @ >=0.10.6,<2
Downloading...
Unpacking...
Warning! Package Mirror: [Error 5] Acesso negado: u'C:\\Users\\Maurcio\\.platformio\\packages\\tool-pioplus\\pioplus.exe'
Looking for other mirror...
Downloading...
Unpacking...
Warning! Package Mirror: [Error 5] Acesso negado: u'C:\\Users\\Maurcio\\.platformio\\packages\\tool-pioplus\\pioplus.exe'
Looking for other mirror...
Error: Could not install 'tool-pioplus' with version requirements '>=0.10.6,<2' for your system 'windows_x86'.
If you use Antivirus, it can block PlatformIO Package Manager. Try to disable it for a while.



is not the antivirus, disabled and even so it continues giving this error

**Comment by ivankravets** [comment]
Please remove `C:\Users\Maurcio\.platformio` folder and start again

**Comment by japina** [comment]
The same happens to me. Tried to remove .platformio but it doesn't help.
pio home produces: ImportError: No module named platform

although the module can be found in shell (outside platformio) when running python.

**Comment by ivankravets** [comment]
Have you resolved this issue?

**Comment by japina** [comment]
Unfortunately no. I tried to delete .platformio few times, but nothing :(
Don't even know where to look to try to debug it.

**Comment by erkobg** [comment]
After a fresh install - removed Atom, Platformio, folders.... It is resolved for me.

**Comment by ivankravets** [comment]
@japina what is your OS?

**Comment by japina** [comment]
Mac OSX.

**Comment by ivankravets** [comment]
@japina please remove `~/.platformio/penv` folder and restart IDE

**Comment by japina** [comment]
I remove the whole ~/.platformio many times, but it didn't help. Did remove ~/.platformio/penv right now, but still nothing :/

**Comment by ivankravets** [comment]
@japina please open PlatformIO IDE Terminal and type
```
pio home
```

Do you see any errors?

**Comment by japina** [comment]
The error that I mentioned previous:

Traceback (most recent call last):
  File "main.py", line 16, in init main
  File "cmd_debug.py", line 15, in init cmd_debug
ImportError: No module named platform

**Comment by ivankravets** [comment]
@japina  Please provide an output from a system Terminal
```
echo $PATH
echo $PYTHONPATH
python --version
pip --version
pip list
```

**Comment by japina** [comment]
1. empty
2. empty
3. Python 2.7.10
4. pip 9.0.1 from /usr/local/lib/python2.7/site-packages (python 2.7)
5. DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in y
our pip.conf under the [list] section) to disable this warning.
arrow (0.10.0)
backports-abc (0.5)
bleep (0.4.4.dev3)
bottle (0.12.13)
certifi (2017.4.17)
chardet (3.0.4)
click (5.1)
colorama (0.3.9)
configobj (5.0.6)
Flask (0.12.2)
future (0.16.0)
glob2 (0.6)
idna (2.5)
ino (0.3.7)
itsdangerous (0.24)
Jinja2 (2.9.6)
lockfile (0.12.2)
MarkupSafe (1.0)
mercurial (4.3.2)
pip (9.0.1)
PyBluez (0.22)
pycairo (1.15.3)
pycam (0.6.1)
pygattosx (0.0.1)
pygobject (3.26.0)
pyobjc-core (4.0)
pyobjc-framework-Cocoa (4.0)
pyportmidi (0.0.7)
pyserial (3.2.1)
python-dateutil (2.6.0)
requests (2.18.1)
semantic-version (2.6.0)
setuptools (36.5.0)
singledispatch (3.4.0.3)
six (1.10.0)
tornado (4.5.2)
urllib3 (1.21.1)
virtualenv (15.1.0)
Werkzeug (0.12.2)
wheel (0.30.0)
wxPython (3.0.2.0)
wxPython-common (3.0.2.0)
xpcconnection (0.0.1)

**Comment by ivankravets** [comment]
@japina please provide contents of `~/.bash_profile`. Your $PATH is empty, it looks that you broke system environment.

**Comment by japina** [comment]
Ah, sorry .. it was late yesterday. I posted data from platformio terminal. System terminal is completely different.

1.
/Users/bostjan/.cargo/bin:/Library/Frameworks/Python.framework/Versions/3.5/bin:/usr/local/Cellar/e2fsprogs/1.42.13/sbin:/Users/bostjan/peskovnik/esp/xtensa-lx106-elf/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/CrossPack-AVR/bin:/usr/local/go/bin:/Library/TeX/texbin:/usr/local/gcc-arm-none-eabi-5_4-2016q2/bin:/Users/bostjan/bin

2. empty

3. Python 2.7.10
4. pip 9.0.1 from /usr/local/lib/python2.7/site-packages (python 2.7)
5.
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
arrow (0.10.0)
backports-abc (0.5)
bleep (0.4.4.dev3)
bottle (0.12.13)
certifi (2017.4.17)
chardet (3.0.4)
click (5.1)
colorama (0.3.9)
configobj (5.0.6)
Flask (0.12.2)
future (0.16.0)
glob2 (0.6)
idna (2.5)
ino (0.3.7)
itsdangerous (0.24)
Jinja2 (2.9.6)
lockfile (0.12.2)
MarkupSafe (1.0)
mercurial (4.3.2)
pip (9.0.1)
PyBluez (0.22)
pycairo (1.15.3)
pycam (0.6.1)
pygattosx (0.0.1)
pygobject (3.26.0)
pyobjc-core (4.0)
pyobjc-framework-Cocoa (4.0)
pyportmidi (0.0.7)
pyserial (3.2.1)
python-dateutil (2.6.0)
requests (2.18.1)
semantic-version (2.6.0)
setuptools (36.5.0)
singledispatch (3.4.0.3)
six (1.10.0)
tornado (4.5.2)
urllib3 (1.21.1)
virtualenv (15.1.0)
Werkzeug (0.12.2)
wheel (0.30.0)
wxPython (3.0.2.0)
wxPython-common (3.0.2.0)
xpcconnection (0.0.1)

**Comment by paulo9999** [comment]
I'm following the discussion here, I'm having the same issue as @japina... 

my $PATH is empty
and I cannot find the folder ~/.bash_profile

**Comment by MHesham** [comment]
I am facing the same issue on Ubuntu 16.04:
```
PlatformIO Plus (https://pioplus.com) v0.10.13
CorePackageManager: Installing contrib-piohome @ >=0.3.2,<2
Error: Detected unknown package 'contrib-piohome'
```
I can see this error in ATOM terminal:
`Uncaught (in promise) Could not start PIO Home server: Error: timeout`

**Comment by ivankravets** [comment]
Fixed, please restart IDE.

**Comment by evoteknologi** [comment]
Why im getting this ? I have tried all method. Remove .platformio and install again, use buit in core, restart IDE, im using vsc dan atom.

![image](https://user-images.githubusercontent.com/33225538/32375489-5b40e08c-c0d4-11e7-9340-ac9ceb7b1ac3.png)

**Comment by ivankravets** [comment]
@evoteknologi could you provide full exception information?

**Comment by evoteknologi** [comment]
@ivankravets 
![image](https://user-images.githubusercontent.com/33225538/32400090-854495ea-c12e-11e7-8fe3-289d69c538f9.png)

![image](https://user-images.githubusercontent.com/33225538/32400100-95659cda-c12e-11e7-8673-c2eef07ba007.png)

My pio home always loading white background in atom, in vsc always loading also.

**Comment by ivankravets** [comment]
@evoteknologi you have restrictions in a system which don't allow to run `pioplus.exe` binary which is responsible for PIO Home. Did you configure it manually?

**Comment by evoteknologi** [comment]
@ivankravets not yet, how to do that sir?

**Comment by evoteknologi** [comment]
@ivankravets now its worked just type pio home in command prompt as administrator. Im forget to run admin. Thank you very much sir

**Comment by AlexFBP** [comment]
For me, worked installing pip as the last image by https://github.com/platformio/platformio-atom-ide/issues/918#issuecomment-341855801 

vscode from elementary 0.4 (ubuntu 16)

`pip install -U platformio`
