### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by vomdth** [platformio/platformio-atom-ide#920]
I get the following error upon opening a project e.g. Sonoff Tasmota. On Windows everything is working fine, this error message appears only on MAC OS sierra. Any ideas what is wrong? Do I need to install or configure any additional packages?!

Traceback (most recent call last):
File "/Users/xxx/.platformio/packages/tool-scons/script/scons", line 190, in <module>
import SCons.Script
ImportError: No module named SCons.Script
========================== [ERROR] Took 0.26 seconds ==========================
Environment sonoff        	[ERROR]
========================== [ERROR] Took 0.26 seconds ==========================

**Comment by ivankravets** [comment]
Please remove `/Users/xxx/.platformio/packages/tool-scons` folder and restart IDE
