### ISSUE TITLE
In some cases build buttons/menu items do not work

### ISSUE THREAD

**Issue by cranphin** [platformio/platformio-atom-ide#921]
Cool, I learned how to debug atom :)

This issue is probably only on Windows.

For some reason, some  of my projects have two leading slashes, and some one leading slash, like (from \.atom\storage\application.json):
- C:\\Storage\\PlatformIO\\sigrok-rc_switch
- C:\\\\Storage\\PlatformIO\\Blink

I think the projects with two slashes are the ones I opened from PlatformIO home.

The folders with two slashes are creating issues in [getActivePioProject](https://github.com/platformio/platformio-atom-ide/blob/develop/lib/project/helpers.js#L23).
The paths list contains the project names with slashes.
The filePath variable contains the editor path, with only one slash.
So [finding](https://github.com/platformio/platformio-atom-ide/blob/develop/lib/project/helpers.js#L32) the project fails, and the first project is used instead.

The result of that is that none of the RunTarget.atomCommandName will match, since it includes the project folder name, and the default command for the project folder will be ran instead.

In similar core atom [code](https://github.com/noseglid/atom-build/blob/master/lib/utils.js#L32), it looks like the use fs.realpathSync(..) to normalize paths first, to solve this. So that would be one way to fix it. Or mayby it's possible to prevent the double slash to be introduced.

**Comment by ivankravets** [comment]
Please navigate to Atom > Settings > Packages > PlatformIO IDE > Advanced and check `Use development version of PlatformIO IDE`.

Please wait while PIO will reinstall it. Restart Atom. Does it work now?

Thanks!
