### ISSUE TITLE
InstallationManager: SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by tenspot** [platformio/platformio-atom-ide#922]
Virtualenv Create:   File "C:\Users\mervyn\AppData\Local\Programs\Python\Python36-32\lib\site.py", line 177
    file=sys.stderr)
        ^
SyntaxError: invalid syntax

**Comment by ivankravets** [comment]
Please provide an output from system Terminal `cmd`
```
echo %PATH%
echo %PYTHONPATH%
python --version
pip --version
pip list
```

**Comment by ivankravets** [comment]
Please reopen if you still need help

**Comment by ivankravets** [comment]
@fumisan @tenspot

Please provide an output from system Terminal `cmd`
```
echo %PATH%
echo %PYTHONPATH%
python --version
pip --version
pip list
```

**Comment by ivankravets** [comment]
Please note that PlatformIO supports only Python 2
