### ISSUE TITLE
PIO Can't find Arduino Libs

### ISSUE THREAD

**Issue by exothink** [platformio/platformio-atom-ide#932]
when importing an Arduino project includes not found unless a full path is added.

doesn't work:  lib_extra_dirs = ~/Documents/Arduino/libraries      <---- added by pio

works:  lib_extra_dirs = C:\Users\jhe\Documents\Arduino\libraries
also works:  lib_extra_dirs = C:/Users/jhe/Documents/Arduino/libraries

Home 0.2.5·Core 3.5.0a9
Win 7 and Win 10

**Comment by ivankravets** [comment]
Fixed in the latest PIO Core
