### ISSUE TITLE
PlatformIO Home screen stuck on Github download wheel of death

### ISSUE THREAD

**Issue by rasw** [platformio/platformio-atom-ide#935]
![platformio_hanging](https://user-images.githubusercontent.com/2217890/30290720-59c70df6-9728-11e7-87c5-c74c95101e18.png)

After the last releases of the update, the PlatformIO home screen hangs trying to access some GitHub contents.  It does not seem to timeout and the home screen does not get displayed.  If I close this all seems well and I can carry on working, but this does happen every time I start-up.

Atom version 1.19.7
PlatfomeIO version 3.5.0a9 

Any ideas on how to return this to normal.

Regards
Richard

**Comment by ivankravets** [comment]
Please provide an output from system Terminal `cmd`
```
echo %PATH%
echo %PYTHONPATH%
python --version
pip --version
pip list
```

**Comment by ivankravets** [comment]
Please reopen if you still need help
