### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by al1fch** [platformio/platformio-atom-ide#943]
c:\users\al\.platformio\penv\scripts\python.exe: can't open file 'C:\Users\al\.platformio\packages\_tmp_installing-xezo7k-package\script\scons': [Errno 2] No such file or directory
 [ERROR] Took 113.58 seconds

**Comment by ivankravets** [comment]
Fixed in https://github.com/platformio/platformio-atom-ide/commit/22127abb693390336a5c0484c8231d4c45f7d619
