### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by sporkbyspork** [platformio/platformio-atom-ide#944]
*** Multiple ways to build the same target were specified for: C:\Users\test\Documents\PlatformIO\Projects\170914-205705-digispark-tiny\.pioenvs\digispark-tiny\lib\TrinketHidCombo\usbdrv\usbdrvasm.o  (from ['C:\\Users\\test\\Documents\\PlatformIO\\Projects\\170914-205705-digispark-tiny\\lib\\TrinketHidCombo\\usbdrv\\usbdrvasm.S'] and from ['C:\\test\\elwood\\Documents\\PlatformIO\\Projects\\170914-205705-digispark-tiny\\lib\\TrinketHidCombo\\usbdrv\\usbdrvasm.asm'])
File "C:\Users\test\.platformio\penv\lib\site-packages\platformio\builder\tools\platformio.py", line 272, in BuildLibrary
 [ERROR] Took 0.64 seconds

**Comment by ivankravets** [comment]
Please open an issue here https://github.com/platformio/platform-atmelavr/issues
