### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by dedo24397** [platformio/platformio-atom-ide#951]
warning: Ignoring missing SConscript 'C:\Users\<user>\.platformio\penv\lib\site-packages\platformio\builder\main.py'
File "C:\Users\<user>\.platformio\packages\tool-scons\script\scons", line 199, in <module>
*** Do not know how to make File target `idedata' (C:\Users\<user>\Documents\Robot_Uno\idedata).  Stop.
 [ERROR] Took 8.02 seconds

**Comment by ivankravets** [comment]
Please remove `C:\Users<user>.platformio\packages\tool-scons` and restart IDE
