### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by damianb-inwebit** [platformio/platformio-atom-ide#969]
Exception: [Errno 13] Permission denied: '/home/inwebit/ Arduino Esp/Adafruit_INA219-master/.pioenvs/do-not-modify-files-here.url':
File "/home/inwebit/.platformio/penv/local/lib/python2.7/site-packages/platformio/builder/main.py", line 93:
PROJECTPIOENVS_DIR=util.get_projectpioenvs_dir(),
File "/home/inwebit/.platformio/penv/local/lib/python2.7/site-packages/platformio/util.py", line 328:
raise Exception(e)
========================== [ERROR] Took 1.13 seconds ==========================
Environment nanoatmega328	[ERROR]
========================== [ERROR] Took 1.13 seconds ==========================

**Comment by ivankravets** [comment]
Please remove `/home/inwebit/ Arduino Esp/Adafruit_INA219-master/.pioenvs`
