### ISSUE TITLE
Double compile and upload

### ISSUE THREAD

**Issue by opeRaptor** [platformio/platformio-atom-ide#98]
It takes over a minute to compile and upload to esp8266 I see a green SUCCESS! and it compiles and uploads again.

The whole process of compiling and uploading takes over 60 seconds, over twice the time it used to take before. I see the green SUCCESS! once and the process starts again a second time until I get a DONE! message.

At the end however, the program runs fine.

**Comment by ivankravets** [comment]
Could you show a screenshot of this problem?

**Comment by opeRaptor** [comment]
Resolved the issue yesterday, the double uploads happens when 2 boards are added to the config file as targets.
