### ISSUE TITLE
Upgrade from 1.1.1 to 1.1.2 fails on first attempt (minor)

### ISSUE THREAD

**Issue by jbbr** [platformio/platformio-atom-ide#99]
I tried upgrading platformio-ide from 1.1.1 to 1.1.2 and got the following error in the dev console:
```
Uncaught Error: spawn /Users/user/.atom/packages/platformio-ide/penv/bin/python ENOENT
```
According to the console error is in `events.js:141`
The directory ` /Users/user/.atom/packages/platformio-ide/penv` does not exists at all (Although everything worked fine before upgrading - I assume it has been deleted during upgrade process)

Cancelling "Installing platformio-ide" dialog did not worked as well.
What did worked was quitting Atom and restarting it. The "Installing platformio-ide" dialog showed again and this time finished successfully.
So this is not a blocker but still confusing and not a perfect experience.

Atom version 1.6.0 (Installed with official platformio-atom-ide installer)
System: OSX 10.11

**Comment by orgkhnargh** [comment]
I haven't been able to reproduce this error.

**Comment by jbbr** [comment]
Just had this problem again when upgrading from 1.1.2 to 1.2.0.

- relatively fresh install of platformio-ide plugin in Atom 1.7.2 (This time not official platformio-atom-ide installer - used "brew cask" instead)
- pressed update in settings for platformio-ide

So nothing fancy here. I made a screenshot this time:

![atomide_upgrade_fail](https://cloud.githubusercontent.com/assets/682607/14898668/379e841e-0d88-11e6-891c-ffeb3fb79b8f.png)

Btw: When pressing "Cancel" the button switches to a disabled "Canceling" button but canceling does not work.
![atomide_canceling](https://cloud.githubusercontent.com/assets/682607/14898718/92180aa0-0d88-11e6-8478-617ed7001e7b.png)

Is there anything I can do to find the cause of this issue?

**Comment by jbbr** [comment]
Just restarted Atom and this time I got:
![atomide_suspended](https://cloud.githubusercontent.com/assets/682607/14898755/c93a0cb8-0d88-11e6-8960-4a3a682a27a4.png)

Update of the plugin itself did worked according to atom (Settings/plugins shows 1.2.0). Also the platformio toolbar is visible. But:

When clicking on "Build" button execution of platformio command failes:

![atomide_build_failed](https://cloud.githubusercontent.com/assets/682607/14898813/282dc5a2-0d89-11e6-8b0f-9697ee47f220.png)

The directory `~/.atom/packages/platformio-ide/penv` is missing. In previous versions of platformio-ide it got recreated automatically when starting atom. This does not seem to work anymore because it seems to think that an installation is still running (Maybe there is a lock file or something which hasn't been deleted due to broken "canceling"?)

**Comment by ivankravets** [comment]
We have release PlatformIO IDE 1.2.1 today. Do you still have this problem?

**Comment by jbbr** [comment]
Much better now:
- Opened Atom and pressed "Upgrade all" in Plugins section
- Got "PlatformIO installing" message which finished successfully
- After finish building any project failed with some Atom-warning toast (Sorry, I forgot the message)
- Restarted Atom, got again the "PlatformIO installing" message, now it asked me to reload the IDE which I did
=> Since then everything is fine

So upgrade experience was a bit rough but at least it worked well in the end.

Thanks!

**Comment by ivankravets** [comment]
Please reopen if you still need any help
