### ISSUE TITLE
C/C++ project index rebuild failed

### ISSUE THREAD

**Issue by rites1978** [platformio/platformio-atom-ide#992]
Traceback (most recent call last):
File "/Users/riteshlal/.platformio/packages/tool-scons/script/scons", line 190, in <module>
import SCons.Script
ImportError: No module named SCons.Script
========================== [ERROR] Took 44.00 seconds ==========================
Environment sonoff        	[ERROR]
========================== [ERROR] Took 44.00 seconds ==========================

**Comment by ivankravets** [comment]
Please remove `/Users/riteshlal/.platformio` and restart IDE
